[Selina] Step3-2-2 - 속성 변경 동작
codesquad-members-2022/swift-drawingapp pull request #100
Opened 2022-03-17 14:56 UTC by ios-h

# Step3-2-2. 속성 변경 동작

## 💻 작업 목록

- [x] 터치될 떄마다 해당 위치에 사각형이 있는지 확인
  - [x] 사각형이 있다면, 사각형이 선택된다.
  - [x] 사각형이 없다면 기존에 선택된 사각형을 선택 취소한다. 기존에 선택된 사각형이 없을 경우 아무 동작도 하지 않는다.
- [x] 사각형 테두리에 선을 표시해서 선택된 것을 인지시키기
- [x] 사각형을 선택하면 화면 우측에 해당 사각형의 현재 배경색과 투명도가 반영된다.
- [x] 배경색 버튼 누르면 랜덤한 추천 색상으로 변경
- [x] 투명도는 10단계로 나눠서 변경하고, alpha 값을 단계로 나눠 적용한다.
- [x] 투명도 좌, 우에 버튼은 각각 투명도 단계를 -1, +1 시킨다. 

## 📱 실행 화면

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/95578975/158830805-a03375ac-5805-4db5-81a1-fe07c396acfb.gif)

2022-03-18 05:24 UTC, godrm commented
> 직사각형이 선택됨을 표시할 때 borderWidth, borderColor를 지정하였습니다. 근데 이 때 border의 투명도도 해당 직사각형의 투명도와 같은 값으로 나옵니다. border만 따로 투명도를 설정할 수 있는 방법은 없는 건가요?

가능하죠. 그럴려면 뷰의 구조를 좀 더 알아야 합니다. UIView.alpha를 바꾸면 모든 요소가 영향을 받죠. layer도 마찬가지에요
그래서 다른 subview를 두거나 sublayer를 두어야 합니다. 지금 방법을 못 찾았으면 차차 확인해봐요

2022-03-18 05:57 UTC, godrm requested changes
이번 단계에서 하는 일이 많아지고 코드가 조금 복잡해졌을 겁니다
그럴수록 입력 흐름과 출력 흐름을 구분해보고, 뷰가 가볍게 동작하도록 해보세요
다음 내용들을 확인해보시고 개선해보세요!

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        let sliderValue = Float(sliderStringValue)!
소숫점 값을 제한하기 위해서 문자열로 바꾸는 것은 좋은 접근이 아닙니다. trunc(), round() 같은 수학 함수를 활용해보세요

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        }
이 메소드는 버튼이 눌렀을 때 호출되는 입력의 흐름이라서, plane까지 전달되는 흐름만 처리하는 게 좋습니다
그리고 plane에서 바뀐 값에 따라서 버튼이나 다른 뷰의 출력을 처리하는 흐름을 분리해보세요.
그 흐름을 나누는 게 중요합니다.

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
>      func planeDidAddedRectangle(_ rectangle: Rectangle) {
사소한 부분인데 `planeDidAddedRectangle` 에서 Did와 Added가 모두 과거형으로 표현되서 어색하네요. 
Did-를 붙이면 뒷 부분을 원형으로 표기하는 게 자연스러울 것 같습니다

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        canvasView.changeRectangle(rectangle)
이 부분에서 canvasView에게 rectangle을 전달하는 게 하위 타입에게 일을 시키는 측면에서 좋은 접근입니다.
다만 Model의 값 자체를 전달하는 것이 항상 최선은 아닐 수 있습니다.
뷰는 모델이 무엇인지 모르고, 출력에 필요한 값들만 받거나 모델에 대한 접근을 최소화하는 게 좋습니다
그걸 전달하는 역할이 뷰 컨트롤러거든요. 
저렇게 간결하게 하면 뷰가 뭔가 판단하거나, 출력 형식을 정하거나 그런 것을 다 해야 합니다
그런데 모델의 값을 원하는 출력의 형식을 정하는 것은 뷰가 하는 게 아니라 여기서 담당해야 하는 역할입니다
그런 측면에서는 좋은 게 아닙니다.

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        canvasView.select(rectangle: rectangle)
여기는 터치를 받아서 선택을 처리해야 하는 입력 부분입니다. 
그러니까 어떤 사각형이 선택될지, 안될지를 여기서 판단하기 보다는 plane에게 이런 이벤트가 있어. 알려주고 끝내는거죠.
이후에 plane이 무언가 선택이 취소되야해. 선택되야해. 같은 이벤트를 보내주면 각각 그거에 맞게 출력을 처리하면 되는거죠. 
입력과 출력의 흐름이 합쳐져 있습니다. 그걸 분리해보세요

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
이런 함수는 Plane 속성과 관련이 없는 응집도가 떨어지는 함수입니다. plane 내부 속성과 관련이 있는게 아니라 rectangle 내부 속성과 관련이 있으니 rectangle.contains(x,y)처럼 하위 타입에 일을 시키는 방식으로 개선해보세요. 
카드 게임에서 카드 속성을 가져오지 않고 카드 자체를 비교했던 것처럼요

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    func backgroundColorDidChanged(color: String, rectangle: Rectangle) {
어딘선가 컬러값을 문자열로 바꿔서 전달해주나 보내요
Color 값을 다룰 때 가장 좋은 것은 Color 타입이겠죠. 일반적인 숫자, 문자로도 값을 표현할 수 있지만 구체적인 타입을 정했으면 그 타입을 활용해보세요.

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +            if rect == rectangle {
이렇게 찾는 것은 retangles.firstIndex() 처럼 배열에서 바로 찾는 방법을 고려해보세요.

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
이 hexValueToInt 함수도 여기에 있지만 plane과 응집도가 떨어지는 함수 같네요. 어떤 타입과 관련이 있을까요?

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +    private var rectangles = [Rectangle: RectangleView]()
뷰는 Rectangle을 갖고 있으면 안되고 뷰와 관련된 정보만 갖고 있는 게 좋습니다
이렇게 모델을 직접 참조하는 것을 하지 않아야 합니다. 뷰는 역할을 최소화하는 게 좋습니다. 
그래서 이렇게 두 개 값을 모두 알고 있어야 한다면, 그건 뷰 컨트롤러가 할 일입니다.

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +        rectangles[rectangle] = rectangleView
사각형 뷰를 생성하는 것도 뷰가 그려야 하는 역할에서 조금 벗어날 수 있습니다. 
어떤 뷰를 생성할 지는 여기서 하기 보다는 (어떤 뷰든지) 특정한 뷰를 생성해서 여기서는 그리는 역할만 하도록 하는거죠

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +            }
어떤 값을 어떤 식으로 표시할 것인가 결정하는 것도 뷰가 하는 게 아니라, 외부에서 뷰에게 알려주는 게 좋습니다
여기서는 color만 바꾸면 되면 컬러값만 주는 거죠

2022-03-18 05:57 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +}
이렇게 내부 구조를 전혀 바꾸는 게 없다면 RectangleView는 UIView를 typealias 만 해도 될 것 같네요

2022-03-18 07:30 UTC, ios-h commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +}
typealias를 사용하는 방법은 미처 생각하지 못했습니다. 리뷰해주신대로 수정하였습니다!

2022-03-18 15:05 UTC, ios-h commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
backgroundColorDidChanged 함수의 매개변수 중 color의 타입을 String에서 Color로 변경하여서 hexValueToInt 함수가 필요 없게 되어 제거했습니다..!

2022-03-18 15:05 UTC, ios-h commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    func backgroundColorDidChanged(color: String, rectangle: Rectangle) {
구체 타입을 활용하도록 String 타입을 Color 타입으로 변경하였습니다!

2022-03-18 15:27 UTC, ios-h commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +            }
backgroundColor를 저장하는 코드가 필요 없는 코드였어서 제거했습니다,,!

2022-03-18 16:38 UTC, ios-h commented on DrawingApp/DrawingApp/Model/Plane.swift
> +            if rect == rectangle {
배열에서 원하는 값의 인덱스를 찾을 때 `firstIndex(of:)`를 사용하면 for 문보다 유용한 것 같네요ㅎㅎ for문을 제거하고 firstIndex를 사용하는 방식으로 변경하였습니다!

2022-03-22 15:14 UTC, AhnSangHee commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        let sliderValue = Float(sliderStringValue)!
round 함수 사용하여 수정하였습니다!

2022-03-22 23:53 UTC, ios-h commented
### 피드백 반영 사항

- 소숫점 값을 제한하기 위해 round() 함수 사용
- 합쳐진 입력과 출력의 흐름 분리
- 함수 이름 변경 (`planeDidAddedRectangle` -> `planeDidAddRectangle` )
- isRectangleExist 함수가 plane 내부 속성이 아닌 rectangle 내부 속성과 관련 있도록 개선
- 색상 변경 시 String 타입을 전달하여 변환하던 것을 구체 타입을 활용할 수 있도록 Color 타입으로 변환
- Plane에서 터치된 좌표에 직사각형이 있는지 찾을 때 for문 대신 `firstIndex(of:)`를 사용하는 방식으로 변경
- 뷰가 모델을 갖지 않도록 변경
- 사각형 뷰를 생성하고 추가하는 역할은 뷰컨트롤러가 하도록 변경
- RectangleView.swift, CanvasView.swift 파일 제거하고 typealias를 활용

2022-03-22 23:53 UTC, ios-h commented
@godrm 피드백 주신 사항 개선하여 푸시하였습니다. 확인해주시면 감사하겠습니다!

2022-03-23 03:55 UTC, godrm commented
우어 지난 미션을 다 수정하셨네요. 수고하셨습니다

2022-03-23 03:56 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    private var rectangles = [Rectangle: RectangleView]()
이제 다음에 도전해볼 것은 ViewController에서 사용하는 Rectangle, RectangleView 등의 구체 타입을 추상화한 프로토콜로 대체해보는 겁니다. 다음 미션에서라도 도전해보세요

2022-03-23 03:56 UTC, merged