[bibi] step2 - Plane 구조체 생성, 화면에 사각형 표시, 사각형 속성 변경
codesquad-members-2022/swift-drawingapp pull request #104
Opened 2022-03-18 03:25 UTC by bibi6666667

안녕하세요, bibi입니다.
프로젝트 마지막 날에 올리는 거의 일주일 만의 PR이네요😅 
혼자 어떻게든 해보려고 하다 보니 진도가 늦긴 했지만, 많은 걸 배운 일주일이라고 생각합니다!

---

## 작업 내용
- [x] Plane 구조체 구현
- [x] TapGestureRecognizer로 사각형 선택 기능 구현
- [x] 사각형 선택 시 파란 테두리로 나타내고, 선택 취소 시 테두리도 삭제
- [x] 선택한 사각형의 배경색과 투명도 보이기
- [x] 선택한 사각형의 배경색 랜덤 변경 기능 구현
- [x] 선택한 사각형의 투명도 조절 기능 구현
---

## 학습 키워드
- Subscript
- Comparable 프로토콜
- 연산 프로퍼티
- UITapGestureRecognizer
- UIStepper
- 16진수 컬러코드

---

## 고민과 해결 & 질문거리

### 뷰(뷰컨트롤러) 와 모델 분리하기
> ViewController는 실제 화면에 필요한 동작과 이벤트 흐름을 전달하는 역할만 하고, Plane에서 주도적으로 관리하도록 구현한다.

개인적으로 이번 단계에서는 새롭게 배워야 하는 뷰 요소들도 많았지만, 모델과 컨트롤러를 분리하는 것이 가장 어려웠던 것 같습니다🤔
특히 '사각형 관련 동작 구현을 위한 주요 정보들은 UIKit을 import한 ViewController에서 처리하는데, 이 로직들을 어떻게 UIKit이 없는 모델로 분리하지?' 가 가장 큰 의문점이었습니다.
예를 들어 사각형의 랜덤 색상을 만드는 generateRandomRGBA() 의 경우 모델로 뺄 수 있겠다! 라고 생각했는데, 모델에서는 해당 메서드에 필요한 CGFloat을 사용하려면 UIKit를 import해야 하더라고요. 그렇다고 모델에 UIKit을 import할 수는 없으니 다른 로직을 분리해 보자.. 라고 생각하고 넘기다 보니, ViewController에서 모델로 분리할 수 있는 로직이 거의 없어졌습니다🥲
그래도 분리할 수 있는 로직들은 최대한 분리하긴 했지만, 뷰컨트롤러에 남아있는 로직들을 어떻게 더 분리할 수 있을지가 고민입니다.

---

요구사항대로 기능 구현은 완료했지만, 아직도 많이 부족한 것 같습니다. 이번 PR도 많은 피드백 부탁드립니다🙇‍♀️
그리고 늘 감사드립니다 JK! 💐

2022-03-18 07:20 UTC, godrm commented
오랜만이군요. 커밋도 엄청 많네요. 그래서 모든 것을 구현하기 보다는 end to end로 입력부터 출력까지 흐름을 만들어보고 개선하는 과정이 좋습니다. 

> 예를 들어 사각형의 랜덤 색상을 만드는 generateRandomRGBA() 의 경우 모델로 뺄 수 있겠다! 라고 생각했는데, 모델에서는 해당 메서드에 필요한 CGFloat을 사용하려면 UIKit를 import해야 하더라고요. 그렇다고 모델에 UIKit을 import할 수는 없으니 다른 로직을 분리해 보자.. 라고 생각하고 넘기다 보니, ViewController에서 모델로 분리할 수 있는 로직이 거의 없어졌습니다🥲

그래서 CGFloat 자체를 안쓰는 타입을 만들어야 하는거죠. 이제는 스위프트에서 언어적으로 float와 double 타입은 CGFloat과 매칭이 됩니다. 
특정 타입(대부분 뷰 컨트롤러)까지는 뷰와 관련된 타입을 쓰고, 그 아래 하위 타입에서는 핵심 로직을 다루고, 그 내부에서만 쓰는 타입을 쓰는 게 좋습니다.

2022-03-18 07:56 UTC, godrm requested changes
뷰 컨트롤러가 역할을 많이 하다보니 plane의 역할을 더 구분하지 못한 것 같습니다
이전 미션에서 ViewController와 Game의 관계를 생각해보세요.
뷰 컨트롤러는 입력의 흐름과 출력의 흐름을 구분해서 전달하는 매개체 역할에 집중하도록 개선해보세요
Plane은 화면에 어떻게 그려질지 모르지만, 핵심적인 로직을 생성하고 관리를 역할만 해보세요.

2022-03-18 07:56 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
이 메소드는 여기서 호출하는 것도 아니고, 내부 속성과 관련 있는 것도 아니니까 Plane과 응집도가 떨어지는 경우입니다. 
이 메소드랑 관련이 높은 타입은 무엇일까요? 그걸 찾아내는 게 객체지향 설계와 구현의 핵심입니다

2022-03-18 07:56 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangleArray: Array<Shape> = Array<Rectangle>()
Array<Shape>을 쓸꺼면 Array<Shape>()로 생성해도 되지 않을까요? 
둘 중에 하나만 써도 됩니다.

2022-03-18 07:56 UTC, godrm commented on DrawingApp/DrawingApp/Model/Shape.swift
>      var id: String { get }
id를 가져가는 것도 속성을 가져가는 것인데, 이걸 가져가서 어떤 행위가 일어나는 지 생각해보세요
그리고 그게 비교하는 거라면, id를 가져가지 않고 Shape를 비교할 수 있도록 처리해보세요

2022-03-18 07:56 UTC, godrm commented on DrawingApp/DrawingApp/UIColorExtension.swift
> +    var rgba: (red: CGFloat, green: CGFloat, blue: CGFloat, alpha: CGFloat) {
이 메소드가 정확하게 왜 필요한지 모르겠지만,
이렇게 개별 값을 CGFloat로 변환하면 또 내부에서 사용하는 값들로 변환해야 할 겁니다
그럴꺼면 이렇게 확장하는 곳에 아예 변환하도록 하는 건 어떨까요? 
그리고 이 부분을 호출해서 주로 사용하는 곳에서만 확장하는 것도 고려해보세요.

2022-03-18 07:56 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +    let shapeFactory = ShapeFactory()
뷰 컨트롤러도 private var를 우선적으로 고려하세요

2022-03-18 07:56 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +            return
이 앱의 핵심 기능이 뷰와 관련이 있다보니 혼란스러울 수 있습니다.
입력을 처리할 때는 좌표를 구했으면 그걸 처리하는 뷰를 여기서 찾을 필요가 없습니다
그 좌표를 처리할 것을 판단하는 게 Plane 아래 어딘가해서 처리할 일인 거죠
뷰 컨트롤러는 입력의 흐름에 맞춰서 전달해주는 역할만 하면 됩니다. 
저 뷰를 사용한다고 생각하지 않아야 입력과 출력의 흐름을 구분할 수 있습니다

2022-03-18 07:56 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        addRectangleToPlane(x: xyPoint.x, y: xyPoint.y, r: rgbaInt.r, g: rgbaInt.g, b: rgbaInt.b, a: rgbaInt.a)
이 부분은 `사각형을 추가하라` 메시지를 받는 입력 부분이네요. 
입력 흐름에서는 핵심적인 로직을 담당하는 하위 타입에게 전달하는 게 뷰 컨트롤러의 역할입니다
모든 것을 여기서 다 처리하려고 하지 않아도 됩니다. Plane에게 사각형 추가하자.고 알려주고 끝나는거죠 

---
그리고 나서 plane이 적절한 상태 변화를 알려주면, 그 변화에 맞춰서 뷰를 추가하던가, 값을 바꾸던가 하면 됩니다. 입력의 흐름과 출력의 흐름이 섞여 있는데 그것을 분리해보세요.

2022-03-18 07:56 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        plane.addRectangle(rectangle)
여기서 필요한 값을 생성하고, 전달하는 것도 뷰 컨트롤러가 꼭 하지 않아도 됩니다.
추상화를 한다는 측면에서 보면 여기서는 간결하게 plane에게 사각형을 추가하자.고 전달만 하면 되는거죠

2022-03-28 14:21 UTC, bibi6666667 commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangleArray: Array<Shape> = Array<Rectangle>()
이 부분은 ShapeFactory의 `createRectangle()->Shape` 의 실제 리턴 객체가 Rectangle이라서 이렇게 배열을 업캐스팅한 방식으로 구현해 보았습니다. 구글링 자료를 보며 팩토리 패턴을 따라 만들며 ShapeFactory 추상화를 위한 프로토콜인 ShapeCreator를 만들고, `createRectangle()->Shape` 메서드를 공통으로 요구했는데, 막상 사용하려니 실제로는 Rectangle을 담는 배열이 필요해 이런 방식을 사용해 보았습니다. 지금 보니 현재 공장에서 생성하는 객체가 하나뿐인데 프로토콜까지 만든 건 과했나 싶기도 하네요..

`rectangleArray = Array<Rectangle>()` 로 선언하면 아래 메서드의 `plane.addRectangle(rectangle)`에서 형변환이 필요해져서, 대안으로 배열을 저렇게 선언해 보았는데요.

``` swift
private func addRectangleToPlane(x: Int, y: Int, r: Int, g: Int, b: Int, a: Int) {
        let randomColor = Color(r: r, g: g, b: b)
        let randomAlpha: Alpha = Alpha(rawValue: a) ?? Alpha.one
        let rectangle = shapeFactory.createRectangle(point: Point(x: Double(x), y: Double(y)), size: Size(width: 150, height: 120), color: randomColor, alpha: randomAlpha)
        plane.addRectangle(rectangle)
    }
```

궁금한 점은 1️⃣혹시 스위프트에서는 `var rectangleArray: Array<Shape> = Array<Rectangle>()`와 같이 업캐스팅해 선언하는 방식이 좋지 못한 방식인가요? 2️⃣ 코드 수정을 위해 "ShapeFactory 리턴타입을 Rectangle로 바꾸고, ShapeCreator 프로토콜 삭제하기" or "현재 상태로 두고 `plane.addRectangle(rectangle)`의 rectangle을 다운캐스팅해 넣기" 중 고민이 되는데, 지금 상태에서 어떤 게 더 바람직할지 궁금합니다.

2022-03-29 04:45 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangleArray: Array<Shape> = Array<Rectangle>()
만약 Rectangle이 Shape 프로토콜을 채택했다면 Array<Shape>에도 Rectangle 인스턴스를 넣을 수 있습니다
꼭 구체타입을 써야 하는 건 아닙니다.

2022-03-31 07:46 UTC, bibi6666667 commented
안녕하세요. bibi입니다!
이번 자율학습(?) 주간 동안 해당 프로젝트의 모델과 뷰를 분리하는 연습을 해 보았습니다.
특히 피드백에서 주셨던
> 뷰 컨트롤러는 입력의 흐름과 출력의 흐름을 구분해서 전달하는 매개체 역할에 집중하도록 개선해보세요
Plane은 화면에 어떻게 그려질지 모르지만, 핵심적인 로직을 생성하고 관리를 역할만 해보세요.

을 최대한 지키려고 하면서, 로직은 모두 Plane으로 빼고 뷰 컨트롤러는 보여주는 역할만 하며 최대한 가볍게 고쳐보았습니다.
말씀대로 프로젝트의 핵심 부분이 뷰를 보여주는 것이다 보니 어떻게 분리할지 고민이 많이 되었네요🤔
지금 상태가 모델과 뷰가 잘 분리된 것인지 잘 모르겠지만, 나름대로 최대한 분리해 보았습니다.

## 질문거리
이번 프로젝트 진행하며 스스로 아쉬운 점은 '객체지향 프로그래밍에서는 getter, setter를 사용하는 것을 지양한다' 를 지키지 못하고 getter, setter를 남발한 것입니다..😭
쓰면 안 되는데.. 하면서도 프로퍼티의 private 접근수준을 지키면서 값을 가져와야 하다 보니 어쩔 수 없이 자꾸 쓰게 되었네요..
객체들의 접근수준을 높게 유지하면서도 getter, setter를 사용하지 않으려면 프로토콜을 잘 사용해야 한다고 들었는데, 문법은 공부해 놨지만 실제로 어떻게 프로젝트에 응용해야 하는지 감이 안 옵니다.😞

2022-04-01 09:20 UTC, godrm approved these changes
몇 가지 항목에 대해서 의견을 남겼습니다.
입력 흐름 -> 모델 변경 -> 출력의 흐름으로 구분해보시면 좋겠습니다.

2022-04-01 09:20 UTC, godrm commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +        let rectangleY = self.point.getY()
스위프트에서는 property라면 항상 getter / setter가 만들어집니다 
그냥 값만 표현해야 하는 Point 같은 타입은 public이어도 되니까 굳이 이렇게 getX , getY를 따로 선언하지 않아도 됩니다. `point.x` , `point.y` 라고 쓴다고 해서 이게 객체지향이 아닌 건 아니에요 
객체 지향에서 얘기하는 객체는 저런 값만 있는 타입은 제외하고 얘기합니다

2022-04-01 09:20 UTC, godrm commented on DrawingApp/DrawingApp/Model/Shape.swift
> +    func getAlpha() -> Alpha
Shape 이라는 프로토콜을 선언할 때도 모든 객체가 이 속성들을 접근해야 하는 게 아니라 
ISP 측면에서 관련 있는 메소드들 역할별로 인터페이스를 분리해보세요

2022-04-01 09:20 UTC, godrm commented on DrawingApp/DrawingApp/Model/ShapeFactory.swift
> +    func createRectangle(point: Point, size: Size, color: Color, alpha: Alpha) -> Rectangle {
Shape가 프로토콜이면 팩토리에서 생성해서 리턴하는 타입을 프로토콜로 지정해도 좋습니다

2022-04-01 09:20 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +            selectedView = nil
이렇게 생각해보세요.
여기 Tap 한 이벤트를 받는 곳이니까 이 흐름은 입력의 흐름입니다. 
그러니까 입력을 전달해주기만 하고, 화면에 결과적으로 무언가 표시되거나 가려지는 것은 출력의 흐름에서 처리해보세요

2022-04-01 09:32 UTC, merged