[Sol] Step3-06 위치, 크기 속성 변경 기능 추가
codesquad-members-2022/swift-drawingapp pull request #107
Opened 2022-03-18 08:26 UTC by Hansolkkim

## 실행 화면
![SS 2022-03-18 PM 04 45 04](https://user-images.githubusercontent.com/92504186/158958618-ca6b9c28-2ca7-4a9a-bf03-0ed04c6ec47a.gif)
---
## 작업 목록
- [x] Refactoring
  - [x] 사각형 뷰의 추상 타입이 NSCopying 프로토콜을 채택하도록 하여 copy() 메서드 구현
  - [x] panAction() 메서드에서 입출력을 모두 처리하고 있어 해당 흐름을 구분
- [x] 선택된 뷰의 좌표를 이동시키는 기능 구현
  - [x] 필요한 버튼을 스토리보드에서 추가하는 방법 사용
  - [x] 버튼의 액션 메서드을 이용해 VC가 입력을 받고 plane에게 전달해주고, plane이 가지고 있는 객체의 변화를 노티받아 VC가 뷰의 출력을 지시하는 흐름으로 설정
- [x] 선택된 뷰의 사이즈를 조절해주는 기능 구현
  - [x] 좌표이동과 마찬가지로 스토리보드를 이용 및 입출력 흐름 과정도 동일
- [x] DrawableAreaView를 분리하여, 해당 뷰에서 발생하는 이벤트 입력을 VC에게 전달하고, VC의 지시를 받아 자신의 뷰를 업데이트하도록 수정
- [x] X, Y, Width, Height의 최솟값을 1으로 설정하여, 최솟값보다 작아지거나 같아지는 경우 속성 값을 감소시키는 버튼을 Disabled 상태가 되도록 설정
---
## 학습 키워드
`NSCopying` , `Delegate`
## 고민과 해결
- 버튼의 갯수가 이번 스텝에서만 8개가 추가됨으로 인해 ViewController가 너무 커져 어떻게 기능을 조금이라도 나눌지 고민했습니다. 이를 위해 코드로 작성했던 DrawableAreaView를 새로운 View로 나누어, 해당 뷰에서 발생하는 입력, 해당 뷰에서 보여질 출력의 흐름을 ViewController로 부터 어느정도 분리할 수 있었습니다.
---
## 질문
- 다른 분들의 PR을 보다가, 프로토콜이 프로퍼티를 정의하는게 좋지 않다는 말씀을 봤습니다. 스텝을 진행하면서 RectangleViewable이라는 사각형 뷰의 추상 타입이 frame, alpha, layer 등의  프로터리를 가지게 되었는데, 찾아보니 프로토콜이 UIView를 상속받을 수 있다는걸 알게됐습니다. 그런데 UIView를 상속받은 프로토콜을 추상타입이라고 부를 수 있을까 궁금해졌습니다. 이렇게 프로토콜이 UIView를 상속받는것이 어색한 부분은 아닌가요?

2022-03-18 09:54 UTC, godrm commented
> 다른 분들의 PR을 보다가, 프로토콜이 프로퍼티를 정의하는게 좋지 않다는 말씀을 봤습니다. 스텝을 진행하면서 RectangleViewable이라는 사각형 뷰의 추상 타입이 frame, alpha, layer 등의 프로터리를 가지게 되었는데, 찾아보니 프로토콜이 UIView를 상속받을 수 있다는걸 알게됐습니다. 그런데 UIView를 상속받은 프로토콜을 추상타입이라고 부를 수 있을까 궁금해졌습니다. 이렇게 프로토콜이 UIView를 상속받는것이 어색한 부분은 아닌가요?

`protocol A : UIView`를 의미하는 걸까요?
이건 UIView를 상속 받는게 아니라 A 프로토콜을 채택하려면 UIView를 상속하라는 의미라서 말한 것과 좀 다른 것 같네요

2022-03-18 10:05 UTC, godrm requested changes
NSCopying은 클래스 일때만 의미가 있는 거니까, struct는 안 하셔도 됩니다
다음 내용들을 확인해보세요

2022-03-18 10:05 UTC, godrm commented on DrawingApp/DrawingApp/Model/AnyRectangularable.swift
>  class AnyRectangularable: Rectangularable {
AnyRectangularable 이건 프로토콜 이름으로 적합한 것 같고 명사형으로 쓰는 클래스 타입으로는 부적절한 것 같습니다 
오히려 클래스라는 것을 몰라서 혼란을 줄 것 같습니다

2022-03-18 10:05 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var specifiedRectangle: AnyRectangularable?
클래스 구체 타입이 아니라 프로토콜로 추상화를 해보면 좋을 것 같네요.

2022-03-18 10:05 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    public func changePointOfSpecifiedRectangle(to newPoint: Point) -> Result<AnyRectangularable, PlaneError> {
여기 메소드들에 `-OfSpecifiedRectangle`가 붙어있는데 뒤에는 Rectangle에 대한 내용이 없어서 혼란스럽네요
plane에게 특정한 사각형을 알려주려면 이름만 붙이는 게 아니라 무엇을 하면 좋을까요?
plane 내부의 속성 이름을 지정해줄 필요는 없습니다.

2022-03-18 10:05 UTC, godrm commented on DrawingApp/DrawingApp/View/DrawableAreaView.swift
> +    }
이런 메소드는 private으로 지정하는 게 좋습니다. 이걸 외부에서 호출한다면 self.addGestureRecognizer가 여러번 동작해서 오동작을 발생할 가능성이 높네요

2022-03-18 10:05 UTC, godrm commented on DrawingApp/DrawingApp/View/PhotoView.swift
> +        return CGRect(x: self.minX, y: self.minY, width: self.width, height: self.height)
이건 copy가 아니지 않아요? 복사는 값이 다 동일해야 할 것 같은데요?

2022-03-18 10:05 UTC, godrm commented on DrawingApp/DrawingApp/View/PhotoView.swift
> +        return CGFloat(self)
이건 왜 필요한거죠? CGFloat 같은 struct는 복사가 의미가 있나요?

2022-03-18 10:05 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    func copy(with zone: NSZone? = nil) -> Any {
여기서 Any 대신에 자기 자신을 쓰는 건 어때요?

2022-03-18 10:05 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +        let newAlpha = self.alpha.copy()
frame 이나 alpha 같은 struct는 그냥 `let newAlpha = self.alpha` 이렇게 쓰세요

2022-03-19 02:37 UTC, Hansolkkim commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    func copy(with zone: NSZone? = nil) -> Any {
@godrm 이전 PR에서[`Copy를 처리할 때는 NSCopying 프로토콜을 한 번 살펴보세요`, `copyToNewInstatnce() 대신에 copy()가 될 순 없나요?`](https://github.com/codesquad-members-2022/swift-drawingapp/pull/89#discussion_r827748402) 라는 리뷰를 받아서, 
NSCopying을 채택해서 copy() 메서드를 구현하는게 더 좋은 접근 방법이라고 말씀하시는거라 생각해 NSCopying을 채택 후 Any 타입을 반환하는 copy 메서드를 구현했습니다.

그런데 Any타입 대신 자기 자신을 반환하도록 하려면 NSCopying 프로토콜을 채택하는게 맞지 않는 것 같습니다.

혹시 이전 리뷰에서 말씀하시고자 했던 말씀이 `Copy를 구현하려면 NSCopying을 참고해보고 메서드 이름은 copy()가 더 적합한 것 같습니다.` 의 느낌이었을까요?

2022-03-19 04:24 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    func copy(with zone: NSZone? = nil) -> Any {
그렇군요. `Any타입 대신 자기 자신을 반환하도록 하려면 NSCopying 프로토콜을 채택하는게 맞지 않는 것 같습니다.` 이 부분을 추론한 이유가 궁금합니다. 단지 함수 이름이 copy냐 아니냐보다 해당하는 역할에 대한 이미 선언된 프로토콜이 있고, 그걸 활용하는 게 더 일반적인 방법이라는 거죠. 
그런데 Any 타입은 모든 타입의 최상위 추상 타입이다보니, 혹시 다른 타입으로 바꿀 수 있냐는 의미였어요. 
프로토콜의 규격에서 벗어나서 안되면 왜 안되는지 이유를 알면 됩니다. 

---
제가 질문하는 것은 작성한 코드를 기반으로 주는 피드백이고, 그거대로만 해야한다는 게 아닙니다. 저의 의견에 의존하지마시고
스스로 되는 이유, 안되는 이유, 이런 의견이 있지만 작성한 코드는 본인이 가장 잘 아니까 해당 의견을 설득할 수 있도록 해보세요

2022-03-19 04:42 UTC, Hansolkkim commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    func copy(with zone: NSZone? = nil) -> Any {
> 그렇군요. `Any타입 대신 자기 자신을 반환하도록 하려면 NSCopying 프로토콜을 채택하는게 맞지 않는 것 같습니다.` 이 부분을 추론한 이유가 궁금합니다. 단지 함수 이름이 copy냐 아니냐보다 해당하는 역할에 대한 이미 선언된 프로토콜이 있고, 그걸 활용하는 게 더 일반적인 방법이라는 거죠. 그런데 Any 타입은 모든 타입의 최상위 추상 타입이다보니, 혹시 다른 타입으로 바꿀 수 있냐는 의미였어요. 프로토콜의 규격에서 벗어나서 안되면 왜 안되는지 이유를 알면 됩니다.
>
> 제가 질문하는 것은 작성한 코드를 기반으로 주는 피드백이고, 그거대로만 해야한다는 게 아닙니다. 저의 의견에 의존하지마시고 스스로 되는 이유, 안되는 이유, 이런 의견이 있지만 작성한 코드는 본인이 가장 잘 아니까 해당 의견을 설득할 수 있도록 해보세요

답변 감사합니다 JK!
이번 과제를 진행하면서 제가 너무 피드백에 의존해서 변경만 하려고 했던 것 같습니다. 제가 만든 코드에 대해 남을 설득할 수 있도록, 조금 더 많은 생각을 하면서 코드를 작성해보겠습니다.

그리고 NSCopying 프로토콜을 채택하는게 맞지 않다고 생각한 이유는 아래와 같습니다.
프로토콜을 채택하는 것은 외부에서 해당 프로토콜을 채택한 객체를 사용할때 사용할 수 있는 메서드를 제공해줄 수 있도록 하는 것인데, NSCopying 프로토콜을 채택하고 copy 메서드의 반환타입을 변경하는 것은 가능하지 않고, 같은 역할을 하지만 (앞에서 말씀드린)copy 메서드를 내부에서 사용한 뒤 타입을 바꿔서 반환하는 메서드를 새로 만든다면 NSCopying 프로토콜을 채택할 필요성이 사라집니다(외부에 제공하고 싶은 copy메서드는 NSCopying 프로토콜을 채택해서 사용하려는 메서드와 다르기 때문입니다.).

2022-03-28 02:27 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/AnyRectangularable.swift
>  class AnyRectangularable: Rectangularable {
그렇네요 클래스 이름 이라기 보다는 프로토콜 이름이라 생각되는 이름이 맞는 것 같습니다. 말씀하신 클래스명 `BasicShape` 으로 수정하겠습니다.

2022-03-28 02:27 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var specifiedRectangle: AnyRectangularable?
해당 부분을 AnyRectangularable 클래스를 생성하면서 수정했던것 같은데 구체타입이 아니라 프로토콜이라도 문제가 없을 뿐더러 추상화가 필요한 부분인 것 같습니다. 해당 프로퍼티의 타입을 Rectangularable 프로토콜 타입으로 수정해보겠습니다.

2022-03-28 02:27 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    public func changePointOfSpecifiedRectangle(to newPoint: Point) -> Result<AnyRectangularable, PlaneError> {
이번 리뷰를 보고 어떤 식으로 이름을 만드는게 적합한지 고민을 했는데, 
ViewController가 Plane에게 먼저 `specifyRectangle()` 이라는 메서드를 호출함으로써 `사각형을 특정해라` 라는 메시지를 전달하고 그 후로 `changePoint(to:)` 라는 이름의 메서드를 호출해 `Point를 바꿔라` 라는 메시지를 전달하는 흐름을 가진다면 굳이 저 메서드의 이름이 목적어가 없어도 되지 않겠나 라는 생각이 들었습니다. 
그래서 Plane 클래스의 메서드 이름 중 `-OfSpecifiedRectangle`이 붙은 메서드 이름에서 해당 부분을 모두 제거하여 수정해보겠습니다.

2022-03-28 02:27 UTC, Hansolkkim commented on DrawingApp/DrawingApp/View/DrawableAreaView.swift
> +    }
아 그렇네요 외부에서 여러번 호출하면 오동작을 할 수 있겠네요 해당 메서드 private 접근 제어자로 수정하면서, 마찬가지로 외부에서 호출할 경우 문제가 발생할 수도 있을거라 생각되는 `tapAction(_:)`, `panAction(_:)`같은 메서드들도 함께 private을 지정해 수정하도록 하겠습니다.

2022-03-28 02:27 UTC, Hansolkkim commented on DrawingApp/DrawingApp/View/PhotoView.swift
> +        return CGFloat(self)
struct라는 사실을 전혀 생각하지 않고, 모든 타입들의 복사 메서드를 만들었습니다.. 클래스로 구현된 타입들의 복사 메서드만 남겨놓도록 하겠습니다!

2022-03-28 02:27 UTC, Hansolkkim commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +        let newAlpha = self.alpha.copy()
struct로 구현된 타입이라는걸 생각하지 않고 복사하는 메서드를 만들었습니다.. struct인 타입들은 모두 말씀하신 방법으로 수정해보겠습니다.

2022-03-28 02:28 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    public func changePointOfSpecifiedRectangle(to newPoint: Point) -> Result<AnyRectangularable, PlaneError> {
이번 리뷰를 보고 어떤 식으로 이름을 만드는게 적합한지 고민을 했는데,
ViewController가 Plane에게 먼저 specifyRectangle() 이라는 메서드를 호출함으로써 사각형을 특정해라 라는 메시지를 전달하고 그 후로 changePoint(to:) 라는 이름의 메서드를 호출해 Point를 바꿔라 라는 메시지를 전달하는 흐름을 가진다면 굳이 저 메서드의 이름이 목적어가 없어도 되지 않겠나 라는 생각이 들었습니다.
그래서 Plane 클래스의 메서드 이름 중 -OfSpecifiedRectangle이 붙은 메서드 이름에서 해당 부분을 모두 제거하여 수정해보겠습니다.

2022-03-28 02:30 UTC, Hansolkkim commented on DrawingApp/DrawingApp/View/PhotoView.swift
> +        return CGRect(x: self.minX, y: self.minY, width: self.width, height: self.height)
`origin.x` 와 `minX` 의 의미를 혼동했던 것 같습니다.. 더군다나 Struct인 타입이라 필요한 메서드도 아니라 판단해 해당 메서드 부분 삭제하도록 하겠습니다.

2022-03-28 03:07 UTC, Hansolkkim commented
리뷰해주신 부분 수정 완료했습니다! struct인 타입들을 복사할때도 모두 copy() 메서드를 만드려고 했던 점에 대해 우선적으로 수정을 진행했습니다.

2022-03-28 08:35 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    func copy(with zone: NSZone? = nil) -> Any {
NSCopying 프로토콜이 Any로 되어 있는 것은 일반화시켜서 채택한 모든 타입이 같은 역할을 하기 위해서입니다. 어쩔수 없는거죠 
단지 타입정보를 맞추지 못해서 동일한 역할을 하는 메소드를 따로 만드는 것은 오히려 헷갈릴 수도 있습니다
`왜 NSCopying을 채택하지 않은걸까?` 당연히 궁금할 수 있습니다. 다른 프로토콜도 같은 이유에서 채택하지 않고 메소드를 만들다보면 역할을 구분하지 않고 메소드를 만들게 되지 않을까 생각합니다. 

`외부에 제공하고 싶은 copy메서드`가 return 타입에 구체 타입으로 리턴해야만 하는 이유가 설득력 있다면 될 것 같네요. 
수고하셨습니다.

2022-03-28 08:35 UTC, merged

2022-03-28 11:59 UTC, Hansolkkim commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    func copy(with zone: NSZone? = nil) -> Any {
답변 감사합니다! 외부에 제공하고 싶은 copy 메서드의 반환 타입이 Any가 아니어야 했던 이유는, copy 메서드를 호출한 이후에 불필요하게 타입 캐스팅하는 부분을 없애려고 했기 때문입니다. 이번 리뷰와 저번 리뷰를 바탕으로 타입 캐스팅을 줄이는 방법에 대해 많이 고민했는데, 이런 부분에서 copy 메서드를 새로 정의해주어 타입 캐스팅을 안하는 방법이 더 마음에 든다고 생각했습니다.

그런데 이번 리뷰를 보니 제가 새로 만든 copy 메서드를 이용하면 `프로토콜을 이용해 역할을 부여해준다`는 개념이 좀 옅어지겠다는 생각이 들었습니다. 제 눈에만 마음에 드는 코드보다는 남들이 봤을때 더 읽기 좋은 코드에 대해서 조금 더 생각을 해보고 이번 스텝 넘어가도록 하겠습니다 감사합니다!