Beck step1 start of i pad app project
codesquad-members-2022/swift-drawingapp pull request #11
Opened 2022-03-01 13:20 UTC by SangHwi-Back

## 작업 목록 (2022/03/01 17:00 종료)

- [x] (Git) 저장소 fork 및 clone 후 작업 branch 생성
- [x] 사각형(뷰)을 만드는 모델을 생성한다. Class를 사용하고 Core Graphics나 UIKit을 임포트 하지 않는다.
- [x] CGSize/CGPoint를 사용하지 않고 Double타입을 기준으로 처리한다. Size/Point 타입을 선언해도 된다.
- [x] UIColor/CGColor를 사용하지 않고 RGB를 이용하여 처리한다.
- [x] 투명도를 1-10사이의 랜덤 값으로 표시한다.
- [x] CustomStringConvertible 프로토콜을 추가해본다.
- [x] 사각형(뷰)을 뷰에 추가하는 뷰컨트롤러를 생성한다.
- [x] 모델을 생성할 때 랜덤값을 보내주는 팩토리 메소드를 생성한다. 모델은 랜덤값을 생성하지 않는다.
- [x] View-ViewController 간의 관계가 명확히 드러나도록 구현한다.

## 학습 키워드

```MVC Pattern``` ```Object-Oriented Programming``` ```XCTest```

## 고민과 해결

* MVC 패턴의 모델을 구현하기 위해 뷰를 구성하기 위한 프로퍼티를 모두 가지고 있는 ViewRandomProperty를 작업하였습니다.
* ViewRandomProperty는 뷰의 프로퍼티를 랜덤으로 만드는 ViewPropertyCreator를 서브클래싱 합니다. ViewPropertyCreator는 여러가지 값을(의도한) 랜덤으로 뽑아내는 RandomizeValue를 서브클래싱 합니다. 각각의 역할은 나눌 수 있다고 판단하여 각각의 클래스로 만들게 되었습니다.
* 계속되는 코멘트 중 하나는 ```접근 제한자``` 였습니다. 이번에는 신경을 써서 작업을 진행하였습니다.

2022-03-02 01:44 UTC, godrm commented
PR 작업 목록을 작성할 때 루카스 요구사항을 그대로 복사하지 마시고,
스스로 작업 단위를 나누고, 요약해서 기록하면 됩니다.

2022-03-02 01:54 UTC, godrm requested changes
이번 단계 요구사항에서 조금 벗어난 부분이 보입니다.
피드백과 요구사항을 다시 한 번 확인해보시고 다시 보내봐주세요. 
뷰를 만드는 게 아니라 모델을 만들어야 하는데 그 부분을 확인하기 어려웠습니다

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/FactoryViewRandomProperty.swift
> +    }
이번 단계가 UIKit 프레임워크를 임포트해서 사용하지 않고 구현하는 건데 UIKit을 임포트하고 있네요
UIView도 있고 뷰 객체를 벌써 만들고 계신건가요? 뷰 없이 Model 부터 선언하고 확인하는 단계였던 것 같은데요?

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/FactoryViewRandomProperty.swift
> +        self.superview = superview
이 타입이 뷰인지 모델인지 모르겠지만, 그렇더라도 superview를 참조할 필요가 없습니다
항상 포함관계에서 하위에 있는 타입은 자신을 포함하는 상위 타입을 모르는 게 더 좋습니다

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/FactoryViewRandomProperty.swift
> +        )
특정한 값으로 인스턴스를 생성하는 메소드를 모아서 팩토리로 분리하는 거였는데, 여기서는 자기가 자신의 인스턴스를 생성하고 있네요
그러면 init()과 어떤 차이가 있는걸까요?

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/String+Extension.swift
> +
사용하지 않는 코드는 주석으로 남기지말고 삭제하시는 게 좋습니다

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/String+Extension.swift
> +        return result
이런 Id를 생성하는 메소드를 String에 확장할 때는 모든 String이 다 사용하는 메소드인지 판단해보고 확장하는 게 좋습니다
특정 타입이나 특정 함수에서만 쓴다면 그것과 관련된 곳에 구현하는 게 더 좋습니다

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/SystemLog.swift
> +    }
로그 라이브러이를 만드셨네요. Logger라는 타입도 확인해보세요

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        view.addSubview(randomView)
이번 단계 요구사항을 오해하신게 아닌가 싶습니다
뷰를 만드는 게 아니라, 뷰를 처리하기 위해 값을 가지는 모델을 선언하고 값을 확인하는 겁니다
이렇게 뷰만 만드는 것을 하지 않기 위해서 나눈 단계입니다. 다시 확인해봐주세요

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/ViewPropertyCreator.swift
> +        (
함수 이름이 동사가 아닌 것 같습니다. 이걸 읽으면 Generator를 위한 좌표를 네모로 만드는 듯한 느낌입니다.

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/ViewRandomProperty.swift
> +typealias RectRGBColor = (r:Double, g:Double, b: Double)
이제는 튜플+alias 보다는 구체적인 값 타입을 지정해보세요

2022-03-02 01:54 UTC, godrm commented on DrawingApp/DrawingApp/ViewRandomProperty.swift
> +    let alpha: Double
alpha에 대한 범위 요구사항이 빠진 것 같습니다

2022-03-02 01:56 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/FactoryViewRandomProperty.swift
> +    }
정신없이 진행하다 보니 요구사항을 벗어난 것 같습니다. 다시 Push 하도록 하겠습니다.

2022-03-02 01:59 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/ViewRandomProperty.swift
> +    let alpha: Double
1-10 *단계* 였군요.... 이번 코드는 실수가 많아 죄송합니다. 다시 Push 후 PR 하도록 하겠습니다.

2022-03-02 04:51 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/ViewController.swift
> +        view.addSubview(randomView)
아... 다시한번 자세히 읽어보고 실수를 깨달았습니다. 수정 후 재요청 드리도록 하겠습니다.

2022-03-02 06:36 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/FactoryViewRandomProperty.swift
> +        )
@godrm 🙋 안녕하세요 JK! 말씀해주신 코멘트를 작업 중 질문드립니다.

제가 최초 작성한 코드는 Model객체의 init()을 호출하는 부분이 뷰 컨트롤러에서 init을 호출하는 것과 다르지 않아서 팩토리 메소드 같지는 않다고 말씀해주시는 것으로 이해했습니다.

개선할 방법을 아래와 같이 생각하고 있는데, 아직도 제가 잘못 이해하고 있는건지 헷갈려서 다시 한번 질문드립니다. 혹시나 틀린 부분이 있다면 지적을 부탁드립니다. 감사합니다! 

1. 무작위로 값을 뽑는 부분을 팩토리 클래스의 Function 혹은 Property(모두 private)로 선언하고 팩토리 메소드에서 사용한다.
2. 팩토리 클래스의 서브 타입으로, 무작위 값 추출에 필요한 최대값만 저장하는 값 타입을 선언합니다. Delegate 패턴을 이용하여 상위 객체에서 받아옵니다.
3. 팩토리 메소드는 클래스에 미리 지정된 Fucntion, Property, Delegate 객체만을 이용해서 Model 객체를 만들어 냅니다.

2022-03-02 06:49 UTC, godrm commented on DrawingApp/DrawingApp/FactoryViewRandomProperty.swift
> +        )
복잡하게 생각하지마시구요
- 어떤 타입 A가 있고, A.init()으로 초기화할 수 있어야 합니다
- A에 대한 팩토리는 A.init()을 대신 호출해주면서 복잡한 값들을 간단하게 넣고 생성할 수 있으면 됩니다
팩토리에서 뭘하더라도 A.init() 역할이 바뀌는 건 없습니다

2022-03-02 06:55 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/FactoryViewRandomProperty.swift
> +        )
넵 알겠습니다. 다시 시도해보겠습니다.... 감사합니다!

2022-03-03 05:27 UTC, godrm commented on DrawingApp/DrawingApp/ViewRandomProperty.swift
> +}
타입이 다르면 파일로 분리해보세요. 여기 Size나 Point가 꼭 Rect 와 관련된 거라면 Nested 타입도 고려해보시구요

2022-03-03 05:27 UTC, merged

2022-03-03 05:46 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/ViewRandomProperty.swift
> +}
Nested 타입을 썼을 때와 쓰지 않았을 때를 고려해보고 Model 소스코드에서 분리하도록 하겠습니다. 감사합니다!