[shingha] Step2 - 속성-변경-동작
codesquad-members-2022/swift-drawingapp pull request #18
Opened 2022-03-02 09:45 UTC by shingha1124

### 체크리스트

- [x] UI 화면 구성
  - [x] 인스펙터 UI 제작
    - [x] 오브젝트 배경색
    - [x] 오브젝트 투명도
  - [x] 상단 메뉴 UI 제작
    - [x] 사각형 생성 버튼 추가
- [x] 기능 구현
  - [x] 드로잉 뷰
    - [x] 생성버튼을 누르면 사각형을 화면에 그린다
    - [x] 사각형이 없으면 기존 선택된 다른 사각형도 선택 취소
    - [x] 오브젝트 선택 시 테두리 on/off
  - [x] 상단 메뉴 UI
    - [x] 생성버튼 이벤트 연결
  - [x] 인스펙터 UI
    - [x] 선택한 오브젝트 배경색 정보 출력
    - [x] 배경색 버튼 탭 시 색상 랜덤 변경
    - [x] 선택한 오브젝트 투명도 정보 출력
    - [x] 투명도 슬라이더, 버튼 조절 시 알파값 조정
      - [x] 투명도는 10단계, +/- 버튼 구현, 더이상 작거나 커질수 없으면 비활성화

### 핵심기능

* 드로잉 뷰
  * 생성버튼을 누르면 화면에 사각형이 출력된다
  * 사각형을 선택하면 선택 테두리가 보인다
  * 빈곳을 누르면 선택 해제
* 인스펙터
  * 사각형 선택 시 해당 오브젝트의 정보가 출력된다
    * 배경색, 알파
  * 사각형 선택 해제시 인스펙터 창 정보는 가려진다
  * 배경색 정보를 클릭시 임의의 색으로 선택한 사각형의 배경이 변경된다
  * 알파의 슬라이드 조절 시 선택한 사각형의 알파값이 조절된다
  * 알파의 +/-버튼 터치시 알파 값이 조절된다
  * 알파값에 따라 +/-버튼이 on/off된다

### 고민과 해결

* 코드정리
  * 기능을 구현하면서 상위객체가 하는 일이 많아짐
  * 어느정도 기능 구현 후 코드정리를 계속 진행 하며 개선해 나감
  * 위 플로우로 코딩을 진행 해보니 괜찮았음
* 팩토리
  * 사실 지금까지 개발하면서 팩토리를 거의 안써보았음..
  * 팩토리를 사용해 보니 객체를 생성 할때 코드가 정리되어 보기 좋음
  * TypeData, DrawingModel, DrawingView 3가지의 Factory로 구현하여 사용중
* PR의 단위( 고민 )
  * 첫번째 올린 PR을 기다리며 Step2개발을 진행하고 있었음
  * 삼일절을 지나 Step1의 리뷰를 받고, 이제 Step2 PR을 올리려는데 양이 많아짐..
  * Step2-1, 2-2로 구분은 해 놓았지만...이럴경우는 나눠서 올리는게 좋은지
    아니면 통합된 2-2를 올리는 것이 좋은지 궁금합니다

Step2를 진행하고 PR을 올리는데 양이 좀 많은것 같습니다 ㅠㅠ
이럴경우 이전 작업한 위치에서 PR을 보내는게 맞는지.. 한번에 보내는게 맞는지 궁금합니다!!
나눠서 올리는게 맞다면 다시 PR을 올려보겠습니다!

2022-03-03 01:17 UTC, godrm commented
그러게요 양이 좀 많아서 천천히 보겠습니다 :)

2022-03-03 05:46 UTC, shingha1124 commented
> 그러게요 양이 좀 많아서 천천히 보겠습니다 :) PR에 커밋과 작업한 파일 분량은 작을 수록 좋습니다. 그래야 집중해서 보게 되니까요 현업에서도 범위가 넓을 수록 피드백이 줄어들고 머지하기 어려워집니다.

넵 ㅠ 조금씩 더 잘게 쪼개서 PR 보내도록 하겠습니다!
step2-1로 브랜치 나눠놓은 부분이 있는데 이곳으로 다시 PR올릴까요???

2022-03-03 07:18 UTC, godrm requested changes
아이고 길다... 
뷰 부분들은 대체로 괜찮은 것 같고, 모델과 연결 부분들에 의견을 남겼습니다. 확인해보세요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +class DrawingModelFactory {
DrawingModelFactory 모델을 생성하는 팩토리인데 UIKit에 의존적인가 보네요? 
분리할 수 있을까요? 여기서 어떤 부분을 참조하는지 모르겠네요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +    }
Square 라는 타입이 있으면 그걸 활용하는 게 좋습니다. 
그걸 구분하기 위해서 `enum ModelType`을 선언하기 보다는 `ModelType` 자리에 메타 타입을 활용해보세요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +        case square(model: Square)
뷰에 대한 팩토리에서도 switch 분기문보다는 그냥 개별 팩토리 메소드가 있는 게 어떨까요?
새로운 뷰가 추가되면 enum도 추가해야 하고, switch도 추가해야 하고, Square와 관련이 없는 코드를 추가해야 하는데도 SquareView 생성하는 부분이 다 수정하게 될 것 같은데요?

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +    func make(type: ViewType) -> SquareView {
그리고 사각형 중에서 정사각형을 의미하는 Square를 의도한건가요? 일부러 직사각형과 다른 정사각형만 만드는 건가요?

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/TypeDataFactory.swift
> +class TypeDataFactory {
팩토리도 타입별로 있는게 좋습니다. 
Id, Size, Point, Color, Alpha가 서로 다른 타입이면 서로 다른 팩토리가 더 이상적입니다.
아무 밀첩하게 관련된 타입들인 경우만 합치는 게 좋습니다.

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Alpha.swift
> +    case zero, one, two, three, four, five, six, seven, eight, nine, ten, max
zero 부터 max까지 있는 것은 좋네요. 
이런 경우는 생성할 때 zero 나 max도 선택할 수 있을텐데 그래도 되는건가요?
또 하나 one 이 더 투명한 것인지, ten이 더 투명한 것인지 유추할 수 있으면 더 좋겠네요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Color.swift
> +        self.b = b < 0 ? 0 : b > 255 ? 255 : b
타입을 생성할 때 어떤 식으로 구현할지를 선택해야 하는데,  
• 범위를 벗어난 값이 들어와도 범위로 잘라서 만들어 줄 것인가  
• 혹은 아예 만들어지지 않도록 예외처리를 할 것인가  
• 아예 넣지도 못하도록 할 것인가  
여러가지 방법이 있습니다. 그 중에서도 개발자들이 실수를 줄일 수 있고, 런타임에 실행하지 않고 컴파일 타임에 점검할 수 있으면 가장 좋습니다. 참고하세요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        var updateSquare: (Square) -> Void = { _ in }
이런 메소드들을 각각 클로저로 선언하는 방법 말고 프로토콜로 추상화해보고, 그걸 다른 타입이 채택해서 구현하도록 해보세요
그러면 action, state 속성도 상위에서 지정할 수 있을 겁니다

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +    private var selectedSquare: Square?
Plane이 팩토리를 가지기 보다는 팩토리는 분리해놓고, Plane에게 생성한 모델을 추가하는 방식은 어떨까요?

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        }
Plane의 역할이 뷰 컨트롤러나 유즈 케이스를 담당하는 객체가 할 일을 포함한 것처럼 보입니다
Plane이 모든 시나리오를 담당할 필요는 없지 않을까요?

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +    init(id: String, point: Point = Point(x: 100, y: 100), size: Size = Size(width: 150, height: 120), color: Color = .black, alpha: Alpha = Alpha.ten) {
이런 하위에 데이터를 저장하는 타입은 기본값을 지정하는 것도 조심할 필요가 있습니다
특히 팩토리가 있는 경우는 굳이 기본값이 없어도 팩토리가 챙겨줄 가능성이 높구요. 
지정 생성자에는 초기값을 추기보다는 간편 생성자를 지원하는 게 더 스위프트 다운 방식입니다

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +        color = Color(r: colorValues[0], g: colorValues[1], b: colorValues[2])
changeRandomColor() 같은 함수는 테스트 하기 어려운 함수입니다. 지난 수업에서 랜덤값을 테스트하는 구조를 참고해보세요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +        self.alpha = Alpha(rawValue: Int(alphaValue)) ?? .ten
update(alpha:) 매개변수고 Alpha를 사용하는 게 어떨까요?

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +        UIColor(red: CGFloat(color.r) / 255, green: CGFloat(color.g) / 255, blue: CGFloat(color.b / 255), alpha: alpha.value)
Square를 UIKit에 독립적으로 만드는 게 이번 미션의 핵심 사항 중에 하나입니다

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +        let hexColor: String
InspectorData 이게 어떤 타입인지 이름으로 유추해서 역할을 잘 모르겠습니다.
alpha와 hexColor를 포괄하는 이름이나 역할을 의미해줘야 할 것 같습니다
하위 값이더라도 String 보다는 선언한 타입을 활용해보세요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Squares.swift
> +    }
이건 그냥 배열과 다를바가 없는 것 같습니다. 모든 배열을 항상 이렇게 일급콜랙션으로 만들라는 건 아닙니다. 
내부에서 요소에 처리해야 줘야 하는 메소드가 제공되지 않으면 그냥 배열과 차이가 없으니까요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/Base/BaseView.swift
> +class BaseView: UIView {
이 BaseView도 그냥 UIView가 대신해도 되지 않을까요? 
하위에 공통 요소가 없는 것 같습니다

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/DrawingBoard/Item/SquareView.swift
> +        frame = model.rect
SquareView가 모든 속성이 필요한 게 아니라면 Square 특정 속성에만 접근할 수 있는 방법도 고려해보세요. 어떤 방법이 있을까요?

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/Inspector/InspectorView.swift
> +        }
뷰가 Plane에 직접적으로 알고 있을 필요는 없습니다. 
뷰는 뷰컨트롤러까지만 알고 있는게 좋습니다.

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/Inspector/ItemView/InspectorItemButtonView.swift
> +    }
이 클래스는 Button을 포장한 셈인데 상속하지 않고도 할 수 있을 것 같은데, 더 헷갈리고 복잡해진 게 아닌가 싶기도 하네요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/Inspector/ItemView/InspectorSliderView.swift
> +    override func bind() {
override라면 super.bind()가 전혀 필요없는 걸까요?

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/Inspector/ItemView/InspectorSliderView.swift
> +    }
InspectorSliderView는 커스텀뷰를 만든 셈이네요. 이런 시도는 좋습니다

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/TopMenu/TopMenuBarView.swift
> +        makeSquare.heightAnchor.constraint(equalToConstant: 50).isActive = true
다시 보니 BaseView를 상속받아서 attribute() layout() 메소드로 하위 뷰들을 채워주고 있는데
이런 메소드들이 UIView에서 기존에 제공해주는 것과 연결고리가 없네요
UIView 동작 방식을 학습하고, 대체할 수 있는 메소드가 있다면 새로 만들지 않고 그걸 쓰면 좋을 것 같습니다

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/TopMenu/TopMenuItemView.swift
> +            self.buttonEventHandler()
UIAction을 사용하면 좋은 점은 이렇게 buttonEventHandler를 클로저로 받지 않고 UIAction을 그대로 받을 수 있다는 점입니다
그 점도 고려해보세요

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +        inspectorView.bind(plane: self.plane)
모든 뷰를 Plane에 바인드하는 방향인데, 직접 연결하기 보다는 뷰 컨트롤러가 받아서 전달해주는 게 어떨까요?

2022-03-03 07:18 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            self.squareViews[square.id] = drawView
presentation 역할을 하는 이런 동작은 좋습니다만 State에서 언급한 내용을 확인해보세요

2022-03-03 07:19 UTC, shingha1124 commented
넵  리뷰 감사합니다 !! 천천히 보면서 수정해보겠습니다!

2022-03-03 07:20 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +class DrawingModelFactory {
제거 가능합니다 ! 몇번 수정하면서 남아있던 잔재물같습니다

2022-03-03 07:22 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +        case square(model: Square)
엇 리뷰내용을 보니 또 그런거 같기도 합니다. 
사용하는 부분에서 간단히 enum으로 인자를 주어 처리하려고 했는데 
그냥 함수로 만들어서 호출하는게 더 심플할것 같네요

2022-03-03 08:12 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +    init(id: String, point: Point = Point(x: 100, y: 100), size: Size = Size(width: 150, height: 120), color: Color = .black, alpha: Alpha = Alpha.ten) {
넵 초기값 지정 부분 제거 했습니다~

2022-03-03 09:21 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/TypeDataFactory.swift
> +class TypeDataFactory {
각 타입별로 팩토리를 만들었씁니다

2022-03-03 09:23 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +        color = Color(r: colorValues[0], g: colorValues[1], b: colorValues[2])
지난 수업을 참고하여 컬러를 만들때 필요한 [int] 랜덤값으로 뽑고,
제너레이션 프로토콜을 제작하여 원하는 테스트를 진행 할 수 있도록 수정했습니다.

2022-03-03 09:27 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +        self.alpha = Alpha(rawValue: Int(alphaValue)) ?? .ten
이 부분이 저도 만들면서 애매했었는데
view->컨트롤러로 이벤트 발생하여 데이터를 넘겨줄때,(ex> alpha, 슬라이더값은 float, 컨트롤러는 Alpha)
컨트롤러에서 사용하는 데이터 타입으로 보낼것인지? ( 뷰에서 float->Alpha 변환 후 컨트롤러 이벤트)
원래 데이터로 보내고 컨트롤러에서 변환하여 쓸것인지? ( 뷰에서 float로 컨트롤러 이벤트를 보내고 컨트롤러에서 변환)
어느시점에서 변환을 하고 보내는게 나은지 애매합니다 ㅠ

2022-03-03 09:29 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +        let hexColor: String
InspectorData 는
인스펙터 뷰에서 사용 할 데이터들을 따로 모아서 관리하고자 하여 생긴 구조체 입니다
사각형데이터를 보내 그곳에서 하나하나 파싱해서 쓰기보다는 구조체로 하나만들어서 보내면 어떨까 싶어
제작해보았습니다

2022-03-03 09:32 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Square.swift
> +        UIColor(red: CGFloat(color.r) / 255, green: CGFloat(color.g) / 255, blue: CGFloat(color.b / 255), alpha: alpha.value)
해당 부분 제거하였습니다!

2022-03-03 09:33 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Present/View/DrawingBoard/Item/SquareView.swift
> +        frame = model.rect
뷰를 상속받지 않고,  SquareView 안에서 뷰를 추가하고 사용하면 될것 같습니다
수정해보겠습니다.

2022-03-03 09:44 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Present/View/TopMenu/TopMenuItemView.swift
> +            self.buttonEventHandler()
클로저 부분을 제거하고, TopMenuItemView의 상위 뷰인 TopMenuBarView에서 버튼의 액션을 설정해 처리하도록 수정하였습니다

2022-03-03 13:43 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        var updateSquare: (Square) -> Void = { _ in }
우선 기존에 클로저로 바인딩 하던 부분을 걷어내고, 프로토콜을 사용해 보았습니다

2022-03-03 13:47 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Present/View/Inspector/InspectorView.swift
> +        }
모델을 넘겨주어 바인딩 하는 부분을 제거 하였습니다!

2022-03-03 13:49 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Present/View/Inspector/ItemView/InspectorItemButtonView.swift
> +    }
인스펙터 창에서 아이템을 보여줄때 타이틀 + 버튼,슬라이드 등을 보여주기위해 
InspectorItemView 에서 title을 가지고 있고, 이를 상속받아 사용 할 수 있도록 구현해보았습니다.

2022-03-03 13:51 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +        inspectorView.bind(plane: self.plane)
클로저 바인딩을 제거하고, 
인스펙터, 탑메뉴바, 드로잉 바에 delegate를 주어 ViewController가 받아서 Plane로 전달하도록 수정했습니다

2022-03-03 14:10 UTC, shingha1124 commented
## 리뷰 체크리스트

- [ ] ModelType 자리에 메타 타입을 활용
- [ ] 모델명 Square를 좀더 명확한 표현으로 변경하기
- [ ] 알파 enum 조금 더 명확한 표현으로 변경
- [ ] Plane이 팩토리를 가지기 보다는 팩토리는 분리해놓고, Plane에게 생성한 모델을 추가하는 방식
- [ ] Plane이 모든 시나리오를 담당할 필요는 없음

------

- [x] 팩토리 내부에서 스위치 문으로 작성해 놓은 부분 개별함수로 제작
- [x] 여러타입을 한 팩토리에서 생성하던 부분 각 팩토리로 분할
- [x] 컬러타입 생성 시 어떻게 처리할지 고민하기
  * 0~255사이의 값이 아니라면 Color값이 생성되지 않도록 함
- [x] viewController <-> Plane 연결 간 클로저로 이용하던 부분 delegate로 변경
- [x] 데이터 init시 초기값을 강제로 지정
- [x] Color 랜덤 값으로 생성 시 테스트 할 수 있도록 구현
  * RandomColorGenerator을 사용하여 랜덤값도 테스트 할수 있도록 제작
- [x] update(alphaValue: Float)함수의 인자값을 Alpha를 받도록 변경
- [x] Square를 UIKit에 독립적으로 만들기
- [x] Squares 클래스 제거
- [x] BaseView 클래스 제거
- [x] SquareView가 모든 속성이 필요한 게 아니라면 Square 특정 속성에만 접근할 수 있는 방법도 고려
  * SquareView가 uiview를 상속받지 않고, 내부의 프로퍼티로 뷰를 구현
- [x] 뷰가 Plane에 직접적으로 알고 있을 필요없음
  * 직접 참조하던 부분 모두 제거
- [x] UIAction을 사용하면 좋은 점은 이렇게 buttonEventHandler를 클로저로 받지 않고 UIAction을 그대로 받을 수 있음
  * 클로저를 제거하고 UIAction을 사용하여 처리
- [x] 모든 뷰를 Plane에 바인드하는 방향인데, 직접 연결하기 보다는 뷰 컨트롤러가 받아서 전달
  * 각 뷰에서 Delegate를 생성하여, ViewController에서 받은 후 Plane로 전달

2022-03-04 01:43 UTC, godrm approved these changes
전반적으로 개선이 잘 된 것 같습니다. 수고하셨습니다 👍

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/SizeFactory.swift
> +        Size(width: 150, height: 120)
특히 이런 고정된 값으로 생성하는 경우는 이름을 일반적인 것보다는 좀 더 구체적으로 명시하는 게 좋습니다

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +        squareView.update(in: square)
이걸보면 SquareView가 square 전체를 참조하는 것처럼 보입니다.
팩토리가 모든 것을 할 필요는 없구요
꼭 필요한 값들만 준다거나 타입이 다를 수 있으니 변환을 하거나 형태를 맞춰서 Presentation을 위해 값 전달해주는 것을 어떻게 할지 같이 고민해보시면 좋겠습니다.

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +}
확실히 개별 클로저보다는 프로토콜로 묶어놓으니 더 관련이 있는 것처럼 보이네요

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +    func alphaChanged(alpha: Alpha?)
프로토콜도 입력이라고 다 같은 것은 아닐수 있습니다. 
점차 이런게 늘어나게 될텐데 관련있는 것끼리 묶어보려고 노력하세요

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +    private var selectedSquare: Square?
선택된 항목을 구현할 때도 개별 참조를 만들것인지, squares 내부에서 선택된 것을 찾거나 고를 것인지도 고민해보세요

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        self.delegate?.didDisSelectedSquare(to: self.selectedSquare)
self.selectedSquare nil인 경우는 별 문제 없을까요?

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +    func makeSquareButtonTapped() {
이런 메소드 이름을 정할 때, UI에서 처리하는 내용을 그대로 Plane에서 알 필요는 없습니다
`어떤 버튼 눌러서 Plane에 무엇을 요청하느냐`는 뷰 컨트롤러 관점에서 결정되는 내용이라고 생각하세요
다시 말해서 Plane에서는 (어떤 화면을 처리해야 하지보다) 무엇을 해야하는지에 더 관심을 가지는 게 좋습니다.

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/DrawingBoard/View/SquareView.swift
> +        view.alpha = alpha
위에도 언급한 것 같은데 하위 모델을 모두 가져와서 처리하기 보다는,
필요한 값만 가져오고 원하는 형태로 바꾸는 것은 Presenter의 역할입니다. 
View는 Presenter가 꾸며주는 데로 그리는 역할에 집중해보세요. 
아마 Square말고 다른 뷰가 더 생기면 조금 더 감이 잡힐 겁니다

2022-03-04 01:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +    }()
만약 뷰 컨트롤러 뷰에 추가할 내용이 길어진다 싶으면, 여기 뷰를 생성하는 것도 Custom View로 묶어서 
PlaneView 같은걸 하나 만들어 버리고 옮길 수 있습니다. 참고하세요

2022-03-04 01:43 UTC, godrm commented on Drawingapp/DrawingappUITests/DrawingappUITests.swift
> +        XCTAssertEqual(randomGenerator.ramdomValue[2], color.b)
UI 테스트는 단위 테스트랑 다르게 뷰를 찾아서 동작을 확인하게 되는데요 
여기는 단위 테스트와 UI 테스트가 섞여 있는 것 같습니다
우선은 UI 테스트는 제외하고, 단위 테스트로 모델의 동작을 확인하는 데 집중하셨으면 합니다

2022-03-04 01:43 UTC, merged

2022-03-04 01:47 UTC, shingha1124 commented on Drawingapp/DrawingappUITests/DrawingappUITests.swift
> +        XCTAssertEqual(randomGenerator.ramdomValue[2], color.b)
앗 어쩐지....뭔가 테스트를 돌리는데 앱이 계속실행되고 하는게 보였는데
UI테스트에서 진행하고 있엇네요 ;;;

2022-03-04 02:27 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        self.delegate?.didDisSelectedSquare(to: self.selectedSquare)
생각해보니... 굳이 옵셔널을 안붙이고 처리할 수 있을것 같습니다
선택된 사각형을 알려주는 함수인데 옵셔널로 보내는것도 이상하긴합니다
수정해보겠습니다