[Alex] Step1 리펙토링
codesquad-members-2022/swift-drawingapp pull request #25
Opened 2022-03-03 11:04 UTC by SongTaehwan

피드백해주신 부분을 반영해보았고 Factory 부분을 리팩토링 해보았습니다.

코드에 코멘트로 질문을 남겨두겠습니다.

이번 PR 은 바로 Merge 하지 않고 피드백 적용 후 Merge 요청을 따로 드리고 싶습니다.

2022-03-03 11:11 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Model/Color.swift
> +    }
배경 - 지정생성자를 매개변수(Double)의 범위에 대한 유효성 검사를 하기 위해 failure init 으로 변경하였습니다.
문제 - `static let black = Color(red: 0, green: 0, blue: 0)` 프리셋을 `!` 붙여야하는 문제가 생겼습니다.
해결 - 프리셋 생성을 목적으로 별도의 지정생성자를 만들었습니다.
질문 - 이 경우는 별도의 생성자를 만들기보다 차라리 강제 언래핑을 하는 것이 더 나은 선택일까요?

2022-03-03 11:24 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Utility/TypeFactory.swift
> +        return Color(red: red, green: green, blue: blue) ?? .white
배경 - failure init 으로 Color 인스턴스 생성

문제 - failure init 으로 인해 매번 사용할 때 마다 옵셔널의 가능성을 염두해야하는 것이 불편하게 느껴집니다.

의견 - 유효하지 않은 범위의 인자를 넘길 경우 생성자 안에서 별도의 default 값을 지정하는 것도 괜찮을 것 같다는 생각이 듭니다.

질문
이전 피드백 중 default 값을 팩토리에서 처리하라고 하셨습니다. 
이러한 이유는 생성자에서 default 값을 주는 것이 `(default 값을 얻을 수 있음을 알지 못할 가능성이 내포된)` 편의성을 제공하는 것 보다 차라리 실패하는 것이 사용자(다른 개발자)로 하여금 동작의 결과를 예측할 수 있게 하기 위함인가요? (함수의 동작을 예측 가능한 범위에 두어 오류 가능성을 줄이기 위함)

2022-03-03 11:37 UTC, SongTaehwan commented on DrawingApp/DrawingApp/ShapeFactory.swift
> +}
베경 - 랜덤한 Color, Size, Point 를 생성하는 방식이 비슷하고 해당 함수들의 역할이 비슷한 같아 프로토콜로 추상화하여 별도의 팩토리를 만들어 리팩토링을 시도했습니다.

문제 - 공통점이 있다고 해서 항상 프로토콜로 추상화하는 것이 변수명을 짓거나 리턴 타입을 지정하는데 제약이 되고 의도가 불분명해지는 것 같아 불필요하다는 생각이 들었습니다. 

질문 - 프로토콜을 제거하고 각각 독립된 팩토리로 구현하는 것이 더 나은 방법인 것 같아보이는데 JK 의 의견이 궁금합니다.

2022-03-03 11:49 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
배경 - 유효하지 않은 인덱스로 배열에 접근할 때 앱이 꺼지는 것 처럼 Subscript 도 같은 맥락에서 접근하는 것이 좋을지 의문이 들었습니다.

의견 - 앱이 꺼지는 것보다 별도로 에러는 던지거나 옵셔널을 리턴하는 방식으로 처리하는 것이 적절한 것 같다는 생각이 듭니다. JK 의 생각은 어떠신지 궁금합니다.

2022-03-04 02:29 UTC, godrm requested changes
다음 피드백을 확인해보시고 수정할 내용이 있는지 판단해보세요
요청하신 데로 머지하지 않겠습니다 :)

2022-03-04 02:29 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
subscript도 위험할 수 있죠. 그래서 Index도 Int가 아니라 타입으로 만들어서 유효한 범위만 접근하도록 하는 게 좋습니다. 
당연히 크래시가 나기 쉬운 것보다는 안전하게 처리하는 게 좋습니다 
그게 subscript든 아니든 마찬가지 입니다.

2022-03-04 02:29 UTC, godrm commented on DrawingApp/DrawingApp/Utility/TypeFactory.swift
> +        return Color(red: red, green: green, blue: blue) ?? .white
타입의 init은 그걸로 만들어지는지 아닌지 확인할 수 있는 게 좋습니다. 범위가 없다면 괜찮지만 안전한 범위가 있다면 실패한 것을 인지시켜주는 게 중요하죠
팩토리는 역할이 좀 다른데요, 자주 쓰는 타입들이나 값들을 init에 대신 값을 넣어서 바로 쓸 수 있도록 해주는 거니까요
특정 타입들은 팩토리 기능을 static 하게 포함하기도 합니다. `CGPoint.zero` 나 `UIColor.black` 처럼 타입이 특정한 값을 바로 생성해주기도 합니다. 
생성자 안에서 디폴트 값을 지정해버리는 것은 지정 생성자보다는 간편 생성자로써 편의 기능이지, 그 타입을 생성하는 고유 권한이 아니라는 맥락입니다. 
옵셔널로 nil이 될 수 있으면 어쩔 수 없이 부가적인 코드가 생길 수 있지만, 타입을 안전하게 생성하는 게 더 중요한 겁니다. 내가 원하는 값으로 생성되지 않은 것을 인지하지 못하고 사용하는 게 논리적인 버그가 되서 더 위험하다는 겁니다.

2022-03-04 02:29 UTC, godrm commented on DrawingApp/DrawingApp/Utility/TypeFactory.swift
> +        let y = Double.random(in: range, digits: 2)
제네릭 알고리즘은 형태가 동일하고, 동작 방식이 동일하고, 단지 타입만 다를 때 사용하는 거죠
PointFactory.makeType()과 SizeFactory.makeType()이 동일한 알고리즘일까요? 이름만 같은걸까요?
일반화는 되어있다보니 아쉽게도 makeType()는 어떤 값으로 타입을 만들어주는 지 정보가 부족합니다. 
랜덤으로 값을 생성하는 것인지, 원점 좌표를 생성하는 것인지, 100x100 크기를 생성하는 것인지 모르겠습니다
일반화의 목적은 모든 코드를 동일하게 만들자가 아닙니다. 동일한 것을 동일하게 부르자인거죠
무언가 생성하는 것을 일반화하면 이렇게 부를 수 있겠지만, 좀 더 구체적인 동작을 표현하는 게 저는 더 좋겠다고 생각이 드네요

2022-03-04 02:29 UTC, godrm commented on DrawingApp/DrawingApp/Utility/TypeFactory.swift
> +        }
타입이 다르면 파일도 분리하는게 좋겠습니다. 
그럴 경우 프로토콜은 어느 파일에 위치하는 게 좋을까요?

2022-03-04 02:29 UTC, godrm commented on DrawingApp/DrawingApp/Utility/ShapeFactoryCluster.swift
> +    static func makeShape(by type: ShapeType) -> Shapable {
enum ShapeType 타입을 고르기 위한 타입을 선언하는 것은 좋지 않습니다
새로운 타입을 선언할 때마다 코드를 고쳐야 하기 때문이죠 
메타 타입에 대해서도 학습해보시기 권해드립니다. 타입을 선언하면 그 자체를 활용할 방법이 있습니다

2022-03-04 06:33 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Utility/ShapeFactoryCluster.swift
> +    static func makeShape(by type: ShapeType) -> Shapable {
메타 타입을 활용하는 방법이 있군요! 한번 적용해보겠습니다!

2022-03-04 06:45 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Utility/TypeFactory.swift
> +        }
채택하고 있는 타입이 많은 경우에는 별도의 파일로 분리하는게 좋다는 생각이듭니다.

2022-03-04 06:50 UTC, SongTaehwan commented
피드백 적용해보았습니다.
이번에는 Merge도 부탁드립니다 :)

2022-03-04 07:00 UTC, godrm approved these changes
피드백 반영은 잘 된 것 같습니다. 다음 단계를 하면서 또 진행해보세요

2022-03-04 07:00 UTC, godrm commented on DrawingApp/DrawingApp/Model/Color.swift
> +        }
이런 경우는 guard 로 early exit도 적당할 것 같네요

2022-03-04 07:00 UTC, godrm commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +    init(id: String, x: Double, y: Double, width: Double, height: Double, color: Color = .white, alpha: Alpha) {
보통은 생략가능한 default 값이 제공되는 Color 같은 것을 맨 마지막에 해야 생략해도 표현이 명확한 경우가 많습니다. 참고하세요

2022-03-04 07:00 UTC, godrm commented on DrawingApp/DrawingApp/Model/Shapable.swift
> +    var alpha: Alpha { get }
프로토콜을 추상화할 때 모든 값이 다 필요한가는 항상 고민하셔야 합니다
프로토콜도 관련있는 것끼리 표현하고 꼭 필요한 것만 가져가도록 하는게 좋습니다
특히 id 같은 건 가져가지 않아도 Equatable 채택도 했으니 처리할 방법이 있을꺼 같네요

2022-03-04 07:00 UTC, godrm commented on DrawingApp/DrawingApp/Utility/ShapeFactoryCluster.swift
> +    }
클러스터로 만들 때도 무엇을 생성할 지 타입을 지정하는 게 아니라,
하위에 여러 타입들 중에서 하나로 만들어지는 경우가 보통입니다. 
외부에서 타입을 지정해서 생성하거나 값에 따라 하위 타입이 만들어지는 거죠. 
`enum ShapeType` 처럼 타입에 대한 값을 지정하지 않습니다

2022-03-04 07:00 UTC, godrm commented on DrawingApp/DrawingApp/Utility/SizeFactory.swift
>          let height = Double.random(in: range, digits: 2)
요구사항에서 size는 랜덤 생성이 아니지 않았어요?

2022-03-04 07:00 UTC, merged