[Damagucci-Juice] step1 아이패드 드로잉 앱 프로젝트
codesquad-members-2022/swift-drawingapp pull request #26
Opened 2022-03-03 12:12 UTC by Damagucci-Juice

# 작업 목록
- [x] 시스템 로그 사용하여 Rectangle 객체 로깅 
    - [ ] `console.app`으로 추적엔 실패, 대신 xcode 내에 console에 남음
- [x] size를 제외한 point, color, alpha, uuid등에 랜덤값 설정
- [x] Factory 클래스를 이용해서 RectangleView 인스턴스를 생성(이름만 View이지, UIKit 도입 안하였습니다.)
- [x] 모델 클래스 파일은 Core Graphics나 UIKit에 독립적인 타입으로 선언한다. (해당 프레임워크를 import 하지 않아야 한다)

# 고민과 해결

## Think1. 열거형에서 switch문을 이용해서 조건이 맞으면 스스로를 return하는 방법

`alpha` 열거형 내부에 스스로를 반환하는 메서드를 만들고자 하였습니다. 무언가 코드가 중복이 되서 상위 클래스에서 랜덤값을 주도록 설정하였습니다. 그러나 무언가 미봉책에 지나지 않는듯한 느낌을 받았습니다. 좀 더 근원적으로 해결하는 방법이 궁금합니다.

# 질문거리

## Q. `os_log`를 사용해서 xcode 내에 콘솔에는 시스템 로그가 찍히는데 `console.app` 에서는 검색이 안되는 문제
블로그를 검색중에 간단하게 시도해보는 방법이 있어서 console.app에서 테스트를 해보는데 안나와서 일단은 접어두고 xcode console에서만 진행을 했습니다. console.app에서도 os_log를 볼 수 있는 방법이 있을까요?

# 구현 상황

![image](https://user-images.githubusercontent.com/50472122/156562405-f07d43dc-e2a6-4b82-81de-cb4ac1381613.png)

2022-03-03 12:33 UTC, Damagucci-Juice commented on DrawingApp/DrawingApp/Factory.swift
> +        }
이 부분에서  셀프를 반환하는 방법을 잘 몰랐는데 찾게되어 남깁니다.
```
enum OnOffSwitch: Togglable {
    case off, on
    mutating func toggle() {
        switch self {
        case .off:
            self = .on
        case .on:
            self = .off
        }
    }
}
var lightSwitch = OnOffSwitch.off
lightSwitch.toggle()
// lightSwitch is now equal to .on
```
이런 방식으로 Alpha 열거형 안에서 랜덤한 값을 내보내는 메서드를 설정해줄 수 있을 듯합니다.

2022-03-03 12:36 UTC, Damagucci-Juice commented on DrawingApp/DrawingApp/Factory.swift
> +        }
위에 쓴 메모와 상동하는데 예를들어 
```
enum Alpha: Int {
    case 어쩌구저쩌구
    mutating func randomAlpha()  {
    // some codes
    }
}
```
하고 `var alpha = Alpha().randomAlpha()` 로 수정해보겠습니다.

2022-03-04 02:33 UTC, godrm commented on DrawingApp/DrawingApp/Factory.swift
> +        }
`Alpha().randomAlpha()` 처럼 이미 init()을 거친 뒤에 다시 random을 바꾸는 것보다는
`Alpha.random()` 형태로 인스턴스를 만들지 않고 랜덤한 인스턴스 값을 만들어주는 형태로 접근해보세요. 
결국 그게 팩토리 메소드가 됩니다

2022-03-04 02:36 UTC, godrm requested changes
다음 피드백을 확인하시고 타입의 선언과 생성 부분을 팩토리로 분리해보세요

2022-03-04 02:36 UTC, godrm commented on DrawingApp/DrawingApp/AppDelegate.swift
> +    }
사용하지 않는 함수나 주석은 과감하게 지우셔도 됩니다

2022-03-04 02:36 UTC, godrm commented on DrawingApp/DrawingApp/Factory.swift
> +        }
데이터를 보관하는 역할을 하는 타입과
그 타입에 필요한 값을 결정해서 넘겨주는 것과 구분해보세요
지금 팩토리라는 것은 이런 값을 생성하거나 지정하기 위한 다른 타입을 말하는 겁니다.

2022-03-04 02:36 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +            os_log("\(rectangle.description)")
os_log도 콘솔에서 확인할 수 있지 않던가요?

2022-03-04 02:50 UTC, Damagucci-Juice commented on DrawingApp/DrawingApp/AppDelegate.swift
> +    }
미쳐 확인 하지 않고 지나간 부분이네요! 수정하겠습니다.

2022-03-04 02:54 UTC, Damagucci-Juice commented on DrawingApp/DrawingApp/Factory.swift
> +        }
혹시, 지금 팩토리 클래스 안에 랙탱글 클래스가 있는데, 이를 분리하고 팩토리 안에는 랙탱글에 랜덤값을 넣어서 생성하는 역할만 남기게끔 하라는 말씀이실까요?

2022-03-04 02:56 UTC, godrm commented on DrawingApp/DrawingApp/Factory.swift
> +        }
아.. 여기가 Factory인가 보군요. Rect 인줄 알았네요. computed property라서 헷갈렸나봅니다
팩토리는 보통 자신의 인스턴스를 만들지 않고 필요한 타입만 생성하는 static 메소드 형태로 끝나는 경우가 많습니다
랜덤하게 생성하는 거라면 그런 의미로 메소드로 만들어보세요. 
computed property는 다른 속성을 기반으로 만들어지는 값을 속성처럼 처리하기 위한 겁니다

2022-03-04 03:02 UTC, Damagucci-Juice commented on DrawingApp/DrawingApp/ViewController.swift
> +            os_log("\(rectangle.description)")
![xcode_os_log](https://user-images.githubusercontent.com/50472122/156691134-78265e0c-78dc-4564-af1a-8fdcd9bc6987.png)

<img width="1410" alt="console_os_log" src="https://user-images.githubusercontent.com/50472122/156691169-4f444246-53bf-462a-a768-f52eb12fbca7.png">

일단은 확인이 되지 않고 있는데 무엇을 잘못했을까요?

2022-03-04 03:10 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +            os_log("\(rectangle.description)")
Xcode에 찍힌걸 보면 검색한 rectangle 문자열은 없는것 같은데요? 🤔

2022-03-04 04:59 UTC, Damagucci-Juice commented on DrawingApp/DrawingApp/ViewController.swift
> +            os_log("\(rectangle.description)")
그러네용 ! 감사합니다 !❤️

2022-03-04 05:51 UTC, Damagucci-Juice commented on DrawingApp/DrawingApp/Factory.swift
> +        var  id: String {               // UUID: xxx-xxx-xxx
# 작업 내용 
- [x] Factory 클래스와 Rectangle 구조체 분리
- [x] Factory에서는 랜덤한 밸류를 생성해서 Rectangle 구조체를 생성하는 역할에 집중

2022-03-04 05:57 UTC, godrm commented on DrawingApp/DrawingApp/Rectangle.swift
> +    }
하위 타입으로 선언하는 것도 좋은 시도입니다만
일반적으로 사용이 될지 아니면 정말 그 타입에만 속하는 것인지도 예측은 시도해보세요

2022-03-04 05:57 UTC, merged