[ebony] - Step2 propertychange
codesquad-members-2022/swift-drawingapp pull request #30
Opened 2022-03-04 03:26 UTC by rising-jun

### 커밋된 코드가 너무 많아지지 않도록 여러번에 나눠서 PR요청 하겠습니다!

#### 🧑🏼‍💻 작업 목록
- [x] 생성한 사각형 객체를 포함하는 Plane 구조체를 구현한다.
- [ ] Plane 구조체를 테스트하는 유닛테스트를 추가한다.
- [ ] 실행하고 새로운 화면을 캡처해서 readme.md 파일에 포함한다.
- [x] 우측에 선택한 사각형 속성을 변경하면 바로 화면에 색상과 투명도가 바뀌도록 구현한다.
터치가 될 때마다 해당 위치에 사각형이 있다면 해당 사각형이 선택되고, 만약 사각형이 없다면 기존에 선택된 다른 사각형도 선택이 취소된다.
- [ ] 사각형 테두리에 선을 표시해서 선택한 것을 인지할 수 있도록 한다. 사각형을 선택하면 화면 우측에 해당 사각형의 현재 배경색과 투명도가 반영된다.
- [x] 배경색 버튼에는 현재 배경색이 R-G-B 순서대로 16진수로 보이며, 버튼을 누를 때마다 랜덤한 추천 색상으로 변경한다.
- [x] 투명도는 10단계로 나눠서 변경할 수 있고, alpha값을 단계로 나눠서 적용한다.
- [ ] 투명도 좌, 우에 버튼은 각각 투명도 단계를 -1, +1 시킨다. 만약 더 이상 작거나 커질 수 없으면 비활성화한다.

#### 💭 학습 키워드
MVC, View - ViewController - Model, Model - ViewController - View의 데이터 흐름, 전달 방법 및 설계
UISplitViewController

#### 👀 고민과 해결
1. MVC에서의 흐름 고민 : View에서 요청이 들어오고, 해당 요청에 맞는 요구사항을 ViewController는 model에 요청합니다. 요청받은 데이터 작업이 끝난 모델은 해당 데이터를 protocol을 통하여 다시 ViewController로 보내고, ViewController는 이를 활용하여 View를 업데이트합니다.
 - protocol을 활용하였습니다.
2. SplitViewController의 View는 어떻게 업데이트 해줘야 할까? : PropertySetViewController에서도 색상을 변경하는 버튼이 있기에 (16진수 랜덤색) 여기에도 Factory를 추가해야 하나 고민하였습니다. 해결 방법으로 DrawingViewController에 "PropertySet에서 랜덤색이 필요해!"라고 DrawingViewController에 전달하였고, DrawingViewController는 Factory에 이를 요청한 후 해당 데이터를 다시 반환하였습니다. 두 ViewController는 SplitViewController에서 서로의 Delegate를 설정해주었습니다.

#### 💡 느낀점
- SplitViewController를 활용하는 방법, 해당 ViewController들이 서로 메시지를 주고 받는 방법 모두를 고민했던 게 가장 기억에 남았습니다.
- step1에서는 데이터 객체에 들어갈 값들을 설계하는데 고민하였다면 이번 스텝에서는 MVC의 흐름을 고민하였습니다.
- 여전히 변수명 함수명 클래스명의 이름이 어색하고 명확하지 않고 살짝 어색하다는 느낌이 듭니다.. 계속해서 디자인api가이드를 확인하고, 개선하려고 노력해보겠습니다!

#### :question:궁금한점
ColorRGB 구조체에서 16진수를 변환하는 변수를 구현하였습니다.
```swift
struct ColorRGB{
    private var hexRGB: String{
        return String(format:"%02X", r) + String(format:"%02X", g) + String(format:"%02X", b)
    }
}
extension ColorRGB: CustomStringConvertible{
    var description: String {
        return "#\(hexRGB)"
    }
}
```
해당 로직을 factory로 빼어둘까? 고민했지만 ColorRGB에서만 사용할 것 같고 간단한 한줄로 끝나는 간단한 로직이라 안에 구현하였습니다.
데이터들 담는 구조체에서 이러한 로직을 구현하는 방법도 괜찮을까요? 아님 안좋은 방법일까요??

감사합니당!

2022-03-04 04:08 UTC, godrm commented
메소드는 필요하면 (그 타입과 관련이 있다면 얼마든지) 구현하는 거죠.

2022-03-04 04:26 UTC, godrm requested changes
뷰 -> 컨트롤러 -> 모델로 들어가는 흐름과 모델 -> 컨트롤러 -> 뷰로 나오는 흐름을 나눠서 처리하도록 개선해보세요.

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/ColorRGB.swift
> +    }
그냥 값을 가져가야 한다면 private(set)을 고려해보면 됩니다만, 컬러값 자체가 아니라 RGB 값을 각각 가져가야 하는 상황들이 있나요?

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/Rectangle.swift
> +    }
값을 가져가야 하는게 당연하게 필요하다면 private(set)으로 처리하셔도 됩니다

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/Plane.swift
> +    }
다른 부분을 좀 더 살펴봐야겠지만, Plane만 보면 역할이 너무 빠져있는 것 같습니다
Rectangle을 추가하고, 가져가는 게 끝이 아니라 어떤 사각형인지 찾거나, 
값이 바뀔 때도 직접 사각형을 가져가서 바꾸는 게 아니라 연결고리가 있어야 합니다

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/ViewPoint.swift
>  }
특히 이런 Size, Point 같은 값만 두는 경우는 값 타입으로 struct - let 정도만 해도 충분합니다.
getter를 따로 구현할 필요가 없습니다.

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/model/RectangleFactory.swift
> +        drawingMessage.addRectangleToPlane(rectangle: rectangle)
팩토리는 필요한 객체의 인스턴스를 생성하는 것에만 집중하면 됩니다
`drawingMessage.addRectangleToPlane(rectangle: rectangle)` 이게 어떤 목적인지 모르겠지만
Plane에 추가할 지 안할지는 여기서 몰라도 되는 겁니다. 
그건 팩토리에게 인스턴스 생성하라고 요청한 모듈에서 필요하면 추가하는거고, 아니면 안하는거죠

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        drawingDelegate?.changedColor(rectangleRGB: color)
이벤트를 처리할 때는 sender 뷰를 찾지마시고, plane에 요청해서 해당 좌표를 처리할 Rectangle을 찾아서 처리하도록 해야 합니다
이벤트를 받으면 데이터 흐름은 하위에 모델로만 흘러가야 합니다
다른 것을 바꾸는 것은 다시 모델에서 거꾸로 거슬러 올라와야 합니다. 두 가지 흐름을 분리하는 게 이번 미션에서 핵심입니다.

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        rectangleFactory?.makeRandomRectangle()
객체를 추가할 때는 팩토리에 요청하고, 생성한 것을 Plane에 전달하는 역할은 해야합니다. 
팩토리가 다른 객체와 직접적으로 연결되면 안됩니다

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +    }
팩토리는 이런 로직의 흐름과 별개로 동작하는 게 좋습니다. 분리해보셨으면 좋겠습니다 
대신 Plane에서 데이터 흐름을 받아서 생성하도록 구현해보세요

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/view/RectangleView.swift
> +    }
이런 메소드는 `RectangleView.init(frame: CGRect.zero)` 로 처리해도 되기 때문에 정말 필요한지는 모르겠네요

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/view/RectangleView.swift
> +        let alpha = rectangle.alphaValue()
뷰가 Rectangle에 모든 속성을 다 가져야 하는 건 아닙니다
뷰에 표시할 때 사용하는 속성만 딱 처리하면 됩니다. 
특히 frame 관련해서는 init(frame:)에서 처리할 수 있지 않을까요? 
뷰를 생성할 때 모델의 모든 값을 알지 않아도 되도록 하는 게 더 좋습니다. 

특히 id는 화면을 그리는 데 필요한 값이 아니죠.
그래서 뷰와 모델을 매칭하는 역할은 둘 다 아는 뷰 컨트롤러가 매칭하는 게 좋습니다.

2022-03-04 04:26 UTC, godrm commented on DrawingApp/DrawingApp/view/SplitViewController.swift
> +        drawingViewController.setDrawingDelegate(drawingDelegate: drawingDelegate)
음.. 델리게이트라도 이렇게 서로 참조하는 구조는 좋은 구조가 아니네요. 
델리게이트는 방향이 단방향이어야 합니다. 서로 참조는 하는 것은 지양하세요
둘이 대등한 관계라면 중간에서 연계하는 상위 모듈이 있어야 합니다. 
그게 SplitViewController 라면 여기서 그 역할을 하셔야 합니다

2022-03-04 04:44 UTC, rising-jun commented on DrawingApp/DrawingApp/ColorRGB.swift
> +    }
없습니다! Private(set)을 활용해보겠습니다!

2022-03-04 04:44 UTC, rising-jun commented on DrawingApp/DrawingApp/Rectangle.swift
> +    }
다른 sturct들도 값을 가져가야 하는 로직이 있다면 private(set)으로 처리해보겠습니다!

2022-03-04 04:44 UTC, rising-jun commented on DrawingApp/DrawingApp/Plane.swift
> +    }
사각형의 속성이 바뀌는 로직과 가져와서 처리하는 로직 모두 plane 안에서 하도록 구현해보겠습니다!

2022-03-04 04:44 UTC, rising-jun commented on DrawingApp/DrawingApp/ViewPoint.swift
>  }
넵 알겠습니다!

2022-03-04 04:44 UTC, rising-jun commented on DrawingApp/DrawingApp/model/RectangleFactory.swift
> +        drawingMessage.addRectangleToPlane(rectangle: rectangle)
아하! 알겠습니다!!

2022-03-04 04:45 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        drawingDelegate?.changedColor(rectangleRGB: color)
넵! 고민해보겠습니다!

2022-03-04 04:45 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        rectangleFactory?.makeRandomRectangle()
넵!

2022-03-04 04:45 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +    }
넵 분리해보겠습니다! 이러한 로직들을 Plane에게 맡겨보겠습니다!

2022-03-04 04:45 UTC, rising-jun commented on DrawingApp/DrawingApp/view/RectangleView.swift
> +        let alpha = rectangle.alphaValue()
넵! 뷰 컨트롤러가 매칭하도록 개선해보겠습니다!

2022-03-04 04:45 UTC, rising-jun commented on DrawingApp/DrawingApp/view/SplitViewController.swift
> +        drawingViewController.setDrawingDelegate(drawingDelegate: drawingDelegate)
아하! 알겠습니다!!

2022-03-06 08:26 UTC, rising-jun commented
- 작업내용
1. 리뷰 해주신 내용들 개선해보았습니다.
2. plane객체가 RectangleFactory를 갖고 있으며, 사각형 속성이 변경되는 로직들을 모두 plane이 하도록 구조를 변경하였습니다.
3. 테스트 코드를 추가하였습니다.

2022-03-07 08:00 UTC, godrm commented on DrawingApp/DrawingApp/model/ColorRGB.swift
>          self.b = b
ColorRGB 인스턴스를 생성하는 관점에서 안전하게 생성됐는지 확인할 수 있어야 합니다.
이 상태에서는 `ColorRGB(r: -1234, g:9999, b: 1234)` 이런 인스턴스가 생기게 되니까요 

타입을 생성할 때 어떤 식으로 구현할지를 선택해야 하는데,  
• 범위를 벗어난 값이 들어와도 범위로 잘라서 만들어 줄 것인가  
• 혹은 아예 만들어지지 않도록 예외처리를 할 것인가  
• 아예 넣지도 못하도록 할 것인가  
여러가지 방법이 있습니다. 그 중에서도 개발자들이 실수를 줄일 수 있고, 런타임에 실행하지 않고 컴파일 타임에 점검할 수 있으면 가장 좋습니다.

2022-03-07 08:01 UTC, godrm commented
대부분 개선이 잘 된거 같네요. 
이제 다음단계에서 Plane과 ViewController 델리게이트 부분을 NotificationCenter로 개선해보세요

2022-03-07 08:01 UTC, merged

2022-03-07 08:08 UTC, rising-jun commented on DrawingApp/DrawingApp/model/ColorRGB.swift
>          self.b = b
넵 고민해보겠습니다!