[Eddy] Step 3: Observer Pattern 적용
codesquad-members-2022/swift-drawingapp pull request #33
Opened 2022-03-04 07:59 UTC by BumgeunSong

## **Screenshot**
![step3](https://user-images.githubusercontent.com/17468015/156721080-a82e45de-b4a4-434e-b78a-280596b8e00d.gif)

## 작업 목록

지난 PR 피드백
- [x] ViewID를 hashMap으로 저장. 검색을 O(1)으로 최적화.
- [x] Random Color 생성 로직을 Plane으로 이동

관찰자 패턴 적용
- [x] Container View Controller와 ContainerVC의 프로퍼티 제거
- [x] Delegate 모두 제거
- [x] Plane, Panel이 notification을 Post하도록 변경
- [x] Canvas, Panel이 Notification을 Observe하도록 변경
- [x] Use case에 따라 View Controller들의 코드 정리

## 학습 키워드
- NotificationCenter
- Notification.Name

## 고민과 해결
- **(고민)** 사각형의 추가나 변경은 잘 되는데, 초기에 4개의 사각형이 View에 뜨지 않는 문제가 있었다. 왜 안 되는지 디버깅을 한참 했다.
- **(해결)** Observer를 등록하는 시점이 문제였다. 초기 Model 업데이트하는 코드 뒤에, Observer를 등록하는 코드가 있었던 것이다. Observer를 먼저 등록하고, 초기 모델을 생성해서 문제를 해결했다.

- **(고민)** Notification에 2개의 객체를 넣으려고 했는데 하나만 지정할 수 있었다.
- **(해결)** 두 객체를 tuple로 만들어서 넘겨준 뒤, 관찰하는 쪽에서 tuple로 type casting을 하도록 해서 해결했다.

- **(고민)** 랜덤 컬러 생성 로직을 모델 쪽으로 넘기려고 시도했다. ViewModel에 Default Parameter를 정하고 Random color로 넣어주려고 했다. 그런데 Protocol로 정의한 View Model의 경우 Default Parameter를 정의할 수가 없다.
- **(해결)** Protocol + Extension 조합을 통해 Default parameter를 구현했다. 처음으로 프로토콜의 구현부를 만들어보았다. 하지만 나중에 보니 Plane으로 로직을 옮기는 게 깔끔해서 결국 코드에서 삭제했다.

2022-03-04 08:03 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
>      }
여기서 나중에 검색할 dictionary를 만들고 viewID: View를 추가했습니다.

2022-03-04 09:09 UTC, BumgeunSong commented
@godrm 이상하게 이번 PR만 슬랙과 연동이 잘 안 되네요.. 제가 뭔가 잘못 설정한 걸까요? 🤔

2022-03-04 09:33 UTC, godrm commented
> @godrm 이상하게 이번 PR만 슬랙과 연동이 잘 안 되네요.. 제가 뭔가 잘못 설정한 걸까요? 🤔

가끔 이벤트가 겹치면 노티가 빠지기도 합니다. 목록에서 보고 있으니 걱정마세요

2022-03-04 10:02 UTC, godrm requested changes
의견을 남겨놓았지만, NotificationCenter 부분들만 수정하면 될 것 같습니다
특히 Name 선언도 어디에 선언하는 게 좋을지 판단해보세요

2022-03-04 10:02 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +    private var viewIDMap = [String: UIView]()
Id를 String으로 쓰기 보다는 Rectangle 타입이 있으면 그걸 Dictionary에 넣어보는 것도 시도해보세요

2022-03-04 10:02 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(colorButtonPressed(_:)), name: .colorButtonPressed, object: nil)
NotificationCenter 학습 영상을 참고해보시구요, object는 sender의 의미입니다. 참고하세요

2022-03-04 10:02 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        guard let newViewModel = notification.object as? ViewModel else { return }
notification에서 object는 sender의 의미이고 observer 매칭에 사용됩니다. 데이터를 보내려면 userInfo을 사용하세요

2022-03-04 10:02 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +    static let mutateAlphaViewModel = Notification.Name("mutateAlphaViewModel")
Notification.Name도 이거끼리 모아놓기 보다는 관련 있는 타입에 선언하는 게 좋습니다
관련있는 타입은 보내는 쪽일까요? 받는 쪽일까요? 어디가 좋을지 판단해보세요

2022-03-06 13:37 UTC, BumgeunSong commented
[개선 사항]
- [x] Notification의 object는 Publisher 객체를 보내도록 하고, userInfo로 필요한 정보를 옮겼습니다.
- [x] Notification.Name을 Publisher 객체의 static let으로 옮겼습니다.

2022-03-06 13:42 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +    }
CanvasViewController가 Plane은 알고 있는 상태, PanelViewController는 모르고 있는 상태입니다.
따라서 matching을 위한 sender 지정은 Plane에만 일단 지정해두고, Panel에는 nil로 정해두었습니다.

2022-03-07 08:03 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(colorButtonPressed(_:)), name: PanelViewController.colorButtonPressed, object: nil)
네 sender를 모르면 object를 지정하지 않아도 됩니다. 
다만 그런 경우는 정말 그 노티를 여기서 처리해야 하는것인가 의심은 해보세요. 
어쩌면 다른 이벤트를 알고 있는게 나을수도 있습니다

2022-03-07 08:04 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        guard let newViewModel = notification.userInfo?["new"] as? ViewModel else { return }
`"new"` 이런 문자열 키값도 상수로 선언해서 실수를 방지하는 게 좋습니다. 
보내는 쪽과 다르면 혼란을 주기도 하거든요

2022-03-07 08:05 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        guard let mutated = plane.selected as? ColorMutable else { return }
이런 경우 guard 하나에 let을 여러줄로 내려서 쓰기도 합니다. 참고하세요

2022-03-07 08:05 UTC, godrm commented
잘 개선이 됐네요.
이전 단계에서 델리게이트를 사용했을 때와 NotificationCenter를 사용한 것과 어떤 차이가 있는지 비교해보면 좋겠습니다.

2022-03-07 08:05 UTC, merged