[shingha] [Step3-1] 관찰자(Observer) 패턴
codesquad-members-2022/swift-drawingapp pull request #39
Opened 2022-03-04 08:49 UTC by shingha1124

## 리뷰 체크리스트

- [x] NotificationCenter 사용하여 ViewController<->Model 연결하기
  * 기존 사용하던 Protocol은 제거

## 질문거리

* NotificationCenter.Post
  * object의 사용 용도
    * 여러 방면으로 테스트를 해보면서 Object가 어떤 역할을 하는것인지 어느정도 감은 잡혔습니다
      그런데 보통 Button을 이용하여 Post를 발생시킨다고 하면, 발생시킨 Button이 Object로 들어가는 것 같은데
    * Object에 Rectangle Model을 넣어서  사용하는 것인지?
      * Rectangle Model을 넣어 넘겨주다고 하면, userinfo에 값을 안넣어도 됨
    * Object에 Rectangle Model의 ID를 넣어서  사용해도 되는것인지?
      * id를 넣으면 userinfo에 변경되는 값만 넣음
    * Object에 Model이 들어가면 id만 볼 수 있게하고 나머지 값은 Private로 변경하여 가려야 하는지?

2022-03-04 08:51 UTC, shingha1124 commented
NotificationCenter을 사용해보면서 질문거리가 생겼습니다!
NotificationCenter.Post의 Object의 값에 어느정도 범위의 타입을 넣어야 하는지??가 궁금합니다

2022-03-06 03:55 UTC, godrm commented
NotificationCenter의 Object는 sender의 의미입니다. 객체나 값을 넘기려면 UserInfo 사전을 활용하세요
어제 올린 학습 강의 영상을 참고하시면 됩니다.

2022-03-06 04:05 UTC, godrm requested changes
이전에 만든 프로토콜 채택하고 구현해서 바인딩하는 방식과 NotificationCenter로 처리하는 방식을 비교해보면 어떤 생각이 들었는지도 궁금합니다
피드백 남긴 NotificationCenter 관련 부분만 개선해보세요

2022-03-06 04:05 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Extension/NSNotification.swift
> +    static let updateAlpha = NSNotification.Name("updateAlpha")
여기 노티는 어떤 객체가 보내게 되나요? 각각 관련있는 타입들에서 선언하는 게 좋습니다. 
타입별로 묶기 보다는 관련있는 타입과 묶으려고 노력해보세요

2022-03-06 04:05 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +            NotificationCenter.default.post(name: NSNotification.Name.didSelectedRectangle, object: selectedRectangle)
object는 sender의 의미니까 userInfo와 구분해보세요

2022-03-06 04:05 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        NotificationCenter.default.post(name: NSNotification.Name.drawRectangle, object: rectangle)
노티 이름도 `drawRectangle` 보다는 자신이 어떤 상황이 바뀐건지를 알려주면 됩니다. 
`내가 이렇게 바뀌었어!`를 알려주는 거지 `너 이렇게 행동해`를 보내는 게 아닙니다

2022-03-06 04:05 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        NotificationCenter.default.post(name: NSNotification.Name.updateAlpha, object: rectangle.id, userInfo: ["alpha": rectangle.alpha])
여기서는 object를 rectangle.id를 보냈네요. 
그걸 생각해보세요. Plane이 바뀌었다는 것을 알려주는 것인가 Rectangle이 바뀌었다는 것을 알려주는 것인가

2022-03-06 04:05 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            }
object를 활용하면 아마 이 부분이 좀 바뀔 겁니다

2022-03-06 04:05 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +        }
노티를 보내고 받을 때 딜레마는 userInfo에 얼마나 많은 정보를 보낼 것인가. 그 부분도 고민해보세요
예를 들어 Rectangle을 보낼까, id만 보낼까, 바뀌었다고만 알려줄 것인가

2022-03-06 05:30 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Extension/NSNotification.swift
> +    static let updateAlpha = NSNotification.Name("updateAlpha")
한곳에 두니 각 이벤트들이 누가 호출하는지 모를수도 있겟다 라고 생각됩니다
각각 이벤트 호출 하는 부분의 클래스로 이동했습니다

2022-03-06 05:31 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +            NotificationCenter.default.post(name: NSNotification.Name.didSelectedRectangle, object: selectedRectangle)
센더와 userInfo를 사용하여 수정했습니다

2022-03-06 13:23 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        NotificationCenter.default.post(name: NSNotification.Name.drawRectangle, object: rectangle)
너 사각형그려 -> 내가 사각형을 만들었어 
라는 느낌으로 수정했습니다

2022-03-06 13:23 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        NotificationCenter.default.post(name: NSNotification.Name.updateAlpha, object: rectangle.id, userInfo: ["alpha": rectangle.alpha])
센더부분을 각각 Plane와 Rectangle에서 호출 하도록 구분 해 보았습니다

2022-03-06 13:24 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            }
오브젝트는 이벤트를 발생시킨 sender, userinfo에 내용을 담아 호출 하도록 했습니다.

2022-03-06 13:28 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +        }
이벤트 발생 후 필요한 데이터만 넘겨주도록 수정했습니다

2022-03-06 13:37 UTC, codesquadIOS commented
> 이전에 만든 프로토콜 채택하고 구현해서 바인딩하는 방식과 NotificationCenter로 처리하는 방식을 비교해보면 어떤 생각이 들었는지도 궁금합니다 피드백 남긴 NotificationCenter 관련 부분만 개선해보세요

프로토콜을 채택해서 사용할때
* 사각형의 옵션( 색, 알파)이 변경되어도 이벤트를 호출할 함수들은 Plane에 구현되어 있어 상위에서 이벤트를 호출해야함
* 프로토콜로 구성되어 있기에, 함수이름이나 매개변수를 지정한대로 적어주지 않으면 컴파일 에러가 발생하여 오류 확인이 쉽다
* 프로토콜을 채택한 클래스에서만 이벤트를 받을 수 있다

NotificationCenter
* 인자로 넘어온 값들을 모두 캐스팅을 해서 사용해줘야 한다
* 실제 변화가 된 객체에서 이벤트를 발생 시킬 수 있다
* 이벤트 이름만 매칭된다면 어느곳에서든지 이벤트를 받을 수 있다

프로토콜을 사용하면 이벤트 발생 시점이나, 리시브를 받는쪽의 코드가 자유롭지 못하다고 느꼇습니다.
plane의 delegate에 넣어준 클래스만 이벤트를 받을 수 있었습니다.

NotificationCenter를 이용하면 이벤트를 원하는 곳에서 발생 시킬 수 있고, 받는곳 또한 원하는 위치에서 받을 수 있었습니다.
코드를 짜기 좀더 자유로웠습니다.
매번 전달받은 데이터를 파싱 후 사용해야하는 번거로움이 있었습니다.

2022-03-07 08:13 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +            let userInfo: [AnyHashable : Any] = ["rectangle":selectedRectangle]
여기서 사전에 키로 사용하는 값도 하드코딩하지말고 상수로 선언해서 보내는 쪽과 받는 쪽이 같은 값을 사용하는 게 좋습니다.
그래야 작은 실수로 혼란을 주지 않습니다.

2022-03-07 08:14 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        static let didSelectedRectangle = NSNotification.Name("didSelectedRectangle")
아래 updateColor 나 makeRectangle은 did가 안 붙어있는데 selected만 did가 붙은 이유가 있나요?

2022-03-07 08:15 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            self.rectangleViews[rectangle.id]?.update(color: color)
self.rectangleViews[rectangle.id] 키를 사용할 때는 id 대신 rectangle을 사용하는 건 어떨까요? 무엇이 필요한가 시도해보세요

2022-03-07 08:16 UTC, merged

2022-03-07 08:35 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            self.rectangleViews[rectangle.id]?.update(color: color)
Plane에서 보내는 이벤트인데 ID를 보내는것도 안맞는거 같습니다
Plane에서 ID까지 관리해서 넘겨주는 느낌이네요

2022-03-07 08:37 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +            let userInfo: [AnyHashable : Any] = ["rectangle":selectedRectangle]
넵 해당부분들은 이벤트를 발생하는 클래스에서 상수로 키를 만들어서 사용하도록 수정했습니다.

2022-03-07 08:37 UTC, codesquadIOS commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        static let didSelectedRectangle = NSNotification.Name("didSelectedRectangle")
영어...라 이런부분들 누락이 좀 있습니다 ㅠㅠ...

2022-03-07 08:39 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        static let didSelectedRectangle = NSNotification.Name("didSelectedRectangle")
그럴수 있죠. 의도가 중요하니까요. 형태를 맞춰보면서 습관을 만드는 게 중요합니다.