[Pigbag] Step02_ View그리기, 변경하기, CustomView, Delegate
codesquad-members-2022/swift-drawingapp pull request #41
Opened 2022-03-05 13:57 UTC by P-SeoB

- 동작 

https://user-images.githubusercontent.com/80263729/156886308-82d6e1d0-e710-4465-a9c8-62a43bfc19e3.mp4

- 작업내용
- [X] CustomView 제작 및 배치
- [X] Delegate를 이용한 이벤트 전달
- [X] View와 Model분리
- [ ] MVC패턴 이해 및 적용
- [ ] Unit테스트 

- - -
- 키워드: image configuation, tapGesture, hittest, UITouch, UIAction, Delegate, MVC

- 고민 및 해결
1. 보통 스토리보드로 `outlet`과 `action`을 추가할때 outlet을 View안의 한 요소라고 한다면 하나의 `ViewController Class`안에 
 View와 Controller가 다 있는 것이라고 생각했습니다.그렇다면 CustomView 클래스를 만들어서 `View(outlet)와 Controller를 분리했을때 outlet에 대한 action은 어디다가 선언해야하는가`에 대한 고민이 있었습니다.
공부한 바로는, View에서 사용자의 입력이 들어오면 View가 ViewController에 어떠한 변화가 있다고 알려만 주고  `변화에 대해 처리하는 것은 ViewController가 해야할 일`이라고 이해했습니다.
따라서, CustomView클래스에 있는 각 component들에 필요한 경우 Action을 주되 protocol과 delegate를 이용해서 처리는ViewController에서 하도록 시도해 보았습니다.

2. alpha값이 계속 1.0으로 나오는 오류가 있었습니다.
여러번의 시도끝에 `모델rectangle`이아니라 그, `View의 alpha`를 가지고왔기 때문이고
View의 alpha값은 기본값으로 1.0을 가지고있고 View안에 subView되어있는 rectangle의 alpha를 가지고 와야된다고 결론을 내렸습니다.
수업시간에 들었던 superView와 subView간의 alpha값 관계에 대해서 다시 복습하게 되었습니다.

- - -

- 추가 설명
<img src="https://user-images.githubusercontent.com/80263729/156886394-cec85aef-78e6-4661-8800-3ab7e5745ad7.png" width="100%" height="70%">

Ex) ***배경색 버튼 터치시***
`DetailView(TouchUpButton)` -> `ViewController_delegate(colorButtonTouched) `->
` plane안의 rectangle모델 변경` -> `rectangleView안의 속성 변경`

2022-03-06 04:32 UTC, godrm requested changes
다음 피드백을 확인해보시고,
입력 이벤트에서 뷰 -> 컨트롤러 -> 모델 흐름과 값이 바뀌었을 때 모델 -> 뷰 컨트롤러 -> 뷰까지 출력 흐름을 구분해보세요.

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/++/UIView++.swift
> +        self.accessibilityIdentifier = id
`self.accessibilityIdentifier` 속성은 어떤 의도로 사용한 것인가요? 이미 있는 속성을 활용할 때는 어떤 영향을 줄지 판단해보고 써야 합니다. 아무 값이나 넣어도 되는 건 아닙니다. 
특히 뷰가 Model의 id를 갖고 있어야 하느냐. 생각해볼 필요가 있습니다. 뷰는 그리기 위한 최소한의 정보만 갖고 있으면 됩니다
id 같은 정보는 뷰와 매칭하기 위한 거라면 양쪽다 알고 있는 ViewController가 관리하는 게 좋습니다. 매칭할 수 있도록 관리해보세요.

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/++/UIView++.swift
> +        let height = rect.size.height
convenience init()을 제공하는 것도 좋지만, UIView 자체를 확장하는 것보다는 구체적으로 사각형을 처리하는 경우만 필요하니까 구체적인 타입만 확장하는 게 좋습니다
모든 뷰가 rect와 rgb와 alpha가 필요한 것은 아닐테니까요

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/Factory/AlphaFactory.swift
> +        let randomAlpha = Float.random(in:Alpha.minValue...Alpha.maxValue)
이렇게 보니 Alpha.random()이 있으면 어떨까 상상해봤습니다

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/Factory/PointFactory.swift
> +        let detailViewWidth = 350.0
팩토리가 이렇게 구체적인 값을 하드코딩해서 알고 있는 건 좋지 않습니다. 화면 위치나 그런 것은 늘 바뀔 수 있는 거니까요. 
팩토리는 버튼인지 detailView가 있는지도 몰라야 하는게 맞습니다. 
그렇다면 어떻게 겹치지 않도록 해줄 수 있을까요?

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +    var rectangleView = RectangleView()
ViewController라도 속성은 private var를 습관적으로 표현해주세요 
이렇게 literal 하게 초기값을 생성하는 것과 추가할 때 명시적으로 init 해주는 것과 비교해보는 것도 좋겠습니다.
왜냐하면 이렇게 선언하면 호출-생성 시점이 달라서 조금 다르게 동작하는 경우가 있기 때문입니다.
그리고 아직 DetailView나 RectangleView 구현을 안 봤지만 뷰는 기존의 지정 생성자와 관련이 있도록 만들어 주는게 좋습니다. 그렇지 않고 매개변수가 없는 생성자를 호출하면 NSObject.init()과 헷갈릴 수도 있습니다. 간편하게 생략한다고 항상 좋은게 아닙니다. 그만큼 의도하지 않게 실수할 수도 있습니다.

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +        view.addSubview(button)
이렇게 버튼에 관련된 코드가 길어진다 싶으면 이것도 RectangleButton 처럼 하위 버튼으로 선언하는 것도 좋습니다. 그러면 뷰 컨트롤러는 더 간단해지겠죠 
참고로 여기서 사용한 UIButton.Configuration.plain() 방식이 최소 지원 버전도 살펴보세요. 모든 iOS에서 가능한 것은 아닐겁니다

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +            self.view.addSubview(rectView)
이 부분은 사각형을 추가할 때 입력 처리 액션 같은데, 여기서는 입력이니까 plane까지 들어가는 흐름만 처리하고
Plane에서 뷰 컨트롤러를 거쳐서 뷰를 추가하는 흐름과 분리해보세요. 그걸 나누는 게 포인트입니다.

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +        let touchedView = self.view.hitTest(touch.location(in: self.view), with: nil)
hitTest() 라는 것은 보통 직접 호출하는 메소드가 아닙니다. 
뷰들 중에서 좌표를 찾는 게 아니라 plane에게 좌표를 넘겨서 모델 중에서 사각형을 찾도록 흐름을 바꿔보세요
입력은 plane까지만 들어가는 게 포인트입니다. 
그리고 특정 사각형이 선택이 되면 plane에서 뷰 컨트롤러를 거쳐서 선택된 사각형을 border를 처리하는 출력 흐름을 만드세요
모델 사각형과 view를 매칭하는 것도 뷰 컨트롤러가 할 일입니다. 매칭할 수 있는 구조를 생각해보세요

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +        self.detailView.alphaLabel.text = "투명도 \(currentSliderValue)"
투명도가 바뀌는 입력 이벤트도 plane까지 들어가는 흐름만 처리하도록 개선해보시고,
출력 흐름에 따라서 선택된 뷰의 투명도와 self.detailView.alphaLabel를 바꾸는 것도 구분해보세요

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +        sender.setTitle("\(randomRGB.hexValue)", for: .normal)                                                  //text를 바꾼다.
알파 이벤트와 동일한 내용을 참고하세요

2022-03-06 04:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
Plane이 좀 더 능동적으로 메소드가 많이 구현되어야 할 것 같습니다
ViewController 역할과 Plane의 역할 구분해보세요

2022-03-06 08:05 UTC, P-SeoB commented on DrawingApp/DrawingApp/++/UIView++.swift
> +        self.accessibilityIdentifier = id
accessibilityIdentifier는 말그대로 접근가능한 식별자로 UIElement를 식별하는데 사용하는 것이라고 이해해서 저희가 만든 ID를 
넣어준다면 특정 View를 검색하는데 용이할것 같아서 사용해 보았습니다.
View에는 최소한의 정보만을 남기도록 개선해보겠습니다!

2022-03-06 08:17 UTC, P-SeoB commented on DrawingApp/DrawingApp/MainViewController.swift
> +    var rectangleView = RectangleView()
기존 지정 생성자와 관련있게 만들어서 예기치 못한 실수를 줄이는 것은 이해했습니다만,, 
`literal 하게 초기값을 생성하는 것과 추가할 때 명시적으로 init 해주는 것과 비교해보는 것` 이 잘 이해가 되지 않습니다.
예를들어.. ViewController class의 viewDidLoad와 같은 함수에서 호출과 동시에 생성을하는 것과
위의 코드처럼 초깃값을 넣고 다른 곳에서 호출을 할때와 같은 상황을 비교해야 하는 걸까요?

2022-03-06 08:17 UTC, P-SeoB commented on DrawingApp/DrawingApp/MainViewController.swift
> +        view.addSubview(button)
최소 지원버전은 미처 확인 못한것 같습니다.
한번더 확인해 보겠습니다!

2022-03-06 08:19 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
넵! Plane을 좀더 개선후에 다시 Push해보겠습니다!

2022-03-06 08:23 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +    var rectangleView = RectangleView()
init()에서 초기화하는 경우, 리터럴로 선언한 경우, viewDidLoad()에서 생성하는 경우가 각각 호출되는 시점이 다르니까 어떻게 다른지 확인해보라는 의미입니다. 간혹 생성만 되고 초기값이 없다거나, 당연히 생성됐다고 생각했지만 안 생기거나, 생겼지만 다시 초기화되면서 바뀐다거나 혼란을 주기도 합니다. 특히 뷰 컨트롤러가 만들어지는 시점, AppDelegate 콜백 메소드 시점, viewDidLoad같은 콜백 메소드 호출 시점이 어떤 순서인지 확인해보세요.

2022-03-06 08:30 UTC, P-SeoB commented on DrawingApp/DrawingApp/MainViewController.swift
> +    var rectangleView = RectangleView()
아하! 이제 이해가 잘되네요!! 상세한 설명 감사합니다 😀

2022-03-07 08:25 UTC, godrm commented on DrawingApp/DrawingApp/++/UIView++.swift
> +        self.accessibilityIdentifier = id
`self.accessibilityIdentifier`는 접근성 관련 API라고 시각장애인들이 뷰를 찾을 때 사용하는 API가 활용하는 id입니다.
뷰 요소에 있는 속성을 활용하는 시도는 좋지만, 그 값이 원래 사용되야 하는 곳을 침범하면 안되는 경우도 있습니다. 참고하세요

2022-03-08 01:29 UTC, P-SeoB commented on DrawingApp/DrawingApp/++/UIView++.swift
> +        self.accessibilityIdentifier = id
아! 참고하겠습니다. 감사합니다!

2022-03-09 07:19 UTC, P-SeoB commented on DrawingApp/DrawingApp/++/UIView++.swift
> +        let height = rect.size.height
UIView자체를 확장하는 방법대신 RetangleView클래스에서 생성되도록 다시 수정했습니다!

2022-03-09 07:20 UTC, P-SeoB commented on DrawingApp/DrawingApp/Factory/AlphaFactory.swift
> +        let randomAlpha = Float.random(in:Alpha.minValue...Alpha.maxValue)
생각해보니 불필요한 Factory가  좀 있는것 같아 삭제후 타입에 Static 함수로 Random을 추가했습니다!

2022-03-09 07:22 UTC, P-SeoB commented on DrawingApp/DrawingApp/Factory/PointFactory.swift
> +        let detailViewWidth = 350.0
button의 zPosition을 조절해서 겹치지 않게 시도해보았습니다.
그러자 겹치지는 않지만 Button이 클릭이 안되는 이슈가 생겨서 bringSubviewToFront()메서드를 통해 해결해 보았습니다!

2022-03-09 08:05 UTC, P-SeoB commented on DrawingApp/DrawingApp/MainViewController.swift
> +    var rectangleView = RectangleView()
- 기존의 생성자 frame과 관련있게 하기위해 view.(frame.zero)로 선언했습니다.

- `뷰 컨트롤러가 만들어지는 시점, AppDelegate 콜백 메소드 시점, viewDidLoad같은 콜백 메소드 호출 시점`을 확인하기 위해 간단하게 print문을 찍어 보았습니다.
![스크린샷 2022-03-09 오후 5 00 04](https://user-images.githubusercontent.com/80263729/157397924-6cedc5ad-a0a1-42a8-80af-e12545cb3c07.png)
![스크린샷 2022-03-08 오전 11 27 43](https://user-images.githubusercontent.com/80263729/157393672-57cb7906-89df-406b-8d99-c571d527904f.png)
위 log과 사진을 종합해보았을떄 순서는 Appdelegate -> ViewController(init) -> SceneDelegate -> 
LoadView -> ViewDidLoad 라고 생각이되며 ViewController가 만들어지는 시점과 View가 그려지는 시점이 다르다는 것을 
알 수 있었습니다.
아직까지 모든 구체적인 사례는 잘 모르겠지만,  init과 loadView사이에 하나의 단계가 더있고, init할때 넣어준 값을  viewDidLoad에서 바꾼다면 결국 ViewDidLoad에서 바뀐것만 적용이 되기 때문에 init후에 다시 값을 바꾸고 싶다면 ViewDidLoad에 혹은 여러 View가 있을경우 ViewWillAppear에 로직을 적용하는게 맞다는 생각이 들었습니다.

2022-03-09 08:07 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
Plane에도 Delegate를 선언해서 입력과 출력을 분리 시도 후 Push했습니다!

2022-03-09 12:48 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +    var rectangleView = RectangleView()
ViewDidLoad 까지는 뷰 컨트롤러가 만들어질 때 한 번만 호출되지만, ViewWillAppear 이후는 생성된 이후에 여러 번 불릴 수 있다는 차이도 있습니다. 그래서 ViewDidLoad를 마지막 시점으로 쓰는 겁니다. ViewWillAppear에 넣으면 뷰가 보일때마다 뷰가 추가되면서 겹칠 수 있겠죠

2022-03-09 12:51 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +        if touchedView.frame.width == 1180 { seletedRectangleView?.layer.borderWidth = 0.0 } //빈 화면 클릭시 width을 초기화한다.
뭐든지 이렇게 하드코딩하는 것은 나쁜 결과를 가져올 수 있습니다. 값을 비교하기 보다는 인스턴스를 비교하려고 노력해보세요
터치한 뷰가 어떤 뷰면 될까요?

2022-03-09 12:53 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +        //사각형 추가 버튼이나 detailView의 슬라이더가 추가된 사각형에 가려지더라도 이벤트를 발생시키기 위해서 최상단으로 View를 올렸습니다.
주석이 코드를 읽었을 때보다 더 상세하게, 코드에 표현되지 않은 정보를 표현할 수 있어야 합니다
그렇지 않으면 오히려 주석은 없는 게 나을 수도 있습니다. 여기 주석들을 상당수 코드가 더 정확한 것 같습니다

2022-03-09 12:54 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
>      var selectedRectangle:Rectangle?
델리게이트는 그렇다고 해도 다른 속성은 늘 private 으로 감추려고 노력해보세요.

2022-03-09 12:55 UTC, godrm commented on DrawingApp/DrawingApp/Protocol/PlaneDelegate.swift
> +    func didFindRectangle(rectrangle:Rectangle)
Plane의 델리게이트면 수업시간에 언급한 것처럼 델리게이트 이름과 매개변수가 Plane과 관련이 있어야 합니다. 
여기 메소드들은 그게 표현되지 않네요

2022-03-09 12:55 UTC, godrm commented on DrawingApp/DrawingApp/ShapeElement/Point.swift
> +    static let maxY:Double = 720.0
Point가 아이패드 앱이 아니거나 아이폰 크기에 따라 달라져야 하는 값을 상수로 갖고 있으면 재사용할 수 있을까요?

2022-03-09 12:56 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleButton.swift
> +final class RectangleButton:UIButton {
코드가 어느 정도 분량이면 길어졌다고 느끼나요? 그게 명확해야 옮길 수 있는 기준이 될 수 있을 것 같네요.

2022-03-09 12:57 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +        self.backgroundColor = UIColor(red: CGFloat(red) / 255, green: CGFloat(green) / 255, blue: CGFloat(blue) / 255, alpha: CGFloat(alpha))
간편 생성자가 있는 것도 괜찮은데, 뷰처럼 다른 속성이나 메소드가 전혀 없다면 기존 생성자를 활용해도 될 것 같다는 생각이 드네요

2022-03-09 12:58 UTC, godrm commented on DrawingApp/DrawingAppTests/DrawingAppTests.swift
> +@testable import DrawingApp
DrawingApp 전체를 모듈로 가져와서 테스트하려기 보다는
수업할 때 예시로 했던 것처럼 테스트 타깃에 필요한 파일만 추가해서 테스트하는 것을 권장합니다. 
그래야 의존성을 정확하게 파악할 수 있습니다.

2022-03-09 12:58 UTC, godrm commented
이제 다음 단계로 옵저버 구조를 위해서 NotificationCenter를 활용해서 개선해보세요

2022-03-09 12:58 UTC, merged

2022-03-10 00:28 UTC, P-SeoB commented on DrawingApp/DrawingApp/MainViewController.swift
> +        if touchedView.frame.width == 1180 { seletedRectangleView?.layer.borderWidth = 0.0 } //빈 화면 클릭시 width을 초기화한다.
터치뷰가 뷰컨트롤러의 view이면 해결이 될것 같습니다!

2022-03-10 00:32 UTC, P-SeoB commented on DrawingApp/DrawingApp/Protocol/PlaneDelegate.swift
> +    func didFindRectangle(rectrangle:Rectangle)
Plane과 관련있게 수정 해보겠습니다!

2022-03-10 00:37 UTC, P-SeoB commented on DrawingApp/DrawingApp/View/RectangleButton.swift
> +final class RectangleButton:UIButton {
아직까지 딱 떨어지는 기준이 있는 것은 아니지만,,
제 기준으론 한 요소를 정의하는데 50줄이상이 있으면 길다고 느껴지는 것 같습니다.

2022-03-10 00:38 UTC, P-SeoB commented on DrawingApp/DrawingAppTests/DrawingAppTests.swift
> +@testable import DrawingApp
넵 필요한 파일만 추가해서 테스트 해보겠습니다!