[푸코] Step03 - Notification 활용(Observer 패턴)
codesquad-members-2022/swift-drawingapp pull request #43
Opened 2022-03-07 02:53 UTC by wnsxor1993

## 결과 화면
![화면 기록 2022-03-07 오전 11 51 43](https://user-images.githubusercontent.com/44107696/156959735-2c319771-b731-44ad-be14-ce12e09642a0.gif)

## 작업 목록
* 리팩토링
- [x] Alpha 내 메서드 삭제 및 init(rawValue:)로 통합
- [x] RandomRectangleView 내 메서드 삭제 및 관련 로직 init 내로 이동
- [x] VC의 presentation 역할 강조 (RightAttributerView Label text 값 전달)  

* 신규 작업
- [x] 연결된 delegate 일괄 제거
- [x] MainViewController에 Notification Observer add
- [x] Plane, RightAttributerView 등에 Notification post
- [x] 기능 별로 extension 분할 정리

## 학습 키워드
- NotificationCenter (default / addObserver / post)
- Notificiation.Name

## 고민과 해결
- 프로그래밍 요구사항에서 속성이 변경되면 Plane 모델 객체에서 변화에 대한 post를 하라고 되어있으나, Slider를 통한 속성 변경과 관련하여 VC나 모델에 변화에 대한 알림이나 데이터 전달이 불가능하여 이를 해결할 방법에 대한 고민을 했습니다.
그러던 중, 이전 delegate 때와 비슷한 동작 방식대로 구현하는 방법이 떠올랐고 Slider의 속성이 변경되면 post를 통해 VC에 알리고, VC에서는 이를 캐치하여 변경된 Slider의 속성 값에 맞춰 Plane에 Rectangle에 대한 속성 변경을 요청하고 이후 사각형 View의 속성 또한 변경하는 형태의 동작 방식으로 구현하였습니다.

- NotificationCenter에 post 시, object를 self로 보냈는데 RandomAttributerView에서 보낸 알림을 VC에서 캐치하지 못 하는 상황이 발생하였습니다. 이유를 알아보던 중, addObserver에서 object를 VC가 소유하고 있는 인스턴스가 아닌 객체의 self( ex. RightAttributerView.self)를 할당하여 생긴 문제인 것을 파악하였고 VC 소유 인스턴스로 변경한 뒤, 정상 작동하는 것을 확인하였습니다.

2022-03-07 08:47 UTC, godrm commented
> ## 고민과 해결
> * 프로그래밍 요구사항에서 속성이 변경되면 Plane 모델 객체에서 변화에 대한 post를 하라고 되어있으나, Slider를 통한 속성 변경과 관련하여 VC나 모델에 변화에 대한 알림이나 데이터 전달이 불가능하여 이를 해결할 방법에 대한 고민을 했습니다.

View -> VC는 보통 NotificationCenter를 잘 안 쓰고 Delegate를 사용하는 편입니다
그 이유는 VC가 View를 소유하기도 하고, 1:1 관계라서 좀 더 명확하거든요. 물론 View의 델리게이트가 꼭 VC일 필요도 없습니다
NotificationCenter는 1:n 이거나 받는 대상이 누구인지 불명확할 때 (느슨한 관계에서) 사용하는 편입니다. 
그래서 모델에서 VC로 올라가는 경우가 대부분이죠. 

> * NotificationCenter에 post 시, object를 self로 보냈는데 RandomAttributerView에서 보낸 알림을 VC에서 캐치하지 못 하는 상황이 발생하였습니다. 이유를 알아보던 중, addObserver에서 object를 VC가 소유하고 있는 인스턴스가 아닌 객체의 self( ex. RightAttributerView.self)를 할당하여 생긴 문제인 것을 파악하였고 VC 소유 인스턴스로 변경한 뒤, 정상 작동하는 것을 확인하였습니다.

object는 sender의 의미입니다. 학습 영상을 참고하시면 됩니다.

2022-03-07 09:07 UTC, godrm requested changes
다음 내용을 확인해보시고, 개선해서 다시 푸시해보세요

2022-03-07 09:07 UTC, godrm commented on DrawingApp/Model/Rectangle/Plane.swift
> +        return count()
이 속성은 속성인가요 메소드인가요? notifyMadeRectangle 이름은 메소드같고, 구현은 computed property로 count를 리턴하는 데 이름과 동작이 뭔가 미스매치가 되는 것 같네요
좀 더 명확하게 표현하는 게 좋겠습니다.

2022-03-07 09:07 UTC, godrm commented on DrawingApp/Model/Rectangle/Plane.swift
>          }
단지 카운트 넘어가는 것만 문제가 될까요? -1도 문제가 될 수 있죠. 그래서 subscript에 Int 인덱스도 안전한 접근은 아닙니다.
String에서 index를 어떻게 다루는 지 한 번 살펴보세요

2022-03-07 09:07 UTC, godrm commented on DrawingApp/Model/Rectangle/Rectangle.swift
>          }
이런 경우는 return `비교식` 정도로 표현해도 좋습니다.

2022-03-07 09:07 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        self.view.addSubview(rectangleView)
이 부분에서 IBAction 같이 입력에 대한 핸들러에서는 뷰 컨트롤러를 거쳐서 plane까지 추가하는 흐름만 다루고
뷰를 추가하는 부분은 plane에서 다시 뷰 컨트롤러를 거쳐서 출력하는 흐름으로 분리하셔야 합니다. 
그리고 이상한데요? 팩토리를 만들었는데 Rectangle 생성을 여기서 하고 있네요. 팩토리에서 만들어서 리턴해줘야 하지 않을까요?
rectangles 이름을 보고 Plane이 아닌줄 알았네요. 역할을 잘 표현해보면 어떨까요?

2022-03-07 09:07 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(showOriginSliderValue), name: .tapGesture, object: self)
이건 좀 이상하네요. 자기가 자기한테 옵저버를 등록할 필요는 없을 것 같은데요?

2022-03-07 09:07 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(moveBlueSlider), name: .changeBlueColor, object: rightAttributerView)
앞서 의견을 남긴 것처럼 View -> ViewController 관계에서 1:1인 경우, 이벤트가 넘어올 때는 NotificationCenter가 꼭 필요한가 고민해보세요.

2022-03-07 09:07 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        }
이 메소드는 입력을 처리하는 것인지, 출력을 처리하는 것인지 구분이 안되네요
입력과 출력을 구분해서 처리해보시고 이름으로도 구분할 수 있으면 더 좋겠습니다 
특히 histTest는 직접 호출하는 메소드가 아닙니다. 모델에서 찾은 속성으로 바로 매칭할 수 있어야 합니다. rectangleInPlane.id를 비교하는 것을 뷰 내부 속성(restorationIdentifier)으로 하지마시고, 뷰와 모델을 모두 알고 있는 뷰 컨트롤러에서 매칭할 수 있는 방법을 찾아보세요

2022-03-07 09:07 UTC, godrm commented on DrawingApp/View/RandomRectangleView.swift
>      }
뷰의 지정 생성자 두 개를 어떤 걸로 RandomRectangleView를 초기화해도 동일하게 동작하는 것을 보장해주는 게 좋습니다
추가적으로 지정 생성자를 만들기보다는 기존 메소드를 호출하거나 기존 메소드로도 동작하는 것을 보장해주는 방법을 고민해보세요.
그렇지 않으면 뷰를 생성하는 다른 사람 입장에서는 굉장히 혼란스러울 수 있습니다.

2022-03-07 09:07 UTC, godrm commented on DrawingApp/View/RightAttributerView.swift
> +    static let changeBlueColor = Notification.Name("changeBlueColor")
Notification.Name도 보내는 타입이 정해져있다면 nested로 포함하는 것도 좋습니다. 
그렇지 않으면 예를 들어 `changeAlpha` 이름이 다른 파일에서도 사용한다면 충돌이 날수도 있습니다.

2022-03-07 15:48 UTC, wnsxor1993 commented on DrawingApp/Model/Rectangle/Plane.swift
> +        return count()
처음에는 새로운 Rectangle이 추가되면 자동으로 NotificationCenter에 post를 하고자 작성한 연산 프로퍼티였습니다만, 현재 수정안에서는 addRectangle 메서드가 호출되면 post가 되도록 수정하여 해당 프로퍼티는 삭제하였습니다

2022-03-07 15:50 UTC, wnsxor1993 commented on DrawingApp/Model/Rectangle/Rectangle.swift
>          }
리턴 타입 변경만 생각하다보니 깔끔하게 정리할 수 있는 방법을 놓쳤네요. 감사합니다!^^

2022-03-07 15:54 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +        self.view.addSubview(rectangleView)
변수명은 직관적으로 plane으로 수정하였고, 말씀하신 흐름 또한 IBAction에서는 Rectangle 생성 및 plane에 추가까지 다루도록 하였습니다. 이후 흐름은 plane에서 post를 통해 보내온 userInfo를 받아서 uiview를 생성하도록 Notification을 활용하였습니다.
아직까지 변수나 메서드는 타인이 알아볼 수 있을 정도로 직관적이게 작성하는 게 미흡한 것 같습니다. 계속해서 작성해보며 개선해나가보겠습니다!

2022-03-07 15:56 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(showOriginSliderValue), name: .tapGesture, object: self)
옵저버에 대한 이해가 부족한 상태라 action 등록의 역할과 혼동하여 사용하였습니다. 해당 부분은 앞에서 말씀하신 사항과 함께 추가적인 학습을 진행 후, 삭제하였습니다.

2022-03-07 15:59 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(moveBlueSlider), name: .changeBlueColor, object: rightAttributerView)
1:1 관계에 직접적인 소유 형태일 뿐 더러, 개인적으로도 delegate 패턴을 활용하는 것이 덜 복잡하다고 느껴져서 해당 요소들은 이전의 delegate 패턴으로 수정하였습니다

2022-03-07 16:08 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +        }
입력과 출력을 구분함과 동시에 Notification을 활용하여 출력에 필요한 Rectangle 값을 받아올 수 있도록 수정하였습니다.
매칭 방법 또한 VC 내에 Dictionary를 추가하여 Rectangle의 id만으로도 매칭이 용이하도록 구현하였습니다.

2022-03-07 16:11 UTC, wnsxor1993 commented on DrawingApp/View/RandomRectangleView.swift
>      }
RandomRectangleView 내에서 모든 속성과 레이아웃을 설정하고 init해야 된다는 생각에 상기의 로직으로 구현했습니다만, view는 VC 내에서도 속성과 레이아웃을 설정해도 괜찮으니 기본 init들만 남겨두고 VC에서 속성과 레이아웃을 설정하는 로직으로 수정하였습니다.

2022-03-07 16:52 UTC, wnsxor1993 commented on DrawingApp/Model/Rectangle/Plane.swift
>          }
Int 인덱스 외의 방법으로 subscript를 수정할 지 고민해보고 차후에 수정해보겠습니다!

2022-03-07 17:00 UTC, wnsxor1993 commented
말씀하신 사항에 대하여 최대한 리팩토링을 진행해보았습니다.
다만 수정을 하고나니 이전과 달리 addObserver의 object를 post하는 객체로 설정할 시 동작을 전혀 캐치하지 못 하는 상황이 발생하여 피치 못하게 nil로 변경한 상태입니다. 제가 post를 설정할 때 어떤 부분을 잘못한 건 지 여쭤보고자 합니다.

추가적으로 Slider의 값이 변경되는 로직에서는 Plane이 아니라 Rectangle 인스턴스가 직접적으로 사용되고 있는데 더 하위의 모델인 Rectangle에도 Observer 패턴을 적용해도 괜찮을 지, 아니면 Plane 같은 최상위의 모델에서만 Observer 패턴을 적용해야 되는지 의문이 들어 이 부분도 여쭤보고 싶습니다.

2022-03-08 02:49 UTC, godrm approved these changes
구조적으로 개선이 되어 있지만, 아쉬운 부분이 있어서 의견을 남겼습니다. 
확인해보시고 다음 단계를 하면서 개선해보세요

2022-03-08 02:49 UTC, godrm commented on DrawingApp/Model/Rectangle/Plane.swift
>          }
이렇게 범위를 지정하는 게 무난한 방법이지만, Int 타입 자체를 안쓰고 범위를 알 수 있도록 제공해주는 게 더 좋은 방법입니다
런타임에 값을 걸러내는 것보다 컴파일 타임에 실수하지 않도록 하는 게 좋다는 거죠

2022-03-08 02:49 UTC, godrm commented on DrawingApp/Model/Rectangle/Plane.swift
> +        NotificationCenter.default.post(name: Plane.makeRectangle, object: self, userInfo: ["rectangle" : rectangle])
`"rectangle"` 같은 문자열 키값도 상수로 선언해야 보내는 쪽, 받는 쪽이 실수하지 않고 같은 값을 사용할 수 있습니다

2022-03-08 02:49 UTC, godrm commented on DrawingApp/Model/Rectangle/Plane.swift
> +            return
리턴 값이 있는게 더 검증하기 좋지 않나요? 왜 없앤걸까요?

2022-03-08 02:49 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +    private var plane = Plane()
꼭 타입이름을 써야 하는건 아닙니다. 그렇지만 어떤 역할인지 명확하게 표현할 수 있는 것은 좋습니다. 계속 고민해보세요

2022-03-08 02:49 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +    private var rectangleUIViews = [String : UIView]()
View와 매칭하는 것도 꼭 Id를 키로 사용하지 않고 Rectangle 자체를 비교해도 좋습니다. 항상 타입을 만들면 타입을 활용해보세요

2022-03-08 02:49 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        let rectangleView = RandomRectangleView(frame: CGRect(x: rectangleValue.point.x, y: rectangleValue.point.y, width: rectangleValue.size.width, height: rectangleValue.size.height))
RandomRectangleView 뷰 이름에 Random이 들어갈 필요가 있나요?

2022-03-08 02:49 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(addRectangleView(_:)), name: Plane.makeRectangle, object: nil)
위에 보니 Plane이 struct로 선언되어 있던데, 이런 경우는 struct 내부 속성이 바뀌어도 struct 주소가 바뀌어 버립니다. 
NotificationCenter가 비교하는 object에 들어있는 struct와 sender가 같지 않은 경우가 생기는거죠. 
그래서 NotificationCenter의 object는 class가 더 잘 어울립니다. 그렇지 않으면 지금처럼 object를 지정하지 못하는 상황도 생길 수 있습니다.

2022-03-08 02:49 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        selectedRectangle = rectangle
이 부분에서 displaySliderValue() 이게 출력의 역할이니까 tapGesture()에 넣는게 아니라 assignSelectRectangle() 여기에 있어야 하지 않을까요? 그럼 selectedRectangle 이걸 비교할 필요도 없지 않을까요?

2022-03-08 02:49 UTC, godrm commented on DrawingApp/View/Delegate/RightAttributerViewDelegate.swift
> +    func moveBlueSlider()
델리게이트 패턴 이야기할 때 알려준 이름, 매개변수 규칙을 준수하도록 설계해보세요

2022-03-08 02:49 UTC, godrm commented on DrawingApp/View/RandomRectangleView.swift
>  class RandomRectangleView: UIView {
위에도 언급했지만 View 자체가 랜덤으로 그려지는 것인지 이름부터 정해져야 하는걸까요?
어떤 값을 넣어줄지 뷰가 이미 알고 있는 걸까요?

2022-03-08 02:49 UTC, merged

2022-03-08 05:21 UTC, wnsxor1993 commented on DrawingApp/Model/Rectangle/Plane.swift
> +        NotificationCenter.default.post(name: Plane.makeRectangle, object: self, userInfo: ["rectangle" : rectangle])
Dictionary를 비롯한 Key 값을 사용하는 작업에 있어서는 상수를 지정해서 사용하는 것을 지향해야 되는 걸까요?

2022-03-08 05:24 UTC, godrm commented on DrawingApp/Model/Rectangle/Plane.swift
> +        NotificationCenter.default.post(name: Plane.makeRectangle, object: self, userInfo: ["rectangle" : rectangle])
모든 숫자나 문자열은 한 곳에서만 사용하는 게 아니고, 여러 곳에서 사용될꺼고 그 의미가 명확하게 표현하는 게 실수를 덜 하게 하니까요
그렇지 않으면 post 할 때 키값을 못 보는 경우에 observer 하고 받아서 꺼낼 때마다 키값을 확인해야 합니다. 
혼자서 개발하는 게 아니라 여러 명이 개발한다고 생각하고 의도를 표현하는 것은 중요합니다.

2022-03-08 05:25 UTC, wnsxor1993 commented on DrawingApp/Model/Rectangle/Plane.swift
> +            return
이전에 리턴 값을 부여했던 이유는 VC에서 해당 메서드를 호출하였을 때, 적절한 Rectangle 값을 받아오기 위함이었는데 해당 요소는 NotificationCenter에 post할 때, userInfo로 전달되어 필요도가 낮아졌습니다.
이와 함께 적절한 값을 찾지 못하여 gurad문이 실행될 경우 Notification으로 연결된 출력 메서드가 실행되지 않으니 확인에 있어서도 큰 차이가 없을 것 같다는 생각이 들어 위와 같이 수정하였습니다.

2022-03-08 05:27 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +    private var rectangleUIViews = [String : UIView]()
Dictionary 등을 사용하더라도 key 값을 Rectangle 내의 원시 값들 보다는 Rectangle 자체를 사용하여 타입을 활용할 수 있도록 구현하는 것이 좋은 방향이라는 말씀으로 이해해도 괜찮을까요?

2022-03-08 05:28 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +    private var rectangleUIViews = [String : UIView]()
그럼요 그래야 내부 속성을 가져와서 처리하지 않게 되니까요

2022-03-08 05:34 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +        let rectangleView = RandomRectangleView(frame: CGRect(x: rectangleValue.point.x, y: rectangleValue.point.y, width: rectangleValue.size.width, height: rectangleValue.size.height))
수정한 이후에 고민하던 부분이었습니다. Random 값은 Factory를 통해서 만들어지는 것이니 단순히 View를 생성하는 로직만 남은 해당 객체의 이름에서 Random을 제거하는 것이 맞는 듯 하여 이를 토대로 수정하였습니다.

2022-03-08 05:43 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +        selectedRectangle = rectangle
결국 tapGesture가 호출되는 시기는 사용자가 클릭했을 때이므로 해당 메서드 자체가 입력을 담당하는 것이고 그렇기에 Model에 관련 데이터를 전달하거나 메서드를 호출해 일을 시키는 흐름까지만 작업을 해야 되는 게 맞고,
이후에 속성 값들을 view에 내보내주는 출력 작업은 Model에서 입력에 대한 적절한 작업을 처리한 이후에 post를 통해서 VC에게 출력에 필요한 메서드를 호출할 수 있도록 알려주는 흐름을 가져야 하니 tapGesture 메서드 내에 출력 메서드가 호출되어서는 안 된다는 것으로 이해하면 괜찮을까요?

2022-03-08 05:48 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(addRectangleView(_:)), name: Plane.makeRectangle, object: nil)
그렇다면 NotificationCenter를 사용해야 하는 Struct의 경우, mutating과 같이 내부 속성을 변경하는 요소들이 있을 경우에는 Class로 전환하여 사용해서 object를 지정할 수 있도록 구현하는 것을 지향해야 할까요?

2022-03-08 05:50 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(addRectangleView(_:)), name: Plane.makeRectangle, object: nil)
그럴수 있습니다. struct는 mutating 하는 속성을 가지는 걸 observe 하기에 적절한 타입이 아닌거죠. 
그런 조건에서 값 변화를 확인하려면 class가 더 좋을 수 있는거죠

2022-03-08 06:30 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        selectedRectangle = rectangle
네. 입력 흐름과 출력 흐름을 구분하는 게 중요한 포인트입니다.

2022-03-08 06:35 UTC, godrm commented
> 추가적으로 Slider의 값이 변경되는 로직에서는 Plane이 아니라 Rectangle 인스턴스가 직접적으로 사용되고 있는데 더 하위의 모델인 Rectangle에도 Observer 패턴을 적용해도 괜찮을 지, 아니면 Plane 같은 최상위의 모델에서만 Observer 패턴을 적용해야 되는지 의문이 들어 이 부분도 여쭤보고 싶습니다.

이건 선택의 문제네요. 상위 모델이 있고 하위 모델이 있을 때 어디에서 노티를 보내느냐... 둘 다 보낼 수도 있고 상위 모델이 종합해서 보낼 수도 있죠. 그런걸 선택하는 게 개발자들의 몫입니다. 각각 보내더라도 sender가 달라질꺼고 더 세분화해서 받을 수도 있으니까요.