[Alex] Step2 속성 변경 동작
codesquad-members-2022/swift-drawingapp pull request #44
Opened 2022-03-07 03:43 UTC by SongTaehwan

# 속성 변경 동작

## 작업 목록

- [x] Plane 구조체 구현
- [x] Plane 구조체 유닛 테스트 추가
- [x] 사각형을 생성하는 버튼 추가
- [x] 터치해서 사각형 선택 및 취소 기능 구현
- [x] 선택한 사각형의 투명도, 배경색을 컨트롤하는 UI 및 기능 구현
- [x] RectangleView 구현

## 결과물

<image src="https://github.com/SongTaehwan/swift-drawingapp/blob/step2/images/step2.gif?raw=true" width="500px" />

## 학습 키워드

- UITapGestureRecognizer
- UIGestureRecognizer
- MVC Pattern
- 좌표 시스템

## 고민과 질문
- 코멘트로 남겨두겠습니다 :)

2022-03-07 04:02 UTC, SongTaehwan commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    }
개인적으로 프래임워크가 제공하는 클래스를 그대로 확장하여 사용하는 방법은 해당 타입을 그대로 사용하면서 기능을 추가할 수있어 장점이 있지만, 무분별하게 사용하면 유지보수를 어렵게 만드는 원인이 될 수 있다고 생각합니다. 
때문에 별도의 커스텀 뷰로 분리하는 것이 응집도를 높이는 방법이라고 생각했습니다만, `extension` 을 어떠한 관점에서 접근하고 어떤 시점에 사용해야할지 잘 모르겠습니다 🥲

2022-03-07 04:06 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Model/Point.swift
> +    static let range = 0.0...500.0
이렇게 범위값이 바뀔 여지가 있다면 static 타입의 속성이어도 var 로 선언하는 건 어떨까요?

2022-03-07 09:11 UTC, godrm commented on DrawingApp/DrawingApp/Model/Point.swift
> +    static let range = 0.0...500.0
그럴수 있죠. 그것도 정해진 건 아니죠. 그렇지만 모든 것을 대비해서 구현해야 하는 것도 아닙니다.

2022-03-07 09:13 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    }
정답이 없죠 ㅎㅎ 필요할 확장하는 거죠 :)

2022-03-07 09:28 UTC, godrm requested changes
다음 피드백을 확인해보시고, 특히 입력과 출력 흐름을 구분해보세요

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    @IBOutlet weak var stepper: UIStepper!
이렇게 뷰 요소가 많아지고, 설정하는 코드도 길어진다면 관련있는 뷰를 묶어서 하위 뷰를 분리하는 것도 고려해보세요

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    @objc func handleOnChangeStep(_ sender: UIStepper) {
handleOnChangeStep() 무슨 스텝이 달라진 것인지 이름만 보면 추측하기 어렵네요. Alpha Step 이라는 의미라면 그 역할을 좀 더 명확하게 하면 좋겠습니다

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        rectangleView.setBackgroundColor(with: CGFloat(self.alphaSlider.value) / 10)
여기서 뷰의 alpha 속성을 바꾸는 것이 단지 선택된 뷰를 미리 알아서 바꾸려는 게 아니어야 합니다
Plane을 선언하고 Rectangle을 구현한 이유는 뷰의 속성을 바꾸기 전에, 내부에서 모델의 값을 바꾸기 위한 겁니다 (입력의 흐름인거죠)
출력에 흐름에 맞춰서 뷰에 표시하는 방법은 달라지고, 테스트하기도 어렵습니다. 그럴수록 모델의 값을 바꾸고, 어떻게 확인할 수 있는지 집중해보세요. 따라서 여기서는 Plane으로 알파값에 대한 이벤트를 전달하는 구현이 있어야 합니다.

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        self.planeView.addSubview(rectangleView)
handleOnPressAddButton()은 무엇을 add하는 것인지 명확하지 않네요
그리고 여기서도 입력의 흐름 : 뷰에서 뷰 컨트롤러를 거쳐서 모델까지 전달되는 것을 담당해야 합니다
반대로 모델에서 뷰 컨트롤러를 거쳐서 뷰에 출력되는 흐름과 분리하셔야 합니다. 그게 중요한 포인트입니다.

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        if sender.state == .ended {
이런 경우는 들여쓰기를 하지 않을 수 있도록 guard else 구문으로 ealry exit을 처리하면 아래에서 필요한 값만 처리할 수 있어서 읽기도 수월해집니다. 참고하세요

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +            self.selectedRectangleView = rectangleView
여기서도 탭 터치 이벤트가 발생하면 Plane까지 뷰를 생성하기 위한 입력의 흐름만 담당하고
뷰를 추가하는 출력의 흐름을 분리해보세요.

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +    init?(rawValue: Float) {
Alpha의 단계는 1부터 opaque까지 있는 Float로 생성하는 게 조금 어색합니다.
어떻게 매치가 되는 것인지 init(rawValue:) 만 봐서는 Float에 무엇을 넣어야 1이 되는지 알아내기 어려울 것 같습니다.

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +    }
`T.Type` 을 활용한 것은 좋은 시도네요

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Model/Size.swift
> +    }
위에서 메타 타입을 사용해서 좋은 시도로 봤는데, 여기를 보니 Size와 정말 관련이 있는 것인지 모르겠습니다
왜냐하면 SizeBuilder 프로토콜과 관련이 있을 뿐이지 Size 타입과 연결 고리가 없는 것 같아요.
특히 T.Type 메타 타입이 있지만, Size 말고 다른 타입이 사용할 수 없을꺼 같은 구현인데요? 
만약 Size가 프로토콜을 채택하고 팩토리가 프로토콜을 보고 Size를 만들어 낼 수 있다면 더 좋을 것 같습니다

2022-03-07 09:28 UTC, godrm commented on DrawingApp/DrawingApp/Utility/Extensions.swift
> +}
여기는 extension들만 모아놨는데, 각 타입별로 필요한 것이라면 별도 파일로 분리하는 게 어떨까요?
서로 다른 타입들끼리는 전혀 연관성이 없어 보입니다. 

---
그리고 모든 UIView가 setBorder() 나 removeBorder()가 필요한 게 아니라면 
UIView를 상속한 특정한 뷰를 만들고 그 뷰부터만 해당 메소드가 지원되도록 하는 게 더 좋겠습니다.

2022-03-07 11:11 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +    init?(rawValue: Float) {
리펙토링을 하면서 용도가 없어진 코드였는데 미처 지우지 못했습니다. 유의하겠습니다 :)

2022-03-07 11:53 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Model/Size.swift
> +    }
```Swift
let size: CGSize = size.convert(using: CGSize.self)
rectangleView.frame.size = size

// ...Alpha, Point 구조체도 위와 같은 맥락의 목적을 가진 convert 메소드를 포함하고 있습니다.
```
@godrm 
위의 코드와 같이 Rectangle 모델의 데이터를 View 에 반영할 때 편의성을 제공할 목적으로 만든 메소드입니다.
값을 가지고 `CGSize` 을 직접 만들거나 `rectangleView.frame.size.x = size.x` 방식의 대안이 될 거라고 생각했는데 오히려 복잡도만 늘리게 된 걸까요?

2022-03-07 12:00 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    @IBOutlet weak var stepper: UIStepper!
@godrm 
하위 뷰로 묶어 분리하라는 말씀은 커스텀 뷰를 만드는 것을 의미하는 건가요?

예를 들어, `class PlaneView: UIView` 내부에 `addButton: UIButton` 을 생성하고 해당 뷰 관련 설정코드를 모두 옮기는 것을 말합니다. 마찬가지로 `class ControlPanel: UIView` 와 나머지 뷰 요소도 동일합니다.

만약 예시의 경우가 맞다면 gesture recognizer 와 버튼의 action 메소드의 경우 Delegation 패턴을 활용해 ViewController 과 인터렉션하는 방식으로 구현해보겠습니다 :)

2022-03-08 02:58 UTC, godrm commented on DrawingApp/DrawingApp/Model/Size.swift
> +    }
Size가 CGSize를 모르고 프로토콜만으로 변경할 수 있으니 좋은 시도입니다. 
다만 T가 CGSize가 들어가는 데, CGSize가 SizeBuilder 프로토콜을 채택해야 하니까 
CGSize를 확장하지 않는다면 
Size가 Core Graphics 프레임워크를 몰라야 하니까 여기가 아니라 상위에서 Size를 확장해서 CGSize를 지원하도록  `CGSize.init(with size:Size) -> CGSize`를 확장도 가능하죠. 
프로토콜을 하위타입인 Size가 채택하고 CGSize가 변환하는 게 아니라서 좀 어색한 것 같습니다.

2022-03-10 06:31 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Model/Size.swift
> +    }
하위 타입인 Size 가 프로토콜을 채택하는 방식으로 수정하였습니다.
또한 interchangable 한 변환은 위해 CGSize 를 확장해 Size 로 변환이 가능하도록 convert 메소드를 추가했습니다.

2022-03-10 06:32 UTC, SongTaehwan commented
# Step3. 관찰자(Observer) 패턴

## 작업 목록

- [x] 적용해 입력과 출력 흐름 분리
- [x] UI 요소에 AutoresizingMask 적용
- [x] NotificationCenter 사용해 Model-ViewController-View 흐름 구축

## 학습 키워드

- AutoresizingMask
- NotificationCenter
- Observer Pattern
- Hashable Protocol
- Property Observer

## 고민과 해결

- 모델 업데이트 후 View 에 반영하기 위해 Rectangle 모델 정보만을 가지고 해당하는 RectangleView 를 어떻게 찾아야할지 방법을 찾아야했습니다.

  - ViewController 에 `var rectangleMap: [Rectangle: RectangleView]` 를 추가해 모델과 View 의 참조를 매핑했습니다.

- 딕셔너리의 키값으로 클래스 인스턴스를 저장하는 과정에서 Hashable 프로토콜을 학습했습니다.

  - 유니크한 hash 값을 얻기 위해 `ObjectIdentifier` 로 얻은 메모리 주소값을 사용했습니다.

- 몇 가지 View 와 Model 만으로도 ViewController 의 코드량이 점점 많아지고 있는 것 같습니다.
  - Container View Controller 를 사용해 하위 ViewController 를 포함시켜 각 ViewController 가 담당하는 역할을 세분화시켜야할 것 같다는 생각이 들었습니다.

2022-03-10 06:34 UTC, SongTaehwan commented
@godrm
선거날 동안 2단계에서 주신 피드백을 반영하고 3단계까지 진행하였습니다.
아직 Merge 가 되지 않아 3단계도 이어서 진행했습니다.

리뷰 부탁드립니다 :)

2022-03-10 07:40 UTC, godrm commented
여기에 댓글을 남겨주지 않으면 push를 한건지 제가 알수가 없습니다. 들어왔다가도 push가 된게 마무리가 된건지 아닌건지 알수가 없으니까요
저랑은 다음 단계를 진행해도 상관없겠지만, 현업에서는 작업한 걸 머지 못받으면 다른일 못하고 있을 수도 있습니다. 어떤 영향을 주는 건지 코드를 사용하는 모두에게 공유하는 시간이라고 생각하셔야 합니다. 
적극적으로 소통하고 확인하셔야 해요. 이게 숙제검사는 아니지만, 개발자들끼리 소통하는 방식이고 코드로 설득하는 과정입니다.
그냥 푸시하면 누가 보겠지 그렇게 생각하시면 안되요.

2022-03-10 07:41 UTC, godrm commented
더구나 이전 단계와 달라진 것을 비교할 수가 없어서 추가로 푸시한 것은 리뷰할 수가 없네요 ㅜㅜ

2022-03-10 07:43 UTC, godrm commented
diff로 이전과 나중에 올린 것을 비교를 할 수가 없으니 넘어갈 수 밖에 없네요. 머지하겠습니다.

2022-03-10 07:43 UTC, merged