[Eddy] Step 4,5: 사진 추가 & 드래그
codesquad-members-2022/swift-drawingapp pull request #45
Opened 2022-03-07 09:26 UTC by BumgeunSong

### Step 4 사진 추가
![step4](https://user-images.githubusercontent.com/17468015/156972996-d4d6341f-b954-4b31-be7f-6d33b9a04f73.gif)

### Step 5 드래그
![step5](https://user-images.githubusercontent.com/17468015/157000787-c752f420-b6d7-4f26-bf3d-17f9a0e108c8.gif)

## 작업 목록

**지난 PR 피드백**
- [x] Factory 메소드를 Factory 객체가 아닌 연관 타입으로 분산
- [x] userInfo key를 static 변수로 변경

**사진 추가**
- [x] Photo 클래스 구현
- [x] Plane에 addPhoto 기능 구현 및 Notification Center로 연결
- [x] CanvasView를 추가하고, 사진추가 버튼을 ImagePickerController와 연결
- [x] Privacy description 추가
- [x] Photo의 경우 Panel에서 색깔 버튼이 disabled 되게 변경 

**드래그**
- [x] Pan 제스처 인식기를 추가
- [x] CanvasView에 임시 뷰 생성 로직 추가
- [x] Pan이 시작되면 임시 뷰 생성&추가
- [x] Pan 중에는 임시 뷰 위치 변경
- [x] Pan 완료시에는 임시 뷰 삭제하고 해당 ViewModel의 위치 데이터 변경 

## 고민과 해결

2022-03-07 09:32 UTC, godrm commented
그렇더라도 4단계/5단계를 나눠서 보냈다면 더 좋았을 것 같네요 ㅎㅎ 
단계별로 좀 더 집중해서 봐야하는 내용이 다르거든요.

2022-03-07 09:40 UTC, BumgeunSong commented
> 그렇더라도 4단계/5단계를 나눠서 보냈다면 더 좋았을 것 같네요 ㅎㅎ 단계별로 좀 더 집중해서 봐야하는 내용이 다르거든요.

빨리 피드백을 받고 싶은 마음에..ㅜ 다음부터는 꼭 분리해서 보내겠습니다!

2022-03-08 02:23 UTC, godrm requested changes
모델을 만들었던 구조와 뷰를 만들면서 구조가 조금 다른 것 같습니다. 
모델과 같은 구조로 만드는 게 좋지 않을까요? 다음 피드백을 확인해보고 개선해보세요

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +    private var viewIDMap = [String: CanvasView]()
매핑할 때 키를 String 대신에 Rectangle이나 혹은 추상화된 타입 자체를 써보세요. 이 부분도 프로토콜로 추상화가 가능할 겁니다

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        view.addGestureRecognizer(tap)
탭을 seld.view에 하나만 추가하는 것과 각각 표시하는 CanvasView(맞나?)에 추가하는 것과 어떤 차이가 있을까요?

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
>          mutatedUIView?.alpha = Converter.toCGFloat(mutated.alpha)
이 부분을 이렇게 할 수도 있을까 생각해보세요. 어떤게 더 자연스러울까요 
`mutated.alpha.toCGFloat()` 또는 `CGFloat.init(with: mutated.alpha)` 
Converter라는 유틸리티 없이, 서로 관련있는 타입끼리만 변환하는 거죠

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        temporaryView.removeFromSuperview()
이 부분은 인상적으로 깔끔하게 처리하셨네요 👏

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        mutatedCavnasView?.frame.origin = Converter.toCGPoint(mutated.origin)
이 부분에서 OriginMutable 으로 바꿨다가 ViewModel로 바꾸는 부분이 좀 어색합니다. 
searchView()에서도 구체타입이 아니어도 되지는 않을까요?

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Photo.swift
> +    }
이렇게 생성하는 메소드를 제공해주는 경우도 많은데 별도 타입으로 분리해서 팩토리에서 정해진 규칙에 맞춰서 생성하는 것도 좋은 방법입니다. createID나 creatAlpha 같은 것에 대해서 간편 생성자가 아니라 분리된 방법으로 값을 지정해주는 거죠. 
타입의 인스턴스를 생성하는 것 자체를 타입이 하느냐 분리해서 하느냐가 더 복잡한 구조에서는 분리하는 게 의존성을 분리하는 게 도움이 되거든요.

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Photo.swift
> +    func transform(to alpha: Alpha) {
transform은 어떤 계산(식)에 의해서 형태를 바꾸는 것을 의미하는 경우가 많습니다. 
계산식을 거꾸로 하면 다시 되돌아갈 수 있는 경우를 포함해서요. 되돌릴 수는 없으니 이 경우는 transform() 보다는 그냥 값을 바꾸는 정도로 표현하는 게 어떨까요?

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +    static let mutatedViewModelKey = "mutated"
여기 상수들도 namespace가 구분되면 어떨까요? Plane.xxx 형태에서 Plane.xxx.yyy 형태로 체계화할 수 있지 않을까요?

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
>          }
didSet을 사용할 때는 어떤 경우에 호출이 될까요?
viewModels가 배열이면 배열에 항목이 추가되거나 삭제되면 되나요? 아니면 배열 자체가 바뀌어도 되나요? 
만약 속성이 클래스라면 어떻게 되나요?

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +    private var viewModelIDMap = [String: ViewModel]()
여기서는 String 대신에 ViewModel 자체를 키로 활용할 수는 없었을까요?

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
>          return viewModels[index]
엄밀히 보면 subscript에 index가 Int 타입인 것도 불안전한 방식입니다. 
-1가 들어오거나 범위가 벗어나면 크래시를 유발하니까요. String에서 Index를 처리하는 방식을 한 번 살펴보세요.
subscript도 안전하게 처리하는게 좋습니다

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +        let newPhoto = Photo.create(from: data)
팩토리를 없애면서 각각 Photo와 Rectangle을 생성하고 있는데 init()과 createXXX()가 어떤 차이가 있을까요?
이런 형태라면 그냥 init을 써도 되는게 아닐까 싶긴 합니다만 init을 활용하는 것과 구분해보는 게 좋습니다.

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
>          mutableViewModel.transform(to: color)
수업에서 언급했던 것처럼 Plane과 Rectangle의 생성 시점 관계에서도 직접적인 관계를 끊도록 개선해보세요

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/ViewModel.swift
> +    static func createSize() -> Size
아.. ViewModel이 구체타입이 아니라 프로토콜이었네요. 다만 많은 것을 포함하고 있는 것처럼 보입니다.
class로 써도 되는 부분도 있을 것 같은데 프로토콜로 억지로 추상화를 시도한 것은 아닌가도 생각해보세요
공통 구현 부분이 필요한 경우나 공통 속성을 가지고 있어야 한다면 Super Class로 선언하고, 프로토콜을 나눠서 채택하는 것도 고려해보세요. 
특히 static 부분은 분리해도 좋을 것 같네요

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/ViewModel.swift
> +    }
팩토리 메소드를 프로토콜을 확장한 시도는 좋네요. 
그렇지만 ViewModel이 아니라 별도 프로토콜로 타입별로 지원해도 될 것 같습니다. 타입이 있다는 것은 타입별로 더 응집도를 높이는 게 좋습니다.

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +class CanvasView: UIImageView {
이 부분은 좀 어색합니다. 모든 사각형까지도 다 이미지뷰가 되어야 하는걸까요?
뷰도 모델처럼 사각형과 이미지 타입으로 분리해보세요.

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +    let id: String
뷰가 id를 갖지 않고, 뷰 컨트롤러가 뷰 인스턴스 자체와 모델을 매칭하는 게 좋습니다. 
이렇게 따로 갖고 있으면 값도 중복되고, 하위 속성을 가져가서 비교하게 됩니다. 뷰도 타입 자체를 비교하는 게 좋습니다

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +        }
이렇게 특정 값으로 생성하는 것도 팩토리 메소드로 분리해서 만드는 것도 좋습니다. 
모델은 create로 분리했던 데 뷰는 지정 생성자를 만들고 있네요. 
특히 뷰는 기존의 지정 생성자를 활용해서 뷰에 필요한 것을 채우는 방식부터 고려해보세요
여기 생성자가 Photo 인지 사각형인지 판단하는 로직까지 갖고 있는 셈이네요

2022-03-08 02:23 UTC, godrm commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +        fatalError("init(coder:) has not been implemented")
언급했던 것처럼 이 메소드는 구현을 하라는 의미로 이렇게 되어 있는 겁니다. 이 메소드도 꼭 구현하셔야 합니다.

2022-03-10 04:47 UTC, BumgeunSong commented
[개선 사항]

1. ViewModel 인스턴스를 Key로 사용해서 검색하도록 변경
2. ViewModel을 나타내는 View 타입으로 UIView 사용.
3. View의 초기값 설정 로직을 View Factory로 분리
4. 구체 Type에 Factory 메서드를 추가 ex. `Color.random()`
5. Converter 로직을 CGFloat, CGSize 등 타입 익스텐션으로 추가. ex. `CGFloat(with: mutated.alpha)`
6. Event와 Key를 namespace로 분리.
7. transform -> set으로 메서드 이름 수정
8. didset를 사용해 dictionary 업데이트하는 로직 삭제.
9. subscript를 optional로 safe하게 수정.

2022-03-10 04:49 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Common/ConverterExtension.swift
> +}
3. Converter 로직을 CGFloat, CGSize 등 타입 익스텐션으로 추가. ex. CGFloat(with: mutated.alpha)
Converter라는 유틸리티 없이, 서로 관련있는 타입끼리만 변환하도록 수정했습니다.

2022-03-10 04:51 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        view.addGestureRecognizer(tap)
tap을 각각 서브뷰에 추가하면 빈 공간을 탭했을 때 gesture가 인식되지 않습니다! 따라서 전체 뷰에 인식기를 추가했습니다.

2022-03-10 04:52 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +    private var viewMap = [UIView: ViewModel]()
ViewModel 인스턴스와 UIView 인스턴스를 Key로 사용해서 검색하도록 변경

2022-03-10 04:53 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/PanelViewController.swift
> +    }
6. Event와 Key를 namespace로 분리했습니다

2022-03-10 04:54 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/Color.swift
> +
4. 구체 Type에 Factory 메서드를 추가했습니다.
구체 타입으로 내려서 random()을 만드니까, 타입과 메서드 이름이 합쳐지면서 설정 로직이 더 명시적으로 드러났습니다.

2022-03-10 04:55 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/ID.swift
> +    }
4. 구체 Type에 Factory 메서드를 추가했습니다.
ID 생성 로직도 구체 타입에 Factory method로 넣어주기 위해서 ID 타입을 별도로 선언했습니다.

2022-03-10 04:56 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +        return (0..<viewModels.count).contains(index) ? viewModels[index] : nil
인덱스를 벗어나면 nil을 return하도록 하고, 리턴타입을 optional 지정했습니다.

2022-03-10 04:59 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +    private var viewModels: [ViewModel] = [] {
8. didset를 사용해 dictionary 업데이트하는 로직 삭제.
관련 프로퍼티에 didset을 설정하면, viewModel add하는 함수가 여러개라도 편리하게 dictionary를 업데이트할 할거라 생각했었습니다. 

하지만 속성에 didset 을 설정했을 때, 문제가 있어 삭제했습니다.
속성이 Value type이라면: 매번 재할당이 일어나고, 추가로 인한 재할당과 아예 다른 값을 재할당하는 경우를 구별할 수가 없게 됩니다. 
속성이 Reference type이라면: 참조는 변하지 않기 때문에 didset이 호출되지 않습니다.

2022-03-10 05:00 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/ViewModel.swift
> +
1. ViewModel 인스턴스를 Key로 사용해서 검색하도록 변경
    - ViewModel이 원래 Protocol이었으나, 추상 타입인 프로토콜에 `Hashable`을 적용하는 것이 적절하지 않다고 판단했습니다.
    - ViewModel을 Rectangle, Photo의 SuperClass로 전환했습니다. Class에 Hashable를 적용해서 [모델 인스턴스:뷰 인스턴스]를 매칭할 수 있게 만들었습니다.
    - 이 결과 id를 key로 사용할 필요가 없어졌습니다. viewModel의 id는 Hashable의 재료로만 사용됩니다.

2022-03-10 05:01 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        return ViewFactory.create(from: viewModel)
2. ViewModel을 나타내는 View 타입으로 UIView 사용.
- 뷰 타입에 ID 프로퍼티가 필요없어지면서 커스텀 뷰(CanvasView)는 필요 없어집니다.
- UIKit의 클래스를 그대로 사용하는 것이 적절하다고 판단했습니다.

2022-03-10 05:03 UTC, BumgeunSong commented on DrawingApp/DrawingApp/View/ViewFactory.swift
> +    }
3. View의 초기값 설정 로직을 View Factory로 분리
- - 이전에 View의 설정 로직이 Init에 들어가있었습니다.
- Extension에 Factory 메소드를 추가하고, 뷰는 기존의 지정 생성자를 활용해서 뷰에 필요한 것을 채우는 방식으로 변경했습니다.
- switch + type casting을 사용해 Rectangle일 경우 UIView 타입으로 나타내고, Photo일 경우 UIImageView 타입으로 나타내려고 했습니다.
- 이 과정에서 이니셜라이저를 쓰는 것과 팩토리 메소드(createXXX())를 쓰는 것의 차이를 느꼈는데, 팩토리 메소드를 씀으로써 '초기값에 대한 설정 로직'과 '생성 로직'을 분리할 수 있다는 장점이 있습니다.

2022-03-10 05:03 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +        NotificationCenter.default.post(name: Plane.event.mutateOriginViewModel, object: self, userInfo: [Plane.InfoKey.mutated: viewModel])
7. transform -> set으로 네이밍 수정

2022-03-10 05:10 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/Size.swift
> +    }
4. 구체 Type에 Factory 메서드를 추가
- Size는 다른 값과 달리 초기값 설정 로직이 random이 아니기 때문에 standard라고 네이밍했습니다.

2022-03-10 07:50 UTC, godrm approved these changes
반영이 잘 된거 같습니다. 수고하셨습니다

2022-03-10 07:50 UTC, godrm commented on DrawingApp/DrawingApp/Common/ConverterExtension.swift
> +}
늘 고민스러운 부분인데요 CGFloat를 확장해서 Alpha를 지원하게 할 것인가, 혹은 Alpha를 확장해서 CGFloat을 지원하게 할 것인가 
어떤 기준으로 선택이 가능할까요?

2022-03-10 07:50 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Color.swift
> +
네 이렇게 static으로 팩토리 메소드를 제공하는 경우도 많이 있죠. 
이것도 딜레마인데요, 타입에 이런것을 계속 static 하게 늘릴 것인가, 팩토리로 분리할 것인가
그렇지만 이렇게 타입에 있으면 이 타입을 생성하려고 할 때 추상화시켜서 분리하기가 어려워집니다. 
그래서 팩토리가 있는 게 좋을 수 있죠

2022-03-10 07:50 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +    private var viewModels: [ViewModel] = [] {
맞아요 그래서 struct냐 class냐에 따라 didset 동작이 달라지기 때문에 조심해서 써야 합니다

2022-03-10 07:50 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/ViewModel.swift
>      }
결국 ViewModel이 class가 되었네요. 혹시 오늘 수업한 것처럼 프로토콜 상속 관계로 표현할 수 있는지도 살펴보세요

2022-03-10 07:51 UTC, merged