[Sol] Step3-02-2 속성 변경 기능 추가 및 Plane 구조체 유닛테스트 작성
codesquad-members-2022/swift-drawingapp pull request #46
Opened 2022-03-07 09:35 UTC by Hansolkkim

## 실행 화면
![SS 2022-03-07 PM 06 18 45](https://user-images.githubusercontent.com/92504186/157002715-f7827f7a-063d-4448-acf4-a16ce61eb832.gif)
## 작업 목록
- [x] Refactoring
  - [x] 튜플형 매개변수에 Label 명시
  - [x] Alpha, BackgroundColor 생성시 값 제한하도록 failable 생성자 이용
- [x] 사각형 뷰와 Rectangle 객체의 매칭을 위해 사각형 뷰에 해당하는 RectangleView 선언
- [x] 사각형 뷰 터치를 구현하기 위해 GestureRecognizer 사용
- [x] 우측의 배경색 버튼을 누르면 랜덤으로 Rectangle 객체 및 매칭되는 사각형 뷰의 BackgroundColor 랜덤하게 변경
- [x] 우측의 UISlider를 이용해 Rectangle 객체 및 매칭되는 사각형 뷰의 Alpha 변경
- [x] 우측의 (-),(+) 버튼을 이용해 단계별로 Rectangle 객체의 Alpha 변경
- [x] Rectangle이 선택되면 그에 맞는 배경색 버튼, UISlider를 설정하기 위한 Delegate 패턴 적용
- [x] 유닛테스트 작성 
## 고민과 해결
- 이전에는 타입에서 값을 제한하기 보다는 제한 값을 넘는 값이 오면 최소,최댓값으로 고정시켜주도록 했습니다. 그런데 저번 리뷰에서 타입 생성시 어떻게 구현할지 고민해보라는 말씀을 듣게 되었고, 말씀 중에 `런타임에 실행하지 않고 컴파일 타임에 점검할 수 있으면 가장 좋다` 는 말씀을 어떻게 적용해볼지 고민했습니다. 
  저는 failable init을 사용하면 해당 사항을 충족시킬 것이라 판단하여 Alpha, BackgroundColor 타입의 초기화 생성자로 failable한 생성자를 사용하도록 수정했습니다.

- 사각형 뷰와 Rectangle 객체의 매칭을 위해 어떤 방식을 사용할 수 있을까 고민하다가, Rectangle 객체의 id 프로퍼티는 고유한 값이 되기 때문에 사각형 뷰를 RectangleView로 선언해주고, UIView를 상속받도록 했습니다. 그리고 새로운 속성인 id를 가질 수 있도록 설정했습니다.

- Alpha를 OpacityLevel이라는 매개변수로 초기화를 시켜줬었는데, 편하게 코드를 작성하려고 하다보니 해당 값을 그냥 UIView 등에서 사용하는 alpha와 같은 CGFloat으로 초기화해주는 초기화 생성자를 하나 더 만들어줬습니다. 그런데 CGFloat로 초기화를 하다보니, 초기화 시 줄 수 있는 값을 제한하는게 불가능하다고 생각되어 다시 해당 초기화 생성자를 제거했습니다.
-

2022-03-08 03:32 UTC, godrm requested changes
입력과 출력 흐름을 나누고, 뷰를 만들 때 반복적으로 값이 복잡하게 처리되는 데 이 부분을 개선해보세요

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +            return nil
opacityLevel를 범위로 걸러내는 것도 좋은 방식입니다만 매개변수가 Int 니까 컴파일 타임에 걸러지지는 않겠죠
컴파일 타임에 확인되려면 opacityLevel 레벨이 예를 들어 1...10까지만 들어갈 수 있는 enum 타입이거나 별도 타입이어야 겠죠
그리고 단계를 정수로 주는데 value가 double이 되는 것도 살짝 어색합니다. 그 관계를 명확하게 알기 어려우니까요
지정한 값을 확인할 수 있고, doubleValue를 가져갈 수도 있는 구조라면 더 좋을 것 같습니다.

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/AlphaFactory.swift
> +    public static func generateRandomAlpha() -> Alpha? {
스위프트 API 디자인 가이드상에서 값을 생성하는 경우는 make-를 주로 사용합니다
그리고 팩토리는 특정한 값으로 안전하게 만들어지는 것을 보장해주기 때문에 옵셔널이 아니어도 좋습니다. 
그런게 Alpha.init()과 다른 점이죠

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/BackgroundColor.swift
>          let max = BackgroundColor.possibleColorValues.max() ?? 255
Alpha와 마찬가지인데 BackgroundColor도 init 할 때는 Int로 정수로 입력하는 데 생성된 값은 Double이라 어떤 관계가 있는지 유추하기 어려울 것 같습니다. 
구현을 모르는 테스트를 한다고 생각해보면 어떤 값을 넣어서 어떤 값이 생성되는지 알 수 있을까요? 
생성 시점 매개변수 타입과 속성의 타입이 다르면 좀 혼란스러울 것 같습니다

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/Converter.swift
> +    public static func convertToUIColor(backgroundColor: BackgroundColor, alpha: Double = 1.0) -> UIColor {
별도 타입을 만들기 보다는 관련있는 타입을 어느 파일에서 확장해서 쓰면 어떨까 생각해보세요
Converter는 오히려 불필요한 타입입니다

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/GenerateRectangleViewDelegate.swift
>      func planeDidAddRectangle(_ rectangle: Rectangle)
델리게이트 수업할 때 언급한 것처럼 이름과 매개변수 규칙을 지켜보세요

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        }
혹시 사각형을 찾지 못한 경우는 위로 알려줄 필요가 없을까요?

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
>      }
테스트용 메소드라는 게 어떤 의미인거죠? 이 메소드는 실제 사용하는게 아니고 테스트할 때만 쓰는건가요?
테스트할 때만 사용하는 메소드라는 게 존재한다면 이상한 것 같습니다.

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        }
이런 경우 상위에서 ID를 계속 전달해줘야 하는데 
선택된 사각형 정보를 뷰 컨트롤러가 갖고 있는게 좋을지, 여기 Plane에서 처리하는 게 좋을지도 고민해보세요
누구의 역할이고 누구의 책임이 좋을까요? 뷰 컨트롤러는 어떤 역할을 주로 하던가요?

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +    private(set) var id: ID
id를 속성으로 가져가지 않고 Equatable을 채택했으면 Rectangle 자체를 비교할 수 있지 않을까요?

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +        return false
이런 경우 return `조건식` 형태로 사용해도 깔끔합니다. 참고하세요

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +        self.id = ID.init()
뷰를 생성하는 데 ID가 꼭 필요한 것일까요?
뷰가 데이터를 저장하고 그걸 가져가서 또 비교하는 것보다는 뷰도 뷰의 인스턴스 자체를 비교하는 방식이 좋습니다.
뷰와 모델을 매칭할 때도 ID가 아니라 인스턴스끼리 비교하도록 해보세요

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +    var plane = Plane()
ViewController의 속성도 private var를 우선적으로 고려하세요

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        plusAlphaValueButton.backgroundColor = .systemGray6
이런 뷰를 바꾸는 동작이 출력에 해당합니다. 터치했을 때 바로 이걸 변경하지 마시고, 
출력의 흐름을 만들고 모델에서 뷰컨트롤러로 알려줄 때 출력하도록 해보세요

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        let convertedOpacityLevel = Int(10 * newAlphaValue)
여기 값을 다루는 게 이상하게 복잡해보이네요. sender.value가 어떤 값이길래 String으로 바꿨다가 다시 Double로 바꾸는건가요?
더구나 다시 Int로 또 바꾸는 과정이 번거로워 보입니다. 개선할 수 없을까요?

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        let convertedOpacityLevel = Int(10 * newAlphaValue)
위에 언급한 것처럼 변환 과정이 번거롭고 계속 반복됩니다.

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        if let specifiedRectangleView = self.touchedView {
self.touchedView 에 넣고 또 specifiedRectangleView 바인딩하는 게 좀 어색합니다. 
matchedView만으로 가능한 게 아닐까요?

2022-03-08 03:32 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        }
서브뷰에서 O(n) 방식으로 다 찾기보다는 매칭해서 O(1)으로 찾는 게 더 좋습니다.

2022-03-08 06:02 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +            return nil
> opacityLevel를 범위로 걸러내는 것도 좋은 방식입니다만 매개변수가 Int 니까 컴파일 타임에 걸러지지는 않겠죠
> 컴파일 타임에 확인되려면 opacityLevel 레벨이 예를 들어 1...10까지만 들어갈 수 있는 enum 타입이거나 별도 타입이어야 겠죠
> 그리고 단계를 정수로 주는데 value가 double이 되는 것도 살짝 어색합니다. 그 관계를 명확하게 알기 어려우니까요
> 지정한 값을 확인할 수 있고, doubleValue를 가져갈 수도 있는 구조라면 더 좋을 것 같습니다.

어제 OCP 강의 때 사용하셨던 방법 이용해서 OpacityLevel이 될 수 있는 프로토타입들을 단계(1...10)만큼 만들어 사용하는 방식으로 수정해보겠습니다.

2022-03-08 07:03 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +            return nil
@godrm 이 부분에 대해서 질문이 있습니다! 
Alpha에 들어갈 수 있는 값을 제한해보라고 하셨는데, 제한하는 방법을 생각해봐도 UISlider.value와 같은 값을 이용하기 위해서는 결국은 Alpha든, OpacityLevel 타입이든 CGFloat와 같은 원시값으로 초기화하는 과정이 필요하게 돼서 여기서 헤메는 중입니다..
기존에 RectangleFactory 등에서는 Alpha에 들어가는 값을 컴파일 타임에서 확인할 수 있도록 제한하는 방법은 이해가 갔는데,
UISlider.value로 Alpha 타입을 만들어줄 때는 그럼 따로 변환하는 과정을 거치던가, 아니면 다른 방법이 있는건지 궁금합니다..

2022-03-08 07:12 UTC, godrm commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +            return nil
Alpha에서 할 일과 상위에서 변환해서 넘겨줄 일을 구분해야하는 거죠 (두 개 피드백이 합쳐져 있었네요)
우선 매개변수 Int 랑 내부 속성 Double 타입인 것은 Alpha 내부 사정이지만 이것을 맞춰보시구요

---
UISlider.value로 만들어 줄때는 외부 입장에서 Alpha에 맞춰야 하는 상황이죠. 
제 말은 Alpha부터 만들면 외부가 복잡해질테니, 필요하면 Alpha에 다른 생성자가 추가될 수도 있겠죠
그렇지만 UISlider.value가 아니더라도 Alpha 자체만 놓고 봐도, 단위 테스트만 하더라도 충분히 안정적으로 생성되고 확인할 수 있어야 합니다. 예를 들어 10으로 넣고 생성했는데 value가 1.0라면 예측가능하지 않아서 테스트하기 어려울 것 같다는 맥락입니다. 

---
변환하는 것은 위의 것과 별개로 상위에서 CGFloat -> Int로 바꾸거나 CGFloat -> Alpha로 바꾸는 함수가 필요할 수 있습니다. 그건 여기 init을 고치라는 의미가 아닙니다. CGFloat 과 Alpha를 둘 다 알고 있는 상위에서 변환하는 기능이 필요한거죠

2022-03-08 09:08 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +            return nil
Alpha의 OpacityLevel에 해당하는 열거형을 선언해주어 초기화에 사용하도록 하여 컴파일 타임에서 입력 가능한 범위를 제한해보고, Alpha의 프로퍼티에 value 외에 opacityLevel도 추가하여 생성 시점과 확인 시점에서의 어색함을 줄여보겠습니다!

제가 초기화 시점에서의 범위 제한과 타입 생성에 대해서 복잡하게 생각하다보니 많이 꼬여버린 것 같습니다. 답변 감사합니다!

2022-03-08 09:08 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +            return nil
Alpha의 OpacityLevel에 해당하는 열거형을 선언해주어 초기화에 사용하도록 하여 컴파일 타임에서 입력 가능한 범위를 제한해보고, Alpha의 프로퍼티에 value 외에 opacityLevel도 추가하여 생성 시점과 확인 시점에서의 어색함을 줄여보겠습니다!

제가 초기화 시점에서의 범위 제한과 타입 생성에 대해서 복잡하게 생각하다보니 많이 꼬여버린 것 같습니다. 답변 감사합니다!

2022-03-08 09:09 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/AlphaFactory.swift
> +    public static func generateRandomAlpha() -> Alpha? {
> 스위프트 API 디자인 가이드상에서 값을 생성하는 경우는 make-를 주로 사용합니다
> 그리고 팩토리는 특정한 값으로 안전하게 만들어지는 것을 보장해주기 때문에 옵셔널이 아니어도 좋습니다.
> 그런게 Alpha.init()과 다른 점이죠

컨벤션이 있는줄 몰랐네요,, 팩토리 메서드들의 이름 `make-` 형태로 수정하고, 팩토리 메서드들의 반환값 타입이 옵셔널이 아니도록 수정해보겠습니다.

2022-03-08 09:09 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/AlphaFactory.swift
> +    public static func generateRandomAlpha() -> Alpha? {
> 스위프트 API 디자인 가이드상에서 값을 생성하는 경우는 make-를 주로 사용합니다
> 그리고 팩토리는 특정한 값으로 안전하게 만들어지는 것을 보장해주기 때문에 옵셔널이 아니어도 좋습니다.
> 그런게 Alpha.init()과 다른 점이죠

컨벤션이 있는줄 몰랐네요,, 팩토리 메서드들의 이름 `make-` 형태로 수정하고, 팩토리 메서드들의 반환값 타입이 옵셔널이 아니도록 수정해보겠습니다.

2022-03-08 09:10 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/BackgroundColor.swift
>          let max = BackgroundColor.possibleColorValues.max() ?? 255
> Alpha와 마찬가지인데 BackgroundColor도 init 할 때는 Int로 정수로 입력하는 데 생성된 값은 Double이라 어떤 관계가 있는지 유추하기 어려울 것 같습니다.
> 구현을 모르는 테스트를 한다고 생각해보면 어떤 값을 넣어서 어떤 값이 생성되는지 알 수 있을까요?
> 생성 시점 매개변수 타입과 속성의 타입이 다르면 좀 혼란스러울 것 같습니다

저도 저 부분을 왜 저렇게 바꿨는지 의아하네요...ㅎㅎㅎ..
해당 부분 Int로 수정하겠습니다..

2022-03-08 09:12 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Converter.swift
> +    public static func convertToUIColor(backgroundColor: BackgroundColor, alpha: Double = 1.0) -> UIColor {
> 별도 타입을 만들기 보다는 관련있는 타입을 어느 파일에서 확장해서 쓰면 어떨까 생각해보세요
> Converter는 오히려 불필요한 타입입니다

파일에서의 특정 타입을 확장하여 수정해보겠습니다! 안그래도 해당 부분을 작성하고 나니 JK께서 이전에 말한 유틸리티에 해당하는 걸 작성한게 아닌가 싶었는데 맞았네요. .감사합니다!

2022-03-08 13:18 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/GenerateRectangleViewDelegate.swift
>      func planeDidAddRectangle(_ rectangle: Rectangle)
> 델리게이트 수업할 때 언급한 것처럼 이름과 매개변수 규칙을 지켜보세요

델리게이트 메서드의 이름 첫 자리는 이벤트의 주체가 되도록, 그리고 매개변수와 같은 타입이도록 해당 메서드 이름을 `rectangleDidAdded(_ rectangle: Rectangle)` 로 수정해보겠습니다!

2022-03-08 13:25 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        }
이 부분에서는 뷰 컨트롤러가 뷰로 부터 변화를 감지하고, 모델(Plane)에게 해당 변화로 인한 업데이트를 요구하는 역할을 합니다.
해당 메서드는 뷰 컨트롤러로부터 Plane이 특정 Rectangle의 backgroundColor를 변경하라는 지시를 받아서 변경하는 메서드인데, 이런 경우에는 뷰 컨트롤러가 Plane에게 Rectangle을 특정해서 바꾸라고 지시하는게 맞는 흐름일까요?

일단, 아래의 리뷰들을 참고해서 id 프로퍼티로 Rectangle을 비교하지 않기 위해 뷰 컨트롤러에서 RectangleView와 Rectangle을 매핑해놓는 프로퍼티를 만들어 소유하고 있도록하고, 위의 메서드를 호출할 때 Rectangle을 특정해서 매개변수로 넘겨주는 방식으로 수정해보려고 합니다. 그런데 이렇게 뷰 컨트롤러가 특정 Rectangle까지 알고 있는게 맞는가 궁금합니다.

2022-03-08 13:28 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +    private(set) var id: ID
id를 유의미하게 사용해보고자 하는 생각으로 id를 속성으로 가지고 가서 비교하는 방법을 사용했습니다. 그런데 이렇게 내부의 속성을 사용하지 않고도 비교할 수 있다면 그런 방법을 사용하는게 더 적절하다고 생각됩니다.
해당 부분을 다시 `private let id: ID` 로 수정하도록 하고, 비교에서는 JK 말씀처럼 Rectangle 자체를 비교하는 방법을 사용해보겠습니다.

2022-03-08 13:29 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +        return false
이전에도 받았던 리뷰인데 생각처럼 잘 못 쓰게 되네요.. 수정하도록 하겠습니다!

2022-03-08 13:29 UTC, Hansolkkim commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +        self.id = ID.init()
넵 RectangleView 객체에서 id 프로퍼티를 제거하고 인스턴스끼리 비교하는 방법을 사용하도록 수정해보겠습니다!

2022-03-08 13:30 UTC, Hansolkkim commented on DrawingApp/DrawingApp/ViewController.swift
> +    var plane = Plane()
제일 상위 타입으로만 사용할거라고 생각해 그 부분을 신경 못 썼던 것 같습니다. 프로퍼티들을 private 접근 제어자를 사용하다록 수정하겠습니다.

2022-03-08 14:08 UTC, Hansolkkim commented on DrawingApp/DrawingApp/ViewController.swift
> +        let convertedOpacityLevel = Int(10 * newAlphaValue)
원하는 길이로 자른 다음 Alpha를 초기화하는데 사용하려고 위와 같이 사용했습니다..
Alpha를 초기화하기 위한 값의 타입을 위에서 바꿨기 때문에 Int로 바꾸는 부분은 삭제했고,
newAlphaValue를 구하는 부분을 타입 변환을 계속해서 사용하는 방법 대신 `Double(round(sender.value * 10) / 10.0)` 으로 수정해보겠습니다!

2022-03-08 14:09 UTC, Hansolkkim commented on DrawingApp/DrawingApp/ViewController.swift
> +        let convertedOpacityLevel = Int(10 * newAlphaValue)
해당 부분도 위에서 답변 드린 대로, `Double(round((touchedView.alpha + 0.1) * 10) / 10.0)` 로 바꾸도록 해보겠습니다.

2022-03-08 14:15 UTC, Hansolkkim commented on DrawingApp/DrawingApp/ViewController.swift
> +        }
위에서 답변 드린 내용으로, RectangleView와 Rectangle을 viewRectangleMap 이라는 `Dictionary<RectangleView: Rectangle>` 프로퍼티에 생성시 매칭해서 넣어주는 방법으로 수정했습니다. 그런데 Delegate 메서드에서 Rectangle 객체를 매개변수로 받아와서 사용하다보니, 다시 View를 찾기 위한 방법은 O(1) 으로 사용하기가 어려워졌습니다.. 
```swift
let matchedView = viewRectangleMap.first(where: { view, rectangle in
    rectangle == specifiedRectangle
})?.key
```
혹시 해당 방법 외에 Value로 Key를 접근할 때 O(1)의 시간복잡도를 갖도록 하는 방법이 있을까요? 아니면 제가 매칭한 방법에서는 O(1)의 방법이 없는걸까요?

2022-03-08 14:17 UTC, Hansolkkim commented on DrawingApp/DrawingApp/ViewController.swift
> +        if let specifiedRectangleView = self.touchedView {
아래의 바인딩부분 제거하고 matchedView만 이용하는 방법으로 수정하겠습니다!

2022-03-09 14:05 UTC, Hansolkkim commented on DrawingApp/DrawingApp/ViewController.swift
> +        let convertedOpacityLevel = Int(10 * newAlphaValue)
해당 부분 수정하다가 `sender.value` 값이 Float 타입인데, Double 타입으로 형변환하는 과정에서 불필요한 소수값이 추가되는 문제가 발생해, Alpha 등에서 사용하는 타입을 모두 Float으로 수정하고, 위에서 말씀드린 방식을 `round(sender.value * 10) / 10` 으로 변경하여 적용하겠습니다.

2022-03-09 15:57 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        }
> 혹시 사각형을 찾지 못한 경우는 위로 알려줄 필요가 없을까요?

알려주기 위해, rectangleDidSpecified(_:) 메서드의 매개변수가 Optional 타입을 받고, 사각형을 찾지 못 한 경우 해당 메서드의 매개변수를 nil로 하여 호출하도록 설정하여 수정해보겠습니다!

2022-03-09 15:58 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
>      }
> 테스트용 메소드라는 게 어떤 의미인거죠? 이 메소드는 실제 사용하는게 아니고 테스트할 때만 쓰는건가요?
> 테스트할 때만 사용하는 메소드라는 게 존재한다면 이상한 것 같습니다.

그런 이유로 사용했습니다.. 해당 부분 수정하고 테스트 코드 수정해보겠습니다!

2022-03-09 16:01 UTC, Hansolkkim commented on DrawingApp/DrawingApp/ViewController.swift
> +        plusAlphaValueButton.backgroundColor = .systemGray6
> 알려주기 위해, rectangleDidSpecified(_:) 메서드의 매개변수가 Optional 타입을 받고, 사각형을 찾지 못 한 경우 해당 메서드의 매개변수를 nil로 하여 호출하도록 설정하여 수정해보겠습니다!

위에서 말씀드렸던 방법을 이용해 모델에서 뷰 컨트롤러로 알려줄 때인 rectangleDidAdded(_:) 메서드에서 매개변수에 nil을 사용해 호출하고, 해당 매개변수가 nil일 경우에 해당 메서드를 호출하도록 수정해보겠습니다.

2022-03-09 16:07 UTC, Hansolkkim commented on DrawingApp/DrawingApp/ViewController.swift
> +        }
해당 부분을 지우고, ViewController가 Rectangle과 RectangleView를 매칭해서 알고있도록 rectangleAndViewMap Dictionary 타입 프로퍼티를 사용하고, 변경된 Rectangle 객체를 델리게이트 메서드의 매개변수로 가져와서 해당 프로퍼티의 Key값으로 사용해 O(1)으로 RectangleView를 찾을 수 있도록 수정하겠습니다!

2022-03-09 16:19 UTC, Hansolkkim commented
리뷰해주셨던 부분 모두 수정 완료했습니다! 
리뷰 내용대로 수정하던 도중 Delegate 메서드의 이름 규칙에 대해 궁금한 점이 생겼습니다.

스타일 가이드에는 Delegate의 메서드의 맨 앞에 오는 이벤트 주체의 이름과 제일 앞 매개변수가 일치해야 된다는 말이 있어서,
이번 스텝에서 제가 사용했던 메서드들은 대부분 Rectangle 객체에 대한 이벤트와 관련되있다고 생각했기 때문에 `rectangleDidAdded(_ rectangle: Rectangle)` 와 같이 사용했습니다.

그런데 다른 클래스에서 기본적으로 구현되어있는 Delegate 메서드에서는, 예를 들어 UITextFieldDelegate의 메서드는
`textFieldDidEndEditing(_ textField: UITextField..)` 의 형태로 구현되어 있었습니다.

그래서 저는 이번 스텝에서의 제가 사용한 Delegate 메서드도 실질적으로는 Plane과 관련되어 있기 때문에 `plane-` 으로 시작되야 맞는 형태가 아닌가 생각이 들었습니다. 그래서 `planeDidAddRectangle(_)` 의 형태로 사용하려고 하니, 매개변수를 Plane 객체 타입으로 사용하는게 어색하게 느껴졌습니다.

혹시 이런 경우에는 컨벤션에 따르면 `rectangleDidAdded(_ rectangle: Rectangle)` , `planeDidAddRectangle(_ plane: Plane)` , 둘 중 어느 형태의 메서드가 더 적합한 형태인지가 궁금한지 알 수 있을까요?

2022-03-10 01:28 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        }
해당 부분, Plane에서는 이전에 선택된 Rectangle을 알고 있도록 하는 프로퍼티를 만들어 알고있도록 하고, 뷰컨트롤러로부터 변화(backgroundColor/ alpha) 지시를 받은 경우에 프로퍼티에 해당하는 Rectangle을 변화하도록 수정했습니다.
그리고 앞서 말씀드린 매핑해놓은 프로퍼티의 경우에는 Key가 Rectangle이고, Value가 RectangleView인 Dictionary인데, 뷰컨트롤러의 프로퍼티가 하위모델인 Rectangle을 직접 안다기보다는, 어떤게 뷰와 매칭되는 Rectangle 객체인지 정도만 아는 것이라 판단되어 이를 계속 사용하도록 하려고 합니다.

2022-03-10 08:12 UTC, godrm approved these changes
개선된 방향에서 다음 스텝을 진행해보세요

2022-03-10 08:12 UTC, godrm commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +        self.value = opacityLevel.rawValue
오 OpacityLevel을 내부에 enum으로 선언했군요. 
이런 경우 value를 OpacityLevel에서 계산하는 computed property로 해도 될 것 같네요

2022-03-10 08:12 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    public func stepUpAlphaValue() -> Rectangle? {
changeAlphaValue()와 stepUpAlphaValue()는 뭐가 다른걸까요?
다 return 타입이 Rectangle? 인것도 좀 어색합니다. 뭔가 result가 필요한 게 아니라 전부 Rectangle이 필요한게 맞나요?

2022-03-10 08:12 UTC, godrm commented on DrawingApp/DrawingApp/Model/PlaneDelegate.swift
> +    func rectangleAlphaDidChanged(_ rectangle: Rectangle)
프로토콜로 델리게이트를 정의할 때 PlaneDelegate 인데 이름 시작, 매개변수가 다 Rectangle인게 어색하네요.
이러면 RectangleDelegate여야 하지 않을까요?

2022-03-10 08:12 UTC, merged

2022-03-10 08:20 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +        self.value = opacityLevel.rawValue
처음에 그렇게 사용했다가, RectangleView에 alpha를 넣어주는 과정에서 `Alpha.opacityLevel.value ` 이렇게 호출하는게 복잡하다고 생각되어 위처럼 value를 다시 사용하는 방법으로 고쳤습니다. computed property로도 호출할때 이름이 어색하지 않는 방법이 없는지 고민해보겠습니다.

2022-03-10 08:33 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    public func stepUpAlphaValue() -> Rectangle? {
> changeAlphaValue()와 stepUpAlphaValue()는 뭐가 다른걸까요?

다 같은 changeAlphaValue(to:) 메서드로 처리할 수 있겠네요 stepUpAlphaValue(), stepDownAlphaValue() 메서드 삭제하고 changeAlphaValue(to:) 메서드로 모두 처리하도록 하겠습니다.

> 다 return 타입이 Rectangle? 인것도 좀 어색합니다. 뭔가 result가 필요한 게 아니라 전부 Rectangle이 필요한게 맞나요?
테스트할 때 Rectangle? 을 반환받는 것이 적절하고, 반환값이 있어도 함수 동작에는 문제가 되지 않아 속성 변경 메서드들이 Rectangle? 타입을 반환하도록 했습니다.. 테스트 함수 짜는 부분이 아직 어려워 해당 부분을 처리할 방법을 더 고민해보고 수정해보겠습니다

2022-03-10 08:36 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/PlaneDelegate.swift
> +    func rectangleAlphaDidChanged(_ rectangle: Rectangle)
> 스타일 가이드에는 Delegate의 메서드의 맨 앞에 오는 이벤트 주체의 이름과 제일 앞 매개변수가 일치해야 된다는 말이 있어서,
이번 스텝에서 제가 사용했던 메서드들은 대부분 Rectangle 객체에 대한 이벤트와 관련되있다고 생각했기 때문에 rectangleDidAdded(_ rectangle: Rectangle) 와 같이 사용했습니다.
> 
> 그런데 다른 클래스에서 기본적으로 구현되어있는 Delegate 메서드에서는, 예를 들어 UITextFieldDelegate의 메서드는
textFieldDidEndEditing(_ textField: UITextField..) 의 형태로 UITextField 타입을 매개변수로 받도록 구현되어 있었습니다.
> 
> 그래서 저는 이번 스텝에서의 제가 사용한 Delegate 메서드도 실질적으로는 Plane과 관련되어 있기 때문에 plane- 으로 시작되야 맞는 형태가 아닌가 생각이 들었습니다. 그래서 planeDidAddRectangle(_) 의 형태로 사용하려고 하니, 매개변수를 Plane 객체 타입으로 사용하는게 어색하게 느껴졌습니다.
> 혹시 이런 경우에는 컨벤션에 따르면 rectangleDidAdded(_ rectangle: Rectangle) , planeDidAddRectangle(_ plane: Plane) , 둘 중 어느 형태의 메서드가 더 적합한 형태인지가 적절한지 알 수 있을까요?

수정 후 댓글에서 질문드린 내용입니다. 델리게이트 메서드들의 이름을 설정하는 부분에 대해서 고민을 했는데 이번 리뷰 내용을 보니 더 궁금한 점이 많아졌습니다..ㅠㅠ
혹시 PlaneDelegate의 프로토콜명을 RectangleDelegate로 수정한다면, 해당 Delegate를 Plane에서 가지고 있어도 이상하지는 않을까요?

2022-03-10 08:42 UTC, godrm commented on DrawingApp/DrawingApp/Model/PlaneDelegate.swift
> +    func rectangleAlphaDidChanged(_ rectangle: Rectangle)
맞아요. Plane에서 보내는 델리게이트면 PlaneDelegate가 맞겠죠. 
PlaneDelegate라면 Plane을 전달해줘야 하는게 아닐까요? 
RectangleDelegate이라면 Plane에서 호출하는 게 아니어야겠죠. 그러니까 이상하다는거죠 ㅎㅎ 
누가 보내느냐. 그렇지만 어떤 정보를 갖고 있느냐 그걸 혼동할 필요는 없습니다.

2022-03-10 08:43 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    public func stepUpAlphaValue() -> Rectangle? {
당연히 return 이 필요없거나 동작에 대한 결과를 주면 되는데, Rectangle?을 반환한다고 동작은 영향을 주지 않지만 이상한 겁니다
적절한 리턴값이 무엇인가를 고민해보세요. Result<> 라는 타입도 있습니다

2022-03-10 09:04 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/PlaneDelegate.swift
> +    func rectangleAlphaDidChanged(_ rectangle: Rectangle)
답변 감사합니다!
그럼 Delegate 메서드들 이름을 모두 `plane-` 으로 시작하도록 수정하고, 매개변수도 (_ plane: Plane) 으로 수정하여 다음 PR때 추가하겠습니다!

2022-03-10 16:23 UTC, Hansolkkim commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    public func stepUpAlphaValue() -> Rectangle? {
Result를 사용하면 Test에서도 더 잘 쓸 수 있겠네요,, 리턴값에 대해 고민해보고 수정해보겠습니다! 감사합니다!