[shingha]Step4 사진 추가하기
codesquad-members-2022/swift-drawingapp pull request #48
Opened 2022-03-07 13:00 UTC by shingha1124

## 체크리스트

- [x] 사진을 고를 수 있게 포토앨범을 띄운다
- [x] 선택한 사진을 앱으로 가져온다
- [x] 선택한 사진을 드로잉 뷰에 그린다
  - [x] 알파값을 조절하면 이미지의 투명도가 변경되도록 한다
  - [x] 배경색 변경은 지원하지 않는다
- [ ] 사진 데이터만 관리하는 모델타입을 선언해야한다
- [ ] 불러온 사진은 바이너리 형태로 메모리에서만 관리한다

## 고민과 해결

* 이미지를 URL로 관리하기
  * 전에 포토앱에서 사용했던 PHPhoto코드를 가져와서 적용
  * 요구사항은 URL로 관리하라는 요구사항이 있어 삽질 시작
    * itemProvider.loadInPlaceFileRepresentation 
      * 이 함수를 사용하면 URL을 가져올수 있었음
    * 아 쉽네? 하고 이미지를 로드하는데 되는게 있고 안되는게 있음
    * 흐응.....왜...?파일 경로도 다 있는데....
    * 해당경로의 이미지를 전부 삭제 후 다시 해봄
    * 이미지로드가 안됨... 
    * 구글링시작.....그닥 나오는것이 없음....
    * 데이터로 변환하고 count를 찍어보니 0 출력
    * 아...데이터 로드가 안되는거였구나 하고 다른 삽질 시작
    * 해당경로의 이미지도 잘 생성되었는데... 확인해보니
      경로의 이미지가 0바이트임...
    * itemProvider.load~~~함수를 전부 호출해본 결과 0바이트로 생성되는것이 있고, 정상적으로 생성되는 것이 있음
    * 이를 바탕으로 구글링을 해보니
    * itemProvider.loadFileRepresentation를 호출해서 임시 이미지 경로를 받아오고, 
      이것을 다른경로로 옮겨서 사용하면 된다고 함
  * 해결
    * itemProvider.loadFileRepresentation함수를 호출하여 선택한 이미지의 임시 경로를 받아옴
    * FileManager를 이용하여 temp폴더에 선택한 이미지를 저장
    * 위에서 새로 만든 경로를 사용하여 이미지 출력

2022-03-08 05:43 UTC, godrm requested changes
소소하게 의견을 남겨봤습니다. 
직접적으로 구체 타입을 의존하는 것을 개선해보세요

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
>          return String((0..<3).reduce(""){ id, _ in
이렇게 makeId가 내부 private static func 이면 Id 생성에 대한 기능은 테스트하기 힘든 구조가 됩니다. 
그래서 의존적인 기능들을 역전해서 사용하는 게 더 좋은거죠. 
이제 팩토리도 테스트 가능한 구조로 개선해보세요. 
모든 생성 함수들을 각각 테스트할 수 있고, 어떤 형태인지 검증할 수 있으면서
DrawingModelFactory가 SizeFactory, PointFactory 각각 의존하지 않도록 개선해보세요

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +        let photoView = PhotoView()
DrawingView 나 PhotoView를 생성할 때도 기존에 있는 지정 생성자를 활용할 수 있는 건 충분히 활용해도 좋습니다. 
특히 point와 size가 frame 값과 매칭되니까 그대로 활용해도 좋습니다. 
새로운 뷰를 생성할 때 계속해서 지정생성자가 추가된다면 어떻게 생성해야 할지 헷갈릴 수도 있습니다 
가능하면 init으로 초기화할 때 필요한 걸 전달해주는 구조가 더 좋습니다. 메소드가 줄어들수록 응집도가 높아지니까요

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/ColorFactory.swift
>          return self.make(using: ramdomGenerator)
정해진 규칙대로 생성하는 것인지 랜덤인지 구분할 수 있으면 더 좋습니다

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Color.swift
> +        return hex
이런 기능을 테스트 가능한 구조로 만들려면 어떻게 하는게 좋을까요?
저라면 Color Element 요소를 위한 타입을 하나 만들고 거기에 func으로 넣을 수 있을 것 같네요

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/PhotoRectangle.swift
> +    }
이 부분은 구현하지 않은 것은 상속 관계 때문인걸까요? 
이런 구조가 클래스 구현 상속의 단점이죠. 그래서 이런 것을 인터페이스 분리 원칙에 따라서 프로토콜로 분리해서 Photo는 Color 기능이 없도록 만들어보세요

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/PhotoRectangle.swift
> +        self.imageUrl = url
URL로 이미지를 관리하면 URL은 로컬 주소, 혹은 리모트 주소 모두가 가능할 것일까요?
URL에 있는 이미지는 메모리에 있는 건 아니네요. 더 관리할 게 많아지겠군요 
PR 본문에 있던 temp 경로 관리하던 게 이것 때문이었네요. 접근 자체는 좋습니다.

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +    func alphaChanged(_ alpha: Alpha)
touchPoint()처럼 colorChanged도 changeColor()가 된다거나 changeAlpha()가 되어야 비슷한 형태가 될 것 같네요

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +    func makeRectangle(url: URL)
makeRectangle()과 makeRectangle(url:)이 조금 겹치면서 어색하네요.

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        let rectangle = DrawingModelFactory.makePhotoRectangle(url: url)
Plane과 DrawingModelFactory도 프로토콜을 이용해서 직접적인 관계를 분리해보세요

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        NotificationCenter.default.post(name: Plane.EventName.didmakeRectangle, object: nil, userInfo: userInfo)
노티를 post하는 sender는 object를 항상 지정해주는 게 좋습니다.

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
>          }
기존에 selectedRectangle 이 있는데 같은 곳을 터치하면 nil로 바뀌었다가 다시 select가 되는걸까요?

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        static let didmakeRectangle = NSNotification.Name("didmakeRectangle")
사소한 것입니다만 didmakeRectangle 는 camel표기법을 지키지 않고 있네요

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
>      enum EventName {
Notification.Name과 EventName이 연결고리가 있으면 더 좋겠습니다.

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/DrawingBoard/View/PhotoView.swift
> +    private let photoView: UIImageView = {
기존의 사각형 DrawingView 가 PhotoView보다 상위가 되는게 적절한가 모르겠습니다.
서로 다른 속성을 갖고 있고 특히 PhotoView에는 Color나 이런게 필요가 없는데 말이죠 
오히려 공통적인 부분만 일반화해서 상위 뷰를 만드는 게 어떨까요?

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            self.rectangleViews[rectangle.id]?.selected(is: false)
`self.rectangleViews : [String:DrawingView]`를 매칭할 때도 rectangle.id 속성을 가져오기 보다는 Rectangle 자체를 비교하는 게 어떨까요?

2022-03-08 05:43 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +                }
plane은 뷰가 아니니까 main 큐에서 처리할 필요는 없습니다.

2022-03-08 07:00 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
>          return String((0..<3).reduce(""){ id, _ in
어제의 수업을 참조하여 init에서 의존성을 넣어 사용하도록 수정했씁니다

2022-03-08 07:04 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +        let photoView = PhotoView()
init로 초기화를 진행할 수 있도록 수정했습니다

2022-03-08 07:06 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/ColorFactory.swift
>          return self.make(using: ramdomGenerator)
함수 이름을  makeRandomColor으로 변경하였습니다.

2022-03-08 07:46 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/PhotoRectangle.swift
> +    }
서로 같은 부분은 DrawingModel이라는 상위 모델을 만들어서 사용하고
다른 부분은 각 프로토콜을 생성하여 사용하도록 수정했습니다.

2022-03-08 07:46 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +    func alphaChanged(_ alpha: Alpha)
함수이름들 변경하였습니다

2022-03-08 07:47 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +    func makeRectangle(url: URL)
각각 생성하는 모델의 이름을 붙였습니다

2022-03-08 07:48 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        let rectangle = DrawingModelFactory.makePhotoRectangle(url: url)
모델의 init에서 팩토리를 받아올수 있게 수정했씁니다

2022-03-08 07:50 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
>          }
조건문을 리펙토링하여 필요할때만 이벤트가 호출되도록 수정했습니다

2022-03-08 07:50 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Plane.swift
> +        static let didmakeRectangle = NSNotification.Name("didmakeRectangle")
PR올린 후 코드 정리하다 발견하여 수정했습니다

2022-03-08 07:51 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Present/View/DrawingBoard/View/PhotoView.swift
> +    private let photoView: UIImageView = {
상위 뷰를 하나 더 만들어서 관리할 수 있도록 수정했습니다

2022-03-08 07:51 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            self.rectangleViews[rectangle.id]?.selected(is: false)
Hashable을 사용하여 Model 자체가 키가 될수 있도록 수정했씁니다

2022-03-08 08:09 UTC, shingha1124 commented
## 체크리스트

- [x] DrawingModelFactory에서 사용하는 여러 Factory를 의존성주입을 통해 사용
- [x] Model 생성 시, 객체 생성 후 업데이트 하지 말고, Init에서 받아 처리하도록 수정
- [ ] Color의 hexFromDecimal을 테스트가능한 구조로 변경
- [x] rectangleModel, photoModel을 상위 Model을 하나 만들어 관리
- [x] Image를 메모리로 관리
- [x] selectedRectangle 코드 리펙토링( 필요한 경우에만 이벤트를 호출 하도록 )
- [x] drawingModel을 키로 사용할 수 있도록 작업

컬러부분 리뷰는 아직 완전히 이해하지 못해 생각해보고 있습니다!

2022-03-08 08:53 UTC, shingha1124 commented
컬러 예외처리부분은 한번 수정해 보았습니다 !
범위를 넘어서는 값이 올 경우 에러가 발생하도록 수정했습니다.

2022-03-09 13:09 UTC, godrm approved these changes
개선이 잘 된거 같습니다. 
다음 단계를 진행해보세요

2022-03-09 13:09 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Color.swift
> +        assert(b > 0 && b < 255 )
assert를 사용하는 것은 debug 시점에만 확인이 가능하고, release에서는 전혀 동작하지 않습니다
그래서 범위를 제한하는 것보다는 타입을 제한하는 게 더 좋습니다
Color.Element 처럼 하위 타입을 만들거나 해서 도전적으로 시도해보라는 의미였습니다. 이정도에서 넘어갑시다.

2022-03-09 13:09 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/SizeFactory.swift
>      }
인스턴스 메소드가 되면 여기 메소드들은 속성이 없는데로 인스턴스를 만들어야 하기 때문에 응집도가 떨어지는 메소드가 됩니다. 
그래서 이게 꼭 좋은 건 아니에요

2022-03-09 13:09 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/DrawingBoard/View/DrawingView.swift
> +        layout()
이 정도 뷰라면 이미 있는 뷰의 메소드들을 활용해도 충분히 처리가 가능할 것 같습니다. 
언제 서브 클래스를 구현할 것인가는 늘 고민해봐야 합니다.

2022-03-09 13:09 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/Inspector/InspectorView.swift
> +            self.delegate?.changeColorButtonTapped(color: color)
뷰에 있는 버튼 액션인데 델리게이트를 호출하는 것은 괜찮지만 Factory에서 컬러를 생성하는 것은 로직이라고 봐야할 것 같습니다
어떤 내용을 처리할지는 여기서 모르는 게 더 좋습니다

2022-03-09 13:10 UTC, merged