[Kai] Step2 : 속성 변경 동작
codesquad-members-2022/swift-drawingapp pull request #49
Opened 2022-03-07 15:47 UTC by TaeKyeongKim

## [작업목록]
- [X] MVC 패턴을 사용하여 사용자의 요청을 처리하도록 설계.
- [X] Plane 구조체 설계. 
- [X] 사각형의 투명도와 색상 변경 가능.
- [X] 변경에 따른 시각적 구현.
- [ ] XCTest. 

## [학습 키워드] 
`Delegation`  `MVC pattern` `UIGestureRecognizer` `UITapGestureRecognizer` `hitTest` `UIStepper`  

## [결과 화면] 
![Mar-08-2022 00-18-22](https://user-images.githubusercontent.com/36659877/157062719-474b8ebf-5d62-477a-9984-2b18a432b7cb.gif)

## [질문] 
- ViewController 에 Dependency Injection 을 시도 해보려 했는데 생각했던것처럼 잘 되지 않아서 일단은 적용을 안한 상태입니다. Setter Inject 방법으로 구현 해보려 했는데 각각의 뷰 기능이 아직 별로 없어서 특정한 프로토콜 로 나누질 못했습니다. 나중에 기능이 더해지면 시도해보는게 좋을지 지금부터 기능을 나누어서 해보면 좋을지 고민입니다.

2022-03-08 06:26 UTC, godrm requested changes
몇 가지 핵심적인 구조 변경에 대해 언급했구요, 특히 뷰를 모두다 서브클래스를 사용할 필요가 없습니다
우선 UILabel, UIButton 같은 뷰를 그대로 쓸 수 있는 경우도 많습니다. 확인해서 개선해보세요

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +    let panelWidth : Double = 200
여기서 화면 요소가 많아지면 View Controller 코드가 뷰 관련 코드가 길고 복잡해집니다.
그러면 화면 요소별로 묶어서 하위뷰를 만들 수 있습니다. 예를 들어 colorRondomizeButton, alphaStepper, stepperLabel 등을 묶을 수 있는거죠 
그러면서 관리할 모델까지 많아지면 Container ViewController 형태로 하위로 MVC가 또 생길 수도 있습니다

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        }
이 부분에서 탭 제스처는 입력 흐름이라서 뷰 -> 뷰 컨트롤러 -> 모델까지 입력만 처리하고 끝나야 합니다.
plane에서 특정한 영역의 사각형을 찾으면 모델 -> 뷰 컨트롤러 -> 뷰까지 출력하는 흐름을 분리해보세요 
여기서 한꺼번에 plane도 호출하고, 뷰 선택도 처리하지 마세요. 그 흐름을 분리하는 게 중요한 포인트입니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        }
특정한 뷰를 찾을 때도 서브뷰에서 다 찾지마시고, 뷰 컨트롤러는 뷰와 모델을 다 알고 있으니 한 번에 매칭해서 찾을 수 있으면 더 좋습니다. 뷰가 많아질 수록 느려지는 동작이니까요.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +    }
RectangleView 구현을 안 봤지만 뷰가 자신의 selected 상태를 갖고 있는 것은 좋지 않습니다
뷰는 뷰를 표시하기 위한 속성들만 갖고 있고, 모델이 가진 selected에 따라서 뷰의 색상, 테두리 등 출력 형태를 결정하는 것은 여기서 처리해야 합니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +    }
여기 함수들은 presenter 역할이라서 출력에 대한 처리 같은데, 이름에서 그걸 구분할 수 있으면 더 좋겠습니다. 
혹시 update-를 그런 의미로 사용한걸까요?

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +//MARK: Event 4.0 : 사용자가 ColorRondomizeButton 를 터치했을때 그 사각형에 대한 정보를 패널에 정보를 표시한다. (1/2)
`Event 4.0` `Event 3.0` 이건 어떤 의도인거죠? 이름만 보면 어떤 동작인지 유추할 수 있는 게 가장 좋습니다. 
여기 있는 주석들이 특별히 더 부가적인 정보를 주는 것 같지는 않습니다. 
주석은 코드 내용보다 더 구체적이고 부가적인 정보를 줘야 의미가 있는 거고, 중복되거나 혼란을 줄 수 있으면 차라리 없는 게 낫습니다

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        }
컬러 값을 문자열로 비교하는 것은 좋지 않네요. 문자열로 무언가 비교하는 것은 거의 대부분 좋지 않습니다.
타입이 있다면 타입끼리 비교하는 게 좋습니다. 더구나 여기서는 컬러값을 비교할 필요가 있나요? 
컨트롤러는 이벤트를 받아서 그것을 처리할 곳에 이벤트를 알려주면 됩니다. 그게 랜덤 컬러인지, 화이트인지 무엇으로 바꾸는지 몰라야 하는거죠.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +    }
여기 이벤트에서는 sender만 있는데 targetModel과 targetView가 어디에 있는지 모르겠네요
출력에 대해서 처리할 때도 sender가 의미가 있어야 하는 데 관련이 없다는 게 의아합니다. 
targetModel 이나 targetView 가 속성이라면 매개변수로 넘기지 않아도 되는거 아닐까요?

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Extensions/Utils.swift
> +    }
어.. CGFloat을 소숫점으로 자르기 위해서 문자열로 바꾸는 것은 매우 안 좋은 변환입니다
심지어 컴파일 단계에서 Double과 CGFloat은 호환되는 타입입니다. 만약 자르려면 수학 함수로 처리하는 게 더 좋습니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Extensions/Utils.swift
> +    }
이런 값을 생성하는 static func을 팩토리 메소드라고 합니다. 스위프트 API 디자인 가이드에서는 make-를 주로 붙이구요
이번 미션에서는 팩토리를 별도 타입으로 분리해보는 걸 연습하고 있습니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Extensions/Utils.swift
> +    }
이 함수가 필요하면 Color에 그냥 구현해도 될꺼 같은데요?

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Extensions/Utils.swift
> +import UIKit
여기서 UIKit은 왜 필요할까요?

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Alpha.swift
> +    case Clear
Clear가 One보다 더 투명하거라면 case에서도 더 위에 있는게 어떨까요?

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Alpha.swift
> +            return 0.1
단계를 만들 때는 Int를 기준으로 생성할 텐데, value가 Double이면 조금 혼란스러울 수도 있을 것 같네요
이럴 때 computed property라면 value가 왜 Double 타입인지 힌트를 주면 더 좋겠습니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Color.swift
> +        //각각의 rgb 가 0~255 사이의 값이 아닐시 0으로 설정해준다.
이 부분을 주석으로만 안내할 게 아니라 타입을 생성할 때부터 Double 수많은 값들 범위 중에서 0부터 255까지만 가능하다는 것을 알 수있도록 해주는 게 가장 좋습니다. 
Card의 Shape 이나 Rank를 하위 타입으로 만들었던 것처럼 Color.Element 타입을 만든다거나 할 수도 있는거죠
타입을 지정하는 것에 대해 좀 더 적극적으로 접근하셔도 좋겠습니다. 
생성할 때 매개변수가 꼭 원시 타입이어야 하는 건 아니니까요

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Plane.swift
> +    func didAppendRect(rect: Rectangle?)
델리게이트 수업할 때 언급한 것처럼 누가 보내는 것인가, 이름 규칙과 매개변수 규칙을 적용해보세요

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Plane.swift
> +        }
이 부분이 이상한데요? willSet 이면 추가되기 전이고 didAppendRect()는 다 추가된 다음에 부른다는 의미 아닌가요?

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Plane.swift
> +    }
subscript도 안전하게 제공하는 게 가장 좋습니다. Int로 매개변수를 주면 -100 이런 값도 들어올 수 있으니까요

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Plane.swift
> +                os_log(.debug,"모델정보: \(rectangle)")
os_log를 붙이는 규칙은 어떻게 정한건가요? 모든 메소드에 있는 것은 아닌가 본데 어디에만 들어간건지 궁금합니다

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Plane.swift
> +    func detectRect(x: Double, y: Double) -> Rectangle? {
`detectRect(x:, y:)`는 x,y에서 시작하는 사각형을 찾는걸까요? 사각형 x와 사각형 y를 찾는걸까요?
좀 더 명확한 이름으로 의도를 표현하면 좋겠습니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Point.swift
> +//Point (좌표) 타입 정의
이런 주석은 추가적인 정보가 부족합니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/Rectangle.swift
> +            delegate?.didChangeProperty(sender: self)
아.. 값을 보관하는 하위 모델들이 모두 델리게이트를 가질 필요는 없습니다 (물론 필요한 경우가 있을수도 있습니다만 여기서는 불필요해보입니다)
이 값을 다루는 Plane이 언제 값을 바꾸는 지 대충 알 수 있지 않던가요?
어디와 어디 사이에만 델리게이트가 필요한 가 고민해보시면 좋겠습니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Model/ShapeFactory.swift
> +        return Color.getRandomColor()
Color.getRandomColor() 코드에서도 언급한 것 같은데
Color.init() 과 여기서처럼 Color.init(랜덤값) 이렇게 호출하는 구조를 나누는 것도 중요합니다
모든 것을 꼭 Color 타입에서 하지 않아도 됩니다. 특히 랜덤 생성같은 경우는 분리하는 게 좋습니다

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/Protocols.swift
> +}
전혀 사용하지 않는 타입 같은데요? 커밋할 때 사용하는 파일만 추가하는 게 좋습니다

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/View/AlphaSlider.swift
> +    }
이미 있는 슬라이더를 사용해도 될 것 같네요. 단지 델리게이트를 추가하려고 서브 클래스를 만들 필요는 없습니다. 
델리게이트를 꼭 만들 필요없이 이미 target-action으로 이벤트를 전달할 수 있으니까요

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/View/PanelView.swift
> +    }
패널뷰가 배경색과 투명도를 label만 포함하는 거였군요. 이런 구조라면 Button과 Slider도 PanelView로 옮겨도 될 것 같은데요?

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/View/RectangleGenerationButton.swift
> +        self.addTarget(self, action: #selector(didTapButton), for: .touchUpInside)
버튼도 마찬가지로 내부 속성이 추가된게 없고, 동작이 특별한게 없다면 상속하지 말고 UIButton을 그대로 사용하고 target-action으로 연결하면 충분할 것 같습니다.

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/View/RectangleView.swift
> +    }
selected 에 대해 앞서도 언급했는데 뷰가 상태를 가지고 있지 않은게 좋습니다

2022-03-08 06:26 UTC, godrm commented on drawingApp/drawingApp/View/StepperLabel.swift
> +    }
모든 뷰를 서브클래스를 만들 필요는 없습니다. 이미 UILabel도 속성만 바꾸면 되는 건 그대로 쓰시면 됩니다

2022-03-08 08:48 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +//MARK: Event 4.0 : 사용자가 ColorRondomizeButton 를 터치했을때 그 사각형에 대한 정보를 패널에 정보를 표시한다. (1/2)
`Event 4.0`, `Event 3.0` 은 사용자가 앱을 통해서  할수 있는 기능을 따로 이름을 정해서 어떠한 기능을 하는지 코멘트 해놓은것입니다. README 에 이벤트 각각의 흐름을 정리해 두어서 각함수가 어떠한 이벤트를 처리할건지 명시해 주었습니다. 하지만 저걸로 혼란을 일으켰다면 좀더 명확한 네이밍으로 수정하겠습니다.

2022-03-08 08:50 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +    let panelWidth : Double = 200
말씀해 주신데로 `colorRondomizeButton`, `alphaStepper`, `stepperLabel` 를 `PanelView` 라는 곳으로 묶어주어 View Controller 를 간결화 했습니다.

2022-03-08 14:03 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Extensions/Utils.swift
> +    }
올림, ceil() 함수를 이용해서 변환 처리를 해주었습니다. 
이해가 잘안되서 그러는데 혹시 컴파일 단계에서 Double과 CGFloat은 호환되는 타입에 문자열을 사용해서 변환하는법이 어떻게 안좋은지 예시를 하나만 주실수 있을까요?

2022-03-08 14:05 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +    }
앗 이건 제가 고친다는걸 까먹고 그대로 PR 한부분이네요.. 죄송합니다

2022-03-09 16:24 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +    }
넵 맞습니다. 이름을 좀더 명확히 짓겠습니다.

2022-03-10 15:18 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        }
넵 말씀 하신대로 따로 분리 해 보았습니다.

2022-03-10 15:23 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        }
특정한 `RectanlgeView` 를 looping 을 하지않고 어떻게 찾아야하나 고민했습니다.
다른분들의 추천에 딕셔너리 로 `var RectangleList = [Rectangle : RectangleView]` 를 지정해주고 `plane` 에서 델리게이트로 보내온 모델들을 키값으로 참조하여 뷰를 찾고 업데이트 해주는 방식으로 수정하였습니다.

2022-03-11 03:40 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +    }
모델에 isSelected 라는 속성을 추가 해주고 뷰는 시각적 요소들만 가지고 있게 수정하였습니다.

2022-03-11 07:21 UTC, TaeKyeongKim commented on drawingApp/drawingApp/View/RectangleGenerationButton.swift
> +        self.addTarget(self, action: #selector(didTapButton), for: .touchUpInside)
커스텀 UIView 를 만들어야한다는 강박 관념이 있었습니다. 말씀하신대로 특별한 동작없는 뷰들은 UIButton, UIView 를 이용하였고, `Panel` 만 오른편 버튼과 레이블 등을 포함하는 커스텀 UIView 로 만들어 봤습니다.

2022-03-11 07:23 UTC, TaeKyeongKim commented on drawingApp/drawingApp/View/PanelView.swift
> +    }
Slider 또한 없어져야하는 파일인데 깃에는 계속 남아 있었네요.. 옮기는 작업은 위에 말씀드린것처럼 처리 하였습니다.

2022-03-11 07:24 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Model/Plane.swift
> +                os_log(.debug,"모델정보: \(rectangle)")
`rectangle` 모델에 속성값이 변경되면 로그를 찍는 규칙을 정했습니다.

2022-03-11 07:25 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Model/Plane.swift
> +        }
willSet 을 연습한다고 하고 나중에 didSet 으로 다시 안 바꾼것같습니다. 수정하였습니다.

2022-03-11 08:03 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Model/ShapeFactory.swift
> +        return Color.getRandomColor()
alpha, color 랜덤 값을 생성해주는 구조체 `RandomGenerator` 를 새로 만들어 봤습니다.

2022-03-11 08:13 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Model/Plane.swift
> +    func detectRect(x: Double, y: Double) -> Rectangle? {
넵 tabCoordX, tabCoordY 로 바꾸어 주었습니다.

2022-03-11 08:15 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Model/Rectangle.swift
> +            delegate?.didChangeProperty(sender: self)
아 그렇군요. plane 에서 델리게이션 처리 하는 방식으로 수정하였습니다.

2022-03-11 08:52 UTC, TaeKyeongKim commented
아직 color 와 alpha 부분은 수정하지 못한상황입니다. MVC 역할의 분리를 집중해서 수정하였습니다.

2022-03-11 09:45 UTC, godrm commented
> 아직 color 와 alpha 부분은 수정하지 못한상황입니다. MVC 역할의 분리를 집중해서 수정하였습니다.

계속 PR을 닫았던데 열어놔도 됩니다. 대신 작업한 만큼 커밋하다가 한꺼번에 push하고 댓글 달아도 되니까요. 
그럼 지금 상태로 리뷰하면 될까요?

2022-03-11 10:11 UTC, godrm approved these changes
추가적으로 몇 가지 의견을 남겼습니다. 더 수정할 내용이 남았으면 열어놓고 그렇지 않으면 머지하고 다시 개선하는 것도 좋을 것 같습니다. 댓글 남겨주세요

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        }catch{
do-try-catch를 사용하는 경우는 catch와 아래로 내려가는 정상 흐름을 꼭 구분해주는 게 좋습니다
그래야 정상 흐름인지, 비정상 흐름인지 구분이 되고 그거에 따라 앱에서 사용자에게 뭔가 표시할지, 다시 시도할지 판단할 수 있게 됩니다.

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        plane.searchRectangleModel(tabCoordX: point.x, tabCoordY: point.y)
이 메소드는 언제 호출이 될까요? 한 번만 호출이 되나요, 여러번 호출이 되나요? 그것에 따라서 다르게 동작할 수 있나요?

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        view.addSubview(rectView)
뷰를 생성하는 부분도 팩토리가 있다면 어떨까요?

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        var parsedModels = models
혹시 배열로 전달해주는 이유가 있나요? 여러개를 선택할 수 있는 건가요?

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +            parsedModels = models.reversed()
이 부분은 잘 모르겠습니다. last만 쓰는 거면 Rectangle 하나만 넘겨줘도 되는 건 아닌가요? 
여기서 여러 model을 다 처리하고 있는 것은 Plane의 역할을 하고 있는 것 같다는 느낌도 드네요. 어떤가요?

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        if let rectView = rectangleList[model] {
이런 코드에서도 if let 으로 하고 들여쓰기를 하기 보다는 guard let으로 binding하고 들여쓰기 없이 쓰는 게 좋습니다. 참고하세요

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +            updatePanel(from: model)
패널을 업데이트할 때도 세부적으로 나누는 건 어떨까요? 바뀌지 않은 모든 값을 다 업데이트해야 하는 건 아니지 않을까요?

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
>      }
command 패턴과 비슷한 구조를 만들었네요.  이렇게 합쳐서 구현한 의도가 궁금합니다.

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
>          }
plane에 접근할 때 계속 두 단계로 plane.getSelectedModel()를 하고 plane.randomizeColor(on: selectedModel) 호출하게 되는 데 한 번에 호출하도록 하는 게 어떨까요?

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Model/Plane.swift
> +        delegate?.didAppendRectangleModel(model: rectangles.last)
만약 Plane이 Rectangle 객체의 생성하는 것까지 가져온다면 어떤 차이가 있을까요? 
외부에서 생성하고 넘겨주는 것과 여기서 생성하는 것은 어떤 차이가 있을까요?

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Model/Plane.swift
> +    func searchRectangleModel(tabCoordX x : Double, tabCoordY y: Double)  {
tabCoordX, tabCoordY 대신에 그냥 x, y로 하는 것과 어떤 차이가 생길까요?
이 메소드를 호출할 때 꼭 tab (그리고 보니 터치 이벤트를 누르는 것은 tap 입니다. tab은 공간을 구분하는 단위죠) 한 경우만 호출해야 하는 것일까요?

2022-03-11 10:11 UTC, godrm commented on drawingApp/drawingApp/Model/Plane.swift
> +              return false
여기서는 세 가지 의견이 있습니다. 
- 단지 좌표를 포함하는 경우를 찾느냐... 찾은 것을 변화시키느냐... 그것을 한꺼번에 하는 느낌입니다
- 그리고 filter로 하게 되면 어떤 것을 찾더라도 나머지 모든 뷰를 다 비교하게 되는데 그걸 의도해서 배열로 넘기는 걸까요?
단 하나를 찾는게 아니라 여러개를 찾아야 하는 이유가 있나요? 
- 
이 부분에서 rectangle에게 이 좌표를 포함하고 있어? 라고 물어보면 어떨까요? plane의 역할과 rectangle의 역할이 혼용되어 있는 것 같아요

2022-03-11 12:20 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Model/Plane.swift
> +    func searchRectangleModel(tabCoordX x : Double, tabCoordY y: Double)  {
명명은 원래 x,y 였는데 조금더 구체적으로 x,y 가 어떤 의미를 하는지 명시해주면 좋겠다 라는 피드백을 받고, 제 생각도 바꾸면 일반 x,y 로 매개 변수를 받는것보다 구체적으로 어떠한 좌표를 넘겨주어야하는지 알수 있기 때문에 이렇게 수정해 봤습니다. (tap 이였네요 ㅎㅎ)

2022-03-11 12:26 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        }catch{
정상 흐름을 구분 하라는 뜻이 잘 이해가 안되는데 catch 문에 에러를 프린트 해주라는 뜻일까요??

2022-03-11 12:28 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        plane.searchRectangleModel(tabCoordX: point.x, tabCoordY: point.y)
사용자가 화면을 터치 했을때 호출되어서 좌표를 plane 에게 넘겨주는 기능으로, 한번 호출됩니다.

2022-03-11 12:35 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        view.addSubview(rectView)
오.. 좋은 생각 인것 같습니다.  개인적으로 뷰 생성하는 과정이 너무 지저분하게 보여서 ViewController 파일이 복잡하게 보였는데 모델만 넘겨주고 해당 정보로 뷰 를 반환 해주는 팩토리 를 만들어 준다면 깔끔해 지고 코드를 재활용을 할수 있을것 같다는 생각이 듭니다.  한번 수정해 보도록 하겠습니다.

2022-03-11 13:27 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        var parsedModels = models
이 부분이 가장 힘든 부분이였는데요.. 
저번 PR 에선 현재 선택된 모델 과 뷰, `targetModel`, `targetView` 를 전역 변수로 지정해주어서 다른 뷰 를 선택하면 `panel.searchRectangleModel()` 이 호출되고 델리게이트 함수인 `manageSelectingViews()`에서 지금 선택된 모델과 뷰를 `targetModel`, `targetView` 로 업데이트 해주는 형식으로 했었습니다.

위 방법에서  `targetModel`, `targetView`  라는 속성을  ViewController 에 할당해주는건 ViewController 이 모델을 직접적으로 다루고있다? 라는 생각이 들어서 이번에 새롭게 짜본 코드에서는  ViewController 안에 `targetModel`, `targetView` 를 사용하지 않고 진행 해 보았습니다. 

초기에 `targetModel`, `targetView` 을 지정해둔 목적은 이전에 선택 되었던 모델과 뷰 를 알아내는 용도로 사용했었고, 이를 대체할수 있는 방법으로 `panel.searchRectangleModel()` 에서 저번에 선택 되었던 모델까지 같이 `manageSelectingViews()` 로 보내준다는 생각으로 코드를 짜보았는데 겹쳐진 사각형의 좌표를 선택하면 여러개의 사각형 모델이 선택되는것을 지금 확인 했습니다..

따라서 새로운 접근으로 Plane 안에서 전에 선택 되었던 모델을 따로 변수로 지정 하여 새로운 좌표 정보와 매칭된 모델을 할당시켜주고, 이전에 선택 되었던 모델을 뷰 에서 시각적으로 선택 해제되는 델리게이트를 구현 해보려고 합니다.

2022-03-11 13:28 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +            parsedModels = models.reversed()
네.. 맞습니다. 수정 하도록 하겠습니다.

2022-03-11 13:30 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +            updatePanel(from: model)
넵 더 세부적으로 나누는게 좋을것같습니다.

2022-03-11 13:46 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
>      }
모델의 속성중에 특정한 부분이 수정된다면, 어떠한 부분이 수정 되었는지에 따라 사각형 뷰 와 패널 에 수정된 속성과 관련된 뷰를 업데이트를 해주어야했고 이 과정을 어떻게 하면 보기 쉽고 재사용이 가능하게 할수 있을까? 라는 생각을 했습니다. 

그러다 예전에 보았던 계산기 프로그램 예제가 생각이 났습니다. 현재 코드와 같이 매개 변수로 두 값이 들어오고 어떤 계산을 할것인지 `operation` 으로 지정해주면 작성된 `operation` 에 의해 값이 계산되는 방법이였는데요, 지금 상황에서 쓸수 있겠다라는 생각을 해서 사용해보았습니다.  

혹시 지금 과 같은 상황에서 사용하면 어색할까요?

2022-03-11 13:50 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        plane.searchRectangleModel(tabCoordX: point.x, tabCoordY: point.y)
tapTriggered() 가 혹시 여러번 호출되지 않냐는 겁니다. 보통 제스처 인식기가 터치 한 번하더라도 상태가 바뀌면서 호출되거든요. 그 부분을 얘기하는 겁니다

2022-03-11 13:53 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        var parsedModels = models
입력 흐름에서 뷰를 선택하는 게 편하다고 생각할 수 있지만, 입력 흐름과 출력 흐름을 연결하지 않고 분리해서 생각하는 게 좋습니다
입력 시점에서 출력 시점에서 사용할 뷰를 찾아놓고 쓰려고 하지말라는 겁니다. 
입력은 입력흐름으로 끝내고, 출력은 출력흐름에서 전달받은 데이터 구조로 출력 뷰를 찾아서 출력하는거죠. 그래야 서로 분리가 가능합니다.

2022-03-11 13:54 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Model/Plane.swift
> +              return false
넵 이부분은 위에서 말씀드린거와 같이 수정하겠습니다. 흑..잘못된 생각을 이해하시기 위해 많은 시간을 쏟으셨을 JK.. 죄송하고 감사합니다. 
앞으로는 이런 시간 안쓰시게 한번더 생각하고 코드를 짜보겠습니다.

2022-03-11 13:55 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        }catch{
정상 흐름 => 정상적으로 생성이 되는 경우 try 이후 catch 범위가 실행되지 않겠죠
비정상 흐름 => try로 시도한 팩토리가 실패하면 아래 코드가 실행되지 않고 catch 범위로 넘어갈테죠
그러면 이 두 흐름이 결과적으로 달라야 한다는 겁니다. 
정상도 비정상도 흐름이 같아지는 것은 이상하다는 거죠

2022-03-11 13:56 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
>          }
넵 수정해보겠습니다.!

2022-03-11 14:02 UTC, TaeKyeongKim commented
> 계속 PR을 닫았던데 열어놔도 됩니다. 대신 작업한 만큼 커밋하다가 한꺼번에 push하고 댓글 달아도 되니까요.
그럼 지금 상태로 리뷰하면 될까요? 

아 ㅎ 그렇군요!  알겠습니다.

> 추가적으로 몇 가지 의견을 남겼습니다. 더 수정할 내용이 남았으면 열어놓고 그렇지 않으면 머지하고 다시 개선하는 것도 좋을 것 같습니다. 댓글 남겨주세요

개인적으로 지금 피드백 해주신 부분 마저 수정하고 머지 하고 싶은데  괜찮을까요?

2022-03-12 07:41 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        plane.searchRectangleModel(tabCoordX: point.x, tabCoordY: point.y)
흠 이부분은 잘이해가 안돼서 이해하는데 시간이 좀 걸리네요..
일단 `tapTriggered()` 가 여러번 호출이 될까요 에 대답은 "아니요" 인것 같습니다
`tabgestureRecognizer` 는 불연속 제스처 로서, 이벤트를 인식하면 액션 메소드 를 한번만 호출 하는 걸로 알고 있습니다. 
만약 연속 제스처인 `pan gesture` 와 `rotation gesture` 등 일경우에 는 제스처 의 상태가 시작되고 끝날때 까지 액션을 계속 호출 주는걸로 알고 있습니다. 
따라서 현재 위의 함수는 `tabgestureRecognizer` 의 액션으로, 사용자가 tap 이라는 특정한 이벤트를 ViewController 에 발생시킬때 한번만 호출 된다고 생각되고 생각됩니다.

2022-03-12 07:51 UTC, TaeKyeongKim commented on drawingApp/drawingApp/Model/Plane.swift
> +        delegate?.didAppendRectangleModel(model: rectangles.last)
ViewController 에서 모델 생성을 하지 않고 plane 안에서 모델을 생성해주는 메소드 를 호출해준다면 모델을 다루는 일은 모두 plane 이 하기 때문에 뷰 와 모델의 역할을 더 뚜렸히 나눌수 있을것같습니다.

2022-03-14 06:29 UTC, TaeKyeongKim commented
## [FeedBack List]
- 1.0 try catch 의 정상흐름과 비정상흐름을 나눠라
→ 모델 생성 하는 부분에 에러가 안생기도록 

- 2.0 gestureRecognizer 의 액션이 여러번 호출 되는지?
→ 댓글에 저의 의견을 적어 봤습니다.

- 3.0 뷰 생성 팩토리 구현하기
→ 전반적인 팩토리 설계를 바꾸어 보았습니다.  정적 팩토리를 만들어 객체의 인스턴트를 만들지 않아도 되도록 구현하였습니다.

- 4.0 targetModel 설정
→ Plane 안에 `selectedModel` 이라는 프로퍼티를 만들어 전에 선택되었고, 현재 선택 된 모델을 파악할수 있도록 했습니다.
→ 기존에 `selectedModel` 를 모델 배열에서 서치를 하여 수정된 알파와 색상을 따로따로 호출했던부분도 `randomizeColorOnSelectedModel`  과 `changeAlphaOnSelectedModel` 를 사용하여 한번에 불러오고 적용되도록 수정했습니다.

- 5.0 guard let 으로 바인딩 하기
→ 전반적인 if let 구문 들을 -> guard let 바인딩으로 수정하였습니다. 

- 6.0 updatePanel 세분화
→  `colorRandomization()` 과 `alphaModification()` 의 `updatePanel` 을 바뀐 뷰에만 적용되도록 수정하였습니다.

2022-03-14 07:48 UTC, godrm commented
수고하셨습니다. 다음 단계 진행해보죠!

2022-03-14 07:48 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
>      }
아주 이상하지는 않았어요.

2022-03-14 07:49 UTC, godrm commented on drawingApp/drawingApp/Controller/ViewController.swift
> +        plane.searchRectangleModel(tabCoordX: point.x, tabCoordY: point.y)
네. Tap은 말한게 맞아요. UIGestureRecognizer 자체가 기본적으로 여러번 호출 가능하기 때문에 그게 인식기마다 다르다는 것을 알면 됩니다.

2022-03-14 07:50 UTC, godrm commented on drawingApp/drawingApp/Models/Model.swift
> +    func selectedStatus() -> Bool
프로토콜로 추상화를 잘 했는데, 이것도 관련 있는 것끼리 묶어서 분리하는 것을 시도해보세요.

2022-03-14 07:50 UTC, merged