[ebony] - Step3 observer
codesquad-members-2022/swift-drawingapp pull request #50
Opened 2022-03-08 08:35 UTC by rising-jun

#### 🧑🏼‍💻 작업 목록
- [x] ViewController는 viewDidLoad에서 Observe를 등록한다.
- [x] 새로운 사각형을 추가하거나 속성 바뀔 때마다 Notification을 받아서 화면을 업데이트한다.
- [x] 속성을 바꾸면 해당 모델 값이 변할 때 마다 Plane 모델 객체에서는 변화에 대해 NotificationCenter에 post한다.
- [x] 모든 동작은 이전 단계와 동일하게 동작해야 한다.

#### 💭 학습 키워드
Notification, NotificationCenter, Observer, NSKeyValueObservation

#### 👀 고민과 해결
Notification과 observer의 관계를 이해하고, NotificationCenter에 대한 역할을 검색해보았습니다.
- Notification의 observer는 어디서 추가해야 하며, 어디서 post를 해야할까? 에 대한 고민을 하였습니다.
- '객체가 변경되었다' 고 알려줘야 하는 곳에서 post를 했고(Plane), 변경을 확인하고 뷰를 변경하거나, 이를 사용하여 다른 로직을 수행하는 곳(ViewController)addObserver를 사용하였습니다.

#### 💡 느낀점
- 이전에는 Delegate를 사용하여 메소드들을 사용하였다면, 이번에는 직접 메소드를 활용하지 않고 Notification을 통하여 post만 하고, 이를 감지하고 있는 객체에서 직접 해당 로직을 수행하는 식으로 변경되었다 느꼈습니다.
- Notification에도 여러가지 방법으로 사용할 수 있다는 것을 공부하였습니다.
 ```swift
        NotificationCenter.default.addObserver(forName: NSNotification.Name?, object: Any?, queue: OperationQueue?, using: (Notification) -> Void)

        NotificationCenter.default.addObserver(observer: Any, selector: Selector, name: NSNotification.Name?, object: Any)
```

첫번째는 동기로 수행되며 object-c방식을 채택하고 있습니다.
두번째 방식은 Queue를 지정하여 비동기로 수행할 수 있고, 클로져를 활용하는 스위프트 방식으로 공부하였습니다.

루카스의 Notification강의를 보고 코드스쿼드 유튜브 구독하였습니다...! 👍

2022-03-09 13:26 UTC, godrm requested changes
NotificationCenter를 잘 시도했습니다만, 몇 가지 아쉬운 부분을 의견남겼습니다. 
수정해서 다시 push해보세요

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/message/DrawingDelegate.swift
>      func deselected()
델리게이트 프로토콜을 선언할 때, 수업 시간에 언급한 것처럼 
관련 타입의 이름, 이벤트 시점에 대한 표현, 매개변수의 규칙등을 고려해서 개선해보세요

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/model/ColorRGB.swift
> +    }
값을 넣은 것이 그대로 들어가지 않고 변화한다는 것은 오히려 혼란을 주고, 테스트하기 어려운 타입이 되어 버립니다
`ColorRGB(r:-10, g:9999, b:1234)` 이런 값을 넣을 수 있고 그게 컴파일러에서 아예 들어가지 않는 게 가장 좋습니다
다 들어가는 데 값이 넣을 때마다 바뀐다면 오히려 어색한 타입이 됩니다

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        rectangleFactory = RectangleFactory()
`rectangleFactory: RectangleFactoryResponse`으로 선언했는데 RectangleFactory()를 직접 생성하는 것처럼 보이네요
의존적인 타입이라면 Plane 외부에서 생성해서 넣어주는 방식을 고려해보세요

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
>      }
이렇게 하위 속성의 값을 가져가기 보다는 Rectangle 처럼 중간 타입이 있으면 그걸 넘겨주는 방법도 있고,
좀 더 나가면 특정한 값을 가져갈 수 있는 프로토콜을 타입처럼 리턴하는 방법도 있습니다. 
Plane의 바로 아래 Rectangle 정도를 찾아주는 것은 괜찮은데, Plane에서 Rectangle의 속성까지 가져갈 수 있는 것은 캡슐화를 깨는 거라고 생각하세요

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        NotificationCenter.default.post(name: .updateRectangleAlpha, object: selectedRectangle)
여기가 PlaneDelegate 메소드들인가요? 근데 좀 어색한 것은 PlaneDelegate 프로토콜이면 Plane -> (전달할 객체 A) 관계에서 A가 이걸 채택해야 하는 것 같은데, Plane이 채택하고 있네요? 어떤 흐름이길래 이렇게 된거죠?

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +    static let updateRectangleAlpha = Notification.Name.init("updateRectangleAlpha")
노티를 같은 타입이라고 이렇게 묶어놓기 보다는, 노티와 관련된 타입과 같이 선언하는 게 좋습니다. 
이걸 받는 타입은 어디죠? 이걸 보내는 타입은 어디죠? 어디에 선언하는 게 좋을까요?

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/model/RectangleFactory.swift
> +    }
RectangleFactory 에 대해 프로토콜로 OCP를 잘 지킨 것 같은데 아쉽게도 생성하는 타입이 Rectangle 구체 타입이네요.
이 부분을 프로토콜로 바꾸면 더 좋겠네요!

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
>      }
NotificationCenter의 object는 sender의 의미입니다. 누가 보내는 노티인지 지정할 수 있으면 하는 게 더 좋습니다

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        drawingDelegate?.updatedAlpha(alpha: rectangle.alpha)
여기 노티를 받는 메소드 이름들이 모든 시나리오를 다 알고 있는 것 같은 이름입니다.
어떤 이벤트인지, 어떤 값이 바뀌었는지를 알려주면 되고, 그것으로 무엇을 할 지 메소드로 명시할 필요는 없습니다
예를 들어 changeViewColorRandomly()보다는 rectangleDidChangedColor() 정도도 충분하고,
그 값이 random인지 특정한 값인지 여기서는 몰라도 되는거죠.

2022-03-09 13:26 UTC, godrm commented on DrawingApp/DrawingApp/view/SplitViewController.swift
> +        NotificationCenter.default.post(name: .changedColorText, object: rectangleRGB)
학습 영상에서 언급한 것처럼 object는 sender의 의미라서 이걸 보내는 인스턴스가 self를 지정해주는 게 보통입니다.
값을 전달할 때는 userInfo를 활용하세요

2022-03-10 06:34 UTC, rising-jun commented on DrawingApp/DrawingApp/model/RectangleFactory.swift
> +    }
@godrm 리뷰 감사합니다!! Rectangle객체를 직접반환하지 않고 Delegate형식으로 반환하는 방식을 말씀하시는건가요!?
```swift
func randomRectangle() {
       factoryDelegate.makeRandomRectangle(rectangle: Rectangle)
  }
```

2022-03-10 09:51 UTC, rising-jun commented
@godrm 리뷰해주신 내용들 이해한대로 개선해보았습니다!
SplitViewController에서의 self메모리 값과, PropertyViewController에서의 SplitViewController메모리값이 다르게 나와서, 일단 NotificationCenter.addObserver의 Object값은 nil로 비워두었습니다.
NotificationCenter.post,addObserver에서 object를 추가하던 중 plane이 struct로 선언되었어서, DrawingViewController에서의 plane과 Plane객체에서의 plane 메모리값이 다르게 표현되었습니다. plane에서 addRectangle(mutating func addRectangle)을 할 때마다 값이 바뀌어 그랬다는 사실을 알게 되었습니다. class와 struct의 차이를 하나 더 알게 되었습니다. 😁

2022-03-10 09:51 UTC, rising-jun commented on DrawingApp/DrawingApp/model/RectangleFactory.swift
> +    }
> RectangleFactory 에 대해 프로토콜로 OCP를 잘 지킨 것 같은데 아쉽게도 생성하는 타입이 Rectangle 구체 타입이네요. 이 부분을 프로토콜로 바꾸면 더 좋겠네요!

리뷰 해주실때 답변해주시면 감사하겠습니다!!

2022-03-10 10:00 UTC, godrm commented on DrawingApp/DrawingApp/model/RectangleFactory.swift
> +    }
델리게이트가 아니라 팩토리가 return 해주는 타입을 프로토콜로 추상화해보라는 겁니다. 
생성할 때는 구체 타입이지만, 반환해서 넘겨줄 때는 프로토콜 타입으로 전달되는거죠

2022-03-10 11:13 UTC, rising-jun commented on DrawingApp/DrawingApp/model/RectangleFactory.swift
> +    }
넵 이해했습니다!! 감사합니다!

2022-03-10 13:06 UTC, godrm commented
맞아요 그렇게 라이브러리 중에는 struct와 어울리는 것, class가 어울리것을 구분해서 사용해야 합니다. 
문법적으로 지원한다고 해서 다 동일하게 동작하는 게 아니니까요

2022-03-10 13:07 UTC, godrm commented on DrawingApp/DrawingApp/message/DrawingDelegate.swift
>      func deselected()
델리게이트 구조를 만들 때 이름, 매개변수에 대한 규칙을 지키면 더 좋겠습니다. 
그래야 누가 누구에게 어떤 상황에서 보내는 것인지 명확하게 의도를 파악할 수 있습니다

2022-03-10 13:07 UTC, godrm commented on DrawingApp/DrawingApp/message/RectangleChangeable.swift
> +    func changeRectangleAlpha(changed: RectangleAlphaChange)
오 저도 안해본거 같은데 이렇게 func에 mutating을 붙이면 struct에도 mutating 함수가 되나요?

2022-03-10 13:09 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        NotificationCenter.default.post(name: Plane.NotiEvent.updateRectangleAlpha, object: self, userInfo: [PlaneNotificationKey.rectangle : selectedRectangle])
이렇게 changed를 넘기고 한 번에 호출할 수도 있는데, 각각 구분하는 것도 좋을 수 있습니다.
뭔가 값을 넘기고 분기해서 처리하는 게 꼭 좋은 구현이 아닙니다

2022-03-10 13:09 UTC, merged

2022-03-11 01:11 UTC, rising-jun commented on DrawingApp/DrawingApp/model/Plane.swift
> +        NotificationCenter.default.post(name: Plane.NotiEvent.updateRectangleAlpha, object: self, userInfo: [PlaneNotificationKey.rectangle : selectedRectangle])
넵 나눠서 개선해보겠습니다!

2022-03-11 01:11 UTC, rising-jun commented on DrawingApp/DrawingApp/message/RectangleChangeable.swift
> +    func changeRectangleAlpha(changed: RectangleAlphaChange)
넵! 근데 struct -> class로 수정해서 필요없을 것 같습니다.

2022-03-11 01:11 UTC, rising-jun commented on DrawingApp/DrawingApp/message/DrawingDelegate.swift
>      func deselected()
넵!! api가이드 한번 더 읽어보고 개선하겠습니다!