[dale] Step3-2.3 UIView 분리, Delegate패턴 구현
codesquad-members-2022/swift-drawingapp pull request #52
Opened 2022-03-08 10:48 UTC by sungju-kim

# 작업목록

- [x] UIView 분리
- [x] Delegate 패턴 구현

# 고민과 해결

모델, 컨트롤러, 뷰를 분리하기 위해 꽤 오랜시간 고민을 했습니다.

설계 단계에서 흐름은 이해가 되는데, 코드로 작성을 할수록 뷰컨트롤러가 모든작업을 진행하고 있어 뷰컨트롤러의 역할을 최대한 분배하는것을 목표로 리팩토링을 진행하였습니다.

Delegate 패턴을 이용하여 뷰 -> 컨트롤러 -> 모델 -> 컨트롤러 -> 뷰  이 흐름에 집중하여 구현을 진행해보니, 각각의 동작이 유기적으로 연결된 느낌을 받았습니다.

2022-03-09 14:15 UTC, godrm requested changes
Delegate 역할로 나눈 시도는 좋았습니다만, 어색한 부분이 보여서 의견을 남겼습니다
특히 팩토리를 델리게이트 구조가 잘 안어울립니다. 그리고 뷰에 대한 델리게이트도 구조 개선이 필요해보입니다
다음 의견들을 살펴보시고, 개선해서 다시 Push해보세요

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +        self.transparency = transparency
이런 검증, 변환 로직은 init에서 할 일이 아니라고 생각하세요.  
값을 넣은 것이 그대로 들어가지 않고 변화한다는 것은 오히려 혼란을 주고, 테스트하기 어려운 타입이 되어 버립니다  
Alpha.init(-9999.1234) 이런 값을 넣을 수 있다면 오히려 혼란을 줄 수 있습니다. 차라리 매개변수 자리에 적절하지 않은 값을 컴파일러에서 검증해서 아예 들어가지 않는 게 가장 좋습니다  
다 들어가는 데 값이 넣을 때마다 바뀐다면 오히려 테스트하기 어렵고 어색한 타입이 됩니다
범위에 대한 요구사항이 오히려 타입을 선언하는 데 혼란을 주고 있는 것 같은데 이 부분은 여기서 마무리하세요

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    func didChangedColor(color : Color)
PlaneDelegate 는 Plane과 관련이 있는 것 같은데, 이름 규칙과 매개변수에서 그게 표현되지 않네요
델리게이트 수업할 때 이야기했던 규칙대로 개선해보세요.

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    var selectedRectangle : Rectangle?
클래스도 속성은 private var를 우선적으로 고려하세요. 
외부에서 바꿀 수 있는 것은 좋은 접근이 아닙니다

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
>              let targetRectangle = rectangles[index]
subscript도 Int로 접근하는 것은 -1도 그렇지만 1234 처럼 큰 값이면 또 처리가 안될 겁니다 
그렇게 범위를 자르는 것보다는 아예 컴파일러에서 걸러지도록 안전하게 처리하는 게 좋습니다
String의 index 부분을 살펴보세요

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        }
이렇게 특정 위치에 대해 판단하는 함수는 리턴값이 있는게 좋을까요? 없는게 좋을까요?
이 동작을 단위 테스트로 검증하려먼 어떻게 검증할 수 있을까요?

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        delegate?.didChangedColor(color: randomColor)
Plane 자체는 어떤 책임일까요?
어떤 이벤트를 받아서 어떤 동작을 하게 될까요?
randomColor로 바꾸는 게 역할이 아니라 어떤 이벤트가 생겼을 때 매개변수로 Random 컬러가 전달되면 되겠구나... 정도로 상상해보세요
랜덤한 값으로 바꾸는 동작을 하더라도 랜덤 요소를 누가 생성할꺼냐도 고민해봐야 합니다
아직은 여기 있어도 괜찮지만, 뷰 컨트롤러와 Plane 사이에 그걸 결정하는 타입이 필요할 수도 있겠네요

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/Model/RectangleFactory.swift
>          }
randomPosition, randomColor, randomAlpha가 여기저기 중복되는 것 같은데요? 
위에 Plane에서도 본 것 같은데.. 같은 동작이라면 한 곳에서 처리할 수 있지 않을까요?
내부에서 사용하는 것도 randomColor나 randomAlpha 그 자체를 테스트하려면 어떻게 해야하나 고민해보세요.

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/View/PropertyChangeBoard.swift
> +        layoutAlphaChangeSlider()
여기서 처리하는 뷰 생성 코드들을 빌더 패턴이라고 부르는 데, 길어지면 그냥 private 메소드로 구현해도 됩니다.
그리고 당장은 오토레이아웃보다 다른 방식을 우선적으로 연습해보세요

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/View/PropertyChangeBoard.swift
> +        self.colorChangeButton.setTitle("\(String(format: "#%02X%02X%02x", red, green, blue))", for: .normal)
여기 코드를 보다보니 PropertyChangeBoard가 self.selectedRectangleView를 갖고 있지 않아도 될꺼 같은데요?
최소한으로 필요한 데이터 값만 넘겨주면 되고, 그게 꼭 뷰일 필요는 없을 것 같습니다

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/View/PropertyChangeBoard.swift
> +    @objc func touchButton() {
touchButton 메소드 이름으로는 이게 색상에 대한 버튼인지 모르겠네요

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/View/PropertyChangeBoard.swift
> +        guard let updatedAlpha = Alpha(transparency: Double(self.alphaChangeSlider.value/10)) else {return}
`Alpha(transparency: Double(self.alphaChangeSlider.value/10))` alpha 값을 생성하는 로직이 나누기 10을 한다거나, 이렇게 되야 한다는 게 좀 어색합니다. 알파값을 생성하기 어려울 것 같은데요?

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +        setBackgroundColor(color: color)
convenience init()을 생성하는 것도 좋은 시도입니다만, 기존에 있는 지정 생성자를 최대한 활요하세요
심지어 지금 여기서는 self.init()을 호출해서 자신의 지정 생성자가 아니라 super.init()에서 상속받은 init()을 호출하고 있네요

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    var id :Id?
뷰 객체가 값을 가지는 것을 지양하세요. Id라도 여기서 가지면 그 값을 가져가려고 하게 될꺼고 상위 모듈이 복잡해집니다
뷰도 뷰 인스턴스 자체를 활용하려고 하셔야 합니다

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    }
이런 메소드가 있다면 init(frame:)만 호출하고 alpha, color만 지정해줘도 되는게 아닐까요?

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleViewBoard.swift
> +    var delegate : RectangleViewBoardDelegate?
델리게이트가 있다는 건 다른 객체에게 무언가 알려줄 수 있다는 건데
selectedRectangleView 속성이 있는 것은 어색합니다. 
하위 뷰가 아닌데 다른 뷰를 참조해야만 하는 이유가 있나요? 
더구나 private이 아니라서 누가 이 값을 바꿀지 알수가 없겠네요 
만약 이렇게 처리한다면 RectangleViewBoard가 모든 사각형을 하위 뷰로 다 갖고 처리하도록 하도록 권한이 넓어진다면 가능할 수도 있겠네요

2022-03-09 14:15 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        rectangleFactory.delegate = self
음.. 팩토리가 델리게이트를 가지는 것은 좀 이상합니다.
팩토리는 보통 인스턴스를 생성하지도 않고, 그냥 메소드 하나로 호출해서 끝나기 때문에 static 한 경우도 많습니다

2022-03-10 01:16 UTC, sungju-kim commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +        self.transparency = transparency
넵

2022-03-10 05:49 UTC, sungju-kim commented on DrawingApp/DrawingApp/ViewController.swift
> +        rectangleFactory.delegate = self
변경 해보겠습니다!

2022-03-10 07:24 UTC, sungju-kim commented on DrawingApp/DrawingApp/View/RectangleViewBoard.swift
> +    var delegate : RectangleViewBoardDelegate?
JK 질문이 있습니다! 
RectangleView 생성시 RectangleViewBoard에 subView로 추가를 하기때문에  RectangleViewBoard가 RectangleView를 가지고 있다고 생각을하여 selectedRectangleView 변수를 RectangleViewBoard 안에 선언해주었습니다. 
해당 RectangleView를 클래스 밖에서 가져오지않고 index값만 받아와 self.subView[index]로 찾아서 사용하는건 문제가 되지않는지 궁금합니다!

2022-03-10 07:37 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleViewBoard.swift
> +    var delegate : RectangleViewBoardDelegate?
글쎄요. 내부에서 처리하는 건 뭘해도 선택할 수 있겠죠. index라는 속성을 외부에서 알고 있어야 하는걸까요? 
RectangleViewBoard의 내부 사정을 외부에서 어디까지 알고 있어야 하느냐는 고민이고 질문입니다. 
그래서 속성을 가져가도록 하는 것은 항상 지양하고, 메소드로 처리하려는 시도가 좋다는 겁니다.

2022-03-10 07:43 UTC, sungju-kim commented on DrawingApp/DrawingApp/View/RectangleViewBoard.swift
> +    var delegate : RectangleViewBoardDelegate?
답변 감사합니다. 참고해서 메소드 위주로 구현해보도록 하겠습니다🙆

2022-03-10 14:06 UTC, sungju-kim commented
피드백 주신부분 최대한 반영하여 리팩토링을 진행했습니다. 
Plane의 subscript 부분과 searchRectangle() 부분은 아직 해결하지 못했습니다. 
searchRectangle에서 찾은 사각형과 해당사각형의 인덱스값을 delegate로 전달해주도록 되어있고, 대부분의 값을 반환하는 메소드가 리턴값이 아닌 delegate로 전달하는 방식이라 전체적인 메소드에 대해 어떤 방식으로 테스트를 할 수 있을지 고민중에 있습니다.

2022-03-11 03:14 UTC, godrm commented on DrawingApp/DrawingApp/Model/RandomGenerator.swift
> +    }
팩토리 뿐 만 아니라 타입을 만들 때 이렇게 기능 단위가 아니라 관련있는 타입 - 객체 단위로 묶는 것도 고려해보세요

2022-03-11 03:14 UTC, merged

2022-03-11 04:51 UTC, sungju-kim commented on DrawingApp/DrawingApp/Model/RandomGenerator.swift
> +    }
넵! 리뷰 감사합니다