[푸코] Step04 - 사진 추가하기
codesquad-members-2022/swift-drawingapp pull request #56
Opened 2022-03-09 07:50 UTC by wnsxor1993

## 결과 화면
![화면 기록 2022-03-09 오후 4 15 43](https://user-images.githubusercontent.com/44107696/157391654-e7b41dc3-616d-4727-a3f9-a6adde60bd8f.gif)

## 작업 목록
* 리팩토링
- [x] Notification.Name 상수화 및 Dictionary Key 값 타입 자체로 변경
- [x] Plane 타입 Class로 변경 (Notification post의 object 지정을 위해)
- [x] tapGesture 입/출력 구분

* 신규 작업
- [x] ImageView 관련 모델 구현 (Image / ImagePlane)
- [x] View 클릭 시 테두리 효과 출력 및 빈공간 클릭 시 해제 기능 구현
- [x] Album에서 선택한 이미지를 ImageView로 생성 기능 구현
- [x] 선택 요소에 따라 AttributerView의 작동 제한 구현

## 학습 키워드
1. UISlider.isEnabled
2. Protocol
3. Hashable / Equatable

## 고민과 해결
- Rectangle과 Image 모델의 프로토콜을 작성하면서 공통 요소에 대한 고민을 하였고, 결국 ImageView나 View 공통 요소인 크기와 위치, 투명도와 함께 Hashable, description, 위치 정보 파악 등을 할 수 있는 요소들을 공통점으로 가지는 것이 좋겠다는 판단을 하고 RectValue 프로토콜 생성하였습니다.

- 처음에는 Plane 내에서 Image와 Rectangle 모두 소유하고서 관리하는 형태를 생각하였으나 하나의 모델이 너무 관리할 요소들이 많아지고 subscript나 count 등의 요소들 또한 소유하는 데이터들의 종류에 따라 중복으로 작성해줘야하는 점들 때문에 각각의 데이터에 따라서 ImagePlane / RectanglePlane으로 분리하였습니다. 
다만 해당 구조에서는 빈공간 선택 시의 필요한 작업들이 Model에서 Notification post를 활용한 방식을 이용할 수 없이, VC 내에서 진행 여부를 판단해주는 구조가 될 수 밖에 없었습니다.

2022-03-10 10:07 UTC, godrm requested changes
rectanglePlane, imagePlane을 나눠놓은 게 어떤 의미인지 이해가 되지 않습니다. 
그 부분을 좀 더 설명해주시고, 다음 피드백을 확인해보시고 개선해보세요.

2022-03-10 10:07 UTC, godrm commented on DrawingApp/Model/Attributes/MyImage.swift
> +    }
이미지를 속성으로 다루기 위해서 UIImage를 포함하는 구조체를 만들었군요
이런 것도 가능한데, 혹시 UIImage 자체를 쓰는 건 안되던가요? 상속받을 수 있었나요? 왜 image를 포함하는 struct로 만들었나요?
그 이유가 궁금합니다.

2022-03-10 10:07 UTC, godrm commented on DrawingApp/Model/Factory/RectangleFactory.swift
> +    }
이 부분은 randomImage를 만드는 것인지, 특정 image를 랜덤 좌표에 만드는 것인지 구분이 안되네요. 무엇을 랜덤하게 하는지 표현하면 더 좋지 않을까요?

2022-03-10 10:07 UTC, godrm commented on DrawingApp/Model/Image/Image.swift
> +        hasher.combine(image.imageInfo())
해시로 비교하는 것과 `==`로 비교하는 게 다르네요.
같은 이미지인지 비교하려면 어떤 속성을 비교하는 게 좋을까요?
Image에서는 ID가 필요없던가요?

2022-03-10 10:07 UTC, godrm commented on DrawingApp/Model/Image/ImagePlane.swift
> +    static let userInfoKey: String = "image"
여기 static 속성들을 namespace로 구분해보면 좋겠네요

2022-03-10 10:07 UTC, godrm commented on DrawingApp/Model/Image/ImagePlane.swift
> +    }
어.. 근데 이상합니다. Plane 이 Rectangle과 Image를 포괄해서 관리해야 하는 건 어떨까요? 
따로 관리하는게 더 좋은 구조일까요?

2022-03-10 10:07 UTC, godrm commented on DrawingApp/Model/Protocol/RectValue.swift
> +    func findLocationRange(xPoint: Double, yPoint: Double) -> Bool
모든 인터페이스를 다 합치는 게 좋은 게 아니라 의미있는 단위로 나누는 게 중요합니다. 프로토콜도 역할에 따라 나눠보세요
description은 이미 CustomStringConvertible가 있으니까 분리해도 좋을 것 같네요

2022-03-10 10:07 UTC, godrm commented on DrawingApp/Model/Rectangle/Rectangle.swift
> +final class Rectangle: RectValue{
하나의 프로토콜로 합치는 게 아니라 프로토콜을 여러개로 나눠보세요

2022-03-10 10:07 UTC, godrm commented on DrawingApp/Model/Rectangle/RectanglePlane.swift
> +
RectanglePlane 과 ImagePlane이 나눠진 이유를 잘 모르겠습니다. 
이 부분이 구조적으로 다형성이 필요했던가요?

2022-03-10 13:15 UTC, wnsxor1993 commented on DrawingApp/Model/Attributes/MyImage.swift
> +    }
처음에는 UIImage 자체를 사용하는 방향으로 접근했습니다만 혹여 rawValue를 다루다 실수하는 일을 방지함과 동시에 차후 이미지와 관련된 수정 요소 등이 추가될 가능성이 있지 않을까 싶어 UIImage 속성을 다루는 구조체를 따로 만들었습니다.

2022-03-10 13:16 UTC, wnsxor1993 commented on DrawingApp/Model/Factory/RectangleFactory.swift
> +    }
이 부분은 단어를 조금 더 고민하고 개선해보도록 하겠습니다!

2022-03-10 13:35 UTC, wnsxor1993 commented on DrawingApp/Model/Image/Image.swift
> +        hasher.combine(image.imageInfo())
해시 비교 때는 간단한 키 값 정도로 부여하겠다는 생각으로 작성하였는데, == 비교와 전혀 다른 거는 다소 이상할 듯 합니다. 확실하게 비교를 하기 위해서는 해당 타입이 가지고 있는 전체 속성들을 비교하는 것이 제일 정확할 것 같아, description을 통한 비교를 하는 방향으로 접근하고자 합니다.
추가적으로 Image에서는 image의 정보 값 자체가 고유한 값으로 사용될 수 있다고 생각하여 ID를 추가하지 않는 방향으로 작업하였습니다.

2022-03-10 13:38 UTC, wnsxor1993 commented on DrawingApp/Model/Image/ImagePlane.swift
> +    static let userInfoKey: String = "image"
namespace라 말씀하신 거는 nested Type을 통해 따로 구분하는 방향을 의미하는 걸까요?

2022-03-10 13:45 UTC, wnsxor1993 commented on DrawingApp/Model/Protocol/RectValue.swift
> +    func findLocationRange(xPoint: Double, yPoint: Double) -> Bool
역할에 따른 세분화도 항상 고려하겠습니다. 그럼 혹시 어떤 프로토콜을 채택한 객체들이 항상 hash 가능해야 되는 등 다른 프로토콜의 구현 요소가 필요할 경우에는 위와 같이 프로토콜에 프로토콜을 채택하는 방식을 적용해도 괜찮을까요?

2022-03-10 14:11 UTC, wnsxor1993 commented on DrawingApp/Model/Image/ImagePlane.swift
> +    }
말씀하신 부분은 계속 고민되던 지점으로 Plane이 모든 모델들을 관리하는 역할이 된다면 동일한 로직의 함수들이 오버로딩이나 함수명 변경을 통해 늘어나면서 비대해지지 않을까라는 생각이 들면서 현재의 방향으로 작성하였습니다.
다만 이 경우 각각의 Plane들로부터 한 번씩 findRectangle 함수가 호출되므로 적절한 값이 없을 경우에 notification을 통해 view 테두리가 해제되던 로직을 사용하지 못 하고, VC 내에서 직접 해당 메서드를 호출해서 처리해줘야 하는 형태가 되어버렸습니다.

이런 문제로 봐서는 Plane이 둘 다 관리하는 것이 좀 더 구조적으로 좋을 듯 합니다. 이 부분 개선해보도록 하겠습니다!

2022-03-11 03:05 UTC, wnsxor1993 commented on DrawingApp/Model/Image/Image.swift
> +        hasher.combine(image.imageInfo())
description을 사용할 경우, 처음 Dictionary의 키 값으로 등록하였을 때와 이후에 속성들을 수정한 뒤의 해시 값이 달라져 키로서 사용이 불가능하다는 점을 확인하였고 Rectangle은 id:Date, Image는 image:Date와 같이 변화가 전혀 없는 값들을 사용하는 방향으로 선회하였습니다.

2022-03-11 03:10 UTC, wnsxor1993 commented
말씀하신 요소들 최대한 수정해보았습니다. 확인 부탁드리겠습니다!^^

2022-03-11 03:16 UTC, godrm commented on DrawingApp/Model/Plane/Plane.swift
> +        }
이 부분이 마치 지난 수업에 이야기했던 discountCondition 처럼 보이지는 않나요? 두 개를 추상화해서 하나로 다루고 다형성으로 관리할 수 없을까요?

2022-03-11 03:18 UTC, godrm commented on DrawingApp/Model/Plane/Plane.swift
> +    }
subscript가 이렇게 여러 타입이라면 사용하는 입장에서 헷갈릴 꺼 같은데, 이런 경우는 어떻게 하는 게 좋을까요?
구분 없이 다룰 수는 없을까요?

2022-03-11 03:20 UTC, godrm commented on DrawingApp/Model/Factory/RectangleFactory.swift
> +    }
개선한 makeRandomRectanglePosition() 이나 makeRandomImagePosition() 이것도 RandomRectangle인지 RandomPosition인지 조금 헷갈리는 부분이 있네요. 이런게 참 사소하면서 객관적으로 만드는 게 어려운 표현 같아요.

2022-03-11 03:21 UTC, godrm commented on DrawingApp/Model/Plane/Plane.swift
> +    }
아.. 이걸보니 합쳤는데 억지로 합친 듯한 느낌입니다. 각각 다루는 게 필요할 수도 있는데, 합치는 게 필요한가 고민해보세요

2022-03-11 03:21 UTC, merged

2022-03-11 06:23 UTC, wnsxor1993 commented on DrawingApp/Model/Plane/Plane.swift
> +    }
말씀하신 부분들 계속 고민하면서 수정해보고 다음 Step의 PR때 보실 수 있도록 반영해보겠습니다!