[shingha] Step5 드래그를 이용하여 오브젝트 움직이기
codesquad-members-2022/swift-drawingapp pull request #57
Opened 2022-03-09 16:08 UTC by shingha1124

## 체크리스트

- [x] 이전 리뷰 내용 수정
- [x] 드래그제스처 추가
- [x] 드래그 시 더미 오브젝트 생성
- [x] 드래그 종료 후 해당 위치로 이동

2022-03-10 09:02 UTC, godrm requested changes
몇 가지 입력에서 입력 흐름과 출력 흐름이 구분이 되지 않았네요. 
다음 피드백을 확인해서 개선해보세요

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +        let screenSize = UIScreen.main.bounds.size
뷰를 다루는 게 아니라면 여기 팩토리에서도 UIScreen 혹은 UIKit에 의존적인 것은 좋지 않습니다
여기서 범위가 필요하다면 매개변수로 넘겨주는 게 좋습니다.

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/ColorFactory.swift
> +        UInt8.random(in: 0...255)
아하 범위가 256 이내에 들어가는 타입을 찾았네요

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/PointFactory.swift
>      }
팩토리에서 x, y를 받아서 그대로 생성할꺼면 팩토리가 필요가 없는게 아닐까요?

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Color.swift
> +    let b: UInt8
적절한 타입을 찾은 것도 좋네요

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Drawing/DrawingModel.swift
> +        self.point = Point(x: point.x - size.width / 2, y: point.y - size.height / 2)
이 좌표는 그냥 좌표라고 부르는 것보다는 origin, center 처럼 좌표의 역할을 표현하면 더 좋겠네요.

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane/Plane.swift
> +        let userInfo: [AnyHashable : Any] = [ParamKey.drawingModel:model]
model 말고 다른 단어는 없을까요? 여기는 다 모델인데 어떤 것을 표현하는 것인지 애매한 것 같기도 합니다

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane/Plane.swift
> +        NotificationCenter.default.post(name: Plane.NotifiName.makeDragDummyView, object: self, userInfo: userInfo)
`Plane.NotifiName.makeDragDummyView` 노티를 보낼 때는 받는 객체가 뭘 할지는 결정이 안된거고
보내는 객체 입장에서 결정하는 게 좋습니다. 뷰를 만들지 그걸로 뭘할지는 받는 쪽에서 결정하는 거죠

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane/Plane.swift
> +        static let makeDragDummyView = NSNotification.Name("makeDragDummyView")
이름이 didMake- 같은 위에 규칙들과 다른 것 같네요.

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/DrawingBoard/View/DrawingView.swift
> +        self.snapshotView(afterScreenUpdates: false)
copy는 뭘 하려는 의도인가요? 같은 뷰를 다시 만드는 거라면 리턴 타입도 Any보다 구체적인 타입이 가능하지 않을까요?
특히 override에서 다형성을 깨고 super.xxx를 호출하지 않는 의도가 있나요?

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/Inspector/InspectorView.swift
>  }
수업 시간에 언급한 델리게이트 프로토콜에 대한 규칙에서, 이름과 매개변수 등을 맞춰보면 좋겠습니다

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            guard let model = notification.object as? DrawingModel,
이렇게 object를 타입 변환을 할꺼면 addObserver() 시점에 sender로 지정해주는 게 좋지 않을까요?

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            self.plane.beganDrag()
메소드가 합칠 수 있지는 않을까요?

2022-03-10 09:02 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/ViewController.swift
> +            self.plane.pointChanged(where: Point(x: location.x, y: location.y))
.changed 랑 .ended 에서는 이벤트 처리를 하면서 출력도 같이 처리하는 것 같네요. 
입력 흐름을 분리하는 것을 잊지마세요

2022-03-10 12:47 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +        let screenSize = UIScreen.main.bounds.size
매개변수로 받아오도록 수정했습니다.

2022-03-10 12:47 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/TypeData/PointFactory.swift
>      }
size, point를 생성하는 팩토리를 제거했습니다

2022-03-10 12:48 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Drawing/DrawingModel.swift
> +        self.point = Point(x: point.x - size.width / 2, y: point.y - size.height / 2)
point. -> origin으로 변경했씁니다

2022-03-10 23:40 UTC, shingha1124 commented
리뷰사항 수정했습니다!
변수명, 함수명 이름짓기가 제일 어려운거 같네요 ㅠㅠ

2022-03-11 03:24 UTC, godrm commented
> 리뷰사항 수정했습니다!
> 변수명, 함수명 이름짓기가 제일 어려운거 같네요 ㅠㅠ

그쵸. 사소하지만 내가 생각한 의도를 객관적이면서 정확하게 표현하는 게 참 어려운 일입니다. 
커밋 내용에 `리뷰내용 수정`보다는 좀 더 구체적으로 무엇을 수정했는지 기록해보세요.

2022-03-11 03:24 UTC, merged