[Selina] Step3-2-1 - 속성 변경 동작
codesquad-members-2022/swift-drawingapp pull request #59
Opened 2022-03-10 08:15 UTC by ios-h

# Step3-2. 속성 변경 동작

## 💻 작업 목록

- [x] 지난 PR 리뷰 반영
  - [x] Alpha 내부에 opacity 변수로 투명도 나타내도록 수정
  - [x] 이니셜라이저에서 minValue = 0, maxValue = 255로 두고 비교하여 minValue보다 작은 값이 들어온다면 0을, maxValue보다 큰 값이 들어오면 255를 주도록 수정
  - [x] Id 클래스를 따로 생성하고 내부에 메소드 추가
  - [x] 팩토리 메소드 수정
- [x] SideInspectorView 생성
- [x] SideInsepctorView에서 사각형 버튼 클릭 시, 뷰컨트롤러가 직사각형 그리도록 delegate 설정
- [x] Plane 구조체 Test 추가하기
- [ ] SideInspectorView를 제외한 영역에 사각형이 그려지도록 하기
  - [x] 일단 범위를 제한적으로 설정하여 사각형이 그리도록 함

## 🤔 고민과 해결

### 1️⃣ Alpha에 opacity를 추가하는 과정에서 오차 발생

Alpha의 rawValue 값을 Double로 변환하고, 그 결과를 0.1로 곱하는 과정에서 오차가 발생했습니다.

rawValue를 Double로 변환하는 데까지는 문제가 없었지만, 0.1로 곱하는 과정에서 부동 소수점의 부정확성으로 인해 오차가 발생한 것인데, 0.1을 곱하지 않고 10을 나눠주는 방식으로 변경하여 해결하였습니다.

### 2️⃣ 색상 값을 16진수로 나타내는 backgroundColorValueView 속성 적용 문제

backgroundColorValueView의 width, height를 설정해주지 않아서 생긴 문제였습니다. width, height 설정하니 해결되었습니다.

### 3️⃣ SideInspectorView를 제외한 영역에만 사각형 그리도록 설정하기

#### 💡 아이디어: SideInspectorView의 시작 x 좌표를 가져와서 그 x 좌표 이상은 안 그리게 하기

- viewDidLoad 내에서 `setInspectorView()`를 호출한 후에 `sideInspectorView.frame` 값을 확인해보았으나, 값을 가져오지 못했습니다. (모두 0 이였습니다). 레이아웃 제약 조건이 오토레이아웃에 의해 배치되지 않기 때문에, `viewDidLayoutSubview()` 메소드를 오버라이드한 후에 접근하면 값을 가져올 수 있었습니다.
- 아직 진행 중입니다...!

## 💡 학습 키워드

- 아이패드
- 클래스
- 뷰 모델
- viewDidLayoutSubviews()

2022-03-10 08:18 UTC, ios-h commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +        return Double(rawValue) / 10
여기서 Double(rawValue)에 0.1을 곱하면 오차가 발생하지만 10을 나눠주면 오차가 발생하지 않는 이유가 궁금합니다..!

2022-03-10 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +        return Double(rawValue) / 10
수학적으로는 `A * 0.1` 와 `A / 10`이 같은 거지만 프로그래밍 세계에서는 다르죠
그리고보니 CS 수업에서 한 번 언급한 적이 있었던 것 같은데... 가물가물 하네요 ㅎㅎ
2진법으로 `0.1`을 정확하게 표현하지 못해서 그런겁니다. 그래서 Float 이나 Double 실수 타입은 실수를 하기 마련이죠. 
그래서 이렇게 변환하는 건 좋은 방법이 아닐 수 있습니다. 단계가 나눠져있다면 선택할 수 있는게 더 좋습니다.

2022-03-10 09:45 UTC, godrm requested changes
이벤트를 처리할 때 입력 흐름과 출력 흐름을 구분하는 것을 꼭 해보세요.
개선하고 다시 push해보세요

2022-03-10 09:45 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +
이렇게 입력을 처리하는 곳에서는 뷰 -> 뷰 컨트롤러 -> 모델로 들어가는 입력 흐름만 처리하고,
아래 뷰를 생성하는 출력 흐름을 분리해야 합니다. 모델에서 뷰 컨트롤러를 거쳐서 다시 뷰에 추가하는 흐름을 나눠보세요

2022-03-10 09:45 UTC, godrm commented on DrawingApp/DrawingApp/Model/Color.swift
> +        self.hexValue = "0x" + hexRed + hexGreen + hexBlue
init에서는 지정한 값들을 검증하고 변환하는 역할보다는 생성하고 초기화하는 역할에 맞추는 게 좋습니다
그 값을 검증하는 것을 여기서 하기보다는 앞단에서 처리하고 여기서는 안전하게 처리되도록 하는 게 좋습니다
init() 매개변수를 일반적인 원시 타입으로 하다보면 이렇게 예외처리 코드가 길어집니다. 타입을 지정하는 것도 늘 신중하게 생각해보세요

2022-03-10 09:45 UTC, godrm commented on DrawingApp/DrawingApp/Model/Id.swift
> +        self.description = Id.makeRandomId()
description을 속성으로 쓰지마세요. 이건 개발 과정에서 필요한 부가적인 정보일 뿐입니다.

2022-03-10 09:45 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
Plane이 단지 사각형을 포함하는 배열 정도만 관리하는 게 아니라, 이벤트를 전달받아서 필요한 동작을 하는 좀 더 능동적인 타입으로 만들어보세요

2022-03-10 10:48 UTC, ios-h commented on DrawingApp/DrawingApp/Model/Id.swift
> +        self.description = Id.makeRandomId()
말씀하신대로 description을 속성으로 사용하지 않고 id 속성을 추가하였습니다!

2022-03-10 12:42 UTC, ios-h commented on DrawingApp/DrawingApp/Model/Color.swift
> +        self.hexValue = "0x" + hexRed + hexGreen + hexBlue
`hexValue`를 삭제하고 `getHexValue()`라는 메소드를 만들어서 hex 값을 리턴하도록 수정하였습니다!

2022-03-10 13:11 UTC, godrm commented
아직 모두다 적용된 건 아닌거죠? push할 때는 하나씩 개선하고 커밋만 해놓고 한꺼번에 push하는 것도 좋습니다

2022-03-10 13:20 UTC, ios-h commented
넵 아직 다 반영하지 못했습니다.. 다 반영하고 한번에 푸시하겠습니다!

2022-03-14 01:59 UTC, ios-h commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +
SideInspectorViewDelegate에서 VC가 모델에게 사각형을 만들라고 명령하고, PlaneDelegate를 이용하여 모델에서 생성한 사각형을 VC로 전달하여 canvasView에 그리도록 변경하였습니다.

2022-03-14 02:02 UTC, ios-h commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    }
addRectangle 메소드를 개선하여 createRectangle()이란 메소드로 변경했고, 내부에서 사각형을 만들어서 Plane이 가진 rectangles 배열에 추가하였습니다. 그리고 delegate를 이용해서 VC에 사각형을 전달했습니다!

2022-03-14 02:03 UTC, ios-h commented
@godrm 남겨주신 리뷰 토대로 수정하여 푸시했습니다. 한번 확인해주시면 감사하겠습니다!

2022-03-14 02:28 UTC, godrm commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +        addSubview(myView)
이 부분을 CanvasView에서 Rectangle을 알고 처리할 것인가 고민해볼 필요는 있습니다
뷰 컨트롤러가 drawRectangle(rectangle:)를 호출하게 될텐데 뷰 컨트롤러에서 UIView를 생성하고 addSubview만 해줄 수도 있는거죠.

2022-03-14 02:28 UTC, godrm commented
다음 단계를 계속 해보시죠 :)

2022-03-14 02:28 UTC, merged

2022-03-14 02:32 UTC, ios-h commented on DrawingApp/DrawingApp/View/CanvasView.swift
> +        addSubview(myView)
이 부분에 대해서는 좀 더 고민해보겠습니다. 감사합니다!