[푸코] Step05 - 드래그 기능 구현
codesquad-members-2022/swift-drawingapp pull request #75
Opened 2022-03-14 02:58 UTC by wnsxor1993

## 결과화면
![화면 기록 2022-03-11 오후 3 24 06](https://user-images.githubusercontent.com/44107696/158095908-a5d1741c-0475-436b-b99e-768d33d964bb.gif)

## 작업 목록
* 리팩토링
- [x] Protocol 구현 요소 부모 Class로 변경 (업캐스팅을 통해 단일 관리체 형태를 유지하기 위해)
- [x] 상속 형태로의 변경에 따른 Plane 내부 구조 수정

* 신규 작업
- [x] PanGestureRecognizer 추가
    - [x] 제스처 상태에 따라 3단계의 로직 흐름 구성
    - [x] 드래그하는 동안의 움직임을 재현해 줄 임시 뷰 구현
    - [x] 입력에 따른 출력은 해당 뷰의 변경 메서드 호출로 구현하여 입/출력 분리
- [x] 드래그 관련하여 View의 프로토콜 생성

## 학습 키워드
1. UIPanGestureRecognizer (state / setTranslation)
2. View.center
3. removeFromSuperView

## 고민과 해결
- 초기에는 드래그가 완료된 이후에 임시 뷰가 생성된 채 사라지지 않는 현상이 발생하였고, 이러다보니 드래그 시에 임시뷰가 마우스를 따라서 움직이는 액션이 전혀 보여지지 않았습니다.. 이 부분에서 많은 시간을 잡아먹혔는데 디버깅을 하면서 생성한 임시 뷰가 막상 changed 단계에서는 nil이 할당되어 있는 부분을 캐치할 수 있었습니다.
드래그 시, dragGesture 자체가 계속 호출된다는 생각을 하지 못 해 해당 메서드 내부에 모든 로직을 구현하다보니 임시 뷰가 생성되고 제거되는 로직이 꼬였던 것이었습니다. 이에 관련된 전체 로직이 꼬이지 않도록 각 상태 단계에 맞춰 잘 배분하였고 이후 정상 작동을 확인할 수 있었습니다.

2022-03-14 08:20 UTC, godrm requested changes
다음 내용을 확인해보시고, 반복적으로 코드가 중복되는 부분을 추상화시켜서 합쳐보세요

2022-03-14 08:20 UTC, godrm commented on DrawingApp/Model/Plane/Plane.swift
>  //  DrawingApp
이건 별건 아닌데 파일 이름은 Plane 인데 주석에 Sub.swift로 바뀌었네요? 뭐가 바뀐거죠?

2022-03-14 08:20 UTC, godrm commented on DrawingApp/Model/Values/Image.swift
> +        return lhs.id == rhs.id && lhs.image == rhs.image && lhs.size == rhs.size && lhs.point == rhs.point && lhs.alpha == rhs.alpha
`==` 객체가 equal로 같으냐 비교할 때 속성들만 같으면 같은거라고 볼 수 있는걸까요?
id까지 같은거라면 완벽히 똑같은 객체가 될텐데... 그러면 속성을 비교할 필요가 있을까요?

2022-03-14 08:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +    private var panGestureExtraImageView: ImageView?
이 두 가지를 일반화시킬 수는 없을까요?

2022-03-14 08:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +    private var selectedValue: RectValue?
selectedValue를 꼭 ViewController가 알고 있어야 할까요? Plane 내부에만 있으면 안될까요?

2022-03-14 08:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
>      private var imageUIViews = [Image : ImageView]()
이 두 가지도 한꺼번에 Rectangle와 Image를 다루고, RectangleView와 ImageView를 다룰 수 있지 않을까요?

2022-03-14 08:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
>          rectangleView.restorationIdentifier = rectangleValue.id
여기도 뷰를 생성하는 부분을 View Factory로 만드는 건 어떨까요?

2022-03-14 08:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        }
거의 같은 코드가 보이지 않나요? 이렇게 타입별로 다르게 처리하지 않고 한꺼번에 처리할 수 있지 않을까요?

2022-03-14 08:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +
panGestureExtraView를 생성하는 부분도 기존 View를 copy하는 방법을 고려해보세요.

2022-03-14 08:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
>          }
타입이 추가될 때마다 이런 처리하는 코드가 반복해서 늘어나지 않는 게 좋습니다. 한꺼번에 처리할 수 있는 방법을 고려해보세요

2022-03-14 08:20 UTC, godrm commented on DrawingApp/View/ImageView.swift
> +    }
changeCenterPositon(x, y) 와 movingCenterPosition(x, y) 이름만 놓고 보면
두 개 차이를 인지하기 어렵습니다. 어떤 것을 어떤 상황에 호출해야 하는걸까요? 조금만 더 구체적으로 인지할 수 있으면 좋겠습니다.

2022-03-14 08:20 UTC, godrm commented on DrawingApp/View/RectangleView.swift
> +    }
완전히 동일한 동작이라면 ViewDragable에 default implementation을 넣어도 좋겠네요

2022-03-14 13:12 UTC, wnsxor1993 commented on DrawingApp/Model/Plane/Plane.swift
>  //  DrawingApp
이 부분은 리팩토링 중에 신규 파일에서 로직을 수정해보고 정상 작동 확인된 뒤에 해당 파일을 그대로 사용하면서 생긴 것 같습니다.

2022-03-14 13:16 UTC, wnsxor1993 commented on DrawingApp/Model/Values/Image.swift
> +        return lhs.id == rhs.id && lhs.image == rhs.image && lhs.size == rhs.size && lhs.point == rhs.point && lhs.alpha == rhs.alpha
id의 경우 극악의 확률이지만 동일한 id가 생성될 가능성이 있어 다른 요소들도 비교하였습니다만, 현재보다는 조금 더 비교 요소를 줄이는 편이 좋을 듯 하여 id와 date 두 가지를 이용하여 비교하는 형태로 수정하였습니다.
추가로 VC 내의 딕셔너리의 키 값 활용을 위해 부모 클래스에 Hashable을 채택하는 형태로 선회하였습니다.

2022-03-14 13:19 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +    private var panGestureExtraImageView: ImageView?
ImageView가 UIView를 상속하는 점을 알아차리지 못 해서 이러한 형태가 되었습니다. 이 부분 조금 더 정리해보겠습니다.

2022-03-14 13:33 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +    private var selectedValue: RectValue?
아직 Plane이 어디까지 역할을 해줘야하는가에 대한 판단이 어려운 것 같습니다. 결국 어떤 프로젝트에서든 여러 모델들을 관리하는 모델은 관리 중인 요소들과 관련된 프로퍼티나 로직들은 전부 소유하는 형태를 지향하는 걸로 생각하면 좋을까요?

2022-03-14 13:35 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
>          rectangleView.restorationIdentifier = rectangleValue.id
이전 작성한 Factory처럼 구현해보겠습니다

2022-03-14 15:19 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +
view는 참조 타입이라 UIView를 인자로 받아와 해당 view의 속성 값을 그대로 extraView에 적용하는 형식으로 구현하였는데, 복사라 말씀하신 부분이 이러한 로직을 말씀하신 걸까요?

2022-03-14 15:23 UTC, wnsxor1993 commented on DrawingApp/View/RectangleView.swift
> +    }
말씀하신 형태로 구현하였습니다만, self.center가 프로토콜 내부에서는 구현할 수가 없는 형태라 매개변수로 UIView를 받아오는 형태로 수정하였습니다.
처음에는 UIView를 상속하는 형태를 생각하였습니다만, UIView의 익스텐션에서 이미 ViewDrable 프로토콜을 채택한 상황이라 이와 같은 형태는 아닌 듯 하여 위의 방식으로 구현하였습니다. 혹시 매개변수 없이 view의 센터 값을 변경하는 로직을 그대로 유지할 수 있는 방식이 있을까요?

2022-03-14 15:26 UTC, wnsxor1993 commented
말씀하신 부분들을 중점으로 로직을 다듬어보고자 하였습니다. 부족한 부분 다시 말씀주시면 최대한 깔끔하게 다듬어볼 수 있도록 하겠습니다.

2022-03-15 01:42 UTC, godrm approved these changes
몇 가지 소소한 의견을 남겼습니다. 
개선하고 머지할 것인가 혹은 머지하고 다음 단계를 하면서 머지할 것인가 판단해주세요

2022-03-15 01:42 UTC, godrm commented on DrawingApp/Model/Factory/CustomViewFactory.swift
> +        return extraView
copy 메소드는 NSCoping 프로토콜을 한 번 살펴보세요
뷰라도 다른 뷰의 속성을 꺼내서 복사하는 게 캡슐화를 깨트릴 수도 있거든요

2022-03-15 01:42 UTC, godrm commented on DrawingApp/Model/Factory/CustomViewFactory.swift
> +    }
팩토리 메소드들은 인스턴스 변수가 없으니까 static func으로 하는 것도 괜찮습니다

2022-03-15 01:42 UTC, godrm commented on DrawingApp/Model/Values/RectValue.swift
> +        hasher.combine("\(id):\(madeTime)")
hasher를 사용할 때 문자열로 바꾸지 않고는 안되던가요?

2022-03-15 01:42 UTC, godrm commented on DrawingApp/Model/Values/RectValue.swift
> +        return lhs.id == rhs.id && lhs.madeTime == rhs.madeTime
`RectValue 객체가 같다`는 어떤 의미가 있을까요?
a. id만 같으면 같은 객체인가? 완전히 동일한 객체를 의미하는 것인가?
b. id는 다르지만 모든 속성이 동일하고 같은 위치에 있으면 같다고 할 수 있는가?
a와 b 경우에 대한 것을 구분할 수 있으면 좋습니다.

2022-03-15 01:42 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        plane.getSelectedValue(value: image)
여기 showRectangleTouchedView와 showImageTouchedView 두 개를 다형성으로 한꺼번에 처리할 수는 없을까요?

2022-03-15 05:13 UTC, wnsxor1993 commented
> 몇 가지 소소한 의견을 남겼습니다. 개선하고 머지할 것인가 혹은 머지하고 다음 단계를 하면서 머지할 것인가 판단해주세요

한 번 더 말씀하신 부분들을 중심으로 개선해보고 푸시해보도록 하겠습니다^^ 머지는 이후로 부탁드리겠습니다!

2022-03-15 05:32 UTC, wnsxor1993 commented on DrawingApp/Model/Factory/CustomViewFactory.swift
> +        return extraView
NSCopying을 구현하는 것 또한 결국 해당 뷰의 속성을 그대로 가진 새로운 뷰를 생성하는 형태처럼 느껴지는데 결국 외부의 뷰가 다른 뷰의 속성에 접근해서 신규 뷰를 생성하는 것이 캡슐화에 적절치 않으므로 이러한 작업을 해당 뷰가 직접 진행하고 소유할 수 있도록 해주기 위한 프로토콜로 이해해도 괜찮을까요?

2022-03-15 05:33 UTC, wnsxor1993 commented on DrawingApp/Model/Values/RectValue.swift
> +        hasher.combine("\(id):\(madeTime)")
각 프로퍼티 별로 haher.combine을 추가하는 방법도 확인하였습니다!

2022-03-15 05:49 UTC, godrm commented on DrawingApp/Model/Factory/CustomViewFactory.swift
> +        return extraView
네 맞아요. private 속성은 복사할 수가 없으니까 자기가 복사하는 게 맞겠죠

2022-03-15 05:52 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
> +        plane.getSelectedValue(value: image)
첫 생성 이후에는 어떤 타입이든 부모 타입인 RectValue를 통해 작업이 가능하니 이를 활용해 전체적으로 다형성을 높일 수 있는 형태로 다듬어보겠습니다.

2022-03-15 06:36 UTC, wnsxor1993 commented on DrawingApp/Model/Values/RectValue.swift
> +        return lhs.id == rhs.id && lhs.madeTime == rhs.madeTime
b의 경우에는 변동 가능성이 있는 속성으로서 다른 객체임에도 해당 속성이 전부 똑같을 수 있기 때문에 이들을 비교하여 같다해서 같은 객체라고 할 수는 없다고 생각합니다.
a의 경우 생성 당시 변동이 없는 고유한 값으로 가정을 하고 할당하였고 이후에도 내외부적으로 변동이 불가한 값이므로 동일한 값을 가지고 있을 때는 두 객체가 동일한 객체라고 판단할 수 있을 거라 생각합니다.
다만 UUID 조차 극악의 확률로 동일한 값이 나올 수 있다하니, id만으로 비교하기에는 약간의 리스크가 존재한다고 생각했습니다. 따라서 완전히 동일한 시간에 생성될 가능성이 낮고, 내외부적으로 수정이 불가한 madeTime 또한 id처럼 고유한 값으로 인식될 수 있으므로 둘을 비교에 활용하여 리스크를 최소 단계까지 낮춰보고자 위와 같은 형태로 작성하였습니다.

혹시 위의 사항에서 말씀하신 부분에 대해 미처 파악하지 못 하여 잘못 생각한 부분이 있다면, 해당 부분을 가르쳐주시면 감사하겠습니다!^^

2022-03-15 06:37 UTC, wnsxor1993 commented
상기의 내용들을 중심으로 다시 한 번 가다듬어보았습니다. 확인 부탁드리겠습니다!^^

2022-03-15 06:42 UTC, godrm commented on DrawingApp/Model/Values/RectValue.swift
> +        return lhs.id == rhs.id && lhs.madeTime == rhs.madeTime
https://lucas.codesquad.kr/masters-2022/course/모바일-iOS-클래스/포커게임-앱/카드덱-구현하고-테스트하기 
에 참고자료로 올라온 내용 중에 Identity와 Equality를 다시 확인해보세요. 
UUID 조차 같은 id가 될 수 있는 것은 위조 신분증처럼 별개 예외 상황인 것 같구요 (그런걸 감안해도 라도 우리는 신분들을 보면 누군가보다 믿어야 한다면 id가 어느정도 고유한 값이라고 가정하고 얘기합시다)
그래서 질문은 `==` 연산으로 무엇을 비교하려고 하는 것인가, 그 의도가 중요한 것 같습니다.

2022-03-15 07:13 UTC, wnsxor1993 commented on DrawingApp/Model/Values/RectValue.swift
> +        return lhs.id == rhs.id && lhs.madeTime == rhs.madeTime
결국 객체가 가진 고유값들을 통해 비교 대상들이 동일한 객체인지를 비교하려고 했습니다만, 해당 부분들은 무엇과 왜 보다는 어떻게에만 초점을 맞추다보니 객체 비교 연산을 전혀 생각하지 못 했습니다.
JK가 말씀하신 부분을 생각해보니 동일한 객체임을 비교하려는 목적이면 다른 프로퍼티를 비교하는 것 보다는 객체 비교 연산을 활용하는 것이 더 적합하다고 판단이 듭니다.

2022-03-15 09:45 UTC, godrm commented on DrawingApp/Model/Factory/CustomViewFactory.swift
>          return value.id
여기 메소드들은 좀 이상한데요? 팩토리에서 내부 속성을 꺼내주는 거라니.. 이런 함수가 필요한가요?

2022-03-15 09:46 UTC, godrm commented on DrawingApp/Model/Factory/CustomViewFactory.swift
>              extraView = extraImageView
아.. 각 타입이 NSCopying 프로토콜을 처리했으면 여기서 팩토리에서 이걸 처리하는 메소드가 있을 필요가 없지 않을까요?
다형성으로 동작한다면 그냥 뷰를 다루는 곳에서 copy()를 호출하면 되지 않을까요?

2022-03-15 11:01 UTC, wnsxor1993 commented on DrawingApp/Model/Factory/CustomViewFactory.swift
>          return value.id
해당 메서드들은 View 프레임 생성 이후에 각 속성 추가를 위한 메서드로서 생성된 속성 값들을 대신 호출하여 받아오고 이 값을 View의 속성에 전달하는 형태로 사용하고자 작성하였습니다.
앞선 리팩토링 과정에서 접근제어자 설정 등이 미흡하여 타 객체의 속성 값에 직접 접근하는 형태가 되어버렸고 현재 해당 부분을 수정하였습니다.

2022-03-15 11:13 UTC, wnsxor1993 commented on DrawingApp/Model/Factory/CustomViewFactory.swift
>              extraView = extraImageView
ViewFactory는 View를 생성하고 속성을 지정해주는 역할만 하는 것이 적합해보입니다. 해당 부분 코드 중복되는 요소를 다시 작은 메서드 단위로 분리하는 형태도 추가하여 다듬도록 하겠습니다.

2022-03-15 11:17 UTC, wnsxor1993 commented
말씀하신 요소들 정리해보았습니다.
추가적으로 Xcode 업데이트 이후인지는 모르겠습니다만, 갑자기  [UIFocus] Failed to update focus with context 관련 내용이 시뮬레이터 실행 직후 및 드래그 완료 후에 콘솔 창에 출력되고 있는데 어떤 부분에서 생긴 문제인지 여쭤보고자 합니다.

2022-03-15 11:18 UTC, godrm commented
> 갑자기 [UIFocus] Failed to update focus with context 관련 내용이 시뮬레이터 실행 직후 및 드래그 완료 후에 콘솔 창에 출력되고 있는데 어떤 부분에서 생긴 문제인지 여쭤보고자 합니다.

이런건 신경쓰지마세요. 애플이 찍어놓은 디버깅 정보들도 꽤 많아요.

2022-03-15 11:22 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +    }
팩토리에서 옮겨오긴 했는데 이게 각각 RectangleView나 ImageView에 메소드로 들어가면 view.copy()로 다형성으로 각 타입이 담당하도록 할 수 있다는 의미였습니다. 
각자 내부 속성을 다룰 수 있는 타입은 자기 자신이니까요.

2022-03-15 11:23 UTC, godrm commented
머지할테니 다음 단계로 넘어가서 개선해보세요

2022-03-15 11:23 UTC, merged