[Pigbag] Step04-1 (Refactory) MainViewController & Rectangle
codesquad-members-2022/swift-drawingapp pull request #76
Opened 2022-03-14 08:45 UTC by P-SeoB

- 작업내용
- [X] 이미지 추가 버튼 추가
- [X] Step3 MainViewController에서  self.view 찾는 입출력 분리 -> 처리로직 Plane으로 이전
- [X] Plane안 프로퍼티 Private로 선언
- [X] Plane 프로퍼티들이 Private로 됨에 따라 test코드 리팩토링.
- [X] Rectangle Protocol선언 및 Factory 선언
- [X] Factory 메서드에서 Case 처리를 위해 Enum이 아닌 ObjectIdentifier 시도.
- [ ] 이미지 추가 버튼 액션 구현
- [ ] 사진데이터 처리 관리 뷰또는 뷰모델 선언

- - -
키워드: ObjectIdentifier, Factory, creator

고민 및 해결:
- Plane의  property들을 private접근자로 바꾸어주었습니다.
이 과정에서 test에서 프로퍼티를 이용해서 하던 로직들을 수정해야했는데,
예를 들어 선택된 사각형의 alpha값을 바꾸는 로직은 Plane에 선택된 사각형이 있어야만 테스트가 가능한데, Plane의 선택된 사각형을 참조할 수 없으므로 직접적으로 Plane에 테스트용 선택된 사각형을 넣어줄 방법이 없어서 Plane에 있는 add메서드와 findRectangle메소드를 이용해 테스트틑 했습니다.

- 빈화면을 클릭시 사각형의 선택을 없애는 로직을 짜야했습니다.
이전에는 ViewController에서 터치한 곳이 view이면 취소되게 하면 됐으나 이또한 출력이라 생각하고 분리를 해야한다면,
`터치한곳이 Rectangle인지 빈화면인지 구분을 어떻게 할까?`에 대한 고민이 있었습니다.

1. `Point(0.0,0.0)이면 빈화면으로 하자.`
 당시 사각형을 판별하기 위해 key 값을 origin.x와 origin.y로 구성하여 Plane에게 전달하는데 self.view는 origin값이 항상 Point(0.0,0.0) 
 하지만 , 랜덤으로 생성된 사각형이 0.0좌표에 생길 수 있으므로 다른 방법이 필요하거나 추가적인 구분할 요소가 필요.

2. `Size매개변수를 하나더 생성`후 plane에서 선택한 View의 size가 최대 크기이면 빈화면을 클릭한것으로 판단하고 로직을 구성

- - -
질문거리:
1. 빈화면 클릭시 사각형을 없애는 로직을 구성하다가,
Plane에서 같은 NotificationName을 가진 Post를 두번하게 되었는데.. 이 과정이 어색하다면 코멘트 남겨주시면 감사하겠습니다!

2. 수업시간에 배운 Protocol과 Factory를 연결하여 설계하던중 `Enum Switch Case`문 대신 `ObjectIdentifier`를 시도해보았습니다
그 결과,,
Enum혹은 타입을 더 선언 안해도 되지만, ViewController에서 `.`을 통한 네임스페이스 기능을 사용하지는 못하였습니다.
만약, 코드를 짠 제가아닌 다른 사용자가 이를 이용하려한다면 조금 불편할 수 있겠다는 생각이 들었습니다.
(물론 메서드나 프로퍼티명을 아주 명확하게 지으면 해결이 될수도 있겠지만..)
이는 Factory안에 Switch 해야하는 Case문이 점차 많아질 수록 한눈에 보기 편한 Enum으로 인한 Switch문이 더 나아 보인다는 생각이 듭니다!
ObjectIdentifier를 이용한 코드를 처음 짜봐서 제가 잘 못 사용한 부분이나, 위의 문제점을 해결할 수 있는 방법이 있다면 코멘트 해주시면 감사하겠습니다!!

2022-03-14 09:27 UTC, godrm requested changes
개선한 부분에서 설명이 필요한 부분들을 댓글로 남겼습니다. 
확인해주시고 댓글로 확인한 다음에 수정하던가 머지하던가 해야 할 것 같네요

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Factory/RectangleFactory.swift
> +            return PlaneRectangle(id: id, origin: origin, size: size, rgb: rgb, alpha: alpha)
`Rectangle.Type`로 넘기는 거라면 type.init()도 가능하지 않을까요?

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +    private let rectangleFactory = RectangleFactory()
느슨한 연결을 시도해 본다면 Factory로 직접 여기서 생성하는게 아니라 (보통 팩토리는 인스턴스를 생성하지 않고 쓰기도 합니다)
Factory를 ViewController에 주입하는 방법도 고려해보세요. 어디서 주입할 수 있을까요?

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
> +            self?.plane.addRectangle(rectangle: rect as! PlaneRectangle)    //모델에 rectangle을 추가
이 부분도 이렇게 생각해보세요
Plane의 역할과 책임은 어디까지인가. 사각형을 만드는 것은 누구의 역할인가
Plane에게 이벤트를 전달하면 생성까지 해도 되는가
그렇다면 Plane은 Factory를 알고 있어야 하나. 모르고도 생성이 가능한가

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/MainViewController.swift
>          self.retangleViews[newRectangle] = rectangleView
뷰를 생성하는 것도 팩토리가 있으면 어떨까요? PlaneRectangleView 와 (ImageRectangle에 대비되는) 이미지뷰를 못 찾겠는데 뷰도 생성해 줄 수 있지 않을까요?

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/Image.swift
> +    }
선언을 봐도, 주석을 봐도 Image 타입이 뭘 하는 역할인지 모르겠네요. 
Plane에 대비되는 이미지 타입인건가요?

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/ImageRectangle.swift
> +
이건 모델인가요? 뷰인가요? Rectangle 이것만 봐서는 모델인 것 같은데 UIKit에 의존적이네요
모델은 UIKit에 독립적으로 구현하셔야 합니다.

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
>          static let didFindRectangle = Notification.Name("didFindRectangle")
주석에 작업한 내용이나 과정을 설명하기 보다는 코드에 대한 정보를 써주는 게 좋습니다.
이런 의사결정 과정은 PR 보내면서 저처럼 코멘트를 추가하는 게 좋습니다.

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/PlaneRectangle.swift
>      var alpha:Alpha
Rectangle이 super class 고 PlaneRectangled sub-class 인가 보네요
여기 속성은 왜 다 var로 되어 있을까요. 항상 private var를 우선적으로 고려하시기 바랍니다. 
바꿀 수 있다고 하더라도 속성을 그대로 바꾸기 보다는 메소드를 제공해 주는 게 좋습니다
그래야 바꾸는 시점을 알 수 있고, 그거에 따라서 뭔가 알려줄 수도 있고 처리할 수 있습니다 
그게 아니면 아예 struct - let 으로 immutable 불변 타입을 고려하는 게 좋죠

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Protocol/Rectangle.swift
> +    var rgb:RGB { get set }
아.. Rectangle이 super-class가 아니라 프로토콜이군요
프로토콜일 때는 이렇게 속성을 get set 으로 다 오픈하게 되니까, 속성을 추상화하기 보다는 메소드를 추상화하는 게 좋습니다
클래스를 이렇게 다 접근하도록 하는 구조는 지양하세요

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/ShapeElement/Size.swift
> +
구현을 하지 않을꺼면 그냥 선언하는 곳에 프로토콜을 채택하는 게 낫겠습니다.

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/PlaneRectangle.swift
>          lhs.id == rhs.id
`특정한 객체가 같다`는 것은 어떤 의미일까요?
id가 같으면 속성을 보지 않아도 같은 걸텐데, id가 다르지만 속성이 같은 경우도 있을 수 있겠죠.
어떤 의미에서 같다는 것을 의미하는지에 따라서 구현도 달라져야 한다고 봅니다. 여기서는 `==` 의미가 어떤 의미일까요?

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +            userInfo: [Plane.UserInfoKey.foundRectangle:foundRectangle as Any]
`foundRectangle as Any` 이게 꼭 필요한가요?

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangles:[Point:PlaneRectangle] = [:]
`[Point:PlaneRectangle]` 이건 좀 이상한데요?
좌표 시스템에 모든 좌표를 다 매칭한다는 건가요? 
1024 x 768 이면 1024 * 768 개 키값이 생기는 건가요?

2022-03-14 09:27 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +                object: self
select 된게 없다는 의미로 userInfo를 안 보낼 수는 있겠네요. 이 자체가 이상하지는 않습니다. 
noti를 보내는 부분 보다는 isEmptySpace(size:) 이 부분이 더 이해가 안 갑니다. 
빈 화면을 클릭했다는 것을 size로 어떻게 알 수 있죠? 그 영역에 사각형이 있는지 없는지 비교해보지 않고 알 수 있나요?

2022-03-15 02:55 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Plane.swift
> +                object: self
음.. TapGesture에서 View를 터치했을때 View의 Size값을 얻을 수 있는데 빈화면을 클릭했다면 사각형들이 add되어있는 SuperView의 사이즈 값이 나올 것이므로 그 값을 비교해서 처리를 시도해보았습니다!

2022-03-15 02:59 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +                object: self
아.. 뷰의 속성으로 판단하려는 거군요. 이게 저랑 관점의 차이같네요.
터치한 뷰가 무엇이든 상관없이, 그 좌표를 가지는 사각형을 찾아야 한다고 생각했거든요.
판단하는 핵심 로직이 뷰의 속성에 의지하는 것보다는 이 방식이 더 좋다고 생각했습니다. 
TapGesture가 아니거나 뷰 속성을 모른다면 가정하는 게 어떨까요?

2022-03-15 03:01 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangles:[Point:PlaneRectangle] = [:]
아.. 제가 질문주신거에 대해 이해한게 맞다면 Point라고 이름을 지어서 오해가 생긴것 같습니다.
PlaneRectangle의 origin(사각형의 시작점)을 Key값으로 두고 Plane사각형의 정보를 Value로 두려고 Dictionary를 만들었습니다.

2022-03-15 03:19 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Plane.swift
> +                object: self
이미 있는 로직에 Size만 추가하면 처리가 간단해서 이렇게 시도한거 같습니다 😂
말씀 주신대로 뷰 속성을 모른다는 가정하에도 한번 고민해보겠습니다!

2022-03-15 03:20 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangles:[Point:PlaneRectangle] = [:]
그렇군요. 그럼 사각형 origin 좌표가 바뀔때마다 여기도 업데이트하는거에요? 필요하면 만들 수 있겠지만 시작점으로 빠르게 찾아야 하는 경우는 어떤 경우가 있나요?

2022-03-15 03:24 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/PlaneRectangle.swift
>          lhs.id == rhs.id
1. id가 같지만 속성이 달라도 같은 객체이다.
2. id는 다르지만 속성이 같은경우 같은 객체이다.
위 두가지 경우를 생각해본다면 지금 이상황에서는 ID보다는 속성이 같은 경우가 맞다고 생각이 듭니다.
왜냐하면, 여기서 제가 `==`를 쓴 이유는 특정 사각형을 뷰에서 선택했을때 그 사각형을 비교하여 찾기 위해 선언 한것인데,,
생각해보니 == 는 `두 객체`를 비교하는 것이니까, 두개의 사각형이 같다고 말하려면 ID보다는 속성을 비교하는게 맞다고 생각이듭니다.

2022-03-15 03:37 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangles:[Point:PlaneRectangle] = [:]
아직 사각형 origin 좌표가 바뀌는 경우는 생각해보지않았지만, 업데이트를 같이 해주어야 할 것같습니다.
질문주신 `시작점으로 빠르게 찾아야하는 경우`는 잘 이해가 되지 않는데.. 설명을 조금만 더 해주시면 감사하겠습니다!

2022-03-15 03:54 UTC, P-SeoB commented
> 개선한 부분에서 설명이 필요한 부분들을 댓글로 남겼습니다. 확인해주시고 댓글로 확인한 다음에 수정하던가 머지하던가 해야 할 것 같네요

전반적으로 개선을 조금 더 필요한것 같습니다. 개선후에 다시 댓글 남기겠습니다!

2022-03-15 11:26 UTC, P-SeoB commented on DrawingApp/DrawingApp/Factory/RectangleFactory.swift
> +            return PlaneRectangle(id: id, origin: origin, size: size, rgb: rgb, alpha: alpha)
프로토콜에 init메서드를 추가하고 type.init으로 리팩토링 했습니다
![스크린샷 2022-03-15 오후 8 26 12](https://user-images.githubusercontent.com/80263729/158367914-2ebd4a16-392f-4d1f-aa97-54b616705e1b.png)

2022-03-15 11:44 UTC, P-SeoB commented on DrawingApp/DrawingApp/MainViewController.swift
> +    private let rectangleFactory = RectangleFactory()
ViewController에 required init을 구현하는 과정에서 어려움을 겪었습니다. (required init에 매개변수를 추가하면 또 다른 init이 되어버리기 때문에..)
따라서,, Setup메서드를 선언하는 방법을 생각하게 되었습니다.
이후 이 Setup메서드를 호출하는 곳은 ViewDidLoad보다는 사각형을 생성하는 것이므로, 사각형을 추가하는 로직에 추가하는 것이 맞는것 같아  사각형 추가하는 버튼액션에 매개변수로 RectangleCreator를 넣어 주입을 시도해보았습니다
![스크린샷 2022-03-15 오후 8 42 20](https://user-images.githubusercontent.com/80263729/158370735-a9ea48c4-ddb8-4a87-9509-f23e81fca709.png)  

![스크린샷 2022-03-15 오후 8 42 30](https://user-images.githubusercontent.com/80263729/158370759-f7d0ee36-d658-49d1-85b4-9cf0cf9e2165.png)
.

2022-03-15 12:18 UTC, P-SeoB commented on DrawingApp/DrawingApp/MainViewController.swift
> +            self?.plane.addRectangle(rectangle: rect as! PlaneRectangle)    //모델에 rectangle을 추가
ViewController는 모델과 뷰사이의 연결 역할이자 모델과 뷰사이에서 일어나는 이벤트들을 처리하는 책임이 있고,
Plane은 모델이므로 ViewController의 지시?에따라 행동을 해야하는 책임과 역할이 있다고 생각이 듭니다.
따라서, `사각형을 생성하라는 지시를 내리는 것은 ViewController 만드는 것은 Plane이 해야합니다.`
Plane이 Factory를 모르고 생성하기 위해서 기존에 만들어진 Rectangle을 넘겨주는 방식 대신에 creator라는 프로토콜을 넘겨주고
프로토콜에 있는 메서드를 통해 생성을하도록 시도해보았습니다.
![스크린샷 2022-03-15 오후 9 14 25](https://user-images.githubusercontent.com/80263729/158375589-e20a2edb-3a5f-453a-8593-705251e32b7d.png)

![스크린샷 2022-03-15 오후 9 17 59](https://user-images.githubusercontent.com/80263729/158376053-7a7e00ec-968a-437c-b55a-604370a55595.png)


이때 as? PlaneRectangle과 같이 캐스팅을 해주어야 했는데, 이경우에는 PlaneRectangle이 될것이 명확하다고 생각이 들어서,
 as!를 사용했습니다.

2022-03-15 13:22 UTC, P-SeoB commented on DrawingApp/DrawingApp/Protocol/Rectangle.swift
> +    var rgb:RGB { get set }
속성대신 생성자와 메서드로 프로토콜을 재 구성 해보았습니다!

2022-03-16 06:29 UTC, P-SeoB commented on DrawingApp/DrawingApp/Factory/RectanlgeViewFactory.swift
> +    static func makeRectangleView(sourceRectangle: Rectangleable) -> RectangleViewable {
View도 타입에 따라 생성될수 있게 Factory를 선언했습니다.
View는 그려지는 매개변수로 들어오는  Rectanglable을 준수하는 객체에 따라 설정하고자, sourceRectangle라는 변수명을 지었고, 제일 기본이 되는 Plane를 default로 두고 타입에 따라 처리하고자 했습니다.

2022-03-16 06:30 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Image.swift
> +    }
아, 아직 구현하지 못한부분인데 들어간것 같습니다 지우도록 하겠습니다!

2022-03-16 06:32 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/PlaneRectangle.swift
> +    static func == (lhs: PlaneRectangle, rhs: PlaneRectangle) -> Bool {
`두개의 사각형이 같다` 라고 말할 수 있는 경우는 ID값이 아니라 속성들이 모두 같을 경우라 생각해서 ID를 제외한 모든 속성이 같으면 같다. 로 `==`를 정의했습니다.

2022-03-16 06:34 UTC, P-SeoB commented on DrawingApp/DrawingApp/Protocol/Rectangleable.swift
> +}
기본 속성들을 가지는 대신 생성자와 메서드들을 가지도록 프로토콜을 리팩토링 했습니다.
사각형이 될수 있는 init메서드에서 RGB와 alpha값은 필수로 생각되지 않아서 옵셔널로 선언했습니다.

2022-03-16 06:38 UTC, P-SeoB commented on DrawingApp/DrawingApp/View/ImageRectangleView.swift
> +}
편의 생성자가아닌 기존에 있는 생성자를 활용하여 생성하고자 했습니다.
대신, RectangleViewable 프로토콜에 있는 메서드들을 통해 Retangleable을 따르는 객체를 이용해서 값을 조정할 수 있게 했습니다.

2022-03-16 06:40 UTC, P-SeoB commented
피드백 주신 부분 수정하여 다시 Push했습니다!

2022-03-16 07:37 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangles:[Point:PlaneRectangle] = [:]
지금 rectangles 사전의 존재 이유를 말하는 겁니다. Point로 PlaneRectangle을 곧바로 빠르게 찾아야 할 경우가 있냐는 거죠.
이렇게 직접 매칭하는 경우는 O(1)로 곧바로 매칭해서 찾아야 할 때 사용하는 데이터 구조니까요

2022-03-16 07:43 UTC, godrm commented on DrawingApp/DrawingApp/Factory/RectanlgeViewFactory.swift
> +            return rectangle
뷰 팩토리가 있는 것은 좋네요. 다만 타입이 추가될 때마다 여기를 추가해야 하는 게 꼭 좋은 건 아닙니다
타입별로 메소드가 나눠져 있는 게 오히려 나을 수도 있어요. 참고하세요

2022-03-16 07:46 UTC, godrm commented on DrawingApp/DrawingApp/Protocol/Rectangleable.swift
> +}
비슷한 이유로 init()은 프로토콜로 추상화하는 게 적합하지 않은 경우도 많습니다. 
채택할 객체가 다 속성이 동일하지는 않을테니까요

2022-03-16 07:47 UTC, godrm commented on DrawingApp/DrawingApp/View/ImageRectangleView.swift
> +}
객체 지향 관점에서는 init 시점에 필요한 것을 다 지정해 줄 수 있는 게 안전한 방법입니다. 생성자의 역할이기도 하구요
이렇게 Rectangleable에서 모든 것을 처리하기 보다는 지정 init에서 채울 필요한 속성만 다루는 것도 좋겠네요.

2022-03-16 07:47 UTC, godrm commented
수고하셨습니다~

2022-03-16 07:47 UTC, merged

2022-03-16 07:55 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangles:[Point:PlaneRectangle] = [:]
아.! 제생각에 배열로 사각형을 관리하게 된다면, 사각형이 많아지면 질수록 탐색시간이 길어질수 있을 것 같아서 Dictionary로 선언을 했고, 좌표대신 origin point로 찾은 이유는 순수 좌표를 넘겼을때 생길수 있는 문제(Ex.겹쳐있는 사각형 중에 어떤 사각형을 고를것인지..) 등의 해결방안으로 origin point를 넘기는 것이 더 효율적이라 생각했습니다!

2022-03-16 07:56 UTC, P-SeoB commented on DrawingApp/DrawingApp/Protocol/Rectangleable.swift
> +}
아하.. 그렇군요! 프로토콜로 init() 을 추상화 하는것은 다시 고민해보겠습니다. 감사합니다!

2022-03-16 07:58 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangles:[Point:PlaneRectangle] = [:]
그럴꺼 같았습니다. 그렇다면 origin 좌표가 같은 위치에는 여러 사각형이 올 수 없는걸까요?

2022-03-16 08:30 UTC, P-SeoB commented on DrawingApp/DrawingApp/Model/Plane.swift
> +    private var rectangles:[Point:PlaneRectangle] = [:]
음.. 일단 사이즈가 고정된 사각형이기 때문에 겹친다면 하나의 사각형처럼 보일테고, 만약 똑같은 위치에 사각형이 온다면 그 후 Dictionary에 후에 추가된 사각형이 Dictionary에 들어 갈것이기 때문에 겹쳐있는 사각형중에 위에 있는 사각형이 선택될것이라 생각이 됩니다.
하지만 만약 크기가 다른 사각형등이 생긴다면.. origin으로는 한계가 있을것 같네요.. 수정해보도록 하겠습니다!