[dale] - 사진 추가하기
codesquad-members-2022/swift-drawingapp pull request #77
Opened 2022-03-14 09:22 UTC by sungju-kim

## 작업 목록
- [x] 사진앨범에서 사진 불러오기
- [x] 선택된 사진 테두리 표시
- [x] 투명도 조절
- [x] 배경색버튼 비활성화  

## 고민과 해결
- 일반 사각형과 사진이 들어있는 사각형을 같은 타입으로 볼것인지 아닌지에 대해 고민을 했습니다.
  - 사진이 들어있는 사각형은 color값이 굳이 들어갈 필요가 없다고 생각해 새로운 타입을 만들어 일반 사각형을 상속 받도록 하고 일반사각형의 color값을 옵셔널값으로 만들어 주었습니다.
  - 사진이 들어있는 사각형을 선택했을때에만 colorChangeButton을 비활성화 시켜야 하기때문에 rectangle의 color값이 nil일때는 버튼을 비활성화 되게 만들었습니다.

2022-03-14 09:49 UTC, godrm requested changes
사진이 추가되면서 기존 구조와 대비되는 구조가 생겼는데, 이 부분이 조금 어색합니다.
다음 내용을 확인해보시고 개선해보세요

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/Model/PhotoRectangle.swift
> +    }
PhotoRectangle 이 모델이라면 UIKit에 독립적으로 만드셔야 합니다. UIImage를 가지고 있으면 안되는거죠

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/Model/PhotoImages.swift
> +
PhotoImages가 어떤 의도인지 잘 모르겠어요. Plane : Rectangle 에 대비되는 PhotoImages : PhotoRactangle 인가요?

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +    var backGroundColor : Color?
이건 좀 사소한건데 보통 `background` 는 한 단어로 표기하는 것 같습니다

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/Model/RectangleFactory.swift
> +        let randomPosition = RandomGenerator.generatePosition(screenSize: screenSize)
여기도 모델 팩토리인데 UIKit에 의존하고 있네요.

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/Model/RectangleViewFactory.swift
> +        guard let color = rectangle.backGroundColor else {return nil}
여기서 `rectangle.backGroundColor` 이 부분을 처리하지 않고 아예 컴파일 시점에 접근할 수 없도록 할 수 있을까요?

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/View/PhotoRectangleView.swift
> +        self.addSubview(photoImageView)
setImage()는 여러번 호출할 수 있을 것 같네요
그러면 호출할 때마다 photoImageView를 addSubview()하는 걸까요?

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +    let photoImages = PhotoImages()
Plane이 여기 두 개를 같이 관리하는 것과 이렇게 따로 관리하는 게 어떤 차이가 있을까요?
새로운 모델 종류가 늘어날 때마다 관리하는 타입도 계속 늘어나야할까요? 어떻게 한꺼번에 관리할 수 있을까요?

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
> +        }
여기 비교-분기문으로 각각 처리하지 않고 비슷한 코드가 많은 데 동일하게 처리할 수 있지 않을까요?

2022-03-14 09:49 UTC, godrm commented on DrawingApp/DrawingApp/ViewController.swift
>          self.rectangleViewBoard.setSelectedRectangleView(at: index)
Plane에서 받은 index를 그대로 사용하는 것은 조심해야 합니다. 모델의 구조와 뷰의 구조가 항상 같다는 보장이 안될 수도 있습니다.
보여주는 형태, 방식 때문에 뷰가 더 많을 수도 있거든요. index로 처리가 될 수도 있지만 rectangle 같은 값 자체로 비교하는 게 더 좋은 경우도 있습니다. 참고하세요

2022-03-15 02:52 UTC, sungju-kim commented on DrawingApp/DrawingApp/View/PhotoRectangleView.swift
> +        self.addSubview(photoImageView)
생각해보니 그렇네요 addSubview는 한번만 할 수 있도록 수정해보겠습니다.

2022-03-15 02:54 UTC, sungju-kim commented on DrawingApp/DrawingApp/Model/PhotoImages.swift
> +
plane과 대비되는 객체로 사용하려고 했는데, 코드를 완성하고 나니 사용하지 않는 객체가 되어버렸습니다. 개선해보겠습니다!

2022-03-15 02:56 UTC, sungju-kim commented on DrawingApp/DrawingApp/Model/PhotoRectangle.swift
> +    }
그부분을 아예 배제하고 설계를 했던것 같습니다. 수정해보겠습니다!

2022-03-15 05:55 UTC, sungju-kim commented on DrawingApp/DrawingApp/ViewController.swift
> +        }
도전 해보겠습니다!

2022-03-15 09:08 UTC, sungju-kim commented on DrawingApp/DrawingApp/ViewController.swift
> +    let photoImages = PhotoImages()
새로운 모델 종류들의 공통점으로 묶어 새로운 타입을 만들어 사용하면 될것같습니다!

2022-03-15 09:09 UTC, sungju-kim commented
피드백 사항 수정해서 푸시했습니다! 리뷰 감사합니다!

2022-03-15 09:48 UTC, godrm commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +    var backgroundImage: Data?
이건 사각형이 이미지까지 갖고 있을 필요가 없지 않나요?
파충류가 포유류 역할까지 하는 게 아닐까요?

2022-03-15 09:48 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleViewFactory.swift
> +    static func makeView(of rectangle : Rectangle) -> RectangleView? {
다음 도전꺼리는 이 부분에서 팩토리가 RectangleView 구체 타입을 리턴하는 게 아니라 프로토콜로 추상화해서 리턴해보세요

2022-03-15 09:50 UTC, godrm commented
Rectangle이 ImageData를 포함하는 부분은 머지하고 다음 단계에서 개선해보세요

2022-03-15 09:50 UTC, merged

2022-03-15 10:00 UTC, sungju-kim commented on DrawingApp/DrawingApp/Model/Rectangle.swift
> +    var backgroundImage: Data?
RectangleFactory 를 개선하면서 Rectangle 과 PhotoRectangle을 동일한 객체로 바라보려고 했습니다. 생각해보니 둘을 포함하는 타입이 있으면 굳이 동일한 객체로 보지 않아도 될것같습니다.

2022-03-15 10:01 UTC, sungju-kim commented on DrawingApp/DrawingApp/View/RectangleViewFactory.swift
> +    static func makeView(of rectangle : Rectangle) -> RectangleView? {
넵 Rectangle 과 PhotoRectangle 분리하면서 함께 해보겠습니다.

2022-03-15 10:02 UTC, sungju-kim commented
> Rectangle이 ImageData를 포함하는 부분은 머지하고 다음 단계에서 개선해보세요

넵 리뷰 감사합니다!