[Alex] Step4 사진 추가하기
codesquad-members-2022/swift-drawingapp pull request #78
Opened 2022-03-14 09:33 UTC by SongTaehwan

# 사진 추가하기

## 작업 목록

- [x] 이미지 추가 버튼
- [x] 버튼 이미지 적용 및 corner radius 부분 적용
- [x] 사각형 추가 시 scale 애니메이션 효과 추가
- [x] RectangleView 를 UIImageView 상속하게 변경
- [x] 앨범에서 선택한 이미지를 화면에 표시
- [x] 표시된 이미지의 투명도 값 변경
- [x] 사진데이터 처리 관리 뷰 또는 뷰 모델 선언

## 데모

<image src="https://github.com/SongTaehwan/swift-drawingapp/blob/step4/images/step4.gif?raw=true" width="500px">

## 학습 키워드

- OptionSet
- UIView.animate
- UIButton.Configuration
- DispatchGroup
- UTType
- PHPickerViewController & PHPickerViewControllerDelegate

## 고민

- 앨범에서 여러 이미지(최대 3장) 선택 후 사각형이 화면에 표시될 때 동시에 표시되지 않는 문제가 발견되었습니다.
- 현재 동기적으로 이벤트를 처리하게 되어 있는 NotificationCenter 가 원인이라는 생각이 들었습니다.
- NotificationCenter 를 비동기적인 흐름을 처리하도록 바꾸어 개선해볼 생각입니다.

2022-03-14 09:37 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    private func configureDelegate() {
Delegate 에 사용되는 메소도를 제외한 나머지 메소드는 모두 **private** 하게 접근 제어를 했습니다.
코드로 ViewController 인스턴트를 생성하는 경우에 불필요한 메소드가 노출되는 것을 방지할 목적입니다.

2022-03-14 09:39 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        }
tap 이벤트 발생 시 `planeViewDidTapped`가 매번 호출되는데 불필요한 흐름이 계속 발생하는 것을 막고자 if 조건을 추가하였습니다.

2022-03-14 09:44 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +            }
RectangleView 가 UIImageView 를 상속하고 있어 사각형의 값을 조건으로 다른 동작을 하고 있습니다.
어떤 값을 조건으로 판별하기 보다는 별도의 View 를 만들어 전체적인 흐름을 분리하는 것이 좋을까요?

예를 들어 `ImageRectangleView` 클래스를 만들고 MVC 흐름에 관여하는 delegate 메소드도 각 View 별로 따로 구현하는 것을 말합니다.

2022-03-14 09:48 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +                collection.append(data)
이미지의 크기에 따라 불러오는 시간이 오래 걸릴 수 있을 것 같아 중복으로 불러오는 것을 방지하고자 캐싱할 목적으로 `Gallery` 구조체에 이미지를 바이너리 형태로 저장하였습니다.

이렇게 하고보니 사진 데이터를 관리한다는 목적에 부합한 것인지 잘 모르겠습니다.

2022-03-14 09:53 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        })
이미지를 불러오는데 오랜 시간이 걸릴 수 있는 것을 염두해 모든 로딩 작업이 끝난 후에 한꺼번에 View 에 보여주는 것이 자연스럽다고 생각해 DispatchGroup 을 활용해보았습니다.
현재 이미지가 화면에 표시될 때 다소 버벅임이 있는데 NotificationCenter 의 흐름도 비동기 방식으로 바꾸어 개선해보겠습니다.

2022-03-14 10:09 UTC, godrm requested changes
사진을 처리하는 모델과 뷰가 추가되면서 기존의 타입들이 영향을 받게 되는데,
기존 기능을 변경해서 분기문으로 이것도 되고 저것도 되게 만들기 보다는
수업에서 언급한 것처럼 추상화를 시키고, 타입이 추가되어도 확장이 가능한 구조를 고민해보세요

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    private func configureDelegate() {
네 익숙하게 private var, private func을 자주 선언해주세요

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        }
`매번 호출된다`는 게 어떤 의미에요? 이벤트가 발생하면 호출되는 건 당연한 것 같은데, 탭해도 특별한 경우만 처리하는 건 이상한 건 아니죠. 
이렇게 생각해보면 어때요? plane에게 탭 이벤트를 계속 전달하는데 plane에서 currentItem이 있을 때만 deselect해도 되지 않을까요? 지금은 마치 ViewController가 plane이 할 일을 미리 다 알고 정해주는 듯한 느낌이네요.

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        }
이런 동작을 데이터가 있느냐 없느냐로 판단하는 게 아니라, 노티를 나누거나 흐름을 나누는 게 어떨까요?
꼭 동일하게 호출하고 분기하는 방법만 있는 건 아닙니다.

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +            }
네. 어디선가 분기처리는 코드는 늘 흐름 자체를 분리하는 걸 고려해보세요. 
혹은 같은 흐름이라면 다형성으로 분기 처리 없이 각각 동작하는 게 더 좋습니다

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    @objc private func planeDidDidSelectItem(_ notification: Notification) {
`planeDidDidSelectItem` 이건 좀 이상한 부분이 있습니다. didSelect를 의미하는 걸까요 혹은 deselect를 의미하는걸까요?

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    @objc private func planeDidDidUnselectItem(_ notification: Notification) {
planeDidDidUnselectItem 오잉 여기고 Did가 반복되는 걸 보니 뭔가 한꺼번에 수정한걸까요

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
>          self.controlPanelView.setAlphaSliderValue(value: rectangle.alpha)
출력의 흐름이면 rectangleView에 뭔가 값을 변경하는 것은 좋은데, 
`self.controlPanelView.setColorButtonAccess(enable: !rectangleView.hasImageContent)` 에서 rectangleView.hasImageContent보다는 rectangle 모델에서 값을 참조하는 게 좋습니다. 뷰의 속성을 가져오기 보다는 모델의 값을 우선적으로 활용해보세요

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +                collection.append(data)
자주 쓴다면 의미가 있겠지만, gallery가 필요한지는 모르겠습니다. 보통은 이미지는 메모리에 보관하기 보다는 메모리를 줄이기 위해서 File로 저장하는 데 미션에서만 제한적으로 쓰는 거라서요

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +                    self.plane.append(item: imageRectangle)
plane은 모델이라 UIKit에 독립적이라서 main queue에서 실행할 필요가 없습니다. 
모델이 추가되고 나서 뷰를 추가할 때만 하면 되는데 이걸 여기서 할 필요가 없다는 의미입니다.

2022-03-14 10:09 UTC, godrm commented on DrawingApp/DrawingApp/View/RectangleView.swift
> +    }
기존에 `RectangleView: UIView`는 그대로 두고 다른 타입을 추가하는 게 어땠을까 생각해봅니다
뭐가 있느냐 없느냐에 따라 동작을 구분하기 보다는,
다형성으로 각각 동작하도록 만드는 방식을 떠올려보세요

2022-03-14 10:12 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        })
다중 선택을 하셨군요! 
DispatchGroup이 다 할 때까지 기다리는 거니까 멈칫거릴 수 밖에 없습니다. 
하나씩 업데이트가 되는 구조로 할 수 있다면 해결해보세요

2022-03-14 10:23 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        }
실행 흐름이 불필요하게 하위 컨텍스트로 이어지지 않도록 상위 컨텍스트에서 차단해야한다고 생각했는데 말씀하신 방법대로 한다면 planeViewDidTapped 의 실행흐름이 plane 에 의존하지 않고 자기할일에 충실해지는 것 같습니다! 반영하겠습니다 :)

2022-03-15 04:43 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +                collection.append(data)
파일 정보가 담긴 URL 객체를 활용하여 사각형을 생성하는 시점에서 UIImage 를 통해 이미지를 메모리로 불러오는 방식으로 바꾸는 게 좋을 것 같네요!
이미지를 미리 불러오면 항상 메모리를 차지하게 되니까 필요할 때 불러오는 방식이 좋은 것 같습니다 :)

2022-03-16 04:28 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    private var rectangleMap = [Rectangle: RectangleShapable]()
RectangleView, ImageRectangleView 모두 rectangleMap 에 저장할 수 있게 사각형 View 를 프로토콜로 추상화했습니다

2022-03-16 04:33 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        guard let rectangleView = RectangleViewFactory.makeView(ofClass: Class, with: rectangle) else { return }
사각형 View 를 생성하는 것도 프로토콜을 사용해 다형성을 적용하니 객체 생성 필요한 분기가 생기고 복잡도가 늘었습니다.
팩토리를 사용하여 객체 생성을 위임하고 리턴 값에 타입케스팅을 사용하는 방식을 적용해보니 다형성의 장점을 느낄 수 있었습니다 :)

2022-03-16 04:37 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        self.controlPanelView.setAlphaSliderControllable(enable: true)
이미지 사각형을 선택하는 경우 배경색 버튼을 비활성화시키고 싶었습니다. 메타 타입을 사용해 문제를 해결하였습니다.
수업 때는 언제 사용해야할지 감이 오지 않았는데 이렇게 직접 활용해볼 기회가 생겨 뿌듯합니다 :)
메타 타입도 다형성을 도울 수 있는 기능이라는 걸 배웠습니다!

2022-03-16 04:39 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Model/Alpha.swift
> +    case opaque = 1.0
원시 타입을 Float 으로 변경해 UIView 의 알파값을 적용할 때 마다 10을 나눠야했던 불편함을 개선했습니다.

2022-03-16 04:41 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Model/Color.swift
>      }
UIInt8 를 사용해 입력 값의 유효성 검사를 컴파일 타임에 확인할 수 있게 개선하였습니다.
Sol 의 도움을 받았습니다 👍

2022-03-16 04:48 UTC, SongTaehwan commented on DrawingApp/DrawingApp/View/Components/ImageRectangleView.swift
> +    }
배경색을 바꾸기 위해 반드시 실행되는 메소드인데 이미지의 경우 배경색을 바꿀 필요가 없어 return 문만 넣어두었습니다.
사실상 더미 메소드와 같은데 협업 시 혼란의 여지가 될 수 있을 것 같습니다. 달리 다른 방법이 떠오르지 않아 이렇게 두었는 주석이라도 남겨두는게 좋을까요?

2022-03-16 04:53 UTC, SongTaehwan commented on DrawingApp/DrawingApp/Utility/RectangleViewFactory.swift
> +            let rectangleView = RectangleView(frame: data.convert(using: CGRect.self))
View 를 생성하는 과정에서 CGRect 타입이 필요해 UIKit 을 import 했는데 팩토리도 특정 프래임워크에 의존하지 않도록 수정해야할까요?

2022-03-16 04:55 UTC, SongTaehwan commented
@godrm 
다형성을 활용에 대한 피드백을 적용해보았습니다. 다형성에 대한 이해도가 더 높아진 것 같습니다 👍 
리뷰 부탁드리겠습니다 :)

2022-03-16 08:05 UTC, godrm approved these changes
개선이 잘 된 것 같습니다. 몇 가지 의견을 남겼습니다. 살펴보시고 다음 단계하면서 같이 개선해보시죠

2022-03-16 08:05 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +    private var rectangleMap = [Rectangle: RectangleShapable]()
잘 처리하셨네요. 혹시 Rectangle은 구체 타입인가요? 프로토콜인가요? 구체 타입이라면 키 타입에 대해서도 프로토콜로 시도해보세요

2022-03-16 08:05 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        guard let rectangleView = RectangleViewFactory.makeView(ofClass: Class, with: rectangle) else { return }
여기서 구체 타입은 Rectangle 인 것 같은데 그 마저도 프로토콜로 추상화를 시도해보세요.

2022-03-16 08:05 UTC, godrm commented on DrawingApp/DrawingApp/Controller/ViewController.swift
> +        self.controlPanelView.setAlphaSliderControllable(enable: true)
`rectangle.isType(of: Rectangle.self)` 이 부분이군요. 이렇게도 할 수 있구요. 프로토콜을 채택하고 있는지 점검하는 방법도 있습니다. 그것을 더 추천합니다.

2022-03-16 08:05 UTC, godrm commented on DrawingApp/DrawingApp/Model/ImageRectangle.swift
> +    private(set) var image: URL?
이렇게 Rectangle에서 상속받아서 만들면 이미지가 불필요한 Color를 갖게 되지 않나요?
마치 포유류를 만들어야 하는데 양서류에서 상속 받은 듯한 선택일 수 있습니다.

2022-03-16 08:05 UTC, merged