[shingha][step8] 오브젝트 목록 표시하기 & 이전 리뷰 수정
codesquad-members-2022/swift-drawingapp pull request #79
Opened 2022-03-14 12:47 UTC by shingha1124

- [ ] 리뷰사항 수정
  - [x] drawingModel에서 이벤트 발생 부분 Plane로 이동
  - [x] ViewController의 Bind 부분, 관련있는 func끼리 모음
  - [x] Plane에서 사용하는 팩토리를 Protocol타입으로 제작, init에서 주입하여 사용
  - [x] inject~~  -> get~~으로 함수 이름 변경
  - [x] ViewFactory를 switch를 안쓰고, 수업때 배운 ObjectIdentifier, type(of)를 사용하도록 개선
  - [ ] ModelFactor 구조개선
- [ ] 오브젝트 목록 표시
  - [x] 하이어라키 뷰 구현
  - [x] 테이블 뷰 구현
  - [x] 테이블 뷰 셀 구현
  - [x] 오브젝트 추가 시 하이어라키에 출력
  - [x] 하이어라키에서 선택 시 드로잉 뷰도 같이 선택
  - [x] 드로잉 뷰에서 선택 시 하이어라키도 선택
  - [x] 맨뒤, 뒤, 맨앞, 앞으로 보내기 구현

모델 팩토리의 경우 좀더 고민이 필요하여 아직 작업 전입니다 
좀더 이해하도록 노력해보고 수정해 보겠습니다!

2022-03-15 02:36 UTC, godrm requested changes
다음 내용들을 확인해보시고, 개선해보세요.

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +        ObjectIdentifier(LabelModel.self): 0
팩토리에서 생성한 개수를 관리하면 지울 때도 팩토리에게 연결해야 하지 않을까요?
Plane에서 관리하는 건 어떨까요? 
아.. 좀 헷갈렸는데 그냥 누적한 생성한 개수만 보려는 건가 보네요.

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +            return DrawingModel(id: id, index: counting, origin: origin, size: size, alpha: alpha)
타입이 늘어날 때마다 이렇게 코드가 추가되는 것보다는 팩토리 자체는 변화가 없도록 만들 수 있을까요?

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane/Plane.swift
> +    func getScreenSize() -> Size
PlaneDelegate 화면 크기가 외부에 의존한다는 것은 알겠는데,
이걸 매번 물어보는 게 좋을까요? 거의 대부분 같은 값일 것 같거든요
그렇다면 한 번만 넘겨주고 끝내도 되는건 아닐까요?

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane/Plane.swift
>  }
프로토콜들을 잘 나눈 것 같습니다. 
근데 나누고 보니까 이게 다 Plane을 위한 걸까요? 파일도 여기에 없어도 될꺼 같기도 하고 그러네요. 
예를 들어 `PlaneMakeModel`는 Plane이 채택하지만 Plane만을 위한걸까요? 어떻게 생각하시나요? 
프로토콜을 선언하는 것과 채택하는 것이 어떤 관계인지 생각해보세요

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Model/Plane/Plane.swift
> +        NotificationCenter.default.post(name: Plane.Event.didSelecteDrawingModel, object: self, userInfo: [ParamKey.drawingModel:model, ParamKey.index: index])
여기 함수 이름과 post 할 때 이벤트 이름이 다른 것 같아요!

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/DrawingBoard/View/LabelView.swift
> +        }
추상화한 DrawingModel 을 넘겼는데, 결국 내부에서 LabelModel 구체 타입으로 바꾸고 있네요. 
이 부분을 추상화한 타입에 의존하도록 개선해보세요.

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/Hierarchy/HierarchyView.swift
> +            return UITableViewCell()
TableView가 delegate와 dataSource를 구분한 기준과 이유가 뭘까요?
`HierarchyDelegate`는 두 가지 역할이 섞여 있는 것 같습니다.
테이블뷰의 데이터 소스도 하고, 델리게이트하고 있네요. 이 부분을 구분하면 더 좋을 것 같습니다

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/TopMenu/View/TopMenuItemView.swift
> +    }
이런 경우 클로저를 넘겨 받아도 되지만 아예 UIAction을 전달 받아도 됩니다. 참고하세요

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/Hierarchy/HierarchyView.swift
> +    func move(to: Plane.MoveTo)
뷰에서 다루는 속성 중에 `Plane.MoveTo` 가 좀 아쉽습니다. 서로 모르게 만들라는 것은 이런 타입도 Plane에 있으면 안 된다고 생각하세요

2022-03-15 02:36 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Present/View/TopMenu/View/View/HieararchyTableViewCell.swift
> +            name.text = "Text \(model.index)"
여기서 switch-case로 처리하는 부분들을 다형성으로 처리해보세요!

2022-03-15 02:37 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +            return DrawingModel(id: id, index: counting, origin: origin, size: size, alpha: alpha)
넵 이부분을 아직 고민해보고 있습니다. 어떤식으로 처리해야 변화가 없이될지 생각이 잘 안떠오르네요 ㅎㅎ

2022-03-15 06:11 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +        ObjectIdentifier(LabelModel.self): 0
삭제까지를 생각을 안하고 있었네요 
Plane로 이동했습니다!

2022-03-15 07:57 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Model/Plane/Plane.swift
>  }
맞게 이해 한건지는 모르겟지면 개선해보았습니다
플레인만을 위한 프로토콜이 아닌 공용으로 쓸수 있는 포로토콜로 네이밍도 바꾸고 파일도 따로 분리해 보았습니다.

2022-03-15 08:22 UTC, shingha1124 commented
모델 팩토리 개선은 좀더 고민해보겠습니다 
이런저런 방법으로 생각 및 삽질 해보고있는데 잘 안되네요 ㅠ

2022-03-15 08:37 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingModelFactory.swift
> +            return DrawingModel(id: id, index: counting, origin: origin, size: size, alpha: alpha)
공통적인 부분을 묶어서만들면 금방될꺼같은데.. 서로 다른 프로퍼티들을 어떻게 처리할지가 고민이네요

2022-03-16 13:53 UTC, shingha1124 commented
대격변이 일어났습니다.....
프로토콜을 정리해보면서 조립식으로 싹 고처보았습니다

2022-03-17 07:41 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +        return DrawingView.init(drawingable: drawingable)
메타 타입을 활용해서 모델과 뷰를 매칭해주고 생성하는 흐름은 좋은 시도입니다.  
다만 타입이 추가될 때마다 이렇게 매번 데이터를 바꾸어야 한다면 그것도 변경에 약한 구조가 됩니다.  
새로운 타입이 추가되도 기존의 생성 코드나 데이터 구조에 영향을 조금만 주는 게 좋습니다  
그럴려면 적어도 팩토리는 타입별로 메소드를 만들어도 됩니다.  
어딘가는 이벤트가 나눠지고, 거기서 생성해야 하는 타입이 나눠질테니 거기서 따로 생성하면 됩니다. 참고하세요.

2022-03-17 07:42 UTC, godrm commented
많이 바뀌었는데 프로토콜로 역할 분리를 잘 하셨네요. 흥미로운 작업이었을 것 같습니다.

2022-03-17 07:42 UTC, merged

2022-03-17 07:42 UTC, shingha1124 commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +        return DrawingView.init(drawingable: drawingable)
넵 위의 내용참고해서 조금 더 수정해보겠습니다.

2022-03-17 07:44 UTC, godrm commented on Drawingapp/Drawingapp/Sources/Common/Factory/Drawing/DrawingViewFactory.swift
> +        return DrawingView.init(drawingable: drawingable)
근데 어디선가 구체타입을 써야한다면 이 정도 코드면 작업하기 어렵지는 않을 수 있겠네요. 꼭 수정해야 하는 정도는 아니에요