[Damagucci-Juice] Step2 - 속성변경하기!
codesquad-members-2022/swift-drawingapp pull request #80
Opened 2022-03-14 12:49 UTC by Damagucci-Juice

# 오래 기다리셨죠?
 
드디어 구찌 PR이 도착했습니다. 😉

# 구현 사항

- [x] MVC 중에서 M -> C 로 갈 때 delegate 패턴을 적용
- [x] "사각형" 버튼을 누르면 사각형 View 추가
- [x] 선택된 사각형 뷰에 선택됨을 알리표는 테두리 추가
    - [x] 화면에 다른 사각형을 선택시 테두리 걷어가기
- [x] 버튼 누르면 사각형 뷰의 색이 변경 
    - [x] 색 버튼의 title 변경 
- [x] Slider 의 변화에 따라 view 투명도 조절

# 고민과 해결

* 메인화면 구성을 컨테이너 뷰로할지.. 스플릿 뷰로 할지 아니면 그냥 뷰로 할지 고민
-> 이것 저것 해보다가, 데일에게 물어본 결과 가장 쉬운 그냥 뷰로 할 것을 추천받아 `그냥` 뷰로 구성

* 델리게이트 패턴이 익숙지 않아 싱하의 도움으로 해결했습니다.
-> UIImagePickerController 와 비슷하게 Delegate 패턴을 쓰는 부분에서 약간의 친숙함이 생겼습니다.

[블로그에 정리한 내용](https://damagucci-juice.tistory.com/37)

* 화면에 다른 사각형을 선택시 테두리를 걷어가는 것에서, 어떤 로직을 짜야할지 모르는 문제
-> 가장 최근에 선택된 사각형을 담을 속성을 옵셔널로 선언

# 질문거리

1. 코드의 깔끔함을 추구해야하는 상황에 온거 같은데.. 뭐가 깨끗하고 좋은 코드인지에 대한 기준이 없습니다. 어쩌면 좋을까요?
2. 취업전까지 필요한 예상 학습 시간

일단, 추상적인 질문 죄송합니다. 
취업 준비 기간을 짧으면 22년, 길게는 23년까지 쓰고 싶은데, 
그 안에서 빠르고 확실하게 성장하는 태도나 습관 같은게 있다면 무엇일까요?

# 구현 화면

![Simulator Screen Recording - iPad Air (4th generation) - 2022-03-14 at 21 46 48](https://user-images.githubusercontent.com/50472122/158175075-535e6555-02de-4972-9170-f771c2dcf35f.gif)

2022-03-15 02:37 UTC, godrm commented
> 1. 코드의 깔끔함을 추구해야하는 상황에 온거 같은데.. 뭐가 깨끗하고 좋은 코드인지에 대한 기준이 없습니다. 어쩌면 좋을까요?
> 2. �취업전까지 필요한 예상 학습 시간

PR은 커밋한 내용과 포함된 코드에 관련된 질문만 해주세요. 이런 질문은 그냥 슬랙에 올리는 게 좋겠습니다.

2022-03-15 03:41 UTC, godrm requested changes
전체적인 구조와 흐름은 좋습니다.
세부적으로 개선할 포인트를 의견으로 남겼습니다. PR 열어놓을테니 수정하시고 나서 다시 push하고 댓글을 남겨주세요

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/Plane.swift
> +}
주석은 코드에 대한 부가적인 정보를 담고 있어야 합니다. 코드를 만드는 과정을 기록하는 수단은 아니에요
그런 걸 작업하는 동안 기록해 놓을 수는 있겠지만 커밋할 때는 다른 사람이 주석과 코드를 같이 읽게 되니까 다른 사람이 읽었을 때도 충분히 도움이 되는 정보(!)가 포함되어야 합니다. 관심없을 꺼 같은건 넣지 않아도 되는거죠

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/Plane.swift
> +}
RectangleAddedDelegate 와 PlaneColorChangeDelegate 등이 어떤 것은 Rectangle-로 시작하고, 다른 것은 Plane-으로 시작하네요. 매개변수는 모두 Rectangle인데 어떤 차이가 있는걸까요?

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/Plane.swift
> +    }
이걸 배열로 전달하는 이유는 모르겠습니다. 어떤 의도가 있는걸까요? 그냥 Rectangle 자체를 활용하는 방법은 어때요?

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/Plane.swift
> +        return (false,99999)
이런 99999 특정한 값으로 없다는 것을 표현하기 보다는 옵셔널을 쓰는게 더 좋습니다. 
그러면 true, false도 따로 넘기지 않아도 되구요.

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/Plane.swift
> +        let touchedResult = isTouchedOnRectangle(at: point)
혹시 isTouchedOnRectangle를 내부에서만 사용하는 거라면 private func으로 지정해주세요

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/Plane.swift
> +    func isTouchedOnRectangle(at point: Rectangle.Point) -> (bool: Bool, index: Int) {
Rectangle.Point 을 Rectangle에서만 쓰는 게 아니라면 nested에 넣지 않고 빼서 선언하는 것도 고려해보세요

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/Rectangle.swift
> +    }
어차피 getter가 필요하다면 private(set)으로 선언하는 것도 좋습니다.

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +    var selectedView: UIView?
ViewController라도 private var를 우선적으로 고려하세요

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +    @IBOutlet weak var colorButton: UIButton!
보통은 IBOutlet 은 속성이니까 위에 따로 선언하고, IBAction은 func이니까 아래쪽에 두는 편입니다. 이렇게 섞어서 선언하지는 않는게 좋습니다.

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +        func BackgroundViewTouched() {
함수 이름은 동사형태로 소문자로 작성해주세요

2022-03-15 03:41 UTC, godrm commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +        self.viewDictionary[rectangle] = rectView
변수 이름에 Dictionary, Array 이런 타입을 그대로 붙이기 보다는 역할을 붙여주세요

2022-03-15 06:55 UTC, Damagucci-Juice commented on DrawingApp/DrawingApp/Plane.swift
> +}
코드를 짜다가 흐름을 놓친것 같습니다. 
수정을 하였는데 

```
PlaneColorChangeDelegate  ->  RectangleColorChangeDelegate
```
이런 식으로 주로 바뀌는 객체를 기준으로 네이밍을 설정하였습니다. 

`바뀌는 객체`를 기준으로 네이밍을 정하는 것이 좋을까요? 
아니면 `델리게이트를 가지고 있는 객체`를 기준으로 정하는 것이 좋을까요?

2022-03-15 07:01 UTC, godrm commented on DrawingApp/DrawingApp/Plane.swift
> +}
좋은 포인트입니다. 그걸 고민해보셔야죠 ㅎㅎ 어떤게 더 말이 되는가 논리적으로 생각해보세요.

2022-03-16 03:11 UTC, Damagucci-Juice commented
추가 6 커밋을 푸쉬하였습니다~

2022-03-16 03:34 UTC, godrm commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +            self.rectangleAndViewContainer.updateValue(view, forKey: rectangle)
스위프트 사전에 값을 바꿀 때는 setValue(_, forKey:)나 updateValue(_, forkey:)` 보다는 subscript를 권장합니다.  
여기서 사용한 메소드는 objective-c 기반의 KeyValue coding 이라는 건데 동작은 하지만 권장하지 않는 방식입니다.

2022-03-16 03:34 UTC, godrm commented
수고하셨습니다. 다음 단계로 갑시다

2022-03-16 03:34 UTC, merged