[ebony] - Step4 addimage
codesquad-members-2022/swift-drawingapp pull request #83
Opened 2022-03-15 10:26 UTC by rising-jun

#### 🧑🏼‍💻 작업 목록
- [x] step3에서 말씀해주신 리뷰내용을 개선해보았습니다. 
- [x] 화면에서 사진을 추가하고,
우측에 선택한 사진 속성을 변경하면 바로 화면에 이미지 투명도가 바뀌도록 구현한다.
- [x] 사진 앨범에서 원하는 사진을 선택할 수 있어야 한다.
- [x] 불러온 사진 데이터는 바이너리 형태로 메모리에서만 관리한다.
- [x] 화면에 추가한 뷰 이외에 사진 데이터만 관리하는 뷰 모델 또는 모델 타입을 선언해야 한다.

#### 💭 학습 키워드
UIImageView, bounds frame

#### 👀 고민과 해결
- 사각형과 이미지를 각각 따로 두고 설계를 하는 고민을 하였습니다.
1. 따로 두기엔 공통되는 속성들, 동작들이 있었습니다.
2. 어떻게 이를 해결하지? 고민하다 이 둘의 공통점, 기능들을 모아둔 상위 클래스를 구현하였고, 이를 상속받도록 구현하였습니다.
- 타입 비교하기.
1. 선택된 뷰가 Photo이면 배경색 변경버튼을 숨기기로 하였습니다.
2. 타입구분을 하여, Photo타입이 아닌경우, 배경색이 항상 뷰에 보여지도록 설정하였습니다. ( 수업내용 참고 )
```swift
private func changeColorButtonIsHidden<T>(customModel: T){
        let photoType: Photo.Type = Photo.self
        photoType == type(of: customModel) ? (colorChangeButton.isHidden = true) : (colorChangeButton.isHidden = false)
    }
```

#### 💡 느낀점
- Protocol의 역할이 생각보다 많고 여러방법으로 사용할 수 있구나 생각하였습니다. ( 추상화, OCP, DI )
- 객체지향에서 객체를 재활용하고, 상위클래스를 구분해 내는 과정(공통되는 속성값들, 기능들을 뽑아내기)을 연습하였고, 이를 활용하여 엄청 편하게 이미지뷰를 추가하였습니다. 추후 다른 뷰를 추가하더라도 많은 코드가 변경되지 않을 것 같습니다.

- 스텝진행이 늦어지더라도, 수업시간에 배운 내용을 미션에 녹여서 구현하는걸 목표로 코드를 작성하였습니다.
감사합니다!!

2022-03-16 03:00 UTC, godrm requested changes
갯수가 많은 것 같지만 관련된 게 있어서 실제로 개선할 사항은 몇 가지 안 될 것 같습니다. 
살펴보시고 일부 구체 타입을 사용하는 부분을 프로토콜만 사용하도록 개선해봅시다!

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/message/CustomEntitiesChangeable.swift
> +    func rectangleCount() -> Int
프로토콜을 나눌 때는 관련 있는 역할에 따라 나누는 것도 좋습니다. 이름도 그것을 유추할 수 있는 포괄적인 표현이면 되구요
다만 Plane 이하 하위 타입들에 대해 표현하기 보다는 Plane이 이걸 어떤 역할로 다루게 되는지 표현하면 가장 좋습니다. 
`CustomEntitiesChangeable` 이름은 나쁘지는 않은데 역할이 드러나지 않고, 그냥 엔티티 타입을 모아놓은 이름 같아서 아쉽습니다.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/CustomViewEntity.swift
> +    private(set) var alpha: Double
이게 최상위 타입으로 선언한 건가 보군요 
지금 미션 DrawingApp 의 도메인이 화면을 처리하는 것이다 보니 Model에 `View` 단어가 들어갈 수 있는 데
이러면 실제 View 역할을 하는 타입과 헷갈릴 수 있습니다. 그래서 타입 이름만으로 어느 역할인지 구분하기 쉽도록 규칙을 정해주는 게 중요합니다.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/CustomViewFactory.swift
>      }
특히 `CustomViewFactory`만 보면 모델의 팩토리가 아니라 뷰 객체 인스턴스를 생성하는 팩토리처럼 읽혀집니다.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Photo.swift
> +    }
getRandomPhoto() 이 부분은 잘 모르겠습니다. 객체가 자기 자신을 return 할 일이 있나요?

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/PhotoPickerDelegate.swift
> +    }
오.. 델리게이트 객체를 따로 구현했네요. 좋은 접근입니다. 꼭 이미지 픽커 컨트롤러가 이걸 처리할 필요는 없죠. 
다만 PhotoPickerDelegate를 생성하고 소유하는 객체 관리 코드가 어떤지 궁금해지네요. 시도는 좋습니다.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/PhotoPickerDelegate.swift
> +    func photoCallBack(photo: UIImage)
노티피케이션이 있는데 PhotoCallBack 프로토콜의 의도는 잘 모르겠습니다

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        return models[point]
이 부분에서 `models: [ViewPoint: CustomViewEntity]`에 대해서 잘 모르겠습니다.
좌표마다 모델을 기록해놔야 하는 이유가 있나요? 터치한 좌표로 이걸 찾으려면 모든 좌표마다 객체가 있는건가요?

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        self.customViewModelFactory = rectangleFactory
팩토리를 의존성 주입해주는 방식은 좋습니다 👍

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        let photoMutable = customViewModelFactory.randomPhoto(imageData: imageData)
`randomPhoto(imageData: imageData)` 이 메소드 이름은 랜덤으로 사진을 골라주는 것 같은 이름이네요.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        let rgbValue = colorMuatble.getRandomColorRGb()
`colorMuatble.getRandomColorRGb()`를 거치는 이유는 모르겠습니다. 그냥 colorMuatble를 사용하면 안되나요? 
그리고보니 getRandomRectangle(), getRandomPhoto() 모두 그렇게 처리하고 있군요
생성한 걸 그냥 넣어도 되지 않을까요?

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        }
이 부분도 구체타입으로 casting 해보기 보다는 프로토콜로 확인해보세요

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        self.selectedModel = models[point]
터치한 좌표가 다를 텐데 여기서 모든 게 확인이 가능한가요? 
설마 터치한 좌표 대신에 뷰에서 origin을 찾아서 넘겨주나요? 
만약 그렇다면 뷰의 속성에 의존하도록 코어 로직을 구현한 셈이네요. 터치한 값은 입력한 값이지만, 그걸로 뷰의 속성을 가져오는 것은 입력 처리에서 로직이 들어간 겁니다. 만약 그걸 판단하더라도 모델에서 핵심적인 값을 판단하셔야 합니다.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        minusAlpha()
이 함수는 소문자가 아니네요. 소문자로 동사형태가 좋겠습니다.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Plane.swift
> +        }
어디는 Notification 정보다 위에 선언되어 있고, 어디는 하단에 선언되어 있네요. 이것도 위치를 일치시켜서 일관성있게 작성해주세요

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/model/Rectangle.swift
>      }
위에도 언급했지만 이게 구체 타입을 넘겨주기 위한 거라면 이런 메소드를 지양하세요

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +    private var customViews: [String: CustomBaseView] = [:]
customViews 뷰를 찾는 map이라면 String (아마도 Id 값인듯) 이렇게 두기 보다는 모델 타입 인스턴스 자체를 키로 활용해보세요. 그것도 중요한 포인트입니다. 하위 속성을 가져오려고 하지 말고 타입 자체를 비교하세요

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        notificationCenter.addObserver(self, selector: #selector(getImageFromDevice), name: PhotoPickerDelegate.Notification.Event.getPhotoFromDevice, object: photoPickerDelegate)
아마 여기 선언한 노티피케이션도 입력 흐름도 있고, 출력 흐름도 있을텐데 여기 추가하는 부분이나 아래 구현하는 부분 모두 역할별로 구분해보세요

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
>      @objc private func addRectangleView(_ notification: Notification){
addRectangleView 이름은 여기서 RectangleView를 add 할 것처럼 보이네요. 
이벤트를 받아서 처리하는 경우는 이름을 구분해보세요.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        guard let rectangle = notification.userInfo?[Plane.Notification.Key.rectangle] as? Rectangle else {
노티를 받아서 변환할 때도 Rectangle 구체 타입이 아니라 필요한 프로토콜로 캐스팅해보세요.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
>          rectangleView.addGestureRecognizer(viewTapGesture)
뷰를 생성하는 부분이 다양해질텐데 뷰도 팩토리를 구현해보면 어떨까요?

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
>          let point = ViewPoint(x: Int(touchedView.frame.origin.x), y: Int(touchedView.frame.origin.y))
그렇군요 터치한 뷰의 origin을 활용하는 군요. 이러면 터치한 뷰를 찾는 로직이 뷰를 활용하기 때문에 여기에 의존하게 됩니다.
터치한 좌표가 어떤 사각형인지, 무시할 것인지, 처리할 것인지 그런 구체적인 비즈니스 로직은 모델에서 처리하는 게 좋습니다. 
전달 과정에서 값을 바꿔버리면 모델에서 역할이 단순해지지만, 하위 로직이 상위 로직에 영향을 받게 됩니다.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/SplitViewController.swift
>          viewControllers = [propertySetViewController, drawingViewController]
여기서 의존성을 주입해주는 게 좋은 시도네요.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/SplitViewController.swift
> +        NotificationCenter.default.post(name: SplitViewController.Notification.Event.updateSelectedPhotoUI, object: self, userInfo: [SplitViewController.Notification.Key.photo : photo])
지금 여기서는 DrawingDelegate로 델리게이트와 NotificationCenter가 모두 사용되고 있는데,
drawingViewDidSelectedPhoto를 호출하는 곳에서 직접 Notification을 보내는 방법도 고려해보세요.
여기를 꼭 거쳐가지 않아도 될 것 같습니다.

2022-03-16 03:00 UTC, godrm commented on DrawingApp/DrawingApp/view/PropertySetViewController.swift
> +    }
어떤 역할인지는 알겠고, 제네릭과 메타타입을 활용해서 잘 구현하셨네요. 
다만 Photo.self 구체 타입을 활용한 부분이 아쉽습니다. Color 속성에 접근하지 못하는 거라면 해당 역할이 있는지 없는지 프로토콜로도 판단할 수 있습니다. 그 부분을 고려해보세요

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/message/CustomEntitiesChangeable.swift
> +    func rectangleCount() -> Int
넵 프로토콜명 더 고민해보겠습니다!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/CustomViewEntity.swift
> +    private(set) var alpha: Double
넵 고민해보겠습니다!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/CustomViewFactory.swift
>      }
이부분도 개선해보겠습니다!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/Photo.swift
> +    }
구체타입이 아닌 프로토콜로 값을 활용하는 개념이 아직 익숙하지 않아 더 연습해봐야 할 것 같습니다 ㅜㅜ

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/PhotoPickerDelegate.swift
> +    }
DrawingViewController가 관리하고(present 메소드를 사용해야 하기 때문) 이 delegate객체에서의 이벤트는 DrawingViewController에서 수신한 후 plane에 가져온 이미지와 함께 photo객체 생성 요청을 합니다!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/PhotoPickerDelegate.swift
> +    func photoCallBack(photo: UIImage)
노티피케이션 전에 구현했던 코드인데, 잊고 삭제를 안했습니다!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/Plane.swift
> +        let photoMutable = customViewModelFactory.randomPhoto(imageData: imageData)
이부분도 개선해보겠습니다!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/Plane.swift
> +        let rgbValue = colorMuatble.getRandomColorRGb()
아하! 말씀하신 방법대로 개선해보겠습니다!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/Plane.swift
> +        }
넵!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/Plane.swift
> +        minusAlpha()
앗 넵 실수했습니다..😂

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/Plane.swift
> +        }
넵!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/model/Rectangle.swift
>      }
넵!

2022-03-16 03:35 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +    private var customViews: [String: CustomBaseView] = [:]
key값으로 id가 아닌 "인스턴스 자체"를 활용해보겠습니다!

2022-03-16 03:36 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        notificationCenter.addObserver(self, selector: #selector(getImageFromDevice), name: PhotoPickerDelegate.Notification.Event.getPhotoFromDevice, object: photoPickerDelegate)
넵 구분해보겠습니당!

2022-03-16 03:36 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
>      @objc private func addRectangleView(_ notification: Notification){
넵 개선해보겠습니다!

2022-03-16 03:36 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        guard let rectangle = notification.userInfo?[Plane.Notification.Key.rectangle] as? Rectangle else {
넵!

2022-03-16 03:36 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
>          rectangleView.addGestureRecognizer(viewTapGesture)
오호! 넵, 뷰 팩토리도 시도해보겠습니다!

2022-03-16 03:36 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
>          let point = ViewPoint(x: Int(touchedView.frame.origin.x), y: Int(touchedView.frame.origin.y))
넵 고민해보고 개선해보겠습니다!

2022-03-16 03:36 UTC, rising-jun commented on DrawingApp/DrawingApp/view/SplitViewController.swift
> +        NotificationCenter.default.post(name: SplitViewController.Notification.Event.updateSelectedPhotoUI, object: self, userInfo: [SplitViewController.Notification.Key.photo : photo])
넵 개선해보겠습니다!

2022-03-16 03:36 UTC, rising-jun commented on DrawingApp/DrawingApp/view/PropertySetViewController.swift
> +    }
넵 고민해보겠습니다!

2022-03-16 14:19 UTC, rising-jun commented
말씀하신 리뷰내용들을 개선하였습니다. 리뷰 항상 감사합니다! @godrm 
💁 작업내용
1. 구체타입을 사용하지 않고 프로토콜값을 사용하였습니다. ( userInfo에서 가져오는 부분만 구체타입 사용)
2. 터치 좌표가 origin에 의존하지 않도록 변경하였습니다.
3. DrawingViewController에서 customViews의 key값 이 모델이 되도록 변경하였습니다.( Hashable )
4. Plane이 채택하던 프로토콜을 역할별로 분리해보았습니다. ( iSP )
5. 구체타입을 key값 설정 외에 사용하지 않도록 하기위해 guard let -> if let으로 변경하였습니다.

느낀점 
1. 프로토콜이 이전에 알았던 활용방법보다 훨씬 많이 사용할 수 있고, 이를 통해 OCP를 개선할 수 있구나.

2022-03-17 08:09 UTC, godrm approved these changes
수고하셨습니다.

2022-03-17 08:09 UTC, godrm commented on DrawingApp/DrawingApp/model/CustomViewModelFactory.swift
> +    }
어떤 의도인지는 알겠습니다만 이건 좀 억지(?)로 만든 타입 같은데요. 왜냐하면 재사용할 가능성이 별로 없어보여요
저라면 이런 타입을 만들기보다는 각각의 관련된 타입에 따로 프로토콜을 채택하도록 확장하는 방법을 고려했을 것 같습니다

2022-03-17 08:09 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        notificationCenter.addObserver(self, selector: #selector(getImageFromDevice), name: PhotoPickerDelegate.Notification.Event.getPhotoFromDevice, object: photoPickerDelegate)
photoPickerDelegate 델리게이트 객체가 보내는 노티를 받는 것은 조금 어색하네요.
보통 델리게이트는 델리게이트한데 뭔가 알려주거나 물어오는 구조라서, 이렇게 노티를 받겠다는 의미는 역할이 잘못 나눠진 건 아닌가 싶습니다.

2022-03-17 08:09 UTC, godrm commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        NotificationCenter.default.post(name: DrawingViewController.Notification.Event.alphaButtonHidden, object: self, userInfo: [DrawingViewController.Notification.Key.customViewModel : rectangleVi
이 부분은 좀 이상해요. `DrawingViewController.Notification.Event.changedColorText` 나 `.alphaButtonHidden`는 여기서 이벤트를 보낼 게 아닌 것 같은데요?
addRectangleViewToSubView() 이거 받는 것처럼 같은걸 어딘가에서 처리하면 되지 않을까요?

2022-03-17 08:09 UTC, merged

2022-03-17 08:13 UTC, rising-jun commented on DrawingApp/DrawingApp/model/CustomViewModelFactory.swift
> +    }
넵 개선해보겠습니다!

2022-03-17 08:14 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        notificationCenter.addObserver(self, selector: #selector(getImageFromDevice), name: PhotoPickerDelegate.Notification.Event.getPhotoFromDevice, object: photoPickerDelegate)
개선해보겠습니다!

2022-03-17 08:14 UTC, rising-jun commented on DrawingApp/DrawingApp/view/DrawingViewController.swift
> +        NotificationCenter.default.post(name: DrawingViewController.Notification.Event.alphaButtonHidden, object: self, userInfo: [DrawingViewController.Notification.Key.customViewModel : rectangleVi
고민해보겠습니다!