[Beck] Step4 - Add Photo
codesquad-members-2022/swift-drawingapp pull request #84
Opened 2022-03-15 10:59 UTC by SangHwi-Back

# 사진 추가하기 기능 추가(완료: 2022.03.15 19:30)

## 기능 설명

* Add 버튼 옆에 Photo 버튼을 추가하여 사진을 배경이미지로 가지는 뷰를 생성할 수 있게 되었습니다.
* 사진은 사진 앱을 통해 가져오고 메인 뷰가 시작될 때 권한 설정에 대해 물어봅니다.
* 권한 설정이 되어 있지 않을 경우 Photo 버튼은 사용할 수 없습니다.

## 구현 방법

hasViewProperty 라는 프로퍼티를 Model 객체에 추가하였습니다.

Plane의 `addRectangle(with:Any?=nil)`에서 전달받게 되면 그것이 뷰와 관련이 있건 없건 간에 뷰와 관련된 프로퍼티가 있다는 표시를 hasViewProperty를 true로 처리합니다.

MainScreenViewController는 Plane에서 알림이 오게 되면 hasViewProperty가 참인지 확인하여 참일 경우는 이미지 뷰를 추가하여 이미지를 적용하려 합니다. 그렇지 않다면 배경색상을 적용합니다.

모든 기능은 동일하지만, 무작위 색상을 설정할 경우도 모델의 hasViewProperty 프로퍼티를 확인하여 참일 경우는 버튼이 아무 작동도 하지 않게 처리하였습니다.

## hasViewProperty는 모델을 제외한 모든 객체에 닫혀 있어야 할까 고민해 보았습니다.

hasViewProperty는 모델이라는 생각으로 작업을 진행하였습니다. 하지만, Xcode 에서 hasViewProperty가 사용된 부분을 검색해보면 실제 사각형들이 나타나는 MainScreenViewController에서만 호출합니다.

결국 뷰 컨트롤러가 한번 쯤 뷰 생성에 관여하는 모델 데이터를 검증하는 과정이 필요하다고 느꼈지만, 지금까지 계속 MVC 구조를 제대로 나누지 못한 것 때문에 고민을 덜 한 것은 아닌지 고민입니다.

2022-03-15 11:02 UTC, SangHwi-Back commented
안녕하십니까 JK. PR 요청 후 코멘트를 일부 수정하였습니다.

수정을 진행하였습니다. 검토 후 머지 혹은 추가 수정 사항에 대한 확인 부탁드립니다.

오늘 하루도 고생 많으셨습니다. 감사합니다.

2022-03-16 03:33 UTC, godrm requested changes
본문에서 우려했던 내용을 살펴봤습니다. 
사진 처리를 위해서 기존 로직에 꽤 많은 영향이 있었네요.
다음 내용을 살펴보시고 개선해봅시다. 다른 타입을 만드는 것부터 시작해보면 어떨까 합니다

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Models/FactoryRectangleProperty.swift
> +            hasViewProperty: hasViewProperty
언급한 hasViewProperty 라는게 어떤 의도인지 좀 더 살펴보고 의견을 남기겠습니다. 
일단 여기에 추가된 것으로 보면 살짝 불안합니다 ㅎㅎ

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +    private var sceneRect: RectangleRect!
이번 미션이 그림을 그리는 앱이다보니 핵심 로직에서도 화면 구성요소를 표현하는 단어가 많아지는 게 당연한 것 같습니다. 모델로 사용하는 `RectangleRect` 도 `사각형사각` 같은 느낌이라 어색합니다. 
이전 PR에서도 타입 이름에 대한 피드백이 많았던 것 같은데, 뷰와 모델이 서로 연관되어 있지만 이름으로 혼란을 주지 않도록 표현하는 것은 중요하니까 다른 사람들이 읽고 혼란스러워하지 않을까 항상 객관적으로 표현해보려고 노력해주세요

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +    func addRectangle(with viewProperty: Any? = nil) {
`viewProperty: Any? = nil` 이 부분은 모든 타입이 올 수 있고 심지어 Any? 이라서 nil도 될 수 있네요
들어올 수 있는 값이 엄청 광범위한데 실제로 구체 타입에 추가적인 속성을 넣으려는 것처럼 보이네요. 
사각형을 추가하는 데 이게 어떤 의도인지 아직도 잘 모르겠습니다. 아래를 더 살펴볼게요

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +        guard let rectangleModel = factory.makeRandomRectangleModel(as: "Subview #\(rectangleModels.count)", rect: sceneRect, hasViewProperty: (viewProperty != nil)) else {
음.. 생성할 때는 viewProperty가 nil인지 아닌지만 보는군요. 그 값을 쓰는 게 아니라니 조금 더 혼란스럽습니다 ㅎㅎ

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +        ] as [Plane.PostKey : Any]
타입 선언과 함께 값을 선언한다면 as로 변환해주기 보다는 `var notificationInfo : [Plane.PostKey : Any] = []` 형태가 더 좋습니다. as는 좀 다른 의미가 됩니다.

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +            notificationInfo.updateValue(viewProperty, forKey: PostKey.viewProperty)
스위프트 사전에 값을 바꿀 때는 `setValue(_, forKey:)`나 updateValue(_, forkey:)` 보다는 subscript를 권장합니다.
여기서 사용한 메소드는 objective-c 기반의 KeyValue coding 이라는 건데 동작은 하지만 권장하지 않는 방식입니다. 
결과적으로는 상위에서 넘겨주는 viewProperty를 noti에 담아서 보내려는 의도인가 보네요. 이러면 또 이걸 받는 부분도 살펴봐야 할 것 같습니다. 
여기까지만 봐도 viewProperty 단지 한 곳이 아니라 여러 곳에 영항을 주는 것 같은데 필요한 값을 context 처럼 전달해주려는 의도라면 괜찮을 수도 있는데, 꼭 필요한지는 옵저버 코드도 살펴봐야 할 것 같네요. 
마치 입력에서 출력까지 어떤 값을 전달하는 모양이네요

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +            noti.userInfo = nil
didSelect()는 이걸 호출하는 메소드가 아니라 주석처럼 델리게이트에서 호출해주는 콜백인거죠?
그럼 매개변수 index는 상위에서 전달해주는 데 plane 내부의 index와 같다는 보장이 얼마나 있을까요? -1이나 엄청 큰 값이 들어올 수도 있을 것 같네요

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Models/RectangleProperty.swift
> +        self.hasViewProperty = hasViewProperty
실제로 값을 가지지 않고 Bool 타입만 있는 게 어떤 의미가 있는지 모르겠습니다.

2022-03-16 03:33 UTC, godrm commented on DrawingApp/DrawingApp/Views/MainScreenViewController.swift
>          view.addSubview(rect)
아.. 사용하는 곳을 보니 알겠네요. Image를 입력 흐름에 넣어서 출력 흐름에 꺼내서 뷰를 생성하네요.
이걸 보니 입력 / 출력 흐름이 분리되어 있지 않은 것고 강하게 결합된 것 같습니다
그리고 데이터 추상화 관점에서도 이미지 데이터를 모델에서 보관하지 않기 때문에 핵심 로직이 이미지를 갖고 있지 않습니다. 
핵심 로직이 있는 모델만 놓고서도 동작이 완벽하게 처리가 되야 합니다. 뷰와 분리해서 모델만으로 테스트 가능하고, 저장도 되야하는거죠. 지금 흐름 상으로는 모델만으로는 Photo 라는 타입을 다룰 방법이 없습니다.
하위 모델이 RectangleProperty 하나 뿐인건가요? 역할 마다 작은 다른 타입을 만드는 건 이상한게 아닙니다. 따로 선언해보면 어떨까요?

2022-03-16 04:28 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Models/Plane.swift
> +    private var sceneRect: RectangleRect!
넵 알겠습니다. 이 타입을 처음 보는 사람이 있다고 가정하고 다시 생각해보겠습니다.

2022-03-16 04:33 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Models/Plane.swift
> +        guard let rectangleModel = factory.makeRandomRectangleModel(as: "Subview #\(rectangleModels.count)", rect: sceneRect, hasViewProperty: (viewProperty != nil)) else {
단순히 뷰 컨트롤러에서 프로퍼티를 전달하는 상황과 그렇지 않은 상황에서 `addRectangle()`이라는 메소드를 사용할 수 있도록 하려고 한건데 프로퍼티가 너무 말도 안되는 것이 되어버리고 말았습니다.

지금의 상황에서 viewProperty는 PHPickerViewController를 호출하여 생성된 애셋 이미지만을 의미하고 있으니, 의도가 좀 더 명확히 보이는 인터페이스 역할을 하는 메소드를 생성하도록 하겠습니다.

2022-03-16 04:40 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Models/Plane.swift
> +        ] as [Plane.PostKey : Any]
as는 하위 타입으로 변환한다는 의미이고 `var notificationInfo: [Plane.PostKey: Any] = []`는 타입 캐스팅이라는 의미이군요.. [AnyHashable: Any]의 의미와는 많이 다른 것 같습니다. 수정하도록 하겠습니다.

2022-03-16 04:43 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Models/Plane.swift
> +            notificationInfo.updateValue(viewProperty, forKey: PostKey.viewProperty)
viewProperty가 `MainViewController` -> `Plane` -> `MainScreenViewController` 로 전달되고 있습니다.

`MainViewController` -> `Plane`, `Plane` -> `MainScreenViewController` 두 개를 이용해서 구조 내 요소들이 가지는 결합을 더 느슨하게 만들어보겠습니다.
넓게 보지 못하는 습관이 또 이상한 코드를 만들었던 것 같습니다.

2022-03-16 04:45 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Models/Plane.swift
> +            noti.userInfo = nil
넵 알겠습니다. 애플리케이션 구조 내 각 요소들 중 validation할 수 있는 요소들이 있는지 더 찾아보도록 하겠습니다.

2022-03-16 04:45 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Models/RectangleProperty.swift
> +        self.hasViewProperty = hasViewProperty
hasViewProperty 를 제외하고도 과제의 기능을 구현할 수 있을 것 같습니다.

다시 시도해보고 PR 드릴 수 있도록 하겠습니다!

2022-03-16 04:46 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Views/MainScreenViewController.swift
>          view.addSubview(rect)
로직을 모델에 분리한다.....

이번 수정 및 다음 스텝에서도 유의하도록 하겠습니다.

2022-03-16 06:54 UTC, SangHwi-Back commented
안녕하세요 JK. 말씀해주신대로 `let viewProperty: Any?`로 처리되었던 부분을 Data 객체로 처리될 수 있게 타입을 변경하였습니다. MainViewController에서 addRectangle()에 다른 데이터를 전달해서 뷰를 만들고 싶을 경우, 그 데이터에 따라 인터페이스를 만들어주면 되도록 함수들을 분리해보았습니다.

이를 통해 `var hasViewProperty: Bool`가 사라지면서 애플리케이션 요소 간 결합력이 느슨해지는 효과가 있었습니다.

그 외에 네이밍 등 지적해주신 부분을 수정했사오니 확인을 부탁드리겠습니다. 감사합니다.

2022-03-16 08:09 UTC, godrm commented on DrawingApp/DrawingApp/Models/FactoryRectangleProperty.swift
>          )
생성자가 통합되어서 추상 데이터 타입처럼 동작하는 것 같습니다
이 부분에 대한 피드백은 단지 hasViewProperty 사용하느냐가 아니라, 
hasViewProperty를 넘기는 걸로 Rectangle와 Photo를 둘 다 하나의 데이터 구조로 처리하고 있다는 부분입니다.
포함하는 하위 속성이 다르면 서로 다른 타입으로 분리해서 단일 책임을 지키고, 다형성으로 각각의 동작을 하도록 나눠보라는 겁니다.
기존에 Rectangle에 대한 속성을 다루는 타입이 있으면 그것은 그대로 두고, 새로운 타입을 추가하는 거죠. 그래야 변경에 닫혀있고 확장에 열려있는거니까요. 기존꺼를 자꾸 바꿀꺼면 기존 코드를 사용하는 부분까지 영향을 주게되고 거의 모든 곳을 수정해야 할테니까요.

2022-03-16 08:13 UTC, godrm commented
어떤 타입 A를 만들고, 비슷한 타입 B를 만들어야 하는데 A에 속성을 추가해서 이럴때는 A처럼, 저럴때는 B처럼 쓰기 보다는
공통적인 부분을 찾아내서 C를 수퍼 클래스 또는 프로토콜로 선언하고, A와 B를 C에서 확장해서 만들 수 있는 것을 시도해보세요
지금은 기존 타입을 바꾸고 있기 때문에 객체지향이 아니라 데이터 중심 프로그래밍을 하고 있는 셈입니다. 
별개 타입을 만들고 공통 부분을 추상화하고 다른 부분은 다형성으로 동작하도록 시도해보세요. 그건 꼭 해보셔야 할 것 같아요!

2022-03-16 09:02 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Models/FactoryRectangleProperty.swift
>          )
사각형은 `배경색이 있는 사각형`, `배경 사진이 있는 사각형`의 타입으로 나누고 이들은 공통 슈퍼 클래스를 상속받으면서
슈퍼 클래스는 `인덱싱이 가능한 객체`라는 의미를 가진 프로토콜로 구현해보도록 하겠습니다.

각 사각형 클래스는 SRP를 따르고 모델 역할인 Plane은 관리하는 모델 데이터 배열이 LSP에 의해 한 곳에서 관리될 수 있도록 해 보도록 하겠습니다.

시간이 좀 걸릴수도 있겠지만 잘 구현해서 다시 확인 요청드리도록 하겠습니다. 감사합니다.

2022-03-16 13:43 UTC, SangHwi-Back commented
말씀해주신대로 타입을 확장할 수 있게 각각 타입별 확장을 시도하였습니다.

사각형 뷰의 모델인 `RectangleProperty` 클래스는 이제 모든 모델을 대표하고 하위 타입들의 슈퍼 클래스로만 역할합니다.
`RectangleProperty`의 하위 클래스로는 `ColoredRectangleProperty`, `ImageRectangleProperty`가 있습니다.

사각형 뷰를 뜻하는 `Rectangle` 클래스는 위의 모델처럼 모든 사각형 뷰를 대표하고 슈퍼 클래스 역할만 합니다.
`Rectangle`도 위와 비슷한 네이밍으로 `ColoredRectangle`, `ImageRectangle` 하위 클래스가 있습니다.

배경색이 있는 경우는 Colored~, 배경이미지가 있는 경우는 Image~ 접두어를 갖습니다.

2022-03-17 08:13 UTC, godrm commented on DrawingApp/DrawingApp/Views/MainScreenViewController.swift
> +        }
결국 타입을 생성하는 부분에서는 구체 타입을 알아야 하는데요
그게 뷰 컨트롤러야만 하는 것인가는 고민스러운 부분입니다.
그래서 저는 구체 타입을 알고 생성하는 팩토리가 있는 게 장점이라고 생각하거든요
뷰를 생성할 때도 이렇게 switch-case를 두고 구분하기 보다는 타입이 늘어나도 코드 변경 없이 뷰를 생성할 수 있으면 가장 좋습니다. 한 번 고민해보세요

2022-03-17 08:13 UTC, godrm commented
수고하셨습니다.

2022-03-17 08:13 UTC, merged

2022-03-17 09:41 UTC, SangHwi-Back commented on DrawingApp/DrawingApp/Views/MainScreenViewController.swift
> +        }
아하... 맨 마지막에 이런 흠을.... 다음 머지때 수정사항을 추가하도록 하겠습니다. 감사합니다.