[푸코] Step06 - 위치 / 크기 조정 요소 추가
codesquad-members-2022/swift-drawingapp pull request #93
Opened 2022-03-16 09:00 UTC by wnsxor1993

## 결과 화면
![화면 기록 2022-03-16 오후 5 42 49](https://user-images.githubusercontent.com/44107696/158551824-0964f587-9a1c-4bd9-a544-10d2d24528d3.gif)

## 작업 목록
* 리팩토링
- [x] Drag 시, ExtraView copy 로직 변경
- [x] Drag 범위 제한 설정
- [x] 하위 모델에도 Notification 적용

* 신규 작업
- [x] 위치 / 크기 관련 Stepper, Label 추가
    - [x] Stepper 관련 Delegate 구현 
    - [x] Stepper value changed action 딜리게이트로 전달
    - [x] Tap 및 Drag에 따른 value change 연동

## 학습 키워드
1. UIStepper
2. NSCopying (copy with zone)

## 고민과 해결
- 처음에는 Plane보다 하위의 모델에까지 Notification을 연결시키는 게 좋을지 고민이 되었습니다. 하지만 이를 활용하지 않다보니 VC에서 모델의 수정을 지시한 후, 제대로 변경이 되었는지 알 지 못 한채 View를 수정하는 메서드를 호출하는 식이 되어 MVC의 형태와는 다소 달라진 것 같다는 생각이 들었습니다.
때문에 전체적으로 Model의 값 변경이 호출될 경우 하위 모델이라도 Notification을 연결시켜 올바른 변화에 따라 View의 출력 기능이 호출될 수 있도록 수정하였습니다.

2022-03-17 08:24 UTC, godrm requested changes
몇 가지 수정해야 하는 사항들을 남겨봤습니다. 확인해보고 개선해보세요

2022-03-17 08:24 UTC, godrm commented on DrawingApp/Model/Values/RectValue.swift
> +        NotificationCenter.default.post(name: RectValue.NotificationName.changeAlpha, object: self)
이런 게 고민스러운 부분인데요. 하위 타입들이 있을 때 모든 타입들이 다 자신의 값이 바뀐 것을 노티하거나 알려야 하는 것인가
옵저버라는 것을 어느 수준까지 할 것인가 말이죠. 장단점이 있습니다. 
RectValue 같은 타입을 struct - let 으로 값 타입으로 선언하다고 생각해보세요. 그럼 노티조차 필요없을 수도 있습니다. 
RectValue 자체가 바뀌었다는 것을 알려주기만 하면 되니까요 그래서 타입과 감지를 같이 고민해보는 게 좋습니다.

2022-03-17 08:24 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +    }
이런 건 plane.selectedValue가 바뀔때마다 지우고 다시 추가하고 그래야 하려나요?

2022-03-17 08:24 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +    }
이런 건 plane.selectedValue가 바뀔때마다 지우고 다시 추가하고 그래야 하려나요?

2022-03-17 08:24 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        rectValue.changePoint(point: newPoint)
이 부분도 plane에게 속성을 가져오지 않고, plane에 바뀔 포인트를 전달해줘도 되지 않을까요?

2022-03-17 08:24 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        rectValue.changePoint(point: newPoint)
이 부분도 plane에게 속성을 가져오지 않고, plane에 바뀔 포인트를 전달해줘도 되지 않을까요?

2022-03-17 08:24 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        rightAttributerView.changeStepperValue()
이 부분은 아마도 Stepper 값이 바뀌면 호출되는 입력 흐름 같은데, 
rightAttributerView.changeStepperValue()는 출력 흐름 아닌가요?

2022-03-17 08:24 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
> +        rightAttributerView.changeStepperValue()
이 부분은 아마도 Stepper 값이 바뀌면 호출되는 입력 흐름 같은데, 
rightAttributerView.changeStepperValue()는 출력 흐름 아닌가요?

2022-03-17 08:24 UTC, godrm commented on DrawingApp/View/UIView.swift
> +    }
이런 메소드가 UIView에 있어야 하는지 모르겠습니다. 
RectangleView나 ImageView가 이미 copy를 구현했다면 그냥 self.copy() 형태로 다형성으로 동작하도록 호출하면 되는게 아닐까요?

2022-03-17 08:24 UTC, godrm commented on DrawingApp/View/UIView.swift
> +    }
이런 메소드가 UIView에 있어야 하는지 모르겠습니다. 
RectangleView나 ImageView가 이미 copy를 구현했다면 그냥 self.copy() 형태로 다형성으로 동작하도록 호출하면 되는게 아닐까요?

2022-03-17 15:29 UTC, wnsxor1993 commented on DrawingApp/Model/Values/RectValue.swift
> +        NotificationCenter.default.post(name: RectValue.NotificationName.changeAlpha, object: self)
말씀하신 부분을 고민하던 중, Plane이 이미 선택된 RectValue를 가지고 있는데 굳이 VC에서 이를 꺼내서 작업을 할 필요가 없다는 점을 알게 되었습니다. 각 하위 모델에서의 수정 메서드 호출은 Plane에서 관리하고 이런 수정이 이루어지면 Plane 인스턴스 자체에서 노티하는 방식으로 충분히 작업 가능하여 이러한 형태로 수정해보고자 합니다.
아래에서 말씀하신 사항들도 이를 토대로 다듬어보겠습니다.

노티를 하지 않고 모델의 데이터가 변경된 것을 감지하는 방식에 대해서는 조금 더 알아보고 이후에 활용할 수 있도록 노력해보겠습니다!

2022-03-17 15:29 UTC, wnsxor1993 commented on DrawingApp/View/UIView.swift
> +    }
UIView의 상위에서 NSObject를 상속하며 convenience 메서드인 copy()를 호출할 수 있고, 이를 호출하면 NSObject를 상속받고 있는 모든 개체에 대해 NSZone을 통해 copy(width:)를 호출한다는 원리를 확실하게 이해하지 못 한 채 사용하여 위와 같은 구현 형태를 작성하였습니다.
이 부분은 수정하도록 하겠습니다.

2022-03-17 15:31 UTC, wnsxor1993 commented
말씀하신 부분들을 중점에 두고 수정 진행하였습니다. 올바른 방향으로 개선한 것인지 확인 부탁드리겠습니다^^

2022-03-18 03:20 UTC, godrm approved these changes
개선이 잘 된 것 같습니다. 소소한 의견을 남겨봤습니다. 
수고하셨습니다

2022-03-18 03:20 UTC, godrm commented on DrawingApp/Model/Values/RectValue.swift
> +        NotificationCenter.default.post(name: RectValue.NotificationName.changeAlpha, object: self)
이런 게 고민스러운 부분인데요. 하위 타입들이 있을 때 모든 타입들이 다 자신의 값이 바뀐 것을 노티하거나 알려야 하는 것인가
옵저버라는 것을 어느 수준까지 할 것인가 말이죠. 장단점이 있습니다. 
RectValue 같은 타입을 struct - let 으로 값 타입으로 선언하다고 생각해보세요. 그럼 노티조차 필요없을 수도 있습니다. 
그래서 타입과 감지를 같이 고민해보는 게 좋습니다.

2022-03-18 03:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
>              os_log("Can't copy CustomView")
위에서 guard let 으로 바인딩을 했으면 panGestureExtraView는 항상 값이 있다고 보장이 되지 않을까요?

2022-03-18 03:20 UTC, godrm commented on DrawingApp/VC/MainViewController.swift
>      }
changeRectValuePoint 랑 changeRectValuePoint 가 거의 같음 메소드인데
하나는 매개변수가 없고, 하나는 extraView가 지정되는 방식이네요. 
두 개가 약간 중복처럼 보이기도 하네요. 좌표만 넘겨도 되는건 아닐까요?

2022-03-18 03:20 UTC, merged

2022-03-18 05:08 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
>              os_log("Can't copy CustomView")
panGestureExtraView에 할당된 UIView나 copy에 할당되어 있는 UIView나 동일한 객체이니, 아래의 사족 없이 copy 그대로 서브뷰에 추가하면 될 것 같습니다!

2022-03-18 05:09 UTC, wnsxor1993 commented on DrawingApp/VC/MainViewController.swift
>      }
이 부분은 UIView를 옵셔널 인자로 받아와서 값이 있을 경우와 없을 경우로 구분해서 수정 point를 인자로 넘기는 방향으로 접근해보고자 합니다