[Eddy] Step 8: 레이어 목록 표시 & 조작 기능
codesquad-members-2022/swift-drawingapp pull request #94
Opened 2022-03-16 12:15 UTC by BumgeunSong

## Screenshot

2022-03-16 13:08 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +    }
NotificationCenter가 observe보다 subscribe/publish라는 점을 고려해서 메서드 명을 수정했고, 메서드만 보고도 '누구'의 '무엇'을 구독하는지 알 수 있게 했습니다.

2022-03-16 13:09 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +    var didCommandMoveHandler: ((Layer, Plane.reorderCommand) -> ())?
클로저의 프로퍼티명은 did+명사+동사로 통일했고, 선언부는 상단에 모아주었습니다.

2022-03-16 13:10 UTC, BumgeunSong commented on DrawingApp/DrawingApp/View/ViewFactory.swift
> +    }
타입에 맞는 UIImage를 생성하는 코드을 어디로 배치할까 하다가 ViewFactory가 가장 관련성이 높은 거 같아 ViewFactory에 넣었습니다.

2022-03-16 13:13 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +    private var layers: [Layer] = []
테이블 뷰 컨트롤러가 Plane의 layer와 동기화되는 상태 변수를 갖고 있습니다. 

사실 Single source of truth를 유지하고 버그를 막기 위해서, 상태 변수를 없애고 Plane에서 데이터 전체를 계속 받아오는 방식도 고민해보았습니다. 

하지만 tableView의 Datasource 안에서 참조를 하기 위해서는 인스턴스 변수 형태가 필요하다는 점을 깨닫고 상태 변수로 두었습니다.

2022-03-16 13:15 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +        tableView.deselectRow(at: indexPath, animated: false)
유저 입력을 처리하는 부분에서는 didSelectRow 메서드가 호출은 되지만, select는 다시 deselect해서 뷰를 조작하지 않도록 막았습니다. 출력 흐름에서 view를 업데이트하도록 분리하고 싶었습니다.

2022-03-16 13:18 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/PanelViewController.swift
> +    }
NC를 사용할 때와 다르게 Closure로 연결시 클로저를 넘겨주기 위해 다른 VC를 알아야 했습니다. ContainerVC의 메서드를 사용해 다른 VC를 불러왔습니다.

2022-03-16 13:21 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/LayerFactory.swift
> +        // Common property to initialize Layer
새롭게 추가된 title 프로퍼티의 경우 ("Rect 1" / "Photo 3") 생성 책임을 가급적 Factory에 모으고 싶었습니다. 

하지만 타이틀에 붙일 번호는 Plane이 가지고 있는 Layer 배열의 상태에 의해서 정해지기 때문에, titleOrder 정보는 클라이언트 개체인 Plane에서 가져오도록 만들었습니다.

2022-03-16 13:24 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/Plane.swift
> +        }
Command를 fromIndex, toIndex로 변환하는 작업의 경우 여러 VC에서 사용할 가능이 있기 때문에 모델인 Plane에 배치했습니다.

2022-03-16 13:30 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +    }
기존에는 Layer를 표현하는 View들이 최상위 뷰의 직접 Subview인 형태였습니다. 

하지만 reorder를 하면서 그렇게 했을 경우 버튼 같은 다른 요소들에 의해서 동작이 버그를 일으킨다는 것을 발견했습니다. 

따라서 최상위 뷰에 CanvasView를 별도로 세팅해주고 Layer를 표현하는 뷰는 그 밑으로 들어가도록 View 하이어라키를 다시 구성했습니다.

2022-03-16 13:38 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
> +        if newView is UILabel { resizeToFit(newLayer, for: newView) }
이 부분은 출력 흐름에서 다시 한번 입력 흐름을 만들기 때문에 분리해보라고 저번 스텝에서 리뷰를 주셨는데요. 

Resize를 해줄만한 적절한 입력 흐름을 찾지 못했습니다. Select 이벤트 시에 해줄까도 생각해봤으나 그러면 선택하지 않는 경우에는 계속 잘려있는 상태로 보이게 될 거 같았습니다. 일단은 적절한 다른 곳을 찾지 못해 유지한 상태입니다.

2022-03-17 08:38 UTC, godrm requested changes
다음 내용들을 확인해보세요 :)

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +    private var layers: [Layer] = []
데이터소스에 참조하더라도 source of truth에서 가져올 수 있지 않을까요?

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +    var didCommandMoveHandler: ((Layer, Plane.reorderCommand) -> ())?
결국 이런 클로저들은 델리게이트의 변형이죠. 
그런 의미에서는 이 클로저들은 관련있는 역할로 관리해야 한다면 그 자체도 프로토콜을 고려해보세요

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +    }
Plane.Event.didReorderLayer 이름 형태 좋네요.

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +        return layers.count
데이터 소스라고 해서 여기서 꼭 layers.count를 접근해서 넘겨줘야 하는 건 아닙니다. 
데이터 소스 객체를 별도로 두는 것도 가능하고, 소스를 가진 다른 객체를 화면을 그리도록 넘겨주는 것도 필요합니다

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +        return cell
이 메소드는 셀을 재사용하기 때문에 셀 마다 한 번만 불리는 게 아니라 스크롤 할때마다 반복해서 호출됩니다
따라서 셀은 유지되고 내용은 다른 것으로 바꿔치기 됩니다. 이런 경우 cell에 `cell.addGestureRecognizer(longPress)`을 넣으면 재사용될 때마다 제스처 인식기가 추가되서 n개가 됩니다. 
그래서 이런 셀을 다룰 때는 `StoryBoardLayerCell` 클래스가 필요할 수도 있습니다. 여기가 길어지면 StoryBoardLayerCell에서 처리해야 하는거죠

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +        tableView.deselectRow(at: indexPath, animated: false)
editing 이 되는게 아니라면 selection을 꼭 막지 않아도 큰 문제는 없습니다. selection 스타일만 조정해도 큰 문제가 안될 수 있습니다

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +        })
위에 언급했었는데, 셀에 제스처를 넣는 시도는 좋은 건 아닙니다. 테이블뷰 전체에 대한 델리게이트로 커버가능할 수도 있거든요
특히 여기서는 AlertAction을 사용하는 데 UIMenu를 사용하는 접근도 시도해보세요

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Controller/PanelViewController.swift
> +    }
이 부분을 VC 구체 타입을 모르게 시도해보세요. 힌트는 위에 있었습니다 :)

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/LayerFactory.swift
> +}
팩토리에서 구분하려고 이런 타입을 새로 선언할 필요는 없습니다. 이럴 때 메타 타입을 활용해보세요

2022-03-17 08:38 UTC, godrm commented on DrawingApp/DrawingApp/Model/Model/LayerFactory.swift
>          }
팩토리에서는 어쩔 수 없이 구체 타입을 알아야 생성할 수 있습니다만,
타입이 추가될 때마다 switch-case를 추가하지 않고도 생성할 수 있으면 가장 좋습니다. 
LayerType로 구분하는 것은 좋은 접근이 아닙니다

2022-03-18 08:07 UTC, BumgeunSong commented
@godrm 
리뷰 주신 사항 반영했습니다!

- [x] Closure를 넘겨주는 VC를 LayerReoderable, LayerFetchable, LayerSelectable 등으로 추상화했습니다.
- [x] LayerType을 제거하고 MetaType을 활용해 LayerFactory를 만들었습니다.
- [x] longPressRecognizer를 제거하고, tableView에서 지원하는 `contextMenuConfigurationForRowAt` 를 사용했습니다.
- [x] LayerTableViewController 가 가지고 있던 layers 프로퍼티를 제거하고, fetchLayer, fetchLayerCount를 통해 Datasource를 Plane에게 요청하도록 변경했습니다.

2022-03-18 08:07 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +}
- [ ] Closure를 넘겨주는 VC를 LayerReoderable, LayerFetchable, LayerSelectable 등으로 추상화했습니다.

2022-03-18 08:08 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Model/Model/LayerFactory.swift
> +    static func makeRandom<T: Layer>(_ type: T.Type, titleOrder: Int, from data: Data? = nil) -> Layer? {
LayerType을 제거하고 MetaType을 활용해 LayerFactory를 만들었습니다.

2022-03-18 08:09 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +        cell.contentConfiguration = config
LayerTableViewController 가 가지고 있던 layers 프로퍼티를 제거하고, fetchLayer, fetchLayerCount를 통해 Datasource를 Plane에게 요청하도록 변경했습니다.

2022-03-18 08:10 UTC, BumgeunSong commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +        guard let layer = fetchLayer?(indexPath.row) else { return nil }
longPressRecognizer를 제거하고, tableView에서 지원하는 contextMenuConfigurationForRowAt 를 사용했습니다.

2022-03-18 09:31 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
>      }
`setHandler(to viewController: UIViewController)` 추상화는 내부에서 어차피 나눠서 할꺼면 그냥 각각 호출해도 되지 않을까 싶네요. 기능을 조합하고 싶었던 걸까요? 아주 이상하지는 않은데 좀 어색하기는 하네요

2022-03-18 09:32 UTC, godrm commented on DrawingApp/DrawingApp/Controller/CanvasViewController.swift
>          photoPicker.delegate = self
다음 도전꺼리는 Plane 자체도 프로토콜로 추상화해보세요.

2022-03-18 09:33 UTC, godrm commented on DrawingApp/DrawingApp/Controller/LayerTableViewController.swift
> +}
ViewController를 역할을 나누는 시도는 좋습니다

2022-03-18 09:33 UTC, godrm commented
수고하셨습니다 :) ViewController에서 Plane 도 의존성을 줄여보세요

2022-03-18 09:33 UTC, merged