[Mase] Step3 - 옵저버 패턴 적용하여 리팩토링
codesquad-members-2022/swift-drawingapp pull request #95
Opened 2022-03-16 16:26 UTC by sanghyeok-kim

## 개선 사항
- `planeDelegate` 삭제 -> `NotificationCenter` 사용
- `UserInfoKeys`로 상수값 별도 관리
- 파일 위치, 폴더명 정리
  - 파일이 점점 늘어나면서 그룹화의 필요성을 느끼게되었습니다.
  - 또한 별도로 관리하자니 연관성이 떨어지고, 그냥 Models 폴더 위에 놓아두자니 애매한 그런 파일들을 정리하고자 했습니다.
  - 추후에 프로젝트 폴더 관리와 관련된 컨벤션이 있는지 공부해서 개선해 나가도록 하겠습니다.
<img width="308" alt="CleanShot 2022-03-17 at 01 46 08@2x" src="https://user-images.githubusercontent.com/57667738/158643159-e4412aeb-c2c2-4891-95b2-d7c5a3387e5c.png">

<br>

## 죄송한 사항
폴더명을 바꾸고 파일 위치를 수정한 다음 커밋을 하니
이전 코드와의 변경점이 비교가 안되고,
전부 그냥 새로 만들어진 것으로 처리되는군요...
다음부터는 폴더명이나 파일 위치 이동하기 전에 꼭 코드 변경사항에 대해 먼저 커밋을 하도록 하겠습니다!!!🙏

2022-03-17 09:05 UTC, godrm requested changes
다음 내용들을 확인해보시고 개선하고 넘어가도록 하겠습니다 :)

2022-03-17 09:05 UTC, godrm commented on DrawingApp/DrawingApp/Controllers/ViewController.swift
>          }
프로토콜로 나눠서 처리하는 것도 좋은 시도입니다만
아예 메소드를 나눠서 BasicShape & Colorable 조합, BasicShape & Alphable 따로 접근하도록 만드는 방법도 있죠

2022-03-17 09:05 UTC, godrm commented on DrawingApp/DrawingApp/Models/Constants/UserInfoKeys.swift
> +}
UserInfoKeys가 여러 타입에서 사용하는 키값이라면 이렇게 분리하면 되는데
특정 타입에서만 사용하는 거라면 관련있는 타입에 표현하는 게 좋습니다

2022-03-17 09:05 UTC, godrm commented on DrawingApp/DrawingApp/Models/Extensions/NotificationNames.swift
> +}
Notification.Name도 여러 타입에서 사용하는 키값이라면 이렇게 분리하면 되는데
특정 타입에서만 사용하는 거라면 관련있는 타입에 표현하는 게 좋습니다

2022-03-17 09:05 UTC, godrm commented on DrawingApp/DrawingApp/Models/Factories/ViewFactory.swift
> +        view.translatesAutoresizingMaskIntoConstraints = false
view.translatesAutoresizingMaskIntoConstraints 값을 언제 사용하나요? false로 하는 이유가 궁금합니다

2022-03-17 09:05 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
>              if isShapeExist(on: coordinate, target: shape) {
isShapeExist 이런 메소드도 Plane 관점에서 보면 응집도가 떨어지는 메소드입니다
`shape.isExist(on: coordinate)` 형태로 shape가 처리해도 되지 않을까요?
카드 속성을 가져오지 않고, 카드 자체를 비교하는 것처럼요

2022-03-17 09:05 UTC, godrm commented on DrawingApp/DrawingApp/Models/Tools/CGConverter.swift
>  class CGConverter {
이런 타입도 서로 관련이 없는 메소드들을 합쳐놓는 타입이라서 지양하세요
각자 관련이 있는 타입을 확장하는 게 더 좋습니다.

2022-03-17 09:05 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +                                        userInfo: [UserInfoKeys.selectedShape: selectedShape])
어차피 위에 `private(set) var selected: BasicShape?` 접근 가능한거면 userInfo로 안 넘겨도 되는건 아닐까요?

2022-03-18 08:43 UTC, sanghyeok-kim commented on DrawingApp/DrawingApp/Models/Factories/ViewFactory.swift
> +        view.translatesAutoresizingMaskIntoConstraints = false
오토레이아웃이 아닌 CGRect 값으로 뷰에 띄워지니까 필요가 없군요.. 삭제했습니다!

2022-03-18 08:45 UTC, sanghyeok-kim commented on DrawingApp/DrawingApp/Models/Extensions/NotificationNames.swift
> +}
위의 `UserInfoKeys`와 함께 `Plane` 안에서 관리하는 방식으로 수정완료했습니다

2022-03-18 08:45 UTC, sanghyeok-kim commented on DrawingApp/DrawingApp/Models/Plane.swift
>              if isShapeExist(on: coordinate, target: shape) {
plane이 아닌 shape가 자체적으로 isExist를 갖도록 수정완료했습니다!

2022-03-18 08:47 UTC, sanghyeok-kim commented on DrawingApp/DrawingApp/Models/Tools/CGConverter.swift
>  class CGConverter {
관련있는 각 타입에 맞게 나누는 것으로 수정완료했습니다!

2022-03-18 08:55 UTC, sanghyeok-kim commented on DrawingApp/DrawingApp/Models/Plane.swift
> +                                        userInfo: [UserInfoKeys.selectedShape: selectedShape])
두 가지 고민을 해봤습니다.

1. `selected`의 접근제어자를 `private(set)`으로 유지
  -> 바뀌기 전의 `selected`는 `userInfo`로 넘기지 않고 VC에서 `plane.selected`를 통해 접근
  -> 그렇게 하면, 말씀하신대로 `userInfo`로 굳이 `shape`를 넘겨주지 않아도 됨

2. `selected`의 접근제어자를 `private`으로 변경
  -> `userInfo`를 통해 바뀌기 전의 `selected`(`newlySelectedShape`)와
바뀌고 난 후의 `selected`(`newlySelectedShape`)를 둘 다 넘겨줌

VC에서 model의 프로퍼티에 직접 접근해서 가져오는 것이 물론 가능은 하지만,
VC가 Subscriber라는 관점으로 생각해 봤을 때 plane이 특정 Event와 함께 던져주는 값을 사용하는게 맞다고 생각했습니다.
그래서 2번 방식으로 수정 완료했습니다.

2022-03-18 08:59 UTC, sanghyeok-kim commented
@godrm

> 프로토콜로 나눠서 처리하는 것도 좋은 시도입니다만 아예 메소드를 나눠서 BasicShape & Colorable 조합, BasicShape & Alphable 따로 접근하도록 만드는 방법도 있죠

이 피드백에 대한 부분은 아직 확실하게 떠오르는 방법이 없어서, 계속 고민해보고 추후에 수정해보겠습니다..

위 피드백을 제외한 나머지는 모두 말씀하신대로 개선해보았습니다.
확인 부탁드리겠습니다!

2022-03-18 09:39 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +                                                           UserInfoKeys.newlySelectedShape: newlySelected])
previouslySelected는 왜 Any로 바꿔주고 newlySelected는 안 바꿔줘도 되나요?

2022-03-18 09:39 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +                                        userInfo: [UserInfoKeys.selectedShape: selectedShape])
괜찮은 접근이네요. 속성을 가져가야 하느냐, 필요한 것을 알려줘야 하느냐는 늘 딜레마입니다. 정답이 없어요

2022-03-18 09:40 UTC, godrm commented on DrawingApp/DrawingApp/Models/Protocols/Alphable.swift
> +    }
UIKit을 어디서 import 하게 되느냐인데 `protocol Alphable`에서 이렇게 사용하면
Alphable 채택하면서 결국 Model은 이 파일을 참조하게 되고 UIKit을 import 하게 됩니다.
그래서 여기보다는 다른 곳에서 확장하는 게 더 좋습니다. 참고하세요

2022-03-18 09:41 UTC, merged

2022-03-28 15:04 UTC, sanghyeok-kim commented on DrawingApp/DrawingApp/Models/Plane.swift
> +                                                           UserInfoKeys.newlySelectedShape: newlySelected])
![CleanShot 2022-03-28 at 23 42 35](https://user-images.githubusercontent.com/57667738/160423636-d63eb764-7d81-4c91-9179-eb56b6bff362.png)

`previouslySelected`는 `Optional` 타입 -`BasicShape?`-인데
`Non-Optional`인 `Any` 타입이 들어가야하는 `userInfo`의 Value 자리에 넣으려 하자
명시적으로 언래핑을 해주라는 경고가 발생했습니다.

반면 `newlySelected`는 `Non-Optional`타입  -`BasicShape`-이기 때문에 `Any` 자리에 그대로 들어갈 수 있습니다.

---

별다른 생각 없이 경고창이 떠서 추가해주었는데,
그 부분을 짚어주셔서 왜 그런지에 대해 생각해보았고
그러다 이상한 점을 발견했습니다.

`previouslySelected`에 `as Any`를 붙여서 언래핑하지 않고, 옵셔널 값 그대로 넣어도
잘 작동한다라는 것이었습니다(언래핑하라는 경고문구가 뜨긴 하지만)...


- 왜 `Any`타입이 들어가야 할 자리에 옵셔널 타입을 넣어도 되는가?
  (왜 컴파일러가 암묵적으로 옵셔널을 언래핑을 해주는가?)
- 옵셔널타입이 들어갈 수 있으려면 `Any`가 아니라 `Any?`여야 하지 않나?


<br>

### 조사해본 결과

`Any`는 옵셔널 타입도 가질 수 있음을 알게되었습니다.
(https://stackoverflow.com/questions/34644128/why-non-optional-any-can-hold-nil)

- `Any`는 모든 '타입'을 암묵적으로 conform하는 `protocol`이고,
  `Optional`도 결국 `enum`으로 되어있는 '타입'이기 때문에 `Any`의 범주 안에 들어간다.
- 따라서 `Any?`가 아니라 `Any`여도 옵셔널 타입을 넣을 수 있다.
- 다만 `Any` 타입에 `nil`값을 직접 할당하는 것은 불가능하다.
  (`nil`은 타입 자체가 없기 때문)

---

우선 이렇게 `Any`에 옵셔널을 넣을 수 있는 이유에 대해서는 알게되었습니다만,

'어차피 암묵적으로 언래핑 해줄거면서 왜 명시적으로 언래핑 하라는 경고창이 뜨는가'
에 대한 해답을 명쾌하게 찾지는 못했습니다..

다른 타입과 달리 `Any` 타입으로 캐스팅을 했을 때에 생길 수 있는 문제가 있나?
하는 정도의 추측을 해보고 있긴 합니다만... 이 부분에 대해서는 더 공부해봐야겠습니다.

2022-03-29 10:03 UTC, godrm commented on DrawingApp/DrawingApp/Models/Plane.swift
> +                                                           UserInfoKeys.newlySelectedShape: newlySelected])
네. Any 타입은 애플 프레임워크에서 어떤 타입이든지 넣을 수 있는 경우에 종종 씁니다만
우리가 굳이 Any로 바꿀 필요는 없습니다. 얘기한 것처럼 대부분의 경우는 그냥 넣으면 되니까요. 참고하세요