[Chez] Step3 - 옵저버패턴 적용
codesquad-members-2022/swift-drawingapp pull request #98
Opened 2022-03-17 12:33 UTC by asqw887

# PR

### **작업 목록**

- [x]  Plane , ViewController 출력 흐름 NotificationCenter 로 변경 
    - [x] Plane Struct를 Class 로 변경 

### **학습 키워드**

- Observer Pattern
- Publisher/Subscriber Pattern 

### 고민과 해결

- `addObserver(_:selector:name:object:)` 에서 object를 모델 객체로 설정을 했더니 selector 메소드를 호출해주지 않는 문제점이 있었다.
 -> 그룹리뷰 때 Plane 이 Struct기 때문에 값이 복사되서 들어와, 문제점이 발생한다고 알려주셔서 Plane을 class로 변경해주어서 해결했습니다.

2022-03-17 12:47 UTC, asqw887 commented on DrawingApp/DrawingApp/Model/Plane.swift
> +            NotificationCenter.default.post(name: .backgroundDidChagned, object: self, userInfo: ["updateRectangle":selected])
data를 전달하는 userInfo 딕셔너리를 이런방식으로 작성해도 괜찮을까요? 넘겨주는 데이터가 모두 Rectangle 객체여서 저는 key값을 모두 동일하게 설정해도 괜찮다고 생각했습니다..

2022-03-18 04:57 UTC, godrm requested changes
다음 내용들을 확인해보세요. 동작 자체는 잘 구성하셨는데, 디테일한 부분에 대해 의견을 남겼습니다. 
이것만 확인하고 나서 머지하면 될 것 같습니다

2022-03-18 04:57 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        NotificationCenter.default.post(name: .rectangleDidAdd, object: self, userInfo: ["updateRectangle":rectangle])
여기서 object가 sender 역할이다보니 class가 아니라 struct면 계속 주소가 바뀔 수 있습니다. 그래서 mutable 한 속성을 다룰 때는 클래스를 고려하는 게 좋습니다.

2022-03-18 04:57 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +        NotificationCenter.default.post(name: .alpahDidChanged, object: self, userInfo: ["updateRectangle":selected])
컬러나 알파값이 바뀐 경우는 rectangle 전체가 필요한가, 해당 값만 필요한가도 고민해볼 필요는 있습니다
예를 들어 plane 전체를 알려줘도 되나? rectangle만 줘도 되나? 아예 안줘도 되나? 그런거죠

2022-03-18 04:57 UTC, godrm commented on DrawingApp/DrawingApp/Model/Plane.swift
> +            NotificationCenter.default.post(name: .backgroundDidChagned, object: self, userInfo: ["updateRectangle":selected])
동일하게 `"updateRectangle"` 키값을 선언하는 것은 괜찮습니다. 다만 보내는 곳과 받는 곳에서 같은 키값을 사용한다는 것을 보장해주려면 이런 값들도 하드코딩 하기 보다는 상수로 선언해주세요. 그래야 일관된 값을 사용할 수 있고 실수를 줄입니다 
그리고 같은 곳에서 두 번 post한다는 것은 합칠 수 있지 않나 생각해보세요
여기서 post는 보내는 입장에서 무엇이 바뀌었냐만 중요합니다. 그걸 받는 객체가 그걸 받아서 무엇을 할지는 신경쓰지 않는거죠. 지금은 마치 사각형 선택도 하고, 배경도 바꿔야해. 두 번 말하는 느낌이네요
아래 alpha까지 보면 3번 말하는거군요!

2022-03-18 04:57 UTC, godrm commented on DrawingApp/DrawingApp/NotificationCenter.swift
> +}
이 속성들은 어떤 타입과 관련이 있을까요? 
항상 관련있는 타입, 응집도있는 게 무엇일까를 고려해보세요. 
받는 타입과 관련이 있을까요 혹은 보내는 타입과 관련이 있을까요?

2022-03-18 04:57 UTC, godrm commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
ViewController들도 항상 속성은 private var를 우선적으로 고려해보세요

2022-03-18 04:57 UTC, godrm commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +        guard let selected = notification.userInfo?["updateRectangle"] as? Rectangle else { return }
위에서 언급한 것처럼 updateRectangle 속성이 필요하다고 했는데, 정작 필요한 건 backgroundColor 인것 같은데요? 어떻게 생각하세요?

2022-03-18 05:35 UTC, asqw887 commented on DrawingApp/DrawingApp/Model/Plane.swift
> +            NotificationCenter.default.post(name: .backgroundDidChagned, object: self, userInfo: ["updateRectangle":selected])
앗, 그렇군요. post는 `사각형이 바뀌었어` 를 전달하고 무엇을 할지는 그걸 받는 객체쪽에서 처리하는게 더 좋겠네요. 
상수로 선언하는 부분도 반영해서 다시 푸시하겠습니다.

2022-03-18 06:25 UTC, asqw887 commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +        guard let selected = notification.userInfo?["updateRectangle"] as? Rectangle else { return }
변경된 backgroundColor 만 필요한 것은 맞지만, 현재 뷰의 배경색을 바꿔주기 위해서는 기존의 alpha 값은 그대로 유지를 해야합니다. 
그래서 새로운 배경색을 만들더라도 `Plane.selectedView.alpha`에 접근을 해야하는데 이렇게 하는것보다 rectangle 전체를 넘겨주는게 좋지 않을까 생각했었습니다.. 

JK가 언급하신 것처럼 backgroundColor 만 넘겨주도록 바꾸는게 더 함수에 목적에 맞는것 같아 수정하였습니다.

2022-03-18 09:06 UTC, asqw887 commented on DrawingApp/DrawingApp/Model/Plane.swift
> +
`선택된 사각형이 바뀌었다` 라고 post만 해주고 ViewController에서 처리하도록 했습니다.

2022-03-18 09:10 UTC, asqw887 commented
@godrm  피드백 주신부분 수정해보았습니다. 확인 부탁드려요 :)

2022-03-18 09:11 UTC, asqw887 commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(changeAlpha(_:)), name: Plane.rectangleDidMutate, object: plane)
`Plane.rectangleDidMutate` 이벤트를 받았을때 세개의 메소드를 호출해주는 방향으로 수정했습니다. 

처음에는 JK가 말씀하신것처럼 backgroundColor,Alpha만 전달받도록 고쳤으나 이 코드때문에 다시 rectangle 전체를 Userinfo 로 전달해주는 방법으로 다시 변경했습니다.

2022-03-18 09:43 UTC, godrm commented on DrawingApp/DrawingApp/ViewController/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(changeAlpha(_:)), name: Plane.rectangleDidMutate, object: plane)
그렇다면 `Plane.rectangleDidMutate`를 Rectangle 변화가 아니라 하위 속성 변화 3개로 쪼개도 되는 것인가 생각해볼 필요도 있겠네요.

2022-03-18 09:43 UTC, godrm commented
수고하셨습니다~!

2022-03-18 09:43 UTC, merged